### ISSUE TITLE
Кодліст / класифікатор: financingParty

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#1]
Частина значень у цій змінній - коди КАТОТТГ, які потрібно трансформувати у людиночитані текстові записи, що позначатимуть місцевий бюджет, з якого виділяється фінансування

Ще частина записів - коди країн, які треба перетворити на людиночитані текстові назви країн

Ще частина записів - власне коди фінансуючих сторін, для котрих нам потрібно отримати розшифровку

**Comment by ndrhzn** [comment]
Пропований варіант обробки цієї проблеми @a-radik 

Для першого кейсу - коли значення це код КАТОТТГ - можна замінити його на текст за тією ж логікою, за якою витягуєте з коду КАТОТТГ назву громади, області, і т.д.

Для другого кейсу - коли значення це код країни - ми можемо підтягнути класифікатор країн (можу взяти це на себе)

Для третього кейсу - коли значення це код організації - нам потрібні розшифровки від команди розробки або проєктного офісу. Цей запит передали, і будемо тиснути, аби нам розписали детально, що там де цього тижня

**Comment by a-radik** [comment]
Давайте деталізуємо алгоритм обробки першого кейсу.

Якщо перші два символа "Фінансуючої сторони" = UA - це код КАТОТТГ. 
Наступним кроком - ми беремо таблицю "Кодифікатор адміністративно-територіальних одиниць та територій територіальних громад" і намагаємось співставити код отриманий від API з кодом в таблиці починаючи з першого рівня. 

Фрагмент таблиці Кодифікатора
![Screenshot 2023-11-02 112700](https://github.com/open-contracting/bi.dream.gov.ua/assets/63779944/95bc0385-5f4c-479c-b531-fb68b756ba96)


На виході співставлення отримуємо Назву об'єкта згідно Кодифікатора наприклад, "Терезине", "Вільна Тарасівка", "Володимирівка", "Гайок". Саме ця назва має бути відображена в полі чи її треба доповнювати додатковим текстом?

@ndrhzn прошу погодити логіку і надати коментар стосовно очикувань, що має з'явитись в полі замість коде КАТОТТГ

Додаю Кодифікатор і Перелік скорочень
[Кодифікатор адміністративно-територіальних одиниць та територій територіальних громад.xlsx](https://github.com/open-contracting/bi.dream.gov.ua/files/13237209/-.xlsx)
[Список скорочень, що використовуються в КАТОТТГ_.docx](https://github.com/open-contracting/bi.dream.gov.ua/files/13237210/_.docx)

Ще одне зауваження - наразі Коифікатор - це статична таблиця датована 21 роком (не факт, що ми маємо саму актуальну версію) і для цього етапу цього має бути достатньо. На майбутньє треба мати джерело що буде містити актуальну інформацію.

**Comment by ndrhzn** [comment]
Думаю, тут краще давати ієрархію до області. Тобто, якщо у нас є  UA74100110010097725 - Іванівка, то принаймні потрібно дати зрозуміти, до якої області ця Іванівка належить, або й навіть вибудовувати весь шлях (населений пункт, територіальна громада, область)

В такому разі варіанти представлення інформації
- Іванівка, Іванівська територіальна громада, Чернігівська область
- Іванівка, Чернігівська область

Щодо актуальності довідника - занотовано, будемо шукати актуальну / підтримувану версію на майбутнє

**Comment by ndrhzn** [comment]
Для другої задачі - коли код це дволітерний код країни - ми фактично можемо взяти офіційний класифікатор. [Ось тут він є у табличному вигляді](https://zakon.rada.gov.ua/rada/show/v0426832-13#Text) (2.2. ПОКАЖЧИК ЛІТЕРНИХ КОДІВ АЛЬФА-2). Мені не дуже подобається, що назви країн українською мовою наразі UPPERCASE, але це вирішувано

**Comment by andrzejbeletsky** [comment]
2буквені коди стран замінено с довідника https://zakon.rada.gov.ua/rada/show/v0426832-13#Text
КАТОТТГ коди замінено на тексти виду Іванівка, Чернігівська область
інші коди замінено згідно 
https://docs.google.com/spreadsheets/d/1PPGIwttgcLIhw-VPNLE-tU8LDMD_fCR1bcPBfEyDr3g/edit#gid=1078474699
але там немає кодів eibEfficiency , eibNkpvu , eibPvu , EU NIP , SSF

**Comment by ndrhzn** [comment]
Та, сьогодні допрацюю коди, котрих бракує та додам їх в репозиторій

**Comment by ndrhzn** [comment]
На рівні quick fix можна зробити так @andrzejbeletsky 

| code          | name_ua                                                       | name_en                                            |
|---------------|---------------------------------------------------------------|----------------------------------------------------|
| eibEfficiency | Енергоефективність громадських будівель в Україні             | Ukraine Public Buildings Energy Efficiency (UPBEE) |
| eibNkpvu      | Надзвичайна кредитна програма для відновлення України (НКПВУ) | Ukraine Early Recovery Programme (UERP)            |
| eibPvu        | Програма відновлення України (ПВУ)                            | Ukraine Recovery Programme (URP)                   |
| euNip         | Neighbourhood Investment Platform (NIP)                       | Інвестиційна платформа сусідства ЄС                |

SSF можна лишити як є. Здається, в адмінці це теж в такий спосіб представлено

**Comment by ndrhzn** [comment]
У нас вже виконана задача перекладу назв регіонів англійською мовою (#36), однак переклади все ще не застосовуються до financingParty codelist. До наступного релізу є сенс виправити це.  @andrzejbeletsky 

Також варто поправити трохи формат відображення підписів - додати після коми пробіл, слово "область" можна писати повніст, а не скорочувати до "обл"

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/2bde610a-d9de-418b-b852-b0b1d8ae0025)

**Comment by ndrhzn** [comment]
Оновив кодліст для країн у файлі DREAM Translations, аби українські назви країн не були UPPERCASE

**Comment by andrzejbeletsky** [comment]
Done

**Comment by ndrhzn** [comment]
Тримаю цю задачу відкритою винятково через те, що помітив проблему з англійською версією кодліста. Тут мені треба буде розібратися з самим кодлістом, аби ми могли оновити

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/e57b754e-6f91-4c86-a339-095c407a5aa1)

**Comment by ndrhzn** [comment]
Потрібно буде пропрацювати наступні кейси з Проєктним офісом

| **Код проєкту** | **Фінансуюча сторона** |
|--------------------|---------------------------|
|   180124-656F0484  |   03358222                |
|   040324-65C62FFA  |   02070987                |
|   200923-8669AA7A  |   03358222                |
|   200224-C77383B9  |   45100259                |
|   280224-FF9E5348  |   31319242                |
|   090124-60A5374B  |   03358222                |
|   070224-9E25D8B9  |   43570096                |
|   190124-4D66A915  |   03358222                |
|   190124-1D754717  |   03358222                |
|   190124-4E6432AC  |   03358222                |
|   170124-224E14B4  |   03358222                |
|   060224-6B9916C0  |   31319242                |
|   080224-94A95BBF  |   31319242                |
|   070224-04E33120  |   03328681                |
|   190124-70E16BE2  |   03358222                |
|   080124-2A9658DD  |   03358222                |
|   070324-DDC37A6D  |   13796704                |
|   090124-54804185  |   03358222                |
|   090124-4F519803  |   03358222                |
|   230124-E94B5026  |   31700972                |
|   290124-91FBCE99  |   31700972                |
|   090124-764EF105  |   03358222                |

**Comment by andrzejbeletsky** [comment]
не-коди країн і не-коди катоттг оброблюються цим код-листом:
https://docs.google.com/spreadsheets/d/1efMobfMAItctWak9UmULWInX02GH5TeKXsWXFHkG5Ww/edit?pli=1#gid=2050112638
