### ISSUE TITLE
Data: Додати financingParty до таблиці "Деталі проєктів"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#100]
Оскільки ми додаємо до таблиці "Деталі проєктів" стовпчик "Юридичні підстави використання коштів", то для контексту потрібно також додати і стовпчик "Фінансуюча сторона". Колеги з Проєктного офісу зазначають, що без "Фінансуючої сторони" буде важко зрозуміти "Юридичні підстави використання коштів".

Коли ми додаємо стовпчик "Фінансуюча сторона", маємо виходити з таких настанов:
- "Фінансуюча сторона" у проєкті привʼязана до обʼєкту інвестицій. Оскільки один проєкт може мати декілька обʼєктів інвестицій, він також може мати декілька записів про фінансуючу сторону. Це можуть бути деккілька різних фінансуючих сторін, або декілька згадок однієї фінансуючої сторони.
- Коли ми відображаємо дані про фінансуючі сторони проєкту в одній комірці, нам потрібно конкатенувати всі унікальні записи про фінансуючі сторони проєкту. Скажімо, якщо в якомусь проєкті є пʼять записів про фінансуючі сторони, але всі пʼять записів - "Фонд ліквідації", тоді ми показуємо лише один запис у комірці - "Фонд ліквідації". Якщо ж у проєкті є три записи про фінансуючі сторони - "Фонд ліквідації", "Фонд ліквідації", "Юнайтед 24", тоді ми показуємо у комірці "Фонд ліквідації", "Юнайтед 24".

Стовпчик "Фінансуюча сторона" можна додати перед стовпчиком "Юридичні підстави використання коштів"

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/b7011c65-e80e-4ce8-850a-d567bafcdc80/state/analysis

**Comment by ndrhzn** [comment]
Перевірено, можна додавати в публічний додаток

**Comment by andrzejbeletsky** [comment]
done
