### ISSUE TITLE
UI: Додати час оновлення даних

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#101]
Наразі ми надаємо інформацію про те, коли саме були оновлені дані, у форматі "Дані станом на DD.MM.YYYY". Але є запит також додати до цього інформацію про годину - скажімо, якщо скрипт для оновлення даних запускається раз на добу о 3:00, тоді можна зазначати "Дані станом на DD.MM.YYYY 3:00"

Насамперед це стосується публічного додатку, в нативному можна нічого не змінювати

**Comment by andrzejbeletsky** [comment]
@karandinserhii 
+ у загальний фільтр ще з аркуша Відбори "Заклад МОЗ", "Заклад МОН"

**Comment by karandinserhii** [comment]
В мешапі доступні наступні допрацювання по цій задачі: 
Відображається час оновлення даних (разом з датою)
Додані фільтри "Заклад МОЗ", "Заклад МОН" у випадаючу панель фільтрів
Виправлено відображення фільтра "Підсектор" у випадаючій панелі фільтрів

Для тестування доступно на [тестовому оточенні](https://bi.qnalytics.com/dream/#/)

**Comment by ndrhzn** [comment]
Дякую, все переглянув - можна виносити в публічний додаток

**Comment by a-radik** [comment]
This is done
