### ISSUE TITLE
Bug: Проєкти, географія котрих визначена некоректно

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#106]
У нас наразі відображаються два проєкти у Криму. Їхня географічна приналежність визначається некоректно - в реальності обидва проєкти приналежать до міста Миколаєва

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/c0f7963b-514a-4b26-8f42-2b981f165bbe)

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/f57b2a85-e362-4dfc-9567-1d1034c7beb7)

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
Маємо 3 проєкти 190324-B4A1F498, 190324-D2210CE3, 190324-E37413DF
Вони посилаються на один і той самий об'єкт 
https://public-api.dream.gov.ua/marketplace/public/dream/objects/4ovh529d-9952-46wb-9197-8ejd498j1w41
Цей об'єкт  має 2 координати: "UA01160150000023108","UA48060150000071713".
UA01160150000023108 - це Миколаївська громада у Криму (Сімферопольський район) (мабудь, це і є помилковий запис).
UA48060150000071713 - це Миколаївська громада у Миколаївській області.

**Comment by ndrhzn** [comment]
Спробуємо розібратися, чи це можна пофіксити на рівні джерела даних. А тоді вже будемо думати, як це виправляти
