### ISSUE TITLE
Data: Прибрати "Тип проєкту" зо всіх сторінок (графіків, карт, таблиць, фільтрів)

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#107]
Наразі ухвалено рішення припинити використовувати це поле на етапі створення даних, оскільки воно не є інформативним / не створює додаткової цінності. Тому також потрібно прибрати це поле з BI

- Сторінка “Показники” - dropdown menu та панель фільтрів
- Сторінка “Проєкти” dropdown menu та панель фільтрів
- Сторінка “Деталі проєктів” - таблиця та панель фільтрів
- Вкладка “Фільтри”
- Вкладка Selections

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
@karandinserhii 
Видалити з мешапу DREAM:
![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/63861139/ab23a269-f976-43fb-97d4-48a23c7a93b3)

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/4cfb64bc-f648-4116-8d80-bc99f590fd77/state/analysis

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у нативному додатку

Можна застосовувати зміни у публічному додатку

**Comment by andrzejbeletsky** [comment]
@karandinserhii 
Видалити з мешапу DREAM:
![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/63861139/f6fd1ed9-91f4-488d-87a1-21597aa6d1ea)

**Comment by a-radik** [comment]
Зроблено  можна дивитись в https://bi.qnalytics.com/dream/#/
