### ISSUE TITLE
UI: Додати до сторінки "Деталі проєктів" інформацію про кількість проєктів у вибірці

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#108]
На сторінці "Деталі проєктів" у користувачів є потреба бачити, скільки проєктів є у вибірці після застосування фільтрів. Зазвичай - на інших сторінках - ми вирішуємо цю задачу за допомогою картки. Але на сторінці "Деталі проєктів" немає карток, а є лише таблиця. 

Тому постає питання, де ми можемо цю інформацію відображати.

**Опція перша - відображати цю інформацію в самій же таблиці.** Ми вже відображаємо узагальнюючі статистики у цій таблиці для деяких показників (Загальний орієнтовний бюджет, Підтверджене фінансування, Фінансове покриття). У такому разі ми можемо відображати інформацію про кількість проєктів замість слова "Всього" у стовпчику "Код проєкту". Також є сенс відображати сумарну кількість контрактних процедур.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/32349f7d-f314-4ae3-b98c-47515296b942)

Опція друга - відображати цю інформацію у додатковому рядку над таблицею за аналогією з тим, як це працює в BI Prozorro.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/70c85b53-a3d6-4fc7-8784-e67f139806f9)

Перший варіант є більш пріоритетним, оскільки він не вимагає додавання нових елементів в розмітці сторінки, котрі б зменшували простір, відведений під таблицю, а використовує вже наявну розмітку.

Другий варіант слід застосовувати лише в тому випадку, якщо перший варіант імплементувати неможливо технічно.

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/b7011c65-e80e-4ce8-850a-d567bafcdc80/state/analysis

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у нативному додатку

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/7b91db5f-9803-4c82-a6e8-a2bc1d30f310)

Можна застосовувати зміни у публічному додатку

**Comment by a-radik** [comment]
@ndrhzn @andrzejbeletsky пропоную зробити форматування числа для розділу груп розрядів і відокремити Всього: від числа

**Comment by ndrhzn** [comment]
Та, давайте

**Comment by a-radik** [comment]
@andrzejbeletsky

**Comment by a-radik** [comment]
Не потребує оновлення мешапу, можна дивитись в https://bi.qnalytics.com/dream/#/

**Comment by andrzejbeletsky** [comment]
done
