### ISSUE TITLE
Data / UI: Замінити картки на аркуші "Фінансування"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#109]
На аркуші "Фінансування" у нас наразі є чотири картки - "Підтверджене фінансування", "Кількість фінансуючих сторін", "Кількість проєктів" та "Кількість органів управління". 

Потрібно прибрати картки "Кількість проєктів" та "Кількість органів управління", та замість них дати картки "Кількість повністю профінансованих проєктів" та "Кількість частково профінансованих проєктів".

Це нові показники, котрих ми ще не використовували в модулі аналітики. Отже, потрібно дати їм визначення

**"Кількість повністю профінансованих проєктів"** - кількість проєктів, у котрих обсяг підтвердженого фінансування більше або дорівнює загальному орієнтовному бюджету. Або ж - якщо визначати це через вже обчислений на рівні проєктів показник "Фінансове покриття" - кількість проєктів, у котрих фінансове покриття більше або дорівнює 100%.

**"Кількість частково профінансованих проєктів"** - кількість проєктів, у котрих обсяг підтвердженого фінансування є більшим від нуля, але менше, ніж загальний орієнтовний бюджет. Або ж - кількість проєктів, у котрих фінансове покриття більше 0%, але менше 100%.

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/9e97c60d-6dd8-491c-aa8b-8ac52e9948d6/state/analysis

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у нативному додатку

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/440154bb-8ff6-4768-8640-66ed5409eb5e)

Переклади додані до таблиці DREAM Translations

Можна застосовувати зміни на публічному додатку

**Comment by ndrhzn** [comment]
Здається, щось зламалося - обидві картки показують однакові числа (і це є загальна кількість проєктів)

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/1586f90f-3a0d-44d6-ab79-0ffa5e040c39)

**Comment by a-radik** [comment]
Не потребує оновлення мешапу, можна дивитись в https://bi.qnalytics.com/dream/#/
