### ISSUE TITLE
Індикатори: Співфінансування

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#11]
У таблиці "Фінансування" у нас є показник "співфінансування". Отже, слід визначити, як цей показник рахувати

**Співфінансування** - це ситуація, коли один проєкт має декілька джерел фінансування (financingParty)

Якщо ми хочемо визначити просто наявність співфінансування на рівні проєкту, тоді ми перевіряємо, чи проєкт має більше ніж одне джерело фінансування

У нашому випадку радше йдеться не просто про наявність співфінансування,  а про відсоток фінансування. І не на рівні проєкту, а на рівні фінансуючої сторони. В такому разі можемо діяти наступним чином

Для кожної фінансуючої сторони у проєкті розраховувати відсоток фінансування. Скажімо, якщо в проєкті є лише одна фінансуюча сторона, відсоток вінансування 100%. Якщо у проєкті дві фінансуючої сторони, можна уявити, що одна з них забезпечує 70% фінансування, інша - 30%. 

Тобто тут, ми співвідносимо обсяг фінансування кожної окремої фінансуючої сторони із загальним обсягом фінансування проєкту. Таким чином ми отримаємо для кожного проєкту і кожної фінансуючої сторони у проєкті відсоток фінансування.

Але у фінальній таблиці нас все одно цікавіть навіть не це. Нас цікавить **медіанний відсоток співфінансування проєктів для кожної фінансуючої сторони**.

Тобто, для кожної фінансуючої сторони ми беремо всі проєкти, де є фінансування від неї. І дивимось, яким є медіанний відсоток фінансування цієї фінансуючої сторони для всіх цих проєктів.

В результаті ми хочемо / розраховуємо побачити, в який спосіб різні фінансуючі сторони беруть участь у проєктах? Наприклад, чи є такі, хто долучається до великої кількості проєктів, але має доволі малий відсоток співфінансування? Або чи є такі, хто долучається до малої кількості проєктів, але фінансує їх фактично повністю?

Чи це є зрозумілим? Чи це видається коректним?

**Comment by andrzejbeletsky** [comment]
Уточнення - відсоток фінансування ми рахуємо до суми фінансування (яка на сьогодні ще може не покривати всю потребу) чи до бюджету?

**Comment by ndrhzn** [comment]
Хороше питання, та. Я його собі ставив, коли описував методику, і поки дійшов висновку, що можна рахувати відсоток фінансування до суми фінансування (особливо з огляду на те, що бюджет цілком може бути необгрунтовано завищений, наприклад). Але краще буде уточнити. Проконсультуюся з цього питання

**Comment by ndrhzn** [comment]
Отже, відповідь щодо цього - рахувати співфінансування від загального бюджету проєкту

**Comment by ndrhzn** [comment]
TO DO: Зробити пояснення щодо того, що означає "Співфінансування" у цьому випадку, як цей показник інтерпретувати, і чому він може бути більше 100%
