### ISSUE TITLE
Data: Додати до таблиці "Деталі проєктів" показники "Кількість укладених контрактів" та "Сума укладених контрактів"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#110]
До таблиці "Деталі проєктів" потрібно додати два нових стовпчики - "Кількість укладених контрактів" та "Сума укладених контрактів"

Кількість укладених контрактів обчислюється за змінною _cdu_response/contractingProcesses/summary/contract/id_

Сума укладених контрактів обчислюється за змінною _cdu_response/contractingProcesses/summary/contract/value_ (а також за потреби _cdu_response/contractingProcesses/summary/contract/currency_)

Ці два стовпчики потрібно додати після стовпчика "Кількість контрактних процедур"

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/b7011c65-e80e-4ce8-850a-d567bafcdc80/state/analysis
Потрібні переклади англійською

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у нативному додатку

Переклади додані до таблиці DREAM Translations

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/24ed9e7e-e844-41b1-8c68-fc6ddef09290)

Можна застосовувати зміни у публічному додатку

**Comment by a-radik** [comment]
Не потребує оновлення мешапу, можна дивитись в https://bi.qnalytics.com/dream/#/
