### ISSUE TITLE
Data / UI: Прибрати зі сторінки "Бюджетування" таблицю "Органи управління та ініціатори"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#111]
На сторінці "Бюджетування" у нас є вкладка таблиці "Органи управління та ініціатори". З огляду на те, що дані щодо органів управління та їхніх звʼязків з ініціаторами наразі не є повною мірою точними, ми вирішили прибрати цю таблицю з відображення - принаймні до того часу, як прояснимо все, що стосується органів управління.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/ab1d76cb-1863-42cc-aa15-b83ffb7f9996)

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
done

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у нативному додатку

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/09149e0b-d695-4ad7-9985-da3f81cc43e5)

Можна застосовувати зміни у публічному додатку

**Comment by a-radik** [comment]
Не потребує оновлення мешапу, можна дивитись в https://bi.qnalytics.com/dream/#/
