### ISSUE TITLE
Charts: Виправити відображення гістограми на графіку розподілу проєктів за наповненням

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#112]
На аркуші "Наповнення" у нас є графік, котрий показує розподіл проєктів за наповненням. За структурою це гістограма, котра розподіляє діапазон від 0 до 100% на інтервали шириною 10%, і показує, скільки проєктів є у кожному діапазоні.

Все працює чудово, якщо не застосовувати жодних фільтрів - оскільки у нас у вибірці є проєкти у всіх можливих інтервалах від 0 до 100. Однак якщо застосовувати фільтр за ініціатором, тоді гістограма починає функціонувати неправильно - як простий стовпчиковий графік.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/7c8f4050-32ae-4271-b9ff-249c3d98a65b)

У цьому прикладі (Ініціатор - Бачанська міська рада) ми бачимо, що є пропущені значення між 11-20 та 31-40. За умов коректного відображення там мав би бути інтервал 21-30, однак у ньому не було б жодних спостережень. А якщо вже бути зовсім прискіпливипи - у нас також мав би бути інтервал 0-10.

Приклад коректної роботи гістограми на тих же даних додається.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/041be52c-7061-4f96-87be-5b3a4c6e13be)

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/660b2add-d9c1-435e-a303-07ffbbf62640/state/analysis

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у нативному додатку

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/4a6c2946-6511-4b03-a9dc-10bed7ddf064)

Можна застосовувати зміни у публічному додатку
