### ISSUE TITLE
Charts / tables: Додати до сторінки "Фінансування" графік та таблицю

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#113]
Концептуально відпочатку ми замислювали сторінку "Фінансування" як "Картку фінансуючої сторони". Тобто сторінку, де є можливість побачити ключові показники за певною фінансуючою стороною.

Однак фактично наразі ця сторінка функціонує у двох модусах:
- Представляє клюочаі статистики щодо фінансування загалом - якщо користувачі не обрали жодну з фінансуючих сторін
- Представляє ключові статистики щодо фінансування для конкретної обраної фінансуючої сторони.

Видається, що ми можемо підсилити обидва сценарії - додати трохи інформації про фінансування загалом та про фінансування конкретної фінансуючої сторони.

Що ми пропонуємо:

- Якщо не обрана жодна фінансуюча сторона (або ж обрано декілька фінансуючих сторін), ми показуємо графік, котрий демонструє обсяг підтвердженого фінансування у розрізі типів та джерел фінансування - такий, як ми відображаємо на сторінці "Показники"

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/21951240-e655-4214-bde2-8070c675f10b)

- Якщо обрана якась конкретна фінансуюча сторона, ми показуємо таблицю із переліком проєктів, підтриманих обраною фінансуючою стороною. В такому разі пропонується додати до таблиці наступні показники: Код проєкту, Назва проєкту, Ініціатор, Загальний орієнтовний бюджет, Підтверджене фінансування _(від обраної фінансуючої сторони)_, Фінансове покриття _(від обраної фінансуючої сторони)_.

Оскільки це новий елемент, нам потрібно буде вирішити, як змінити layout на сторінці "Фінансування" - в який спосіб розташувати карту, стовпчиковий графік, та графік / таблицю. Це є наразі відкрите питання.

**Comment by andrzejbeletsky** [comment]
є, працюю.

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/9e97c60d-6dd8-491c-aa8b-8ac52e9948d6/state/analysis

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у нативному додатку

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/f58c821f-18ac-4827-b06f-9715af910011)

Що варто допрацювати / змінити:

- Кольорова шкала / принцип кольорового кодування для treemap - можна застосовувати такий же принцип, як і на аркуші "Проєкти" #114 
- Layout - варто змінити layout. Бачу тут пару варіантів:

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/1ef1b7a8-6772-4c8b-86ac-4367eef4e060)

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/d8e1e1fd-b70f-485b-96cb-d6d5e489371b)

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/9e97c60d-6dd8-491c-aa8b-8ac52e9948d6/state/analysis

**Comment by a-radik** [comment]
@karandinserhii
