### ISSUE TITLE
Charts: Змінити принцип кольорового кодування для treemap на сторінці "Проєкти"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#114]
Наразі для treemap на сторінкці "Проєкти" ми використовуємо принцип кодування кольором, котрий результує у візуальному хаосі. Кожен окремий підсектор у рамках кожного сектора отримує свій власний колір, через це у нас утворюється навала кольорів, на котрій досить важко сфокусуватися.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/a778878b-313c-4548-81f2-a763843f1845)

Що і з цим можна зробити

- Використовувати один колір в межах одного сектору (всі сектори в межах одного сектору позначаються однаковим кольором, при цьому кордони між полігонами підсекторів мають бути чіткими і видимими)

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/863f8e4f-c285-4c96-9112-f8131aaf87e4)

- Використовувати для підсекторів одного сектору відтінки одного кольору на позначення числових значень (тобто в такому випадку нам потрібно спершу створити кольорову шкалу для розрізнення секторів, а потім від базового кольору кожного сектору побудувати градієнт, що залежить від числового значення кожного підсектору)

Друге рішення є більш advanced, і я не впевнений, чи Qlik підтримує цю ідею, але перше мало б спрацювати. І таким чином у нас зменшиться візуальний хаос на сторінці.

Аналогічна проблема також існує на сторінці "Показники", але там трохи більше варіацій через те, що у користувачів є можливість комбінувати виміри. Тому цю проблему ми адресуємо окремо.

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
перший варіант реалізовано
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/1563015f-f9f5-4336-bf0a-e6ec160561a9/state/analysis
Другий варіант теоретично можливий. Через визначення формули ARGB кольору кожного квадрату. І дійсно, треба заводити таблицю базових кольорів кожного сегменту.

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у нативному додатку

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/9e4e9951-126b-4c72-bd69-bb04deee3a05)

Можна виводити оновлення на публічний додаток

**Comment by a-radik** [comment]
https://bi.qnalytics.com/dream/#/
