### ISSUE TITLE
Filters: Перейменувати вкладку "Фільтри", додати нові фільтри та впорядкувати їх

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#116]
В рамках задачі з впорядкування фільтрів в BI ми хочемо зробити так, аби всі (або ж майже всі) фільтри були доступні на вкладці "Фільтри", і можна було створювати різноманітні вибірки без необхідності стрибати між різними вікнами. Разом з тим, ми хочемо, аби ці фільтри були впорядковані логічним чином, аби користувачі розуміли, до чого стосується той чи інший фільтр.

Пропонуємо тут наступні зміни

- **Перейменувати кнопку / вкладку "Фільтри" на "Всі фільтри"**, аби сигналізувати користувачам, що там може бути доступно більше фільтрів. ніж на кожній окремо взятій сторінці

- На сторінці "Всі фільтри" додати та впорядкувати наступні елементи 

| Деталі проєктів                | Залучені організації  | Місцезнаходження | Фінансування         | Контрактні процедури | Документи та класифікатори            |
|--------------------------------|-----------------------|--------------|----------------------|----------------------|---------------------------------------|
| Код проєкту                    | Ініціатор             | Область      | Тип фінансування     | Наявність тендерів   | Наявність ПКД                         |
| Дата створення проєкту         | Балансоутримувач      | Район        | Джерело фінансування | Наявність контрактів | Заклад МОН                            |
| Рік і місяць створення проєкту | Виконавець            | Громада      | Фінансуюча сторона   |                      | Заклад МОЗ                            |
| Статус проєкту                 | Орган управління      |              | Профінансованість   |                      | Код стратегічного рівня               |
| Характер проєкту               | Тип ініціатора        |              |                      |                      |   |
| Сектор                         | Тип органу управління |              |                      |                      |                                       |
| Підсектор                      |                       |              |                      |                      |                                       |

Оскільки фільтрів багато, їх потрібно **впорядкувати за групами** (група зазначена у заголовку таблиці) та ймовірно **впорядкувати у декілька колонок** (скажімо, якщо зараз у нас 6 груп фільтрів, то це може бути дві колонки по три групи фільтрів у кожній). В такому разі, звісно, ширина вкладки "Всі фільтри" має бути щонайменше вдвічі більшою за поточну.

Також варто звернути увагу, що тут є декілька нових фільтрів, котрі у нас не обовʼязково використовуються експліцитно на даний момент (в тому сенсі, що ми не маємо на якійсь зі сторінок готову кнопку для цього)

- **Код проєкту** (ми можемо фільтрувати за кодом проєкту з таблиці "Деталі проєктів", але не маємо готовї кнопки для цього)
- **Дата створення проєкту** (ми можемо фільтрувати за датою створення проєкту з таблиці "Деталі проєктів", але не маємо готовї кнопки для цього)
- **Рік і місяць створення проєкту** (ми можемо фільтрувати за роком і місяцем створення проєкту з вкладки "За датами", але не маємо готовї кнопки для цього)
- **Профінансованість** - це новий фільтр, котрий має показувати наявність фінансування у проєкту. Пропонуємо тут розділити всі проєкти на три категорії - "Повністю профінансовано", "Частково профінансовано", "Відсутнє фінансування" - за аналогією з тим, як це працює на основному порталі.
- **Наявність контрактів** - новий фільтр, котрий має показувати, чи є за конкретними контрактними процедурами укладені контракти (_cdu_response/contractingProcesses/summary/contract/id_)

**Comment by andrzejbeletsky** [comment]
Take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/98004ed9-600c-47f6-bf44-5382691007d8/state/analysis
Потрібні переклади назв груп
@karandinserhii, @a-radik  На аркуші "Відбори" для зручності я зробив групування фільтрів.

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/98004ed9-600c-47f6-bf44-5382691007d8/state/analysis

**Comment by ndrhzn** [comment]
Цю задачу можна вважати виконаною у нативному додатку. Можна виносити зміни у публічний додаток / mashup

**Comment by a-radik** [comment]
1. Чому тут не зробити 6 колонок (так буде краще з точки зору розміщення на аркуші) ?
2. Гадаю що треба деякі фільтри зробити розгорнутими щоб можна було в найбільш часто використовуваних фільтрах робити вібор в один клік
@ndrhzn

**Comment by ndrhzn** [comment]
Щодо верстки - у шість колонок цілком підходить.

Щодо розгортання фільтрів - загалом має сенс. Якщо говорити про те, які фільтри мають / можуть бути розгорнутими - я би сказав так

- Сектор
- Ініціатор
- Область
- Район
- Громада
- Фінансуюча сторона

Але є більш важливе питання - в який спосіб цей розділ представлений у мешапі (і звідки до нього можна дістатися)

Ми проговорювали варіант зробити ці фільтри доступними за кліком на кнопку "Фільтри" (котру пропонували перейменувати у "Всі фільтри". Таким чином, аби цей перелік фільтрів був доступний як поп-ап з будь-якої сторінки. Аби можна було сформувати вибірку, без необхідності уходити з того аркуша, на котрому користувач знаходиться.

Але тепера ми маємо окрему вкладку "Відбори", на котрій знаходяться всі фільтри, які ми пропрацювали, а також у нас все ще лишається кнопка "Фільтри".

Питання

- Чи ми можемо зробити це не через вкладку "Відбори", а через кнопку "Фільтри"?
- Якщо не можемо, то чи можна в такому разі лишити вкладку "Відбори", а кнопку "Фільтри" сховати?

@a-radik

**Comment by ndrhzn** [comment]
![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/94b42038-f68c-4171-9f24-a6302e86b9cd)

**Comment by ndrhzn** [comment]
Ще раз зафіксую тут очікувану поведінку:

- Користувачі з будь-якої сторінки клікають на кнопку "Фільтри" (котру треба перейменувати у "Всі фільтри") у правому верхньому куті
- Наразі за кліком на цю кнопку збоку зʼявляється панель із фільтрами. Це можна лишити, але замість цієї панелі з фільтрами потрібно показувати ось ті згруповані фільтри, котрі підготував Анджей

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/aebfa769-fff9-4cd5-b569-88743b3d2588)

**Comment by ndrhzn** [comment]
Пара правок, котрі стосуються самих фільтрів:

- Якщо ми вже розгорнули "Сектор" і винесли його першим у списку, тоді є сенс дати "Підсектор" після нього
- Є сенс колонки "Документи та класифікатори" та "Фінансування" поміняти місцями ("Фінансування є більш важливим і порядок має це відображати)

І ще є пара спостережень щодо самої сторінки:

- Потрібно зробити кнопку більш помітною (але, звісно, у межах розумного), аби користувачам було легше її знайти. Наразі видається, що можна просто змінити колір шрифта на чорний, і тоді елемент "Всі фільтри" буде простіше ідентифікувати

- Користувачі під час тестування зауважили, що для них не дуже очевидно, що для того, аби закрити сторінку, потрібно знову клікнути на кнопку "Всі фільтри". Їхня інтуіція полягає в тому, що клік на лого (герб) або ж на іконку будь-якої сторінки мав би результувати у закритті сторінки "Всі фільтри".  Чи ми можемо так зробити? Або ж - в який ще спосіб ми можемо підказати користувачам, як закрити сторіку із фільтрами?

**Comment by a-radik** [comment]
Деякі питання треба буде пропрацювати з R&D. Зможемо наприкінці поточного/початку наступного тижня.
