### ISSUE TITLE
Filters / UI: Додати можливість обирати стовпчики для відображення у таблиці "Деталі проєктів"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#117]
Оскільки ми постійно додаємо до таблиці "Деталі проєктів" нові стовпчики, назріла потреба систематизувати нашу роботу з обсягом та дозуванням інформації.

Пропонуємо дати можливість користувачам самостійно обирати, які стовпчики вони хочуть відображати у таблиці. При цьому ми для кожного стовпчика визначимо default state - visible / hidden. Таким чином **за замовчуванням ми будемо показувати користувачам базовий набір змінних, але у них буде можливість модифікувати цей набір** - додавати чи прибирати стовпчики для відображення.

Перелік змінних у таблиці та їхній default state

| Назва стовпчика                       | Default state |
|---------------------------------------|---------------|
| Код проєкту                           | Visible       |
| Дата створення проєкту                | Hidden        |
| Назва проєкту                         | Visible       |
| Статус проєкту                        | Visible       |
| Характер проєкту                      | Hidden        |
| Тип ініціатора                        | Hidden        |
| Ініціатор                             | Visible       |
| Тип органу управління                 | Hidden        |
| Орган управління                      | Visible       |
| Виконавець                            | Hidden        |
| Балансоутримувач                      | Hidden        |
| Назва об'єкта                         | Visible       |
| Сектор                                | Visible       |
| Підсектор                             | Hidden        |
| Область                               | Visible       |
| Район                                 | Hidden        |
| Громада                               | Visible       |
| Загальний орієнтовний бюджет, ₴       | Visible       |
| Підтверджене фінансування, ₴          | Visible       |
| Фінансове покриття                    | Visible       |
| Фінансуюча сторона                    | Visible       |
| Кількість контрактних процедур        | Hidden        |
| Кількість укладених контрактів        | Hidden        |
| Сума укладених контрактів             | Visible       |
| Стратегічні документи                 | Hidden        |
| Юридичні підстави використання коштів | Hidden        |

Відтак, щоразу як ми будемо додавати нові змінні до таблиці, ми маємо визначати їхній default state. 

Щодо механіки вибору змінних - можемо спробувати зробити checkbox за аналогією з тим, як ми обираємо показники на сторінці "Наповнення".

Цей checkbox має розташовуватись з правого боку таблиці, там само, де знаходиться панель фільтрів. Кількість фільтрів ми плануємо суттєво зменшити, і це має звільнити місце для елементу вибору змінних у таблиці.

Відкрите питання - чи ми хочемо застосовувати зміни у таблиці одразу після вибору елементу в checkbox, чи хочемо додати якусь кнопку для застосування вибору. Це може мати значення в сценаріях, коли користувач обирає кілька змінних - якщо ми будемо застосовувати зміни одразу, тоді нам доведеться перемальовувати таблицю після кожної зміни.

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/b7011c65-e80e-4ce8-850a-d567bafcdc80/state/analysis

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у нативному додатку

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/6f0b16fb-e4fd-4b6f-934e-bbc6de5da079)

Загалом все добре, є пара дрібних правок

- Варто додати заголовок для цього блоку - "Оберіть стовпчики для відображення" / "Select columns"
- Стовпчик "Фінансуюча сторона" зробити hidden by default

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/b7011c65-e80e-4ce8-850a-d567bafcdc80/state/analysis

**Comment by ndrhzn** [comment]
Дякую. Цю задачу можна вважати виконаною у нативному додатку. Можна виносити у публічний додаток

**Comment by a-radik** [comment]
@karandinserhii
