### ISSUE TITLE
Bug: Різні варіанти написання назви організації

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#118]
Наразі у нас можлива ситуація, коли для одного ініціатора ми маємо два варіанти написання назви. В такому разі користувачі можуть бачити різні записи для одного ініціатора у фільтрі "Ініціатор"

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/562a14d8-c27b-4cb0-bac4-a1651af9ac54)

Ця проблема, ймовірно, походить від того, що в деяких випадках ми забираємо назву ініціатора прямо з даних проєкту, а в деяких - коли в даних проєкту є лише ідентифікатор - з даних компаній. Але можливо є й інші причини.

Приклади проблеми

Балаклійська міська рада 
БАЛАКЛІЙСЬКА МІСЬКА РАДА ХАРКІВСЬКОЇ ОБЛАСТІ 

БОРОДЯНСЬКА СЕЛИЩНА РАДА 
Бородянська селищна рада Київської області 

Іванівська сільська рада 
ІВАНІВСЬКА СІЛЬСЬКА РАДА ЧЕРНІГІВСЬКОГО РАЙОНУ ЧЕРНІГІВСЬКОЇ ОБЛАСТІ 
Іванівська сільська рада Чернігівського району Чернігівської області 

Таїровська селищна рада 
ТАЇРОВСЬКА СЕЛИЩНА РАДА ОДЕСЬКОГО РАЙОНУ ОДЕСЬКОЇ ОБЛАСТІ 

Перш ніж братися за виправлення проблеми, варто чітко сформулювати її причини та проаналізувати різні варіанти рішення.

**Comment by andrzejbeletsky** [comment]
Щодо
"Балаклійська міська рада,
БАЛАКЛІЙСЬКА МІСЬКА РАДА ХАРКІВСЬКОЇ ОБЛАСТІ"
Маємо проєкти
https://public-api.dream.gov.ua/marketplace/public/dream/ideas/43q5rzwa-7k13-4865-8o3a-2ne1814a07o2
https://public-api.dream.gov.ua/marketplace/public/dream/ideas/ic5q002m-ai2b-425t-9680-w081j7m73a18
В них initiator з "id": "UA-EDR-04058628" має такі різні назви в "legalName"

**Comment by andrzejbeletsky** [comment]
Також
"Таїровська селищна рада
ТАЇРОВСЬКА СЕЛИЩНА РАДА ОДЕСЬКОГО РАЙОНУ ОДЕСЬКОЇ ОБЛАСТІ"
https://public-api.dream.gov.ua/marketplace/public/dream/ideas/4l8o9b36-3e0s-47gd-ajd8-qz3tm29d9i83
https://public-api.dream.gov.ua/marketplace/public/dream/ideas/6bso5284-36q7-4xiv-b04z-347qxv51m130

**Comment by ndrhzn** [comment]
Зрозумів, дякую! В такому разі спершу спробуємо розібратися із проблемою на рівні джерела даних

**Comment by ndrhzn** [comment]
Отже, розробники кажуть, що проблему на рівні джерела даних наразі виправити немає можливості. Це означає, що нам доведеться вирішувати цю проблему на рівні BI

Які тут можливі варіанти / сценарії?

Припускаю, що у нас вже є таблиця initiators (або щось подібне до цього). Ймовірно, там є ідентифікатор та назва. І в такому разі там для деяких ідентифікаторів може бути декілька значень (два чи три - з тих прикладів, які ми зафіксували).

В такому разі нам потрібно робити що на зразок групування за ідентифікатором, і в кожній групі обирати лише перше значення.

Чи можливі інші сценарії вирішення проблеми? @andrzejbeletsky

**Comment by andrzejbeletsky** [comment]
Так, можна вибрати одне з групи. 
Брати будь-яке ?

**Comment by ndrhzn** [comment]
Я думаю, можна взяти будь-яке, наразі преференцій немає

**Comment by andrzejbeletsky** [comment]
Done.
Take a look

**Comment by ndrhzn** [comment]
Оригінальна проблема, здається, вирішена (перевірено на тих прикладах, які були описані вище).

Але тепера у нас можлива ситуація, коли організація може називатися двома різними способами  - у стовпчику "Ініціатор" та "Орган управління"

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/4e8693a9-94bb-4ab3-8749-9d3b5e8f5eb1)

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/d7a76d51-b9d6-4e1c-861a-10738d64a55d)

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/bdde97ab-a5ab-4939-a4df-9f211d803abb)

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by ndrhzn** [comment]
Тепера ніби все працює коректно, дякую! Можна застосовувати зміни і робити їх доступними у тестовому середовищі
