### ISSUE TITLE
UX: Додати можливість експортувати дані з візуалізацій

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#119]
Наразі у нас є можливість зберігати самі візуалізації у вигляді зображень або ж PDF файлів. Однак у користувачів також є запит на те, аби мати можливість експортувати дані, з котрих відмальовуються візуалізації.

Наприклад, якщо обрано графік, що показує бюджет проєктів у розрізі громад, тоді можна отримати таблицію, з якої відмальовується цей графік

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/ddf18580-994c-4973-bbe1-3d6f42a3e089)

Тобто потрібно буде додати іконку експорту даних поруч з іконкою експорту зображення

Експорт даних може бути або в CSV, або в XLSX.

**Comment by andrzejbeletsky** [comment]
@a-radik Це можливо?

**Comment by a-radik** [comment]
@karandinserhii

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у тестовому середовищі на прикладі одного обʼєкта

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/2612bf18-a425-440a-9306-23b4072d5521)

Поведінку відтестовано - все ніби працює коректно. 

Далі це потрібно додати до всіх візуалізацій і карт (всюди, де у нас є експорт зображень, має бути і експорт даних)

**Comment by ndrhzn** [comment]
Звернув увагу на пару речей

- На сторінці "Показники" немає можливості завантажити дані з обʼєктів "За регіонами", "За датами", "За категоріями" (відсутні іконки)

- На сторінці "Проєкти" завантаження даних з обʼєкта "За регіонами" (карта) не працює - за кліком на іконку просто зʼявляється білий екран, після чого сторінку потрібно перезавантажувати

- На сторінці "Фінансування" немає можливості завантажити дані з карти (відсутня іконка)

Чи є якась принципова технічна проблема із картами?

**Comment by ndrhzn** [comment]
Добре, в такому разі зараз фокусуємось на тому, аби не натякати на можливість завантаження даних там, де це неможливо, а потім будемо розбиратися із відображенням кнопки в контейнерів.

З того, що я бачу зара - ніби всюди вже поприбирали кнопки з мап. На цьому і зафіксуємось для найближчого релізу
