### ISSUE TITLE
Data / Filters: Бюджет проєкту

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#120]
У нас вже є змінна "Загальний орієнтовний бюджет" проєкту, котру ми використовуємо на декількох аркушах. Однак користувачі також мають потребу у фільтрі за бюджетом.

Наразі пропонується розбити всі проєкти за групами залежно від показника "Загальний орієнтовний бюджет", і після цього ми зможемо додати фільтр, у котрому можна буде обрати одну або декілька груп.

**Групи**
- 0-20 млн грн _(більше нуля, але менше 20 млн)_
- 20-40 млн грн _(більше 20 млн, але менше 40 млн)_
- 40-300 млн грн  _(більше 40 млн, але менше 300 млн)_
- понад 300 млн грн

Цей фільтр, звісно, буде доступний через загальну панель фільтрів (#116), а також на сторінках "Показники", "Проєкти", "Деталі проєктів", "Бюджетування". Деталі можна буде визначити після того, як цей фільтр буде готовий.

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/98004ed9-600c-47f6-bf44-5382691007d8/state/analysis
Фільтр "Група бюджету"

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у нативному додатку

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/ac6292d8-76e0-4249-9d65-494d3e1c63fd)

Загалом добре, але є пара дрібних правок

- Перейменувати фільтр з "Група бюджету" на "Бюджет проєкту"
- Наразі у самому фільтрі категорії підписані латинкою, незалежно від того, обрана українська мова інтерфейсу чи англійська (замість "млн" в українській версії підписано "m"). Це варто виправити

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Цю задачу можна вважати виконаною у нативному додатку. Далі можна виносити у публічний додаток

**Comment by ndrhzn** [comment]
Додати, так

- Сторінка "Показники"  - перед "Фінансуюча сторона"
- Сторінка "Проєкти" - перед "Фінансуюча сторона"
- Сторінка "Деталі проєктів" - перед "Фінансуюча сторона"

На сторінку "Бюджетування" можна не додавати, оскільки там ми робимо графік, котрий слугуватиме таким само фільтром

**Comment by andrzejbeletsky** [comment]
done
