### ISSUE TITLE
Charts: Додати графік "Бюджет проєкту" на сторінку "Бюджетування"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#122]
Тепера, коли у нас є нова змінна "Бюджет проєкту" (#120 ), ми можемо додати на сторінку "Бюджетування" стовпчиковий графік, котрий буде показувати кількість проєктів у кожній групі.

Це може бути стовпчиковий графік, де на одній осі у нас змінна "Бюджет проєкту" (чотири можливих значення), а на іншій осі - кількість проєктів у кожній групі. Що з цього знаходиться на осі Х, а що на осі Y - залежить від того, як ми розташуємо елементи на сторінці.

Наразі у нас є три елементи, котрі розташовуються таким чином

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/defc3221-7a85-45ed-96f4-2276a227ee9a)

Якщо в нас будуть чотири елементи, тоді можна спробувати розташувати їх таким чином

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/efed78d5-a9ea-4c1f-85e9-c685ca4d3047)

В такому разі можна зробити для нового стовпчикового графіку "Бюджет проєкту" по осі Х, а кількість проєктів у кожній групі - по осі Y. Групи мають бути сортовані не за числовим показником (кількість проєктів), а за зростанням бюджету.

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/cf2a7f3f-bb09-42c2-8ea8-af41903cea91/state/analysis

**Comment by ndrhzn** [comment]
Поточний статус - зроблено у нативному додатку

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/ff7937e7-5b6f-4500-8824-99a623303b55)

Можна віддавати у Mashup
