### ISSUE TITLE
Data: Видалити змінну "Запитання по SPILNO-мапі" з аркушу "Наповнення"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#124]
На аркуші "Наповнення" у нас є змінна "Запитання по SPILNO-мапі". Її слід прибрати відусіль - з графіку, таблиці, та панелі фільтрів.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/486a89bf-1804-435b-b966-2af892493833)

З точки зору моделі даних API "Запитання" та "Відповіді" по SPILNO-мапі є двома окремими елементами, але фактично вони повʼязані - якщо є відповіді, тоді є і запитання. Тому для нас немає сенсу тримати і запитання, і відповіді. Лишаємо тільки відповіді.

На що потрібно звернути увагу під час цієї операції - чи не вплине це на підрахунки відсотку наповнення (тобто чи там зараз кількість наявних елементів ділиться на фіксоване значення (умовно 12)  чи на формульне значення (умовно COUNT(COLUMNS))

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
Done
