### ISSUE TITLE
Data / Filters: Додати інформацію та фільтри про укриття та харчоблоки

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#126]
Від Проєктного офісу надійшла термінова задача, котру потрібно включити в цей реліз. 

Необхідно додати нові стовпчики у таблицю "Деталі проєктів", а також нові фільтри на вкладку "Всі фільтри"

**Стовпчики у таблиці "Деталі проєктів"**

- **"Тип укриття" / Shelter type** additionalClassifications/id where additionalClassifications/scheme="UA-RADA-5403-VI"
- **"Тип харчоблоку" / Kitchen type** additionalClassifications/id where additionalClassifications/scheme="UA-RADA-305-2021"

Ці стовпчики мають бути **прихованими за замовчуванням**, але у користувачів має бути можливість додати їх до таблиці через панель "Оберіть стовпчики для відображення".  На панелі "Оберіть стовпчики для відображення" їх можна додати після опції "Юридичні підстави використання коштів"

**Фільтри на сторінці "Всі фільтри" у колонці "Документи та класифікатори"**

- **"Наявність укриття" / Shelter availability** additionalClassifications/id where additionalClassifications/scheme="UA-RADA-5403-VI"
-  **"Наявність харчоблоку" / Kitchen availability** additionalClassifications/id where additionalClassifications/scheme="UA-RADA-305-2021"
- **"Тип укриття" / Shelter type** additionalClassifications/id where additionalClassifications/scheme="UA-RADA-5403-VI"
- **"Тип харчоблоку" / Kitchen type** additionalClassifications/id where additionalClassifications/scheme="UA-RADA-305-2021"

Змінні "Наявність укриття" та "Наявність харчоблоку" можуть приймати два значення - "Так" або "Ні" (Yes / No)

**Кодлісти**

**UA-RADA-5403-VI** (Тип укриття)

| **code**                  | **name_en**                 | **name_ua**                                           |
|---------------------------|-----------------------------|-------------------------------------------------------|
| shelter                   | Shelter                     | Сховище                                               |
| antiRadiationShelter      | Antiradiation shelter       | Протирадіаційне укриття                               |
| dualPurposeShelter        | Dual-purpose shelter        | Споруди подвійного призначення                        |
| rapidlyConstructedShelter | Rapidly constructed shelter | Швидкоспоруджувана захисна споруда цивільного захисту |
| simplestShelter           | Simplest shelter            | Найпростіше укриття                                   |

**UA-RADA-305-2021** (Тип харчоблоку)

| **code**   | **name_en** | **name_ua**   |
|------------|-------------|---------------|
| basic      | Basic       | Базова кухня  |
| sustaining | Sustaining  | Опорна кухня  |
| fabric     | Fabric      | Фабрика-кухня |

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/b7011c65-e80e-4ce8-850a-d567bafcdc80/state/analysis
