### ISSUE TITLE
Filters: Додати фільтр "Юридичні підстави використання коштів" на сторінку "Всі фільтри"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#127]
У нас вже є змінна "Юридичні підстави використання коштів" у таблиці "Деталі проєктів" (#97). 

Тепера користувачі просять додати це поле в якості фільтра. Видається доречним тримати це у вкладці "Всі фільтри" у секції "Документи та класифікатори" ( #116 )

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
done
@karandinserhii додати до фільтрів

**Comment by andrzejbeletsky** [comment]
Готово в тест-мєшапі
