### ISSUE TITLE
Data: Зробити розрізнення громад за областями

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#128]
Коли ми на рівні фільтрів чи вимірів говоримо про громади, то в нас всі агрегації відбуваються за іменем громади. Водночас, у нас можуть бути громади з однаковим іменем у різних областях. Таким чином у фільтрах і на графіку ці громади розрізнені не будуть, і лише на карті буде зрозуміло, що йдеться про різні громади, а не одну. 

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/a6128c74-fc2c-43c3-92d0-b1eba15c8dfc)

Ця проблема була відома і раніше (обговорювали її на одному з дзвінків), однак лише зараз назріла потреба у її вирішенні.

Які тут можливі варіанти?

- **Додати до громади назву області через кому**, як ми це робимо, коли йдеться про фінансуючу сторону. Це доволі просте рішення з технічної точки зору. 

**Переваги** такого рішення

1) У фільтрах та на графіках буде одразу зрозуміло, про яку громаду йдеться

**Недоліки** такого рішення

1) У нас, здається, можлива ситуація, коли громади мають однакові назви навіть у межах області (наскільки це поширено?). 

2) У фільтрах та на графіках назва області ймовірно буде обрізатися - принаймні у частині випадків. На графіках в такому разі у нас мають бути тултіпи

3)  У таблиці "Деталі проєктів" у нас вже є окремий стовпчик "Область". Якщо ми будемо давати область і в стовпчику "Область", і в стовпчику "Громада", це виглядатиме вкрай дивно.

- **Додати до громади в дужках код КАТТОТГ** - тобто повний код, котрий зазначений в даних проєкту

**Переваги** тут такі ж, як і у попереднього рішення

**Недоліки** - майже такі ж, як і у попереднього рішення, за винятком того, що у нас не виникає дублювання області 

Чи є в нас ще якісь опції? Давайте обговоримо, перш ніж робити. @a-radik @andrzejbeletsky

**Comment by ndrhzn** [comment]
Також слід памʼятати, що не у всіх випадках додавання області до громади матиме сенс. Наприклад, якщо у нас є treemap, де на одному рівні ієрархії область, а на іншому громада, додавання області до громади лише дублюватиме інформацію.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/b8cf5a59-5175-4fff-bcad-9c158081776d)

**Comment by ndrhzn** [comment]
Отже, якщо підсумувати, у нас є задача, котра по суті складається з двох аспектів - як ми групуємо / агрегуємо дані, і як ми презентуємо дані

- Агрегація / групування має відбуватися на рівні "область, район, громада". Тобто, якщо у нас є фільтр чи стовпчик, котрий позначає певну громаду, то це має бути громада певного району і області. Дані громад з однаковими назвами не мають групуватися та агрегуватися

- Презентація даних має враховувати контекст. Скажімо, у фільтрах та стовпчикових графіках ми цілком можемо давати назву області в дужках, але на treemap, де є область і громада, в ідеалі краще назву області не давати взагалі

Питання наразі такі:

- Як багато часу у нас займе притомна імплементація, тобто така в якій враховані всі принципи, описані вище?
- Якщо ця задача не може бути виконана умовно впродовж одного дня, то чи ми можемо спершу зробити грубо (додати область в дужках всюди), а вже потім допрацьовувати нюанси?

**Comment by andrzejbeletsky** [comment]
in progress.
зроблю спочатку грубо (додам назву області в дужках)

**Comment by ndrhzn** [comment]
Це ті випадки, коли в межах однієї області є декілька громад з однією назвою?

**Comment by andrzejbeletsky** [comment]
так

**Comment by ndrhzn** [comment]
Ок, тобто виходить, що на рівні області у нас таке можливо через те, що може бути міська, сільська та селищна громада. Наприклад,  у Дніпропетровській області - Покровська 

На рівні Синельниківського району маємо селищну, на рівні Нікопольского району - міську та сільську.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/a1431ea8-b266-49ac-9b72-5606bf4a0708)

Виходить, що нам треба додавати ще тип громади (чи є ця інформація у довіднику?). А потім - якщо цього не буде достатньо - і район

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/4cfb64bc-f648-4116-8d80-bc99f590fd77/state/analysis
поки що додана тільки назва області

**Comment by ndrhzn** [comment]
Ось це Покровська громада, Дніпропетровська область

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/1bf80831-456b-41d7-94a4-aed3aaba0380)

Отже, треба додавати тип громади

Також варто писати не "о." а "обл."

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/4cfb64bc-f648-4116-8d80-bc99f590fd77/state/analysis

**Comment by ndrhzn** [comment]
Дякую! Що варто зробити

- Змінити форматування підпису. Давайте зафіксуємо такий формат - "Назва громади тип громади, назва області". На прикладі "Чернігівська міська, Чернігівська обл."

- У таблиці "Деталі проєктів" зробити стовпчик "Область" прихованим за замовчуванням (#117)

**Comment by ndrhzn** [comment]
Зафіксую також, що у нас лишиться задача пропрацювати ось такий кейс

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/deec94ca-9ecc-4930-a593-5f25e13bce7c)

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/4cfb64bc-f648-4116-8d80-bc99f590fd77/state/analysis

**Comment by ndrhzn** [comment]
Дякую, можна релізити ці зміни, решту будемо допрацьовувати згодом

**Comment by andrzejbeletsky** [comment]
зарелізив на прод

**Comment by ndrhzn** [comment]
Одна річ, на котру звернули увагу, що при пошуку за назвою громади тепера матчиться також і назва області. Це, звісно, абсолютно нормальна поведінка. Але питання в тому, чи ми можемо її змінити.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/5fbd49cb-8aef-4586-b046-2fd06208dcfa)

Не впевнений, чи є в Qlik якийсь експліцитний контроль над scope of search. Але питання в тому, чи можемо ми, наприклад, в першу чергу показувати громади, а не області, або ж в ідеалі - не матчити області взагалі.

Чи є щось, що впливає на scope of search? Скажімо - можливо мені здалося, а може й ні - якщо підпис області у дужках, буде така ж поведінка?

**Comment by andrzejbeletsky** [comment]
by default клик працює в режимі "Normal search"
https://help.qlik.com/en-US/sense/February2024/Subsystems/Hub/Content/Sense_Hub/Selections/SelectionsToolbar/text-search-selections-visualizations.htm

take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/98004ed9-600c-47f6-bf44-5382691007d8/state/analysis
включений "Wildcard search"
![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/63861139/295706a5-724e-4fc6-b83d-2d2c59f26af6)
якщо бекспейсом видалити першу *, то пошук тексту с початку:
![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/63861139/74e78f0d-4563-4a4f-8d16-e9716b086d9a)
