### ISSUE TITLE
Data: Додати стовпчики "Заклад МОН" та "Заклад МОЗ" до таблиці "Деталі проєктів"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#129]
Від Проєктного офісу надійшов запит на те, аби бачити у таблиці "Деталі проєктів" (#10 ) змінні "Заклад МОН" та "Заклад МОЗ" (#98 , #99 )

Наразі вони доступні лише через вкладку "Всі фільтри" (#116 ).

За замовчуванням вони мають бути прихованими, але у користувачів має бути вибрати їх для відображення через панель "Оберіть стовпчики для відображення" (#117 ). Можна їх додати наприкінці - після змінної "Тип харчоблоку".

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
done
оновлено на проді
