### ISSUE TITLE
Фінансування: Фільтри

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#13]
У цьому блоці ми закладали такі фільтри

- Тип фінансування
- Джерело фінансування
- Фінансуюча сторона

Що варто змінити

**Замінити назви фільтрів в англійській версії**

Fund type > Funding type
Fund source > Funding source
Finance party > Financing party

**Використати кодлісти**  [fundingTypes](https://github.com/open-contracting/bi.dream.gov.ua/blob/main/codelists/fundingTypes.csv) та  [fundingSourceCategories](https://github.com/open-contracting/bi.dream.gov.ua/blob/main/codelists/fundingSourceCategories.csv) для фільтрів у англійській версії

**Comment by ndrhzn** [comment]
В цьому пункті проговорювали дві зміни

- Розгорнути фільтр, аби користувачі бачили перші N опцій доступними
- Опції у фільтрі відсортувати за обсягом підтвердженого фінансування від найбільшого до найменшого

Сортування вже імплементовано, а от фільтр все ще треба розгорнути

Окрім того, на публічній сторінці потрібно змінити порядок фільтрів (наразі він не такий, як у нативному додатку)

Пропоную встановити такий порядок фільтрів

Фінансуюча сторона
Джерело фінансування
Тип фінансування
Тип ініціатора
Тип органу управління

**Comment by ndrhzn** [comment]
Це заторкає і "Фінансування", і "Деалі фінансування"

**Comment by a-radik** [comment]
Готово
https://bi.qnalytics.com/dream/#/financing
