### ISSUE TITLE
Data / Codelists: Додати назви юридичних осіб до кодліста financingParty

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#132]
У нас зʼявилися випадки, коли фінансуючою стороною є юридична особа. У таких випадках у змінній financingParty/id ми отримуємо код ЄДРПОУ (якщо дані на вході якісні, що не завжди так).

Наразі на публічному додатку це виглядає ось так

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/adab7b6b-c6bb-4c43-987e-9d06e781637c)

Нам потрібно замість цих кодів ЄДРПОУ підставити людиночитані назви організацій. На щастя, у даних також є елемент financingParty/name, у котрому міститься інформація про назву юридичної особи. 

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/b4f98552-68a4-497f-adac-225a0b7e1b93)

В такому разі логіка обробки цих кейсів може бути така:

Якщо financeCategory="legalEntity", тоді ми назву організації забираємо із змінної financingParty/name

Тут, однак, є нюанс - для деяких кодів ми можемо мати декілька варіантів назви.

Наприклад, 

| 4653578 | Комунальне підприємство "Глухівський водоканал" Глухівської міської ради |
|---------|--------------------------------------------------------------------------|
| 4653578 | КП "Глухівський водоканал"                                               |

Або

| 31319242 | ОКП «МИКОЛАЇВОБЛТЕ­ПЛОЕНЕРГО»     |
|----------|-----------------------------------|
| 31319242 | ОКП «МИКОЛАЇВОБЛТЕ­ПЛОЕНЕРГО» ММР |

Оскільки, ми хочемо мати можливість агрегувати всі дані на рівні організації, нам потрібно визначитися, в який спосіб з декількох назв організації обирати одну. Це є сенс обговорити перед тим, як застосовувати зміни.

Також треба враховувати, що ця зміна заторкне лише українську версію. Але нам потрібно відображати коректні назви і для англійської версії також. Чи ми можемо автоматично транслітерувати назви, чи нам потрібно підтримувати кодліст із перекладами у таблиці  DREAM Translations?

**Comment by ndrhzn** [comment]
#1

**Comment by ndrhzn** [comment]
Можна розглянути варіант транслітерації на стороні Qlik

**Comment by andrzejbeletsky** [comment]
in progress.
financingParty/name не завантажувався з API - додаю завантаження.

**Comment by andrzejbeletsky** [comment]
Done
Take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/ea25bb7c-1161-43a5-b132-6ff1beb82566/state/analysis
Назва береться як сама остання в часі.

Зроблена проста транслітерація (без аналізу чи перша велика, чи у складі слова, де всі великі). Таблиця в DREAM Translations на аркуші translit. 
Всі великі транслітеруються також у великі. Тому є артефакти, коли слово починається з великої і транслітерується в 2-4 букви.

**Comment by ndrhzn** [comment]
Я трохи поправив таблицю транслітерації в DREAM Translations, аби вона краще відповідала тому, що у таблиці Кабміну. Видається, що після оновлення не має бути артефактів на зразок "CHernihivvodokanal"

**Comment by andrzejbeletsky** [comment]
done

Тепер можливі артефакти в назвах, де є кілька великих підряд
[5ca9fa3f-12da-4f37-b408-761dcd7c9c84.xlsx](https://github.com/open-contracting/bi.dream.gov.ua/files/15469807/5ca9fa3f-12da-4f37-b408-761dcd7c9c84.xlsx)

**Comment by ndrhzn** [comment]
Українська версія - назви юридичних осіб додані

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/7e592d79-9d76-467d-84fe-fc1867d1b854)

Англійська версія - назви юридичних осіб транслітеровані

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/f7eedab0-3e23-4d7c-b156-3af817b103dc)

Готово на тестовому, можна релізити на публічний

**Comment by andrzejbeletsky** [comment]
Done
