### ISSUE TITLE
Bug: Проєкти із наявним фінансуванням ідентифікуються як проєкти без фінансування

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#133]
У минулому релізі ми додали розріз "Профінансованість", що категоризує проєкти на такі у яких фінансування "Відсутнє", присутнє "Частково" або ж наявне "Повністю".

Втім, якщо застосувати цей фільтр та переглянути таблицю "Деталі проєктів", ми побачимо, що у таблиці є проєкти із наявним фінансуванням. 

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/23f6cdbc-017f-4bf5-bf67-47bcf98dd93b)

Чому так відбувається?

Через це у нас можливі ситуації, коли для вибірки проєктів із "Відсутнім" фінансуванням, ми маємо в сумі десятки мільйонів підтвердженого фінансування.

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/27ca72ea-9842-438e-af41-900c095d6e90)

**Comment by ndrhzn** [comment]
#116

**Comment by andrzejbeletsky** [comment]
in progress
баг із помилкою округлення для значень <1%
Також питання - якщо є фінансування, але нема бюджету, як рахувати % фінансування? Ставити 100% ?

**Comment by ndrhzn** [comment]
Гм, видається, що такої ситуації у нас не мало б бути суто з точки зору валідації даних (на рівні введення даних в систему заборонено вводити фінансування більше за бюджет).

Тому зустрічне питання - чи у нас справді є такі випадки? Я перевірив за таблицею "Деталі проєктів" - ніби не зустрів таких кейсів.

Якщо вони є, тоді алгоритм може бути такий:

- Для змінної "Профінансованість" ми ставимо значення "Частково" (ми знаємо напевне, що фінансування є, але не можемо стверджувати, що воно покриває потребу на 100%)
- Для змінної "Фінансове покриття" ми ставимо "-", оскільки обчислити значення не видається можливим

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
done.

так, ці випадки з проєктами в статусі 'Відмінено'
на випадок, якщо така ситуація з'явиться, імплементовано запропоновану логіку

**Comment by ndrhzn** [comment]
Готово на тестовому, можна релізити на публічний

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/9aa8e0f8-a505-47f6-b191-98f864b10f2e)

**Comment by andrzejbeletsky** [comment]
Done
