### ISSUE TITLE
UI / UX: Змінити принцип сортування у фільтрі "Фінансуюча сторона"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#134]
Наразі у фільтрі "Фінансуюча сторона" елементи у нас відсортовані за сумою фінансування кожної окремої фінансуючої сторони. В такий спосіб та організація, котра дає найбільше коштів, є першою у списку.  Проєктний офіс пропонує відмовитися від цього принципу впорядкування елементів на користь або алфавітного впорядкування, або ж впорядкування за кількістюю проєктів).

Видається, що сортування за кількісним показником завше краще, ніж сортування за алфавітом. Тому потрібно впорядкувати організації за кількістю проєктів, профінансованих кожною організацією. Таким чином організація, котра фінансує найбільшу кількість проєктів, має бути першою в списку. А організація, котра фінансує найменшу кількість проєктів - останньою в списку.

Ця зміна заторкає всі інстанції фільтру "Фінансуюча сторона" на сторінках

- Показники
- Проєкти
- Деталі проєктів
- Фінансування
- Деталі фінансування
- Бюджетування
- Всі фільтри

**Comment by andrzejbeletsky** [comment]
Done
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/cf2a7f3f-bb09-42c2-8ea8-af41903cea91/state/analysis

**Comment by ndrhzn** [comment]
Оскільки і тут, і в #141  ми застосовуємо сортування за кількістю проєктів, то порядок фінансуючих сторін / джерел фінансування мав би збігатися в таблиці та у фільтрі. Але чомусь це так не працює  @andrzejbeletsky 

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/117a861a-33b6-49e3-80ba-5cf92bfedb33)

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
це через те, що у фільтрі маємо загальну цифру, а в таблиці є розбивка на декілька рядків, через наявність додаткових розрізів

**Comment by andrzejbeletsky** [comment]
![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/63861139/467238b7-be34-40e3-98ed-357cc7919d8d)

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/4cfb64bc-f648-4116-8d80-bc99f590fd77/state/analysis
Під капотом створені в моделі нові поля (укр та англ) для Громад без додавання області.
Вони стають явно видимі, якщо користувач почне на тримапі кліком вибирати спочатку область і обере громаду, в селекшн буде видно, що відбір зроблено в полі з суфіксом '_'
