### ISSUE TITLE
UI / UX: Додати можливість закривати сторінку "Всі фільтри" не лише за кліком на кнопку "Всі фільтри"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#135]
Сторінка "Всі фільтри" у нас відкривається і закривається лише в один спосіб - за кліком на кнопку "Всі фільтри". Від користувачів маємо відгуки, що для них ця інтеракція є геть неочевидною, і вони не дуже розуміють, як закрити сторінку.

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/e367ad13-655b-4e09-90e6-5ad08455ddcc)

З нашого попереднього обговорення виходило, що для цього немає швидкого рішення, і потрібно окреме залучення R&D.

У цьому підході до задачі потрібно зрозуміти:

- Чи це є в принципі вирішувана задача засобами Mashup
- Якщо це вирішувана задача, то скільки часу це може зайняти

**Comment by ndrhzn** [comment]
#116

**Comment by ndrhzn** [comment]
Давайте спробуємо перший варіант - при натисканні на кнопку "Всі фільтри" замінювати запис на "Закрити". Також опціонально можна заміняти в цей же час іконку із фільтром на іконку із хрестиком

**Comment by ndrhzn** [comment]
@a-radik чи в нас є якісь новини по цій задачі?

**Comment by a-radik** [comment]
Наразі немає. Цього тижня ближче до середини тижня займемось

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у тестовому додатку

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/a3039019-0201-41ac-8dcc-6a542dbf89f7)

Можна застосовувати зміни на публічному додатку
