### ISSUE TITLE
UI / UX: Змінити порядок фільтрів на сторінках "Фінансування", "Деталі фінансування", "Бюджетування", "Всі фільтри"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#136]
Наразі у нас на сторінках "Фінансування", "Деталі фінансування", "Бюджетування" та "Всі фільтри" застосовується такий порядок фільтрів, що стосуються фінансування:

- Фінансуча сторона
- Джерело фінансування
- Тип фінансування

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/98e68e80-0c1b-4434-a975-bfb497480fa0)

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/0fc18453-8531-4a5a-916d-a45d327d401c)

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/58abbba2-cb03-4fa2-af8f-77c8c90db1b3)

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/e69cd022-ee58-40a1-a71c-f1ea0151f80d)

Історично це було зумовлено тим, що ми прагнули йти від конкретного (Фінансуюча сторона, тобто конкретна організація, котра дає кошти) до загального (Тип фінансування, тобто вказівка на те, чи це є державні кошти, чи кошти міжнародних партнерів). Це своєю чергою було вмотивовано інтерпретацією сторінок "Фінансування" та "Деталі фінансування" як таких, що сфокусовані на конкретній організації, а не, наприклад, на масиві організацій.

Тепера ми вирішили обернути цю логіку і йти від загального до конкретного. Тому порядок фільтрів на сторінках "Фінансування", "Деталі фінансування", "Бюджетування", "Всі фільтри" має бути такий:

- Тип фінансування (або ж "Категорія фінансування" за новою назвою)
- Джерело фінансування (або ж "Тип джерела фінансування" за новою назвою)
- Фінансуюча сторона (або ж "Джерело фінансування" за новою назвою)

Важливо, що фільтр "Фінансуюча сторона" має лишатися розкритим. Припускаю, що якщо фільтр, котрий іде третім, буде розкритим, а фільтри, котрі йдуть перед ним, будуть закритими, то виглядатиме це не дуже добре. В такому разі можна розкрити також і всі попередні фільтри. І тоді ймовірно потрібно буде зменишити розмір фільтру "Фінансуюча сторона".

**Comment by ndrhzn** [comment]
#125

**Comment by a-radik** [comment]
так в мешапі потрібні зміни. чи потрібно в нативному клієнті зміни пока не розбирались

**Comment by ndrhzn** [comment]
І за ці зміни в мешапі теж десь в середині тижня зможете взятися?

**Comment by a-radik** [comment]
так

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у тестовому додатку

Тут є декілька коментарів  @a-radik @karandinserhii 

- У фільтрі "Джерело фінансування" злетіло сортування. У #134 у нас було зазначено, що у цьому фільтрі джерела фінансування мають бути відсортовані за кількістю проєктів, і @andrzejbeletsky виконав цю задачу, однак зараз джерела фінансування сортовані за алфавітом.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/f81dbb01-01ee-486b-9870-e52e631f6c33)

- Раніше фільтр "Фінансуюча сторона" / "Джерело фінансування" на сторінці "Всі фільтри" був розкритим, але після зміни порядку він став закритим. І загалом всі фільтри, котрі раніше були відкритими, стали закритими.  [Ось тут ми раніше описували, які фільтри мають бути розкритими](https://github.com/open-contracting/bi.dream.gov.ua/issues/116#issuecomment-2056550675). #116 

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/c5763947-b69e-4f68-ab68-695e08647b94)

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у тестовому додатку

- Джерела фінансування відсортовані за кількістю проєктів

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/9dbc2b81-be2e-4d6e-9bc4-8f847267b649)

- Фільтри на сторінці "Всі фільтри" розкриті

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/629a74f5-5b03-46b8-b126-42380d3ccba8)

Можна релізити на публічному додатку
