### ISSUE TITLE
UI / UX: Перекласти слово Values з таблиці "Сектори економіки" на сторінці "Бюджетування"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#137]
На сторінці "Бюджетування" ми маємо таблицю "Сектори економіки", у котрій поміж іншим відображається слово Values.

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/6eed1d7f-6cbf-4b01-950d-a34ac78a7e5f)

Наразі цей елемент не несе ніякої користі, але займає досить багато місця. Втім видається, що прибрати ми його не можемо, бо це просто структурний елемент pivot table в Qlik. В такому разі ми маємо щонайменше його перекласти і в українській версії замість Values писати "Значення"

**Comment by ndrhzn** [comment]
Це питання вже піднімалося раніше (#32 ), однак тоді було зазначено, що

> Це залежить від мови вашого браузера. Ми на це не впиваємо, нажаль. Якщо мова браузера російська - буде перекладено українською. Український переклад, вендор поки що не робить, тому ми підкладаємо замість росій1ського український.

[посилання на дискусію](https://github.com/open-contracting/bi.dream.gov.ua/issues/32#issuecomment-1865914286)

Водночас ми все ж маємо переклади для інших елементів інтерфейсу, тому питання в тому, чи ми можемо змінити і переклад цього елементу.

**Comment by ndrhzn** [comment]
Розглянути опцію прибрати Values зовсім, можливо перейти на використання іншого типу зведеної таблиці

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
змінено тип півота і продубльовано налаштування  на альтернативний півот. він не має "Values".
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/cf2a7f3f-bb09-42c2-8ea8-af41903cea91/state/analysis

**Comment by a-radik** [comment]
треба дивитись на проді бо там оновлена тема і там з кольорами вибору вса має бути ок.
скажіть чи підходить така таблиця (варіант відображення). якщо так можна релізити

**Comment by ndrhzn** [comment]
Таблиця підходить

**Comment by a-radik** [comment]
upd. Тему (кольори) треба подивитись, бо для цього об'єкту і справді могли ще не змінювати тему оскільки не було аппруву по зовнішньому вигляду
