### ISSUE TITLE
Bug: Елемент без перекладу / розшифровки на сторінці "Наповнення"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#138]
На сторінці "Наповнення" на певних розмірах екранів у нас стає видимим текст prop_choice. 

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/5cfbf2fe-74a9-48f4-aeda-c33c0df70b26)

У цього елемента має бути людиночитана назва англійською та українською мовами. 

У таблиці  DREAM Translations наразі немає запису prop_choice, але є fldProp_choice (Секції без даних, Sections without data). Чи підходить цей переклад? Чи потрібен якийсь інший з огляду на функціональне призначення підписаного елемента?

**Comment by ndrhzn** [comment]
#30

**Comment by andrzejbeletsky** [comment]
Done
Дивний баг кліка. Не зміг відтворити.
prop_choice не повинно було відображатися зовсім, бо відключена ця опція. Але на цей випадок тепер буде як Оберіть секції без даних, або Select sections without data
