### ISSUE TITLE
UI / UX: Згрупувати за проєктами рядки у таблиці "Деталі" на сторінці "Бюджетування"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#139]
Наразі на сторінці "Бюджетування" ми маємо таблицю "Деталі", у котрій ми показуємо розбивку за статтями бюджету для кожного проєкту. Проблема, з якою стикаються користувачі, полягає в тому, що їм не дуже очевидно, що один проєкт може бути представления декількома рядками таблиці.  

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/311f4595-f0c1-461e-8f22-5791e6051e94)

Ця проблема лише загострюється тим, що користувачі можуть відсортувати рядки не лише за кодом проєкту (за такого сортування статті витрат, що належать до одного проєкту знаходяться поруч), але й за будь-яким іншим показником (і тоді статті витрати, що належать до одного проєкту, можуть знаходитися геть в різних місцях таблиці).

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/09c7513a-34f9-40fd-bfef-9cdceebea918)

Як можна вирішити цю проблему? Чи можна якось згрупувати рядки таким чином, аби завжди було можна ідентифікувати, що певна група рядків належить до одного проєкту?

**Comment by ndrhzn** [comment]
#32

**Comment by ndrhzn** [comment]
Розглянути варіант зробити зведену таблицю, котра постійна розгорнута

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look
Залишилась пряма таблиця, але з відключеною можливістю інтерактивного сортування.
пошук в діменшенах працює.
сортування по коду проєкту.
якщо рядки належать одному проєкту, назва проєкту тільки в першому рядку, щоб не повторювати.

**Comment by andrzejbeletsky** [comment]
для мэшапу треба зміни.
вигляд в нативному клієнті:
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/cf2a7f3f-bb09-42c2-8ea8-af41903cea91/state/analysis

**Comment by ndrhzn** [comment]
До того, що реалізовано у нативному додатку, я би додав сортування статей витрат за загальним орієнтовним бюджетом в межах проєкту

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/f14a1544-346d-4a87-b5cf-b61783a51634)

**Comment by a-radik** [comment]
Деталі треба доробити (змінити на зведену, як домовлялись) оскільки цей варіант має певні вади. Анджей зараз цим займається

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/cf2a7f3f-bb09-42c2-8ea8-af41903cea91/state/analysis

пробую міняти селекшени на чорний.

**Comment by ndrhzn** [comment]
Дякую, цей варіант справді краще. Але все ще лишається питання, чи можна в рамках проєкту відсортувати значення за кількісним показником?

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/153ebb43-da58-4b5e-8361-8850c09f39da)

Також з точки зору оформлення таблиці, чи може тут бути так, аби було чергування кольорів для рядків? Умовно - один проєкт білий, наступний сірий, і так далі? Аби підкреслити групування і полегшити ідентифікацію записів, котрі належать до одного проєкту?

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look
новий вигляд таблиці Деталі
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/cf2a7f3f-bb09-42c2-8ea8-af41903cea91/state/analysis
Розмальовка зеброю поки не виходить.
як щодо реалізованого варіанту з тоталом по проєкту?

**Comment by ndrhzn** [comment]
Порадився із Проєктним офісом - видається, що варіант без рядка "Всього" більше подобається. Чи ми можемо прибрати цей рядок, але зберегти все інше - сортування проєктів та сортування статей витрат у межах проєкту за бюджетом?

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/cf2a7f3f-bb09-42c2-8ea8-af41903cea91/state/analysis

**Comment by ndrhzn** [comment]
Можна в такому вигляді релізити. Але я би ще попросив розтягнути по ширині, бо зара не вписується повністю в контейнер

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/2192d277-0e8b-4f53-a6b7-ecc2d3bdb2e5)

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by a-radik** [comment]
В новому об'єкті по-іншому реалізовано кольори вибору значень. Вони не регулюються темой додатку. Можливо зробити це через стилі при відображенні в мешапі. Орієнтовно потрібно 2-3 години щоб знайти потрібний стиль і все налагодити в мешапі.
Робимо?

**Comment by ndrhzn** [comment]
Гаразд, робимо

**Comment by ndrhzn** [comment]
Тут у нас також була підзадача "розтягнути таблицю по ширині контейнера", по котрій було зафіксовано in progress, але змін поки не бачу.  @andrzejbeletsky є якісь новини щодо цього?

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/8fb64857-6335-473d-8185-b210b2e35d19)

**Comment by andrzejbeletsky** [comment]
Вдалося розширити за рахунок розширення останнього стовпчика (він є мірою)
https://bi.qnalytics.com/dream/#/budget

**Comment by ndrhzn** [comment]
Добре, дякую! Можна релізити на публічному додатку
