### ISSUE TITLE
UI / UX: Змінити принцип сортування у таблиці "Деталі фінансування"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#141]
Наразі на сторінці "Деталі фінансування" таблиця за замовчуванням відсортована за показником "Підтверджене фінансування".

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/67f8095e-d011-4cbf-a5ff-902d428f178e)

Потрібно трохи змістити акцент і зробити сортування за замовчуванням за кількістю проєктів

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/e989bddd-f12e-4d97-ba27-a17daa784404)

**Comment by ndrhzn** [comment]
#12

**Comment by andrzejbeletsky** [comment]
done

**Comment by ndrhzn** [comment]
Готово на тестовому, можна релізити на публічний

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/c5067f4b-5280-462f-877e-eeb75e89743c)

**Comment by andrzejbeletsky** [comment]
Done
