### ISSUE TITLE
Bug / UI / Mashup: Замінити зелений колір на чорний у таблиці на сторінці "Бюджетування"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#142]
Після оновлення серверу у нас все ще лишаються артефакти від стилів Qlik за замовчуванням

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/00a4004e-de0c-4dd9-a524-453e380d20f1)

Це вже виправлено у фільтрах, однак все ще не виправлено у pivot table

**Comment by ndrhzn** [comment]
#32

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
Зміна відповідних стилей в темі додатку вирішує проблему.
https://bi.qnalytics.com/dream/#/budget
Але стикнувся з новим челенджем - оновлений сервер розробки кліка (Травень 2024) змінив стилі за замовчуванням, тому зелений колір відбору знову повернувся в елементи, які раніше були змінені на чорний.
Для зміни кольору відбору в об'єктах стандартних фільтрах на аркушах в оновленій версії можна тепер зробити рідними параметрами об'єкта (не міняючи тему). Але для інших місць (головний селекшн-бар, селекшени в об'єктах) потрібно знову знайти елементи в темі, щоб зробити колір відбору чорним. 
Питання - поки прод-серевер не оновлений на нову версію, починати пошук в нових стилях чи відкласти цю задачу на час майбутнього оновлення прод-сервера?

**Comment by a-radik** [comment]
@ndrhzn ?

**Comment by a-radik** [comment]
bi.qnalytics.com вже оновили, там остання версія, тому кольори будуть відрізнятись мі версіями

по оновленню, коли будете готові скажете.

стосовно оптимального способу навідь не уявляю що це може бути. Це недокументовані, нестандартні зміни. 

зараз поправили тему, на проді вже має працювати

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у тестовому додатку. Зміни можна застосовувати на публічному додатку

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/3fbd2a72-d840-4ddf-b921-c6a2a57fbb30)

Водночас маю уточнення - тут ще є зелений колір під активною вкладкою контейнера. В який спосіб це виправляється?  @a-radik

**Comment by ndrhzn** [comment]
Дякую, можна в прод

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/11c437dc-80d0-4bed-9f0c-8ee77f4b8b77)
