### ISSUE TITLE
UI / UX / Bug: Відсутнє посилання на сторінку проєкту на DREAM у експорті даних

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#144]
Минулого року ми працювали над тим, аби додати посилання на сторінку проєкту до завантажених даних (йдеться насамперед про сторінку "Деталі проєктів"). 

План був такий

- Відображати посилання на сторінку проєкту на коді проєкту
- Посилання для експорту зберігати у прихованому стовпчику (котрий не відображається у застосунку, але стає доступним під час експорту)

Наразі ми відображаємо посилання на сторінку проєкту на коді проєкту

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/5b5846ea-2812-42d4-a5ac-5f6929db4497)

Але у експортованих даних посилання вже відсутнє

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/c158fbe6-20c3-4c0c-9273-5ea8439dd5e7)

Можливо це якось повʼязано із тим, що ми тепера відображаємо не всі стовпчики у таблиці, але лише частину з них (наприклад, обрані користувачами стовпчики).

В будь-якому разі потрібно зрозуміти, чому це перестало працювати, і виправити ситуацію.

**Comment by ndrhzn** [comment]
#26

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by ndrhzn** [comment]
Готово на тестовому, можна релізити на публічний

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/ec479ba9-28f1-473b-9347-6586209052d4)

**Comment by andrzejbeletsky** [comment]
Done
