### ISSUE TITLE
UI / UX: Прибрати назву області у назві громади у treemap на сторінці "Показники", коли відображаються громади у розрізі областей

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#145]
У попередньому релізі ми зробили розрізнення громад за областями. Лишився один артефакт, одна інстанція, де це розрізнення не є дуже корисним.

На сторінці "Показники" у випадку, коли ми маємо treemap із областями та громадами, підписи областей у громадах є надлишковими, оскільки ми і так знаємо, до якої області належить та чи інша громада. 

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/fb879d26-67d4-4809-9ee5-dcea20899717)

Питання в тому, чи є у нас можливість прибирати назву області тільки на цьому представленні? Тобто, чи ми можемо за сукупністю умов визначити, що частина підпису, котра стосується області, не має відображатися?

**Comment by ndrhzn** [comment]
#128

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/4cfb64bc-f648-4116-8d80-bc99f590fd77/state/analysis
Під капотом створені в моделі нові поля (укр та англ) для Громад без додавання області.
Вони стають явно видимі, якщо користувач почне на тримапі кліком вибирати спочатку область і обере громаду, в селекшн буде видно, що відбір зроблено в полі з суфіксом '_'
