### ISSUE TITLE
UI / UX: Додати можливість завантажувати дані з візуалізацій у контейнері

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#146]
У попередньому релізі ми додали можливість експортувати дані з візуалізацій. Однак ми також зрозуміли, що немає можливості експортувати дані з карт, і що візуалізації, котрі знаходяться у контейнері, мають спільний для всіх click action (спільну іконку для експорту даних). 

Це означає, що якщо в контейнері є карта і графік, тоді ми або можемо

- Показувати іконку експорту даних для всіх візуалізацій в контейнері включно з картою - із розумінням того, що експорт даних з карти все одно не працюватиме (отже, користувачі можуть клікати на іконку, однак нічого не відбуватиметься)
- Не показувати іконку експорту даних в контейнері взагалі

В минулому релізі ми обрали другий шлях, і таким чином для візуалізацій, котрі знаходяться у контейнері, експорт даних наразі неможливий. Водночас ми зафіксували, що "Для об'єктів, що знаходяться в контейнері, на сторінках "Показники", "Проєкти", можна буде пропрацювати відображення кнопки заватаження для всіх, крім мапи" ([посилання на дискусію](https://github.com/open-contracting/bi.dream.gov.ua/issues/119#issuecomment-2060733505))

**Comment by ndrhzn** [comment]
#119

**Comment by ndrhzn** [comment]
@a-radik чи у нас є якісь новини по цій задачі?

**Comment by a-radik** [comment]
Наразі немає. Цього тижня ближче до середини тижня займемось

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у тестовому додатку. Можна застосовувати зміни на публічному додатку

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/719c0596-c3b2-42dc-ab03-0c2dcba10aac)
