### ISSUE TITLE
Data: Додати стовпчик "Дата останнього оновлення" до таблиці "Деталі проєктів"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#147]
У таблиці "Деталі проєктів" у нас є стовпчик "Дата створення проєкту", однак користувачі також у деяких сценаріях потребують стовпчика "Дата оновлення проєкту".

На рівні даних проєкту ця інформація знаходиться у елементі **updated** (або ж, якщо йти від повної адреси JSON, **cdu_response/updated**).

Ці стовпчики потрібно додати після стовпчика "Дата створення проєкту". За замовчуванням він має бути прихованими, але у користувачів має бути вибрати їх для відображення через панель "Оберіть стовпчики для відображення".

**Comment by ndrhzn** [comment]
#10 #117

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
done

**Comment by ndrhzn** [comment]
Готово на тестовому, можна релізити на публічний

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/d599dcad-48cc-4355-b207-f3438b6beb0d)

**Comment by andrzejbeletsky** [comment]
Done
