### ISSUE TITLE
Data:  Додати на сторінку "Деталі проєктів" інформацію про "Проєкти МФО", "Програми державного бюджету" та "Програми місцевого бюджету", "Форма надання фінансування" та "Вид допомоги"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#148]
У нас в даних зʼявились нові елементи, котрі стосуються фінансування. Отже, ми можемо додати їх до аналітичного додатку. 

елемент даних | назва українською | назва англіською
-- | -- | --
approaches/budget/finance/classification/financeProjectid або approaches/budget/finance/classification/financeProjectName | Проєкт МФО | IFI project
approaches/budget/finance/classification/budgetProgramName | Програма державного бюджету | State budget program
approaches/budget/finance/classification/localBudgetProgramKFKName | Програма місцевого бюджету | Local budget program
approaches/budget/finance/measures/fundingForm | Форма надання фінансування | Funding form
approaches/budget/finance/measures/fundingType | Вид допомоги | Type of assistance

**Проєкти МФО**

Назва **проєкту МФО** може походити або з кодліста, або ж зі змінної approaches/budget/finance/classification/financeProjectName.

Сценарій тут такий - якщо approaches/budget/finance/classification/financeProjectid="other", тоді назву проєкту нам потрібно брати з елементу approaches/budget/finance/classification/financeProjectName.

Втім, якщо pproaches/budget/finance/classification/financeProjectid != "other", тоді нам потрібно дивитися у кодліст (додаю кодліст в оригінальній формі, оскільки він достатньо довгий і його немає сенсу включати сюди в якості таблиці).

Для змінних "Форма надання фінансування" та "Вид допомоги" нам потрібно буде використовувати кодлісти.

**Форма надання фінансування**

код | назва українською | назва англійською
-- | -- | --
grant | грант | grant
credit | кредит | loan
contribution | безповоротна допомога | contribution
support | технічна допомога | technical assistance

**Вид допомоги**

код | назва українською | назва англійською
-- | -- | --
financial | фінансова підтримка | financial support
nonFinancial | нефінансова (натуральна) підтримка | non-financial support

Ці стовпчики потрібно додати після стовпчика "Юридичні підстави використання коштів". За замовчуванням вони мають бути прихованими, але у користувачів має бути вибрати їх для відображення через панель "Оберіть стовпчики для відображення".

**Comment by ndrhzn** [comment]
[dream_budget_financingProject.json](https://github.com/open-contracting/bi.dream.gov.ua/files/15414066/dream_budget_financingProject.json)

**Comment by ndrhzn** [comment]
#10 #117

**Comment by andrzejbeletsky** [comment]
нові елементи не завантажувались з API.
додав завантаження

**Comment by andrzejbeletsky** [comment]
done
take a look

**Comment by ndrhzn** [comment]
Українська версія

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/e6fa904c-20a1-40d5-9c70-9d57d8ef4cc8)

Англійська версія

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/3053abf8-98be-43b0-85bc-f81296094c6d)

Готово на тестовому, можна релізити на публічний

**Comment by andrzejbeletsky** [comment]
Done
