### ISSUE TITLE
UI / Filters: Додати фільтр "Профінансованість" на сторінку "Бюджетування"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#149]
У минулому релізі ми додали розріз "Профінансованість", що категоризує проєкти на такі у яких фінансування "Відсутнє", присутнє "Частково" або ж наявне "Повністю".

Наразі цей фільтр є на сторінці "Всі фільтри" , а також на сторінках "Показники", "Проєкти" і "Деталі проєктів". Нам також потрібно його додати до сторінки "Бюджетування".

Можна додати цей елемент перед фільтром "Ініціатор"

**Comment by ndrhzn** [comment]
#125 #116

**Comment by andrzejbeletsky** [comment]
Done

**Comment by ndrhzn** [comment]
Готово на тестовому, можна релізити на публічний

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/9d9e4035-6b5f-4981-a2ab-3b96e988f2f9)

**Comment by andrzejbeletsky** [comment]
Done
