### ISSUE TITLE
UI / UX: Якщо проєкт має декілька обʼєктів, відображати їх через кому у таблиці "Деталі проєктів"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#150]
У нас наразі можливі ситуації, коли в одному проєкті є декілька обʼєктів. У такому разі у таблиці "Деталі проєктів" це відображається таким чином, що для кожного обʼєкта створюється окремий рядок.

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/777c778a-6743-44d4-9004-436bb7d4638a)

Ми вже стикалися із цим у #48, і домовились для одного проєкту завжди мати тільки один рядок. Якщо у нас є декілька значень для якоїсь змінної (наприклад, декілька ініціаторів або ж декілька громад), ми даємо їх в одній комірці через кому.

Подібний підхід потрібно застосовувати і для обʼєктів.

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look 
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/b7011c65-e80e-4ce8-850a-d567bafcdc80/state/analysis

Тепер у таблиці стовпчики Назва об'єкта, Сектор, Підсектор, Область, Район, пов'язаних з об'єктами, не є вимірами. Пошук за цими полями здійснюється з панелей фільтрів.

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у тестовому додатку (для перевірки використовується код 310524-2CC3BA01, за яким у публічному додатку все ще відображається два рядки)

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/9eecef20-7199-40d9-9e8b-52369cc003f9)

Можна застосовувати зміни у публічному додатку

**Comment by ndrhzn** [comment]
Чи ми можемо застосувати ці зміни на публічному додатку, @andrzejbeletsky ?  Там вже є випадки, коли у проєктів 29 обʼєктів, користувачі не дуже розуміють, як то відчитувати

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/3a6be76a-2cc1-4a67-beab-a55a85064449)

**Comment by andrzejbeletsky** [comment]
Треба разом з мешапом, бо на аркушах змінилась кількість об'єктів.
@karandinserhii Чи маємо готовність до релізу мешапу в прод?
