### ISSUE TITLE
UI / UX: Заміняти картку "Кількість джерел фінансування" на сторінці "Фінансування", коли обрано одне джерело фінансування

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#151]
На сторінці "Фінансування" у нас є картка "Кількість джерел фінансування"

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/a72a6079-260f-4e79-90b2-2cf92026b678)

Коли обрано лише одне джерело фінансування, від цієї картки мало користі

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/ab947aac-ea7b-423f-b4be-44ab51fd95a3)

Водночас користувачі зауважили, що одна з найперших речей, котру вони хочуть бачити, коли обрано одне джерело фінансування - загальна кількість проєктів, підтриманих цим джерелом фінансування.

У нас є окремі картки "Кількість повністю профінансованих проєктів" та "Кількість частково профінансованих проєктів", і загальну кількість, звісно, можна отримати, склавши докупи ці два значення. Однак це є додаткове зусилля, і в деяких випадках (коли кількість проєктів є великою)  - це є операція, котру без калькулятора частина користувачів виконати не зможе.

Тому пропонується така зміна: Якщо обране одне джерело фінансування, замість картки "Кількість джерел фінансування" показувати картку "Кількість проєктів", що має відповідати загальній кількості проєктів, профінансованих обраним джерелом фінансування.

Якщо ця зміна неможлива, тоді можемо розглянути варіант показувати загальну кількість проєктів у таблиці - замість слова Totals (за аналогією з тим, як ми робимо це у таблиці "Деталі проєктів")

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/9e97c60d-6dd8-491c-aa8b-8ac52e9948d6/state/analysis

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано у тестовому додатку

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/1e9ed7e6-a379-44a2-afd8-29992dd8d1e9)

Можна застосовувати зміни у публічному додатку
