### ISSUE TITLE
Data: Додати елемент "Створювач проєкту" до таблиці "Деталі проєктів" та сторінки "Всі фільтри"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#155]
У моделі даних зʼявилась нова роль організації (party role) в проєкті - projectAuthor. Ця роль запроваджена на позначення організації, котра власне завела проєкт у систему.  

```
"parties": [
      {
        "id": "UA-EDR-05408846",
        "roles": [
          "balancer",
          "projectAuthor",
          "implementer",
          "initiator"
        ],
        "identifier": {
          "id": "05408846",
          "scheme": "UA-EDR",
          "legalName": "Ірпінська міська рада"
        }
      }
    ]
```

Українська назва ролі - "Створювач проєкту", англійська назва - "Project author".

Нам потрібно додати новий елемент "Створювач проєкту" до аналітичного модулю

- Як новий фільтр на сторінку "Всі фільтри" до блоку "Залучені організації". Цей елемент має бути першим у списку перед фільтром "Ініціатор"

- Як новий стовпчик до таблиці "Деталі проєктів". Цей стовпчик має йти перед стовпчиком "Ініціатор". За замовчуванням він має бути прихованим, але у користувачів має бути можливість обрати цей стовпчик для відображення за допомогою бокового меню "Оберіть стовпчики для відображення"

Як у випадку зо всіма іншими організаціями, ми хочемо бачити в цьому стовпчику і назву організації, і код ЄДРПОУ у форматі "Назва організаці | Код ЄДРПОУ" (parties/identifier/legalName | parties/identifier/id)

**Comment by ndrhzn** [comment]
Обговорення:

- Також додаємо на стрінку "Наповнення" у якості розрізу
- Естімейт ~ 2 години
- Зміни в мешапі не потрібні

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
done
