### ISSUE TITLE
Data: Додати до таблиці "Деталі проєктів" стовпчик "Кількість обʼєктів"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#156]
У нас наразі стала можливою ситуація, коли один проєкт має декілька повʼязаних обʼєктів (максимум станом на сьогодні - 29).

```
"relatedProcesses": [
      {
        "id": "xfpen4f9-9w3j-4ucu-b81o-7167q968r00l",
        "scheme": "UA-DREAM",
        "identifier": "q77rnx0r-8sb5-43u9-bi00-55oo96egy1i8",
        "relationship": "object"
      },
      {
        "id": "w53mx22k-96j2-43nx-b1pr-39e1h542ppp8",
        "scheme": "UA-DREAM",
        "identifier": "8d9b4omg-298d-4046-8wac-4c5d0c57zi6y",
        "relationship": "object"
      },
      {
        "id": "tom3j99n-55b5-47w6-b3h5-4nz9t3d341fw",
        "scheme": "UA-DREAM",
        "identifier": "h3d800m7-7k75-41q2-b380-hu6104442gr0",
        "relationship": "object"
      }
```
    
Тому є потреба відображати у таблиці "Деталі проєктів" стовпчик "Кількість обʼєктів" / "Number of objects".

Цей стовпчик має йти після стовпчика "Назва обʼєкта". За замовчуванням він має бути прихованим, але у користувачів має бути можливість обрати його через бокову панель "Оберіть стовпчики для відображення".

**Comment by ndrhzn** [comment]
Обговорення

- Естімейт - ~15 хв
- Зміни в мешапі не потрібні

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
done
