### ISSUE TITLE
Data: Додати до таблиці "Деталі проєктів" стовпчик "Орієнтовна тривалість"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#157]
У моделі даних зʼявився новий елемент, що позначає тривалість проєкту - cdu_response/period/durationInMonth

```
"period": {
      "durationInMonth": 8
    }
```

Потрібно додати цей елемент до таблиці "Деталі проєктів" після стовпчика "Характер проєкту". За замовчуванням цей стовпчик має бути прихованим, але у користувачів має бути можливість обрати його для відображення через бокову панель "Оберіть стовпчики для відображення".

Українська назва елементу - "Орієнтовна тривалість, місяців", англійська - "Forseen duration, months". 

У деяких проєктів цей елемент може бути відсутній, в такому разі ми можемо позначати відсутні дані як "-".

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
done
