### ISSUE TITLE
Data: Транслітерувати назви організацій для відображення на англомовній версії додатку

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#158]
В одному з попередніх релізів ми транслітерували назви юридичних осіб у джерелах фінансування. Наразі пропонується застосувати цю ж операцію для всіх організацій у проєкті, оскільки ми й досі відображаємо назви організацій українською мовою в англійській версії додатку.

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/2de7765e-6815-4e92-a9d1-3139348e10b7)

Транслітерацію потрібно застосувати до всіх змінних, що позначають організації, а саме

- Створювач проєкту (нове поле)
- Ініціатор
- Орган управління
- Виконавець
- Балансоутримувач

Після застосування транслітерації при переключенні на англомовну версію додатку користувачі мають бачити транслітеровані назви організацій у графіках та таблицях.

**Comment by ndrhzn** [comment]
Обговорення

- Естімейт ~ до 2 годин
- Зміни в мешапі не потрібні

**Comment by andrzejbeletsky** [comment]
done
