### ISSUE TITLE
Data / UI: Перейменувати змінну "Підтверджене фінансування" / "Confirmed funding"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#159]
У рамках уніфікації назв елементів між секторальною системою, публічним порталом, та аналітичним модулем, маємо потребу перейменувати змінну "Підтверджене фінансування" / Confirmed funding.

Нова назва змінної - **Наявне фінансування / Commited funding**.

Ця зміна заторкає всі інстанції цієї змінної на аркушах

- Показники
- Проєкти
- Деталі проєктів
- Фінансування
- Деталі фінансування
- Бюджетування

**Comment by ndrhzn** [comment]
Обговорення

- ~ 30 хвилин
- Зміни в мешапі не потрібні

**Comment by andrzejbeletsky** [comment]
done
