### ISSUE TITLE
Bug: Розмір фільтрів "Район" і "Громада" на сторінці "Всі фільтри"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#161]
На вкладці "Всі фільтри" внаслідок змін у мешапі змінився розмір фільтрів "Район" і "Громада". Тепера за один раз можна бачити лише один елемент. 

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/43458395-4f14-4c7c-bf16-bac96f562dbd)

Пропонується зробити фільтри "Область", "Район" і "Громада" однакового розміру, аби вони рівномірно заповнювали сторінку по висоті екрану.

**Comment by ndrhzn** [comment]
Обговорення

    Не відображати фільтри розгорнутим
    Естімейт - 15 хв
    Зміни в мешапі не потрібн

**Comment by andrzejbeletsky** [comment]
done
