### ISSUE TITLE
UX / Filters: Деталі фінансових програм > Фільтр "Фінансова програма"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#162]
> Наразі фільтр "Фінансова програма" працює таким чином, що якщо його застосувати, то зникають показники з частини стовпчиків
> 
> 
> 
> Фільтр не застосований
> 
> 
> 
> ![зображення](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/38f8c636-4601-4990-8b93-d43c7cafb2cc)
> 
> 
> 
> Фільтр застосований
> 
> 
> 
> ![зображення](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/fb105dd6-71d2-45f7-a0ba-ca83fc15e4ec)
> 
> 
> 
> Видається, що це не дуже правильна поведінка. Як це має працюєвати - уявімо, що у нас в цій таблиці є дані щодо 10 різних фінансових програм, нам потрібно обрати лише ті проєкти, які мають фінансування в рамках якоїсь фінансової програми. 
> 
> 
> 
> Отже, коли ми обираємо щось у фільтрі "Фінансова програма", фільтрація має застосовуватись насамперед до проєктів, а не до окремих стовпчиків, що стосуються фінансування.
> 

 _Originally posted by @ndrhzn in [#154](https://github.com/open-contracting/bi.dream.gov.ua/issues/154#issuecomment-2202328422)_

**Comment by ndrhzn** [comment]
Обговорення

- Естімейт - до двох годин
- Зміни в мешапі не потрібні

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
done
