### ISSUE TITLE
Data: Деталі фінансових програм > Надійшло / Disbursed

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#163]
> У моделі даних зʼявились нові елементи, котрі вказують на фінансовий прогрес в проєкті, зокрема на те, скільки коштів надійшло. Наразі, здається, лише один проєкт має цей елемент даних заповненим, однак ми вже можемо будувати процес обробки даних для відображення у таблиці.
> 
> 
> 
> Потрібні нам дані містяться в елементі cdu_response/approaches/implementation/financialProgress/breakdown
> 
> 
> 
> ```
> 
> "implementation": {
> 
>     "financialProgress": {
> 
>       "breakdown": [
> 
>         {
> 
>           "id": "0235c342-4781-4e83-8e31-699d4c171903",
> 
>           "period": {
> 
>             "endDate": "2024-05-31",
> 
>             "startDate": "2024-05-01"
> 
>           },
> 
>           "measures": {
> 
>             "disbursed": 21127088
> 
>           },
> 
>           "classifications": {
> 
>             "budgetFinanceId": "76467cb0-1f42-c8d5-f4f1-5dcae53eecdb"
> 
>           }
> 
>         },
> 
>         {
> 
>           "id": "4d90b9df-886a-4b0c-872e-a47c78dc24f6",
> 
>           "period": {
> 
>             "endDate": "2024-06-30",
> 
>             "startDate": "2024-06-01"
> 
>           },
> 
>           "measures": {
> 
>             "disbursed": 35211813
> 
>           },
> 
>           "classifications": {
> 
>             "budgetFinanceId": "76467cb0-1f42-c8d5-f4f1-5dcae53eecdb"
> 
>           }
> 
>         },
> 
>         {
> 
>           "id": "70d50484-3cc3-47ab-b670-c9b025795c2b",
> 
>           "period": {
> 
>             "endDate": "2024-08-31",
> 
>             "startDate": "2024-08-01"
> 
>           },
> 
>           "measures": {
> 
>             "disbursed": 11510589
> 
>           },
> 
>           "classifications": {
> 
>             "budgetFinanceId": "76467cb0-1f42-c8d5-f4f1-5dcae53eecdb"
> 
>           }
> 
>         },
> 
>         {
> 
>           "id": "80b31c62-c16c-4d2d-bcb0-a6f11d33dae0",
> 
>           "period": {
> 
>             "endDate": "2024-07-31",
> 
>             "startDate": "2024-07-01"
> 
>           },
> 
>           "measures": {
> 
>             "disbursed": 35211813
> 
>           },
> 
>           "classifications": {
> 
>             "budgetFinanceId": "76467cb0-1f42-c8d5-f4f1-5dcae53eecdb"
> 
>           }
> 
>         }
> 
>       ]
> 
>     }
> 
>   }
> 
> ```
> 
> 
> 
> cdu_response/approaches/implementation/financialProgress/breakdown/measures/disbursed - вказує на те, скільки коштів надійшло
> 
> 
> 
> cdu_response/approaches/implementation/financialProgress/breakdown/classifications/budgetFinanceId - вказує на те, з якого джерела даних походять кошти
> 
> 
> 
> Тобто, аби визначити, чи це "Надійшло. Державний бюджет", чи "Надійшло. Місцевий бюджет", нам потрібно звʼязати 
> 
> cdu_response/approaches/implementation/financialProgress/breakdown/classifications/budgetFinanceId із cdu_response/approaches/budget/finance/id.
> 
> 
> 
> Скажімо, у цьому прикладі у нас  cdu_response/approaches/implementation/financialProgress/breakdown/classifications/budgetFinanceId = "76467cb0-1f42-c8d5-f4f1-5dcae53eecdb".
> 
> 
> 
> Якщо ми подивимось у елемент cdu_response/approaches/budget/finance, там можна знайти запис із відповідним id
> 
> 
> 
> ```
> 
> {
> 
>     "id": "76467cb0-1f42-c8d5-f4f1-5dcae53eecdb",
> 
>     "value": {
> 
>       "amount": 103061303,
> 
>       "currency": "UAH"
> 
>     },
> 
>     "period": {
> 
>       "endDate": "2024-12-31",
> 
>       "startDate": "2024-01-01"
> 
>     },
> 
>     "status": "committed",
> 
>     "measures": {
> 
>       "fiscalYear": 2024,
> 
>       "relatedItem": "498d8222-a541-4b7a-9073-c5775ba2ef84"
> 
>     },
> 
>     "legalBasis": "Постанова Кабінету Міністрів України від 28 квітня 2023 р. № 419 (зі змінами)",
> 
>     "financeType": "stateFunds",
> 
>     "classification": {
> 
>       "budgetProgramId": "2211310",
> 
>       "budgetProgramKVK": "221",
> 
>       "budgetProgramName": "Субвенція з державного бюджету місцевим бюджетам на облаштування безпечних умов у закладах, що надають загальну середню освіту"
> 
>     },
> 
>     "financeCategory": "centralBudget",
> 
>     "relatedProcesses": [
> 
>       {
> 
>         "id": "rje2f34f-gac0-4mfc-8n39-7w00ze6p30gg",
> 
>         "scheme": "UA-DREAM",
> 
>         "identifier": "8w2ht6q5-613z-4td5-9rin-1s28he8p11e9",
> 
>         "relationship": "fundingProgram"
> 
>       }
> 
>     ]
> 
>   }
> 
> 
> 
> ```
> 
> 
> 
> В цьому елементі ми також можемо подивитися financeCategory і встановити, що це кошти державного бюджету. Отже, надходження ми можемо кваліфікувати як "Надійшло. Державний бюджет". За цим же принципом ми можемо ідентифікувати і "Надійшло. Місцевий бюджет" та "Надійшло. Інші джерела"
> 
>  

 _Originally posted by @ndrhzn in [#154](https://github.com/open-contracting/bi.dream.gov.ua/issues/154#issuecomment-2205586949)_

**Comment by ndrhzn** [comment]
Обговорення

- Естімейт - 3 години
- Зміни в мешапі не потрібні

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by ndrhzn** [comment]
@andrzejbeletsky давайте це релізнемо в прод зараз, бо "Проєктний офіс" має потребу бачити це

**Comment by andrzejbeletsky** [comment]
done

**Comment by andrzejbeletsky** [comment]
done
