### ISSUE TITLE
Bug: Розрізнення громад з однаковими назвами та типом у межах області

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#164]
Раніше ми вже вирішували проблему розрізнення громад з однаковими назвами за областями. Зокрема ми додали до назви громади тип громади та назву області. Однак користувачі звернули увагу, що у нас можлива сиутація, коли в межах однієї області можуть бути дві громади з однаковими назвами та типом (але різними районами).

Приклад, на який звернули увагу:

- Миколаївська громада, Синельниківський район, Дніпропетровська область
- Миколаївська громада, Дніпровський район, Дніпропетровська область

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/cc872f68-f81b-4ab4-96f4-455999e8b729)

У нас вони рахуються як одна громада, оскільки обидві громади належать до однієї області, мають однаковий тип, а розрізнення за районом ми не маємо. 

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/7a7d1927-c4f3-4892-9ee6-c4a3b105f84d)

Як ми можемо вирішити цю проблему? Чи єдиний варіант - додати назву району до назви громади?

**Comment by ndrhzn** [comment]
Обговорення

- Можливо показувати їх окремими стовпчиками, а додаткову інформацію виводити в тултіпі
- Можливо додавати назву району після назви громади

Рішення

- Додаємо назву району після назви громади
- Проаналізувати, на які елементи це впливає (таблиця Деталі проєктів, Treemap на сторінці Показники) і як їх потрібно змінити
- Естімейт - 3 години
- Зміни в мешапі не потрібні

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
done
take a look

**Comment by ndrhzn** [comment]
Хоча в контексті цієї задачі #165 теж набуває нових нюансів, оскільки на цьому графіку ми не можемо просто показати N/A, нам тут важлива привʼязка до області

**Comment by a-radik** [comment]
Це і [165](https://github.com/open-contracting/bi.dream.gov.ua/issues/165) вже можна публікувати, правильно?

**Comment by ndrhzn** [comment]
Так
