### ISSUE TITLE
Сторінка: Фінансові програми, заявки

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#166]
Потрібно створити нову сторінку

Назва сторінки: Фінансові програми, заявки / Financial programs, submissions
Адреса сторінки: /submissions
Можлива іконка: Щось на зразок [lui-icon lui-icon--run-script](https://qlik-oss.github.io/leonardo-ui/icons.html)

Місце сторінки в боковому меню:  Після сторінки "Деталі фінансових програм"

Ця сторінка буде містити наступні елементи (для цих елементів у нас будуть окремі задачі):

- [ ] Картки #167 
- [ ] Графіки #173 
- [ ] Таблиця #168 
- [ ] Фільтри #169

**Comment by ndrhzn** [comment]
#167

**Comment by ndrhzn** [comment]
Розташування елементів на сторінці

![Image](https://github.com/user-attachments/assets/aa55deba-a3c0-4b0b-aadc-648c1db4f422)

**Comment by ndrhzn** [comment]
#168 #169

**Comment by a-radik** [comment]
Вітаю.
Подивився проміжний результат в мешапі і гадаю, що нам варто обговорити деякі зміни в підході. Ось що маємо на разі якщо відкривати на широкому екрані

![Image](https://github.com/user-attachments/assets/4d2323c9-31f8-455e-ad7d-5a1b77685b78)

це вигляд на менших екранах
![Image](https://github.com/user-attachments/assets/965200c4-a7d6-4a1e-9f1c-6a9aa8c142f1)

Що пропонується:

- відв'язати бублік зліва від показників. По-перше для кількості отриманих і кількості схвалених заявок графік не змінюється. По-друге для заявників і проектів це збиватиме користувача з пантилику бо в заявника нема статусу, а в проєктів статуси інші, а насправді графік відображатиме кількості заявників за статусами  заявок де вони присутні і до тогож в заявника може бути декілька заявок в різних статусах сума частинок на графіку не буде збігатись з показником. Загалом такі речі не можна показувати на дольовій діаграмі. Пропоную її лишити окремо щоб вона показувала  посто загальну кількість заявок за статусами. Якщо користувач захоче подивитись цю інформацію по області/громаді/заявнику він може скористатись відборами
- стовбчикову діаграму, що відображає кількості за вибраним покаником винести окремо на аркуші. Що я помітив в мешапі це велика кількість вільного, місця. це мсце можна зайняти стовбчивою діаграмою і додати в діаграму можливість вибору розрізу (т.зв. альтернатимні виміри). 
- в таблиці є грошові міри але на візуалізації вони відсутні. пропонується додати наприклад, bullet chart, який буде відображати наявне фінансування порівняно до кошторису або фінансового запиту за вибором
- в таблиці є область, громада і заявник. За структурою джерела даних може мати делілька значень на одну заявку. Гадаю що буде корисним, якщо користувачі натимуть змогу обирати відповідні значення кліком по таблиці, для цього ці колонки треба переробити з мір на обраховувані виміри

@ndrhzn , що скажете, якщо треба, давайте проговоримо на колі ці зміни

**Comment by ndrhzn** [comment]
Ще не мав можливості переглянути оновлення. Трохи згодом сьогодні подивлюся
та відпишу щодо цього

**Comment by a-radik** [comment]
Зауважу, що мешап ми не викладали, дивіться в нативному клієнті

**Comment by ndrhzn** [comment]
**[Уніфікація назв на англійській версії сторінки]**

У нас на сторінці в англійській версії на позначення заявки у деяких випадках вживається submission, а в деяких - application. Потрібно все уніфікувати.

Ось перелік обʼєктів, котрі потрібно перейментувати в таблиці та у панелі фільтрів:

- Submission code > Application code
- Submission date > Application date
- Submission status > Application status

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by a-radik** [comment]
@ndrhzn Мені цей варіант лейауту подобається більше. Чи є у вас зауваження чи можемо взяти це в роботу для мешапу?
@andrzejbeletsky прибери будь ласка borders в контейнері на цьому аркуші

**Comment by ndrhzn** [comment]
@a-radik щодо вигляду та розташування елементів відкоментував ось тут #173 . Щодо bullet chart - поки не робимо, але можливо трохи згодом повернемось, коли буде краще розуміння сценаріїв

**Comment by a-radik** [comment]
@ndrhzn 
https://bi.qnalytics.com/dream/#/submissions

**Comment by ndrhzn** [comment]
Дякую, дивимось!

Поки є таке побажання:

- Оскільки ми всюди вирішили писати не submissions, а applications, то Проєктний офіс попросив замінити також адресу сторінки

**Comment by a-radik** [comment]
готово
https://bi.qnalytics.com/dream/#/applications

**Comment by ndrhzn** [comment]
**[Взаємодія між графіком і таблицею]**

Виявив дивну поведінку таблиці, що виникає, якщо використовувати стовпчиковий графік в якості фільтра за заявником.

Почнемо з того, що застосуємо фільтр за однією з областей (просто, аби зменшити вибірку і було простіше спостерігати зміни)

На графіку ми можемо бачити заявників. У таблиці ми можемо бачити ініціаторів.

![image](https://github.com/user-attachments/assets/6c5488c1-6a57-45ff-a373-8bff9a23cb56)

Далі оберемо на графіку якогось одного заявника - наприклад того, що має найбільшу кількість заявок. У таблиці чомусь зникають значення зі стовпчику "Ініціатор".

![image](https://github.com/user-attachments/assets/7f892c15-1da3-494b-a862-2f1c15f68c91)

Чому так відбувається, і як це виправити? @andrzejbeletsky

**Comment by andrzejbeletsky** [comment]
виправив баг
