### ISSUE TITLE
Фінансові програми, заявки: Таблиця

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#168]
**Джерела даних** 

- [Submissions endpoint](https://public-api.dream.gov.ua/marketplace/public/dream/submissions) 
- [Ideas endpoint](https://public-api.dream.gov.ua/marketplace/public/dream/ideas)
- [Prequalifications endpoint](https://public-api.dream.gov.ua/marketplace/public/dream/prequalifications)
- [IFI Projects endpoint](https://public-api.dream.gov.ua/marketplace/public/dream/ifiprojects)
- [ISB e-construction endpoint](https://public-isb.dream.gov.ua/isb/e-construction/design-documentation?design-task-code=)

**Звʼязки між різними сутностями**

У цій таблиці повʼязані / представлені сутностей - **Заявки** (submissions), **Відбори** (prequalifications), **Фінансові програми** (ifiprojects), **Проєкти** (ideas), **Проєктно-кошторисна документація** (e-construction).

Основною сутністю у нас у цій таблиці є Заявки. 

Заявки повʼязані із Проєктами (relatedProcesses, relationship="project") та Відборами (relatedProcesses, relationship="qualification").

Відбори повʼязані із Фінансовими програмами (relatedProcesses, relationship="fundingProgram").

Тобто, якщо у нас є потреба **встановити, до якої фінансової програми належить заявка**, нам потрібно:

- Встановити, із яким Відбором повʼязана заявка
- Встановити із якою Фінансовою програмою повʼязаний відбір

Якщо у нас є потреба **встановити наявне фінансування**, нам потрібно:
- Встановити, із яким Проєктом повʼязана заявка
- У даних фінансування проєкту встановити, яким є обсяг фінансування в рамках фінансової програми (при цьому цей елемент буде лише в тих випадках, якщо заявка була схвалена)

Якщо у нас є потреба **отримати інформацію про Загальну кошторисну вартість по заявці**, нам потрібно:

- Встановити, із яким Проєктом повʼязана заявка
- У даних проєкту знайти код техічного завдання
- Звернутися до Проєктно-кошторисної документації і отримати там загальну кошторисну вартість

**Елементи даних**

name_ua | name_en | default_state | endpoint | path | notes
-- | -- | -- | -- | -- | --
Код проєкту | Project code | visible | ideas | cdu_response/internal_code | JOIN via submissions endpoint > cdu_response/relatedProcesses/identifier WHERE cdu_response/relatedProcesses/relationship = "project"
Код заявки | Submission code | hidden | submissions | cdu_response/internal_code |  
Дата створення | Date | hidden | submissions | cdu_response/date |  
Опис | Description | visible | submissions | cdu_response/items/description/translation | WHERE cdu_response/items/description/lang = "uk"
Статус заявки | Submission status | visible | submissions | cdu_response/status |  
Фінансова програма | Financial program | visible | ifiprojects | cdu_reponse/title/translation | WHERE cdu_response/title/lang = “uk”. JOIN submission to prequalification, JOIN prequalification to ifiproject via relatedProcesses
Заявник | Applicant | visible | submissions | cdu_response/parties/identifier/legalName \| cdu_response/parties/identifier/id | WHERE cdu_response/parties/roles LIKE "%applicant%"
Ініціатор | Initiator | hidden | submissions | cdu_response/parties/identifier/legalName \| cdu_response/parties/identifier/id | WHERE cdu_response/parties/roles LIKE "%initiator%"
Погоджувач | Approver | hidden | submissions | cdu_response/parties/identifier/legalName \| cdu_response/parties/identifier/id | WHERE cdu_response/parties/roles LIKE "%approver%"
Область | Region | visible | submissions | cdu_response/parties/address/addressDetails/territory/id | WHERE cdu_response/parties/roles LIKE “%applicant%”
Район | District | hidden | submissions | cdu_response/parties/address/addressDetails/territory/id | WHERE cdu_response/parties/roles LIKE “%applicant%”
Громада | Community | visible | submissions | cdu_response/parties/address/addressDetails/territory/id | WHERE cdu_response/parties/roles LIKE “%applicant%”
Сума фінансового запиту | Amount of money requested | visible | submissions | cdu_response/items/value/amount |  
Загальна кошторисна вартість | Total estimated cost | visible | isb, e-construction | designDocumentation/costEstimate/amount/estimate_val | JOIN sumbission to project via relatedProcesses, extract design task code from project (cdu_response/approaches/items/additionalClassifications/id where cdu_response/approaches/items/additionalClassifications/scheme = "UA-SESC"), query isb e-construction
Наявне фінансування | Confirmed funding | visible | ideas | cdu_response/approaches/budget/finance/value/amount | WHERE cdu_response_approaches/budget/finance/financeCategory = ‘centralBudget’. JOIN submission to project via relatedProcesses

**Comment by andrzejbeletsky** [comment]
"У даних фінансування проєкту встановити, яким є обсяг фінансування в рамках фінансової програми (при цьому цей елемент буде лише в тих випадках, якщо заявка була схвалена)"
Як виясняємо, чи була заявка схвалена?

**Comment by ndrhzn** [comment]
> Як виясняємо, чи була заявка схвалена?

Статус заявки = active

**Comment by ndrhzn** [comment]
Естімейт - 4 години (плюс до того, що вже було зроблено)

**Comment by andrzejbeletsky** [comment]
done
take a look

**Comment by ndrhzn** [comment]
Це, очевидно, артефакт #165 

![image](https://github.com/user-attachments/assets/0eaefbf5-5ae3-4649-818a-568cf4cb6ca8)

**Comment by ndrhzn** [comment]
Здається, тут загубився стовпчик "Опис"

**Comment by ndrhzn** [comment]
**[Заявки без назви фінпрограми]**

У цій таблиці у нас є проблема із тим, що назва фінансової програми відображається лише для тих проєктів, які мають схвалені заявки. 

Чому так відбувається?  Видається, що так не має бути.

Візьмемо для прикладу одну з заявок, для котрої не відображається назва фінпрограми - 310524-B8CA5E68, статус - Очікує розгляду.

Якщо подивитися на дані цієї заявки за її ідентифікатором - [k700xa79-r23b-484c-8g0h-vz4hjnti59a4](https://public-api.dream.gov.ua/marketplace/public/dream/submissions/k700xa79-r23b-484c-8g0h-vz4hjnti59a4), - там ми побачимо такі relatedProcesses

```
"relatedProcesses": [
      {
        "id": "sy5m8bi5-hyno-4081-b4cx-te318845g064",
        "scheme": "UA-DREAM",
        "identifier": "9g6730py-st3o-4g9s-9062-s563m7973j14",
        "relationship": "project"
      },
      {
        "id": "37nev182-qzi5-4i7v-9n97-w2iog3220450",
        "scheme": "UA-DREAM",
        "identifier": "n983q44a-f670-4e39-9yvz-3cx2ina5wt84",
        "relationship": "qualification"
      }
    ]
```

Тут нас цікавить той запис, що має `"relationship": "qualification"`. За ідентифікатором цього процесу - [n983q44a-f670-4e39-9yvz-3cx2ina5wt84](https://public-api.dream.gov.ua/marketplace/public/dream/prequalifications/n983q44a-f670-4e39-9yvz-3cx2ina5wt84) - ми можемо звернутися до даних відбору. У цих даних буде такий масив relatedProcesses

```
"relatedProcesses": [
      {
        "id": "b7k10rlv-r5na-4l4y-a5hm-0xlw896174b9",
        "scheme": "UA-DREAM",
        "identifier": "35hclg3d-07o5-4zal-as22-401ixjl4uk00",
        "relationship": "fundingProgram"
      }
    ]
```

Тут є ідентифікатор фінпрограми. Якщо ми звернемось з цим ідентифікатором - [35hclg3d-07o5-4zal-as22-401ixjl4uk00](https://public-api.dream.gov.ua/marketplace/public/dream/ifiprojects/35hclg3d-07o5-4zal-as22-401ixjl4uk00) - до ifiprojects endpoint, там має знайтися назва фінансової програми

```
"title": [
      {
        "lang": "uk",
        "translation": "Субвенція з державного бюджету місцевим бюджетам на придбання обладнання, створення та модернізацію (проведення реконструкції та капітального ремонту) їдалень (харчоблоків) закладів загальної середньої освіти"
      },
      {
        "lang": "en",
        "translation": ""
      }
    ]
```

@andrzejbeletsky чи ви застосовували якусь іншу логіку, чи з якоїсь причини ця не спрацювала?

**Comment by ndrhzn** [comment]
**[Сума фінансового запиту = 0]**

У нас досить багато записів, де сума фінансового запиту = 0. На практиці, припускаю, це означає, що у заявці відсутня інформація про суму фінансового запиту (це ймовірно може бути валідна ситуація у певних статусах заявки). У таких випадках є сенс робити так само, як ми робимо із загальною кошторисною вартістю, коли в нас немає даних для цього показника (#186 )

![image](https://github.com/user-attachments/assets/d533e06f-1e35-4877-8310-a6b540a7fec3)

**Comment by ndrhzn** [comment]
**[Кількість заявок, відображення усіх заявок у таблиці, акцент на заявках у таблиці]**

Наразі у нас таблиця відображає 370 записів - за кількістю проєктів, а не заявок. Таким чином ми отримуємо не всі дані щодо заявок у таблиці, а також акцент зміщується з заявок на проєкти. Маємо це виправити, оскільки таблиця, і загалом вся сторінка, має бути саме про заявки. 

Тому першим стовпчиком у нас нехай буде код заявки. Звісно, він має бути visible by default. Другим стовпчиком може бути код проєкту, він може бути hidden by default.

Код заявки ми згодом перетворимо на посилання на сторінку заявки на порталі (коли заявки отримають свої сторінки на порталі)

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/4db2d41f-92d2-49db-9050-c9c37af50ccf/state/analysis

**Comment by ndrhzn** [comment]
**[Перетворити код заявки на посилання на сторінку заявки]**

На порталі нарешті зʼявилися сторінки заявок:

- Приклад посилання на українську версію https://dream.gov.ua/ua/application/DREAM-UA-230424-E82E4042 (`https://dream.gov.ua/ua/application/DREAM-UA-{code}`)
- Приклад посилання на англіську версію https://dream.gov.ua/application/DREAM-UA-230424-E82E4042 (`https://dream.gov.ua/application/DREAM-UA-{code}`)

Нам потрібно зробити так, аби код заявки був посиланням на сторінку заявки - аналогічно тому, як ми робимо із проєктами. 

Під час експорту таблиці з даними посилання на заявку має бути окремим стовпчиком. 

Якщо користувачі знаходяться на українській версії BI, посилання має вести на українську версію заявки, якщо на англійській версії BI - посилання має вести на англійську версію заявки

**Comment by ndrhzn** [comment]
**[Проблема із описами заявок]**

Здається, всі заявки наразі мають однаковий опис

![зображення](https://github.com/user-attachments/assets/315e1534-a404-4d0f-9750-b87890669c96)

**Comment by ndrhzn** [comment]
**[Додати стовпчики "Сектор" та "Виконавець фінансової програми" до таблиці]**

Проєктний офіс попросив додати два нових стовпчики до таблиці - "Сектор" та "Виконавець фінансової програми"

name_ua | name_en | default_state | endpoint | path | notes
-- | -- | -- | -- | -- | --
Сектор | Sector | hidden | ifiprojects | cdu_response/sector | IF number of character in cdu_response/sector = 1
Виконавець фінансової програми | Implementer of the financial program | hidden | ifiprojects | cdu_response/parties/legalName \| cdu_response/parties/ | WHERE cdu_response/parties/roles LIKE "%implementer%"

Розташування цих стовпчиків у таблиці буде описано окремим коментарем, оскільки також є побажання щодо зміни порядку інших стовпчиків.

**Comment by ndrhzn** [comment]
**[Змінити порядок стовпчиків]**

Порядок стовпчиків у таблиці та у боковій панелі "Оберіть стовпчики для відображення"

Код заявки
Дата створення
Код проєкту
Заявник
Ініціатор
Погоджувач
Фінансова програма
Виконавець фінансової програми
Сектор
Статус заявки
Опис
Область
Район
Громада
Сума фінансового запиту
Загальна кошторисна вартість
Наявне фінансування

**Comment by andrzejbeletsky** [comment]
take a look
географія пов'язана з #173

**Comment by andrzejbeletsky** [comment]
take a look
