### ISSUE TITLE
Data: Додати стовпчик "Загальна кошторисна вартість" до таблиці "Деталі фінансових програм"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#170]
У таблиці "Деталі фінансових програм" потрібно додати стовпчик "Загальна кошторисна вартість / Total estimated cost".

Цей стовпчик має знаходитися перед стовпчиком "Сума фінансового запиту", після стовпчика "Код бюджету, з якого здійснюється співфінансування проєкту". За замовчування стовпчик має бути видимим.

Дані для цього стовпчика мають надходити з ISB e-construction endpoint.

Структура запиту 

`https://public-isb.dream.gov.ua/isb/e-construction/design-documentation?design-task-code={design-task-code}`

Сам design-task-code у нас знаходиться у даних проєкту в елементі `cdu_response/approaches/items/additionalClassifications/id` WHERE `cdu_response/approaches/items/additionalClassifications/scheme = “UA-SESC”`

Тобто у даних проєкту нам потрібно взяти ідентифікатор ПКД, звернутися з ним до АРІ, і у відповіді взяти елемент `designDocumentation/costEstimate/amount/estimate_val`

**Comment by ndrhzn** [comment]
#154

**Comment by ndrhzn** [comment]
Давайте підвищимо пріоритет цієї задачі, оскільки "Проєктний офіс" має потребу у ньому для зовнішніх партнерів @andrzejbeletsky

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
готово
переносити в прод?

**Comment by ndrhzn** [comment]
Видається так, що там в оригінальних даних одиниця виміру - "тис грн", тому нам потрібно множити цей показник на 1000, аби отримати коректний результат

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Дякую! Зараз виглядає коректно. Можна релізити на прод

**Comment by andrzejbeletsky** [comment]
готово на проді
