### ISSUE TITLE
Data / Bug: Показник "Сума укладених контрактів" у таблиці "Деталі проєктів" відсутній у проєктів з укладеними контрактами

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#171]
Виявив, що у нас в таблиці “Деталі проєктів” є проєкти з укладеними контрактами, але із показником “Сума укладених контрактів” = 0.

Наразі нарахував 1164 таких проєкти. 

Відсутність даних може бути повʼяазана зі зміною моделі даних в АРІ. Аби виправити проблему, потрібно зрозуміти, де потрібно брати інформацію про суму укладеного контракту.

**Comment by andrzejbeletsky** [comment]
https://public-api.dream.gov.ua/marketplace/public/dream/ideas/1ct02n1i-s6ja-4me8-bxc4-r98h44jvw94r
contracts не має value:amount
По іншим, гадаю, таке саме

**Comment by ndrhzn** [comment]
Та, це я вже перевірив також, тепера думаю, як нам із цим працювати, бо фактично дані про суму контракту можуть бути в трьох різних місцях

- `contractingProcesses/summary/contracts/value/amount`
- `contractingProcesses/relatedProcesses/details/amount` (для тих випадків, коли процедура поза Prozorro)
- брати ідентифікатор контракту та йти з ним в ISB (для тих випадків, коли елемент `contractingProcesses/summary/contracts/value/amount` відсутній, але ідентифікатор контракту є)

Це видається загалом не дуже гарною стратегією, але з великою ймовірністю якийсь час доведетсья із цим працювати.

Альтернативно можна спростити цю схему і навіть не дивитися у contractingProcesses/summary/contracts/value/amount, а одразу брати дані з ISB.
