### ISSUE TITLE
Data: Не враховувати контрактні процедури зі статусом cancelled у таблиці "Деталі проєктів"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#172]
Наразі у нас в таблиці "Деталі проєктів" у стовпчику "Кількість контрактних процедур" враховуються всі контрактні процедури в проєктах, незалежно від їхніх статусів. При цьому частина цих контрактних процедур може мати статус cancelled, отже відображати / враховувати їх не має сенсу.

| cdu_response_contractingProcesses.id | summary_status |
| ------------------------------------------- | -------------- |
| 613                                         | cancelled      |
| 245                                         | complete       |
| 2995                                        | implementation |
| 692                                         | preparation    |

Тобто в якості правила можна зафіксувати, що для розрахунку показника "Кількість контрактних процедур" ми не враховуємо процедури зі статусом cancelled.

**Comment by andrzejbeletsky** [comment]
done
