### ISSUE TITLE
Фінансові програми, заявки: Графіки

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#173]
На сторінці "Фінансові програми, заявки" нам потрібно створити наступні графіки

- **Розподіл заявок за статусами**. Цей графік має відповідати на питання на зразок - якою є частка підтриманих (або відхилених) заявок із числа отриманих заявок.

> **Джерело даних:** [submissions endpoint](https://public-api.dream.gov.ua/marketplace/public/dream/submissions)
>
> **Елементи даних:** cdu_response/status, internal/code
>
> **Форма презентації:** Donut chart (за аналогією з тим, як ми презентуємо розподіл проєктів за статусами)
>

- **Розподіл заявок за заявником**.  Цей графік має відповідати на питання, які організації є найбільш активними у подачі заявок

> **Джерело даних:** [submissions endpoint](https://public-api.dream.gov.ua/marketplace/public/dream/submissions)
>
> **Елементи даних:** internal/code, cdu_response/parties/identifiers/legalName | cdu_response/parties/identifiers/id WHERE cdu_response/parties/roles LIKE "%applicant%" AND cdu_response/parties/identifiers/scheme = "UA-EDR"
>
> Форма презентації: Стовпчиковий графік, де по осі Y відображаються організації, а по осі Х - кількість заявок

-  **Розподіл заявок за регіонами**. Цей графік має відповідати на питання - з яких регіонів надійшла найбільша / найменше кількість заявок (або ж - які регіони є більш активними, а які є менш активними)

> **Джерело даних:** [submissions endpoint](https://public-api.dream.gov.ua/marketplace/public/dream/submissions)
>
> **Елементи даних:** Internal/code, cdu_response/parties/address/addressDetails/territory/id WHERE cdu_response/parties/roles LIKE “%applicant%” AND cdu_response/parties/address/addressDetails/territory/scheme = "UA-CATOTTG"
>
> **Форма презентації:** Карта. За замовчуванням ми маємо бачити дані у розрізі областей, але якщо користувачі обирають у фільтрі конкретну область, тоді ми маємо бачити дані у розрізі громад цієї області

**Розташування графіків**

Розташування графіків описано в загальній задачі, що стосується сторінки. 

Важливо, що ми пропонуємо не показувати графік "Розподіл заявок за статусом" та "Розподіл заявок за заявником" одночасно. 

Ми показуємо графік "Розподіл заявок за статусом" за замовчуванням, але у користувачів має бути можливість обрати для відображення вимір "заявник" і побачити графік "Розподіл заявок за заявником" - за аналогією з тим, як це реалізовано на сторінці "Показники", де у користувачів є можилвість обрати для відображення на стовпчиковому графіку різні виміри.

**Взаємодія з іншими елементами сторінки**

Графіки мають змінюватися залежно від того, яка картка є обраною. Пропонуємо наступні варіанти відображення графіків залежно від обраної картки

обрана картка | графік за статусами | графік за заявниками | карта
-- | -- | -- | --
Кількість отриманих заявок | Кількість отриманих заявок у розрізі статусів | Кількість отриманих заявок у розрізі заявників | Кількість отриманих заявок у розрізі регіонів
Кількість схвалених заявок | Кількість отриманих заявок у розрізі статусів | Кількість схвалених заявок у розрізі заявників | Кількість схвалених заявок у розрізі регіонів
Кількість заявників | Кількість заявників у розрізі статусів їхніх заявок (тобто, з загальної кількості заявників - скільки мають схвалені заявки, скільки мають відхилені заявки, і т.д.) | Кількість отриманих заявок у розрізі заявників | Кількість заявників у розрізі регіонів
Кількість проєктів | Кількість проєктів у розрізі статусів | Кількість проєктів у розрізі заявників | Кількість проєктів у розрізі регіонів

**[Кодліст статусів заявки](https://standards.dream.gov.ua/mdm/directories/financial-submission-statuses)** 

id | en | uk
-- | -- | --
pending | pending | Очікує розгляду
draft | draft | Чернетка
approval | approval | На погодженні
active | active | Схвалено
withdrawn | withdrawn | Відкликано
unsuccessful | unsuccessful | Не схвалено

**Comment by ndrhzn** [comment]
Естімейт - 16

**Comment by andrzejbeletsky** [comment]
done
take a look

**Comment by ndrhzn** [comment]
**[Зміни у графіках]**

@a-radik справедливо [зауважив деякі проблеми](https://github.com/open-contracting/bi.dream.gov.ua/issues/166#issuecomment-2283650902) із тим, як у нас наразі виглядають та працюють графіки.

Що тут можна зробити

- Відвʼязати donut chart від карток / показників. Це видається правильним рішенням, оскільки справді привʼязка до показників / карток може лише заплутувати

- Або прибрати з donut chart легенду та відсортувати сегменти за числовим показником від найбільшого до найменшого, або переробити donut chart на bar chart без використання кольорового кодування в принципі

- Стовпчиковий графік, що відображає обраний показник у розрізі заявників, справді можна винести окремо, якщо для цього є місце

Щодо інших запропонованих змін ще міркуємо

**Comment by ndrhzn** [comment]
[Заявки без привʼязки до громади / Проблеми з відображенням заявок на карті]

У нас наразі можливі ситуації, коли внаслідок вибору певного заявника на карті нічого не відображається. Ця проблема походить з того, що ми тут спираємось на дані щодо розташування заявника (`cdu_response/parties/address/addressDetails/territory/id`), і, як видно з наведеного прикладу, у цих даних часто може бути відсутня деталізація до рівня громади.

![image](https://github.com/user-attachments/assets/8752ee9a-5c06-4321-819c-92808a1e2757)

Як можна вирішити цю проблему?

- Можна брати дані щодо розташування не з адреси заявника, а з адреси обʼєкту інвестицій в заявці (cdu_response/items/locations/gazetteer/identifiers WHERE cdu_response/items/locations/gazetteer/scheme = "UA-CATOTTG"). Тут ми припускаємо, що рівень деталізації розташування обʼєкту інвестицій має зазначатися більш детально, ніж адреса заявника. Це видається найбільш оптимальним варіантом для цієї задачі.
- Якщо цей варіант не дасть нам бажаних результатів, тоді можна буде спробувати брати розташування обʼєкта із повʼязаного проєкта.

**Comment by a-radik** [comment]
Уточнюю, як саме має це працювати: в разі відсутності даних про заявника отримувати гео дані з об'єктів інвестицій, а в разі відсутності останніх брати дані проєктів?
Чи завжди брати дані з одного з наведених джерел?

**Comment by ndrhzn** [comment]
Видається, що краще спробувати брати все з одного джерела. Тобто зараз, скажімо, перестати використовувати дані щодо адреси заявника, і натомість використовувати дані щодо розташування обʼєкту інвестицій в заявці.

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
![зображення](https://github.com/user-attachments/assets/49ee2595-b7e4-4a05-ad0f-8f18235be6cb)

Є декілька коментарів:

- Чи є якісь варіанти налаштування donut chart, які б дозволили не обрізати підписи, а також бачити нормально сегмент для категорії "Відхилено"? Зараз ми бачимо підпис "Відхилено", але без додаткових зусиль не зможемо побачити сам сегмент та зрозуміти значення? Якщо таких варіантів немає, тоді ймовірно є сенс відмовитися від використання donut chart на користь bar chart

- Layout загалом краще, але хочеться ще трохи допрацювати. Міркуємо про те, чи не зробити всі контейнери однакової ширини? А також можна спробувати зробити карту в центральному контейнері, тоді буде такий порядок
   1) Графік за статусами
   2) Карта
   3) Графік за заявниками

**Comment by ndrhzn** [comment]
**[Donut chart / графік розподілу за статусами]**

Відповіді щодо donut chart так і не отримав, і наразі у нас на тесті він знову з легендою. При цьому легенда вся не вміщається у контейнер, і підписи у нас дублюються і в легенді, і на графіку. 

![зображення](https://github.com/user-attachments/assets/45777ef7-98e1-4291-b0a5-6d639506d8e9)

Видається, що найпростіше - не шукати варіанти налаштування donut chart, а просто замінити його на bar chart

**Comment by ndrhzn** [comment]
**[Дані щодо розташування]**

Навіть після зміни елемента даних, з котрого ми забираємо дані щодо розташування, проблема лишається (хіба що можливо трохи змінилася її природа). Наразі маємо досить багато записів, для котрих у нас немає інформації навіть про область (припускаю, це просто випадки, де відсутні дані щодо розташування обʼєкту інвестицій). 

Отже, на карті ми не бачимо повних даних навіть на рівні областей, що вже казати про громади.

![зображення](https://github.com/user-attachments/assets/88305995-3fa4-4f78-8519-0ab9c39010e0)

Порадившись із Проєктним офісом, пропонуємо спробувати ще раз змінити підхід, і забирати дані щодо розташування з даних повʼязаного з проєктом обʼєкта (тобто так, як ми робимо у всіх інших модулях).

Це стосується і стовпчиків "Область", "Район", "Громада" у таблиці, і, звісно, даних, з яких відмальовується карта.

**Comment by andrzejbeletsky** [comment]
in progress
перероблюю на географію об'єктів

**Comment by andrzejbeletsky** [comment]
take a look
