### ISSUE TITLE
Data: Додати стовпчик "Код обʼєкта в РПЗМ" до таблиці "Деталі проєктів"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#174]
До таблиці "Деталі проєктів" потрібно додати новий стовпчик

**Назва**: "Код обʼєкта в РПЗМ" / RDDP code
**Розташування**: Після стовпчика "Заклад МОЗ"
**Джерело даних**: [objects endpoint](https://public-api.dream.gov.ua/marketplace/public/dream/objects)
**Елемент даних**:  `cdu_response/relatedProcesses/identifier` WHERE `cdu_response/relatedProcesses/scheme=‘UA-RDDP’`
**Default state**: hidden

На рівні даних у цьому елементі наразі можливі невалідні значення на зразок '-', 'testAnna', 'ВІДСУТНІЙ', 'иаиииии', 'н\б', 'На даний час в РПЗМ не внесено', 'на даний час не внесено В РПЗМ', 'Не внесено', '0', а також інші варіанти, котрі на практиці можуть не бути кодами обʼєктів в РПЗМ. Наразі ми пропрацьовуємо це з Проєктним офісом, аби зрозуміти, як краще обробляти такі випадки. В ідеалі вони мають бути виправлені на рівні джерела даних, але якщо це не є можливим, тоді нам потрібно буде придумувати, як обробляти їх на стороні BI.

**Comment by ndrhzn** [comment]
Естімейт - 1.5 години
Зміни в мешапі - не потрібні

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Загалом все добре. Треба тільки зробити поправку на матчинг лише валідних кодів РПЗМ, описану ось тут #175. У цій таблиці нам потрібно виводити лише валідні коди РПЗМ

**Comment by ndrhzn** [comment]
Готове до релізу на прод

**Comment by a-radik** [comment]
@andrzejbeletsky
