### ISSUE TITLE
UI: Згорнути фільтр "Джерело фінансування" на сторінці "Фінансування"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#176]
За аналогією із тим, як ми зробили на сторінці "Бюджетування", на сторінці "Фінансування" потрібно згорнути фільтр "Джерело фінансування", оскільки на певних розмірах екрану він відображається у розгорнутому вигляді некоректно.

![Image](https://github.com/user-attachments/assets/6f5ae0e9-a24b-4d57-a141-14491fdc36bc)

**Comment by andrzejbeletsky** [comment]
done

**Comment by ndrhzn** [comment]
Можна на прод

**Comment by andrzejbeletsky** [comment]
done
