### ISSUE TITLE
Data: Заповнити на сторінці "Деталі фінансових програм" показник "Сума ще не виділених коштів"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#177]
На сторінці "Деталі фінансових програм" у нас зарезервований показник "Сума ще не виділених коштів", що розраховується як різниця між "Заплановано" та "Надійшло" у розрізах "Державний бюджет", "Місцевий бюджет", "Інші джерела". 

Оскільки у нас вже є показник "Надійшло", ми нарешті можемо додати і показник "Сума ще не виділених коштів".

**Comment by ndrhzn** [comment]
#163 #154

**Comment by andrzejbeletsky** [comment]
done
take a look

**Comment by andrzejbeletsky** [comment]
done
