### ISSUE TITLE
Data: Додати стовпчик "Витрачено" до таблиці "Деталі фінансових програм"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#178]
У нас наче нарешті зʼявились дані для показника "Витрачено" . Ці дані знаходяться у елементі `contractingProcesses/summary/contracts/implementations/financialProgress/breakdown/measures/paid`.

Приклад елементу `contractingProcesses/summary/contracts/implementations/financialProgress/breakdown`

```
{
  "id": "a9a61ac7-25b5-4e76-9c07-db4ae0e3ca2e",
  "period": {
    "endDate": "2023-12",
    "startDate": "2023-12"
  },
  "measures": {
    "paid": 3515872.94,
    "signed": 3515872.94
  },
  "classifications": {
    "date": "2024-07-10T09:35:11.630587Z",
    "contractingFinanceId": "f9974410-ccf8-41c4-9ed6-6e65d6d5f4bb"
  }
}
```

Нам треба взяти цей показник і привʼязати його до джерела фінансування, використовуючи `contractingProcesses/summary/contracts/implementations/financialProgress/breakdown/classifications/contractingFinanceId`.

Логіка буде наступна:

- Ми беремо елемент `contractingProcesses/summary/contracts/implementations/financialProgress/breakdown/classifications/contractingFinanceId`

- У масиві `contractingProcesses/summary/budget/finance` ми шукаємо `contractingProcesses/summary/budget/finance/classification/budgetFinanceId` де `contractingProcesses/summary/budget/finance/id` = `contractingProcesses/summary/contracts/implementations/financialProgress/breakdown/classifications/contractingFinanceId`

- У масиві `approaches/budget/finance` ми шукаємо елемент, у якому `approaches/budget/finance/id` = `contractingProcesses/summary/budget/finance/classification/budgetFinanceId` з попереднього кроку. У знайденому елементі ми можемо звернутися до елементу "financeCategory", що буде вказувати на те, чи фінансування надходить із державного бюджету, місцевого бюджету, чи інших джерел фінансування.

---

Наприклад, у проєкті [9a41s188-xid4-4p99-b27q-2j0s8g7b47k0](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/9a41s188-xid4-4p99-b27q-2j0s8g7b47k0) ми маємо `contractingProcesses/summary/contracts/implementations`

```
{
  "financialProgress": {
    "breakdown": [
      {
        "id": "1bf01135-b92c-43ef-88cb-f90ad761af93",
        "period": {
          "endDate": "2023-11",
          "startDate": "2023-11"
        },
        "measures": {
          "paid": 1912519.59,
          "signed": 1912519.59
        },
        "classifications": {
          "date": "2024-07-04T10:20:38.680810Z",
          "contractingFinanceId": "ce42d22e-433a-4ce2-a399-de9ed5b7814b"
        }
      }
    ]
  }
}
```

Ідентифікатор, котрий нас цікавить - `ce42d22e-433a-4ce2-a399-de9ed5b7814b`.

У елементі `contractingProcesses/summary/budget/finance/id` ми можемо знайти відповідник для цього ідентифікатора. Нас цікавить contractingProcesses/summary/budget/finance/classification/budgetFinanceId - `2f0b43e5-b888-4e92-bcac-657f6d71ca92`.

```
{
  "budget": {
    "finance": [
      {
        "id": "94e788e8-5430-4994-8c2e-80bbfaa48dfc",
        "classification": {
          "budgetFinanceId": "8e77fc15-2958-2108-d16a-e17066e37e27"
        }
      },
      {
        "id": "c4dacd53-ed95-4ddb-8603-f3708c371403",
        "classification": {
          "budgetFinanceId": "72bfdb0e-f947-4884-8ff8-328ff66e870c"
        }
      },
      {
        "id": "ce42d22e-433a-4ce2-a399-de9ed5b7814b",
        "classification": {
          "budgetFinanceId": "2f0b43e5-b888-4e92-bcac-657f6d71ca92"
        }
      },
      {
        "id": "d9cc0aab-cf1f-4189-9ad8-ac5bb7ae95fb",
        "classification": {
          "budgetFinanceId": "03d73eb3-e5fc-4dbf-abea-fb833112ab3c"
        }
      }
    ]
  }
}
```

Далі у `approaches/budget/finance` ми можемо знайти запис, де `approaches/budget/finance/id` = 2f0b43e5-b888-4e92-bcac-657f6d71ca92`.

```
{
  "id": "2f0b43e5-b888-4e92-bcac-657f6d71ca92",
  "value": {
    "amount": 8135866.37,
    "currency": "UAH"
  },
  "period": {
    "endDate": "2023-08-18",
    "startDate": "2023-07-14"
  },
  "status": "indicative",
  "measures": {
    "fiscalYear": 2024
  },
  "financeType": "stateFunds",
  "classification": {
    "budgetProgramId": "2211310",
    "budgetProgramKVK": "221",
    "budgetProgramName": "Субвенція з державного бюджету місцевим бюджетам на облаштування безпечних умов у закладах, що надають загальну середню освіту"
  },
  "financeCategory": "centralBudget"
}
```

І вже тут нас цікавить financeCategory.

**Comment by andrzejbeletsky** [comment]
done.
take a look

**Comment by ndrhzn** [comment]
Давайте на прод

**Comment by andrzejbeletsky** [comment]
done
