### ISSUE TITLE
Data: Додати показник "Недофінансована частка проєкта" до таблиці "Деталі фінансових програм"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#179]
Щойно ми додамо до сторінки "Деталі фінансових програм" показник "Загальна кошторисна вартість", можна буде додати і обчислювальний показник "Недофінансована частка проєкта", що має розраховуватись за формулою 

`Загальна кошторисна вартість - 
(Заплановано. Місцевий бюджет + Заплановано. Державний бюджет (субвенція) + Заплановано. Інші джерела)`

Цей показник у нас вже зарезерований, однак наразі всі значення у ньому статичні N/A.

**Comment by ndrhzn** [comment]
#170 #154

**Comment by andrzejbeletsky** [comment]
done
take a look

**Comment by ndrhzn** [comment]
Спершу треба поправити показник "Загальна кошторисна вартість", як описано у #186

**Comment by andrzejbeletsky** [comment]
done
