### ISSUE TITLE
Дані / Розріз / Фільтр: Тип організації / органу управління

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#18]
Є запит додати розріз / фільтр, що вказував би на тип організації. Ця інформація наразі міститься у companies endpoint, в елементі details/classifications, де scheme=“TED-TYPE”. Можливі значення цієї змінної - ministry, administration, centralBody, localBody, enterprise. 

Щонайменше, ми можемо додати це як властивість ініціатора, незалежно від того, як швидко ми імплементуємо “орган управління”, бо ця інформація вже наявна.

**Comment by a-radik** [comment]
@ndrhzn подивились дані. потрібно одразу готувати Кодлісти для цього нового розрізу.

**Comment by ndrhzn** [comment]
Та, звісно. Маю цю задачу у себе.

**Comment by andrzejbeletsky** [comment]
Не завжди присутня схема “TED-TYPE”, тому буде не заповнено "Тип організації"

**Comment by ndrhzn** [comment]
Та, звернув на це увагу теж. Думаю, для організацій без TED-TYPE можна ставити або "Інші", або просто N/A

**Comment by ndrhzn** [comment]
Кодліст [доступний за посиланням](https://github.com/open-contracting/bi.dream.gov.ua/blob/main/codelists/TED-TYPE.csv) @andrzejbeletsky 

Щодо відображення цієї змінної у фільтрі та в таблиці - важливо чітко комунікувати, що саме ми показуємо і за якою ознакою фільтруємо

Якщо тип організації привʼязаний до ініціатора проєкту (зара ніби саме так), то ймовірно має сенс писати "Тип ініціатора" або "Initiator type". 

В майбутньому, коли ми привʼяжемо тип організації до органу управління, будемо писати "Тип органу управління" або "Management body type"
