### ISSUE TITLE
Data: Додати показник "Залишкова кошторисна вартість" до таблиці "Деталі фінансових програм"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#180]
Щойно ми додамо до сторінки "Деталі фінансових програм" показники "Загальна кошторисна вартість" та "Витрачено", можна буде додати і обчислювальний показник "Залишкова кошторисна вартість", що має розраховуватись за формулою.

Загальна кошторисна вартість - (Витрачено. Місцевий бюджет + Витрачено. Державний бюджет (субвенція) + Витрачено. Інші джерела)

Цей показник у нас вже зарезерований, однак наразі всі значення у ньому статичні N/A.

**Comment by ndrhzn** [comment]
#154 #170 #178

**Comment by andrzejbeletsky** [comment]
done
take a look

**Comment by ndrhzn** [comment]
Спершу треба поправити показник "Загальна кошторисна вартість", як описано у #186

**Comment by ndrhzn** [comment]
Якщо "Загальна кошторисна вартість" = NA, то і тут має бути NA

**Comment by andrzejbeletsky** [comment]
done
