### ISSUE TITLE
Data: Не враховувати контрактні процедури зі статусом cancelled для показників "Кількість укладених контрактів" та "Сума укладених контрактів" у таблиці "Деталі проєктів"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#181]
У таблиці "Деталі проєктів" у нас є показник "Кількість укладених контрактів" та "Сума укладених контрактів". 

Оскільки ми вже вирішили не враховувати контрактні процедури зі статусом cancelled для показника "Кількість контрактних процедур", є сенс поширити цю логіку і на розрахунок показників "Кількість укладених контрактів" та "Сума укладених контрактів".

Тобто, загальний підхід такий - ми спершу перевіряємо, чи контрактна процедура не є скасованою. Якщо вона не є скасованою, ми дивимось, чи є у цій контрактній процедурі укладені контракти. Якщо вони є, ми рахуємо їхню кількість та суму.

В принципі, для коректного розрахунку кількості та суми укладених контрактів, нам також треба пересвідчитись, що ми не враховуємо контракти зі статусом cancelled. Але це є частина іншої задачі щодо розрахунку показника "Сума укладених контрактів", повʼязаноʼ зі зміною моделі даних по контрактних процедурах.

**Comment by ndrhzn** [comment]
#172

**Comment by andrzejbeletsky** [comment]
done
take a look

**Comment by ndrhzn** [comment]
Виглядає коректно, можна релізити на прод

**Comment by andrzejbeletsky** [comment]
done
