### ISSUE TITLE
Data: Додати показник "Залишок коштів" до таблиці "Деталі фінансових програм"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#182]
До таблиці "Деталі фінансових програм" потрібно додати новий показник "Залишок коштів", що має розраховуватись за формулою "Заплановано" - "Витрачено".  Звісно, це можна робити лише після того, як буде додано стовпчики із показником "Витрачено".

Цей показник має репрезентуватись у розрізі категорій фінансування. Тобто фактично нам потрібно мати три нових стовпчика

ua | en
-- | --
Залишок коштів. Місцевий бюджет | Balance. Local budget
Залишок коштів. Державний бюджет | Balance. Central budget
Залишок коштів. Інші джерела | Balance. Other

Ці стовпчики мають розташовуватись після стовпчиків із показником "Витрачено". За замовчуванням вони мають бути прихованими, але у користувачів має бути можливість обрати їх через бокову панель "Оберіть стовпчики для відображення".

**Comment by ndrhzn** [comment]
#154 #178

**Comment by andrzejbeletsky** [comment]
in progress
