### ISSUE TITLE
Data: Забирати дані для показника "Сума укладених контрактів" з ISB

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#183]
Через зміну моделі даних контрактних процедур у проєктах у нас наразі для частини контрактних процедур із наявними контрактами відсутня інформація про суму контракту.

Фактично у нас зараз є **два окремих сценарії**, котрі потрібно обробляти
- Коли процедура відбувається поза системою Prozorro
- Коли процедура відбувається у системі Prozorro

**Як ми розрізняємо, які процедури відбуваються у системі Prozorro, а які поза нею?**
- У даних контрактних процедур ми маємо елемент `cdu_response/contractingProcesses/relatedProcesses/details/platform`, що вказує на те, де відбувається процедура
- Значення цього елемента може бути national або international. Якщо значення = "national", це вказує на те, що процедура відбувається у системі Prozorro. Якщо значення = "international", це вказує на те, що процедура відбувається поза системою Prozorro.

Для кожного з цих сценарїів у нас буде окрема **процедура отримання суми контракту**:

- Якщо процедура відбувається поза системою Prozorro, дані про суму контракту мають бути доступні у елементі `cdu_response/contractingProcesses/summary/contracts/value/amount`.
- Якщо процедура відбувається у системі Prozorro, нам потрібно
  1. Відфільтрувати процедури за статусом `cdu_response_contractingProcesses_relatedProcesses.details_status != "cancelled"`
  2. Відфільтрувати процедури за формою звʼязку `cdu_response/contractingProcesses/relatedProcesses/relationship = "procurement"`
  3. Отримати ідентифікатор контракту. Сам ідентифікатор знаходиться в елементі `cdu_response/contractingProcesses/relatedProcesses/details/contract`
  4. Звернутися з цим ідентифікатором контракту до API ISB за схемою `https://public-isb.dream.gov.ua/isb/contracts/{contract_id}`. Наприклад, [https://public-isb.dream.gov.ua/isb/contracts/7b9da3e0ffba47e88e77783c1465ac1a](https://public-isb.dream.gov.ua/isb/contracts/7b9da3e0ffba47e88e77783c1465ac1a)
  5. У відповіді отримати елемент `value/amount`

Звісно, в обох сценаріях ми враховуємо лише ті контрактні процедури, які не є скасованими.

**Comment by ndrhzn** [comment]
#171 #172

**Comment by andrzejbeletsky** [comment]
done
take a look

**Comment by ndrhzn** [comment]
Дякую! Виглядає коректно, можна релізити на прод

**Comment by andrzejbeletsky** [comment]
done
