### ISSUE TITLE
Bug / Data: Ставити NA у показнику "Загальна кошторисна вартість" на сторінці "Деталі фінансових програм" для тих випадків, коли неможливо отримати дані

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#186]
Зараз у нас у чотирьох проєктах на сторінці "Деталі фінансових програм" показник "Загальна кошторисна вартість" дорівнює нулю. 

![Image](https://github.com/user-attachments/assets/4968cfef-573c-48d7-8c0a-f1bfcbd8b146)

Практично це означає, що у даних ISB потрібний нам показник відсутній. Це ми задокументували для команди розробки, аби вони зʼясували, чи проблема в оригінальних даних ЄДЕССБ чи у чомусь іншому.

Зі свого боку ми маємо трохи змінити принцип відображення цих даних, і замість нулів вказувати NA, аби сигналізувати, що дані відсутні, а не що загальна кошторисна вартість дорівнює нулю.

Це своєю чергою також вплине на всі обчислювальні показники. Наприклад, у нас показник "Недофінансована частка проєкту" залежить від показника "Загальна кошторисна вартість". Отже, якщо "Загальна кошторисна вартість" = NA, тоді і "Недофінансована частка проєкту" має бути NA.

**Comment by ndrhzn** [comment]
#170 #179

**Comment by andrzejbeletsky** [comment]
done

**Comment by andrzejbeletsky** [comment]
done
