### ISSUE TITLE
Data / Bug: Проєкти зі схваленими заявками не відображаються у "Деталях фінансових програм"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#187]
Якщо подивитися на кількість проєктів по субвенції на укриття у таблиці "Деталі фінансових програм", то там буде 55 проєктів. Якщо подивиися на кількість проєктів зі схваленими заявками на сторінці "Фінансові програми. Заявки", там буде 57 проєктів.

Два проєкти, котрі наразі не враховуються:

[m8nk2p0c-9ktm-4t68-b5t4-77960lt2i035](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/m8nk2p0c-9ktm-4t68-b5t4-77960lt2i035)
[28q50u64-mm14-4vs2-bffk-x19t405zx1v6](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/28q50u64-mm14-4vs2-bffk-x19t405zx1v6)

Проблема наразі на рівні даних: в одному проєкті відсутній budget/finance в принципі, у іншому відсутній елемент budget/finance/relatedProcesses = ‘fundingProgram’.

Коли ми створювали сторінку "Деталі фінансових програм", ми брали в якості критерію відбору проєктів саме наявність елемента cdu_response/approaches/budget/finance/relatedProcesses = ‘fundingProgram’. 

Ми можемо змінити принцип відбору і брати ті проєкти, які мають схвалені заявки в рамках фінансової програми (оскільки ми вже вибудували звʼязок між проєктами, заявками, та фінансовими програмами).

- Вибудувати звʼязок проєкту із фінпрограмою через заявки та відбори (ми це вже робимо для таблиці на сторінці "Фінансові програми. Заявки")
- Брати для сторінки "Деталі фінансових програм" ті проєкти, що мають статус заявки active

За цією новою логікою нам ймовірно також потрібно змінити підхід до того, звідки ми беремо дані для фільтра "Фінансова програма". 

Наразі ми беремо назву фінансової програми з елемента `cdu_response/approaches/budget/finance/classification/budgetProgramName` у даних проєкта. Однак, якщо у проєкті немає budget/finance в принципі, тоді і цього елемента там природньо не буде. Тому ймовірно для нас має сенс забирати назву фінпрограми власне даних фінпрограми (ifiprojects endpoint, `cdu_reponse/title/translation`).

У фільтрі ймовірно має сенс відображати лише ті фінпрограми, по котрих хоча б є заявки (можливо згодом ми змінимо цю логіку, але наразі навряд є сенс показувати десяток фінпрограм, якщо заявки є лише по двох)

**Comment by ndrhzn** [comment]
#154 #168

**Comment by ndrhzn** [comment]
Поки не застосовуємо ці зміни, оскільки виявилось, що можливі фінпрограми без заявок та відборів. Отже, для таких фінпрограм привʼязка проєктів через заявки та відбори не спрацьовуватиме

**Comment by ndrhzn** [comment]
Тут виходить так, що у нас неминуче може бути декілька способів привʼязки проєктів до фінпрограм. Наразі ми маємо два:
- Через cdu_response/approaches/budget/finance/relatedProcesses
- Через заявки і відбори

Ймовірно згодом зʼявляться додаткові варіанти, котрі потрібно буде опрацьовувати. Це означає, що для визначення привʼязки проєктів до фінпрограм, нам потрібно використовувати сукупність / комбінацію ознак, а не якусь одну ознаку.

**Comment by ndrhzn** [comment]
Якщо повертатися до першопочаткової проблеми - у нас відібрано 57 проєктів, але в таблиці ми бачимо лише 55 - тоді які у нас є варіанти з огляду на все вищезазначене?

Ми не відмовляємось від старого способу визначення привʼязки проєктів до фінпрограм, але додаємо новий.

- У нас є перелік проєктів у привʼязці до фінпрограми, визначений через cdu_response/approaches/budget/finance/relatedProcesses = ‘fundingProgram’ (55 проєктів)
- У нас є перелік проєктів у привʼязці до фінпрограми, визначений через заявки зі статусом active, відбори та власне фінпрограми (57 проєктів)

Наприклад, ми можемо взяти обидва переліки проєктів, обʼєднати їх, та відкинути дублікати. Чи такий підхід має сенс? Чи є інші способи це зробити? @andrzejbeletsky 

Звісно, якби у нас була лише одна фінпрограма, тоді нам би не потрібно було вигадувати це все, але це власне винятково для того, аби ми в майбутньому могли нормально опрацьовувати всі випадки.

**Comment by andrzejbeletsky** [comment]
У нас на різних аркушах різні поля для визначення Фінансової програми.
На аркуші "Деталі фінансових програм" значення береться з budgetProgramName у даних проєкта.
На аркуші "Фінансові програми. Заявки" - з даних фінпрограми (ifiprojects endpoint, cdu_reponse/title/translation).
При об'єднанні переліків проєктів як визначати назву Фінансової програми?

**Comment by ndrhzn** [comment]
Справедливо. Але для однієї фінпрограми назви мають бути однакові в обох джерелах. 

Тому ймовірно є сенс робити таким чином

- Беремо назву фінпрограми та перелік проєктів з першого джерела
- Беремо назву фінпрограми та перелік проєктів з другого джерела
- Обʼєднуємо обидва джерела, відкидаємо дублікати
- Беремо перелік проєктів та назву фінпрограми з цієї нової таблиці

Чи має такий підхід сенс? Чи тут є щось, що потенційно може не спрацювати?

**Comment by andrzejbeletsky** [comment]
Ці 2 джерела мають неоднакові назви Фінпрограм.
Беремо наприклад проєкт "250424-753D758F".
В проєктах це "Субвенція з державного бюджету місцевим бюджетам на облаштування безпечних умов у закладах, що надають загальну середню освіту"
В ifiprojects це "Державна субвенція на облаштування безпечних умов у закладах загальної середньої освіти"

**Comment by ndrhzn** [comment]
Ок, тоді йдемо таким шляхом

- У даних проєктів у нас є ідентифікатор фінпрограми: `cdu_response/approaches/budget/finance/relatedProcesses/identifier`
- Якщо із цим ідентифікатором звернутися до ifiprojects endpoint, тоді там можна взяти назву фінпрграми. В такому разі на `cdu/response/approaches/budget/finance/classification/budgetProgramName` ми навіть не звертаємо уваги.

Чи такий підхід працюватиме?

**Comment by andrzejbeletsky** [comment]
take a look

Note:
На сторінці "Фінансові програми. Заявки" Фінансова програма є тільки в проєктах з активними заявками

**Comment by ndrhzn** [comment]
Дякую! Видається, що зараз все відображається коректно. Припускаю, що ми ще повернемось до питання привʼязки проєктів до фінпрограм, але поточний алгоритм покриває два окремих сценарії, це вже непогано.

Думаю, можна на прод

**Comment by andrzejbeletsky** [comment]
на проді
