### ISSUE TITLE
Data: Додати нові проєкти до таблиці "Деталі фінансових програм"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#194]
У нас зʼявився новий спосіб привʼязки проєктів до фінансових програм - він може бути особливо корисний для тих випадків, коли відбір проєктів на фінпрограму відбувався без використання заявок (але загалом працює для всіх випадків)

Тепера перелік проєктів в рамках фінпрограми можна отримати через ifiprojects endpoint за допомогою додаткового параметра projects

**Структура запиту**

`https://public-api.dream.gov.ua/marketplace/public/dream/ifiprojects/{id}/projects `

**Приклад реального запиту**

- Фінпрограма МОН по укриттях (проєкти вже заведені до таблиці "Деталі фінансових програм") 
https://public-api.dream.gov.ua/marketplace/public/dream/ifiprojects/8w2ht6q5-613z-4td5-9rin-1s28he8p11e9/projects
- Фінпрограма МОЗ по укриттях (проєкти потрібно завести до таблиці "Деталі фінансових програм") 
https://public-api.dream.gov.ua/marketplace/public/dream/ifiprojects/y7l8wi9y-98kg-49nb-btv0-l2385w5g9d35/projects 

**Приклад відповіді**

```
{
  "data": [
    {
      "id": "1ycy78kr-wa36-41f2-b9l3-et8di32uf247",
      "date": "2024-07-26T12:08:27.506975Z"
    },
    {
      "id": "346y34i8-8ful-42k3-a31u-s79dp024xu8y",
      "date": "2024-07-26T12:07:00.423374Z"
    },
    {
      "id": "3870z240-4m68-4hdx-bu2k-6fh9fy00mb14",
      "date": "2024-07-26T12:10:39.296663Z"
    }
  ]
}
```

Наразі нам потрібно додати до таблиці "Деталі фінансових програм" проєкти, відібрані у рамках фінпрорами "Субвенція з державного бюджету місцевим бюджетам на облаштування безпечних умов у закладах охорони здоров’я"
- [Посилання на фінпрограму ](https://public-api.dream.gov.ua/marketplace/public/dream/ifiprojects/y7l8wi9y-98kg-49nb-btv0-l2385w5g9d35)
- [Посилання на проєкти у рамках фінпрограми](https://public-api.dream.gov.ua/marketplace/public/dream/ifiprojects/y7l8wi9y-98kg-49nb-btv0-l2385w5g9d35/projects ) 

Звісно, оскільки в рамках цієї фінпрограми не було заявок і відборів, ми не зможемо відобразити елементи даних, котрі ми традиційно забираємо з заявок - наприклад, суму фінансового запиту. Для таких випадків є сенс ставити N/A.

**Comment by ndrhzn** [comment]
#154

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Дякую! Наче все гаразд, давайте на прод
