### ISSUE TITLE
Інвестиційні проєкти: Таблиця

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#196]
name_ua | name_en | endpoint | path | notes | default state
-- | -- | -- | -- | -- | --
Код інвестиційного проєкту | Investment project code | investmentprojects | internal/code |   | visible
Назва | Title | investmentprojects | cdu_response/title/translation | WHERE cdu_response/title/lang = "uk" |  
Опис | Description | investmentprojects |   |   | hidden
Мета | Purpose | investmentprojects | cdu_response/purpose | тут не буквальні значення, а коди, котрі потрібно буде розшифрувати за допомогою кодліста | hidden
Статус | Status | investmentprojects | cdu_response/status | тут не буквальні значення, а коди, котрі потрібно буде розшифрувати за допомогою кодліста |  
Головний розпорядник коштів | Disposer | investmentprojects | cdu_response/parties/identifiers/legalName \| cdu_response/parties/identifiers/id | WHERE cdu_response/parties/roles LIKE "%disposer%" | visible
Сектор | Sector | investmentprojects | cdu_response/classification/id | WHERE cdu_response/classification/scheme = "WB-ECO" | visible
Підсектор | Subsector | investmentprojects | cdu_response/classification/id | WHERE cdu_response/classification/scheme = "WB-ECO" | hidden
Функціональна природа послуги | Functional nature of the service | investmentprojects | cdu_response/additionalClassifications/id | WHERE cdu_response/additionalClassifications/scheme = "UA-BUDGET-KFK" | hidden
Пріоритет уряду | Government priority | investmentprojects | cdu_response/additionalClassifications/id | cdu_response/additionalClassifications/scheme = "GoU-GOALS" | visible
Код стратегічного рівня | Strategic level code | investmentprojects | cdu_response/additionalClassifications/id + cdu_response/additionalClassifications/uri | cdu_response/additionalClassifications/scheme = "UA-GIS", uri може бути відсутній | hidden
Дата початку | Start date | investmentprojects | cdu_response/period/startDate |   | visible
Дата завершення | End date | investmentprojects | cdu_response/period/endDate |   | visible
Кількість повʼязаних активностей | Number of related projects | investmentprojects | https://public-api-dev.dream.gov.ua/marketplace/public/dream/investmentprojects/{id}//projects | COUNT OF | hidden
Повʼязані активності | Related projects | investmentprojects | https://public-api-dev.dream.gov.ua/marketplace/public/dream/investmentprojects/{id}//projects | COMMA SEPARATED LIST OF internal/code | hidden
Компоненти | Components | investmentprojects | cdu_response/approaches/items/description/translation | WHERE cdu_response/approaches/id = "single" AND cdu_response/approaches/items/description/lang = "uk" | hidden
Ініціатор | Initiator | investmentprojects | cdu_response/parties/identifiers/legalName \| cdu_response/parties/identifiers/id | WHERE cdu_response/parties/roles LIKE "%initiator%" | visible
Виконавець | Implementer | investmentprojects | cdu_response/parties/identifiers/legalName \| cdu_response/parties/identifiers/id | WHERE cdu_response/parties/roles LIKE "%implementer%" | hidden
Ризики | Risks | investmentprojects | cdu_response/riskAllocation/description | Тут може бути декілька ризиків. Потрібно дати їх всі, розділені крапкою з комою | hidden
Стадія проєкту | Stage | investmentprojects | cdu_response/requirementResponses/requirement/id | Отриманий ідентифікатор треба звʼязати із cdu_response/criteria/requirementGroups/requirements/title за допомогою cdu_response/criteria/requirementGroups/requirements/id. При цому cdu_response/criteria/id = "ORTS0029001001000000000000" | visible
Бюджет проєкту | Budget | investmentprojects | cdu_response/budget/budgetBreakdown/amount/amount | SUM OF | visible
Бюджет проєкту на 2025 рік | Year 2025 budget | investmentprojects | cdu_response/budget/budgetBreakdown/amount/amount | SUM OF. WHERE cdu_response/budget/budgetBreakdown/period/startDate ⩾ 2025-01-01 AND  cdu_response/budget/budgetBreakdown/period/endDate ⩽  2025-12-31 | visible
Наявне фінансування | Commited funding | investmentprojects | budget/finance/value/amount | SUM OF | visible
Наявне фінансування. Державний бюджет | Commited funding. Central budget | investmentprojects | budget/finance/value/amount | SUM OF WHERE cdu_response/budget/finance/financeCategory = "centralBudget" | hidden
Наявне фінансування. Місцевий бюджет | Commited funding. Local budget | investmentprojects | budget/finance/value/amount | SUM OF WHERE cdu_response/budget/finance/financeCategory = "localBudget" | hidden
Наявне фінансування. Інші джерела | Commited funding. Other | investmentprojects | budget/finance/value/amount | SUM OF WHERE cdu_response/budget/finance/financeCategory NOT IN [‘centralBudget’, 'localBudget'] | hidden

**Comment by ndrhzn** [comment]
**[Кодліст - Мета інвестиційного проєкту]**

code | ua | en
-- | -- | --
quality | Підвищення якості послуг | Improving the quality of services
improvement | Покращення стану інфраструктури | Improving infrastructure
satisfaction | Задоволення попиту | Demand satisfaction
copmliance | Підвищення рівня відповідності сучасним стандартам | Increasing the level of compliance with modern standards
capacity | Нарощування потужностей | Capacity building
other | Інше | Other

**Comment by ndrhzn** [comment]
**[Класифікатор - Пріоритет уряду]**

```
{
  "additionalClassifications": [
    {
      "id": "030400",
      "scheme": "GoU-GOALS"
    }
  ]
}
```

Для змінної "Пріоритет уряду" ми отримуємо не буквальне значення, а код, котрий нам потрібно розшифрувати, використовуючи класифікатор.

Класифікатор DREAM знаходяться за посиланням `https://standards.dream.gov.ua/classifications`.

Аби отримати значення конкретного коду класифікатора, потрібно надіслати запит до АРІ у форматі `https://standards.dream.gov.ua/classifications/{scheme}:{id}`. Тобто для наведеного вище прикладу запит виглядатиме як `https://standards.dream.gov.ua/classifications/GoU-GOALS:030400`

Якщо надіслати цей запит, то відповідь буде наступна

```
{
  "item": {
    "scheme": "GoU-GOALS",
    "id": "030400",
    "title": {
      "en": "Розвиток мережі дошкільної освіти, повної загальної середньї освіти, професіцйно-технічної освіти",
      "uk": "Розвиток мережі дошкільної освіти, повної загальної середньї освіти, професіцйно-технічної освіти"
    },
    "childrens": false
  }
}
```

У цій відповіді нас цікавить `item/title/uk` та `item/title/en` для української та англійської версії відповідно. Втім, як видно з наведеного прикладу, ймовірно перекладу англійською мовою в нас не буде.

**Comment by ndrhzn** [comment]
**[Класифікатор - Функціональна природа послуги]**

За аналогією із класифікатором "Пріоритет уряду", нам потрібно звернутися із кодом до АРІ довідників.

```
{
  "additionalClassifications": [
    {
      "id": "0921",
      "scheme": "UA-BUDGET-KFK"
    }
  ]
}
```

Для наведеного прикладу запит буде таким:  `https://standards.dream.gov.ua/classifications/UA-BUDGET-KFK:0921`.

Відповідь буде наступна

```
{
  "item": {
    "scheme": "UA-BUDGET-KFK",
    "id": "0921",
    "title": {
      "en": "Заклади загальної середньої освіти",
      "uk": "Заклади загальної середньої освіти"
    },
    "childrens": false
  }
}
```

У цій відповіді нас цікавить `item/title/uk` та `item/title/en` для української та англійської версії відповідно. Втім, як видно з наведеного прикладу, ймовірно перекладу англійською мовою в нас не буде.

**Comment by ndrhzn** [comment]
**[Кодліст - Стадія проєкту]**

У завданні описано, як лінкувати код стадії до значення / розшифровки коду. Але в принципі можна витягти всі коди та розшифровки, і тримати їх в якості кодліста. Наразі обмежимось українською версію (для англійською можемо просто поки дублювати українську), але згодом перекладемо.

code | uk
-- | --
ORTS0029001001000000000000-1 | Проєктна ідея (концепція проєкту)
ORTS0029001001000000000000-2 | Підготовлене (Попереднє Інвестиційне ТЕО - Концептуальна записка проєкту)
ORTS0029001001000000000000-3 | Підготовлено Інвестиційне ТЕО проєкту
ORTS0029001001000000000000-4 | Підготовлено ПКД (стадія ТЕО)
ORTS0029001001000000000000-5 | Підготовлено ПКД (стадія Проєкт)
ORTS0029001001000000000000-6 | Проєкт готовий до закупівлі
ORTS0029001001000000000000-7 | Проєкт перебуває на стадії реалізації (до 20% готовності)
ORTS0029001001000000000000-8 | Проєкт перебуває на стадії реалізації (20%-50% готовності)
ORTS0029001001000000000000-9 | Проєкт перебуває на стадії реалізації (50%-80% готовності)
ORTS0029001001000000000000-10 | Проєкт перебуває на стадії реалізації (більше 80% готовності)

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/fb67dfc9-965f-4697-b62f-2a837ac73708/state/analysis

**Comment by ndrhzn** [comment]
Дякую! Наразі є декілька правок

- Стовпчик "Опис" прибираємо з таблиці зовсім. Звернули увагу, що там є купа HTML розмітки, яку нормально не вичистити, та й користі від довжелезних текстів в аналітиці мало
- У стовпчику "Код стратегічного рівня" потрібно перетворити код на людиночитане значення. У нас цей кодліст вже є у DREAM Translations і використовується в модулі аналітики на сторінці "Деталі проєктів"
- У стовпчику "Код стратегічного рівня" у нас є текстовий елемент (зараз це код, але має бути людиночитаний текст) і посилання на документ. Потрібно перетворити цей текстовий елемент на посилання, використовуючи ту адресу, що у нас власне міститься у посиланні
- Стовпчик "Повʼязані активності" наразі містить ідентифікатори проєктів, але тут нам потрібні коди проєктів (тобто за ідентифікатором потрібно підтягнути код)

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Оскільки ми вирішили прибрати показник "Кількість розпорядників коштів" з карток, то є потреба додати цю узагальнюючу статистику до таблиці. 

Чи ми можемо ось тут - за аналогією із кількістю інвестиційних проєктів - показувати кількість розпорядників коштів?

![image](https://github.com/user-attachments/assets/853fa0e3-9050-4cfd-849c-72ea5b02e8ea)

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Виглядає добре, дякую! Інших правок щодо таблиці поки не маємо

**Comment by ndrhzn** [comment]
**[ Зміни в таблиці]**

NB: Всі описані зміни передбачають, що частину даних ми будемо забирати не з АРІ, а з таблиці (Google Spreadsheet). Посилання на таблицю буде надане окремим повідомленням у Slack.

- **Потрібно додати стовпчик "Бал" / Score**. Він має знаходитися у кінці таблиці (тобто після стовпчика "Наявне фінансуання. Інші джерела", за замовчуванням має бути видимим. Числа мають бути відформатовані таким чином, аби містити 5 знаків після коми (потрібно давати достатньо деталізації для розрізення оцінок проєктів)
- **Потрібно відсортувати таблицю** за стовпчиком "Бал" / Score він найбільшого до найменшого
- **Потрібно замінити дані для стовпчика "Пріоритет уряду"**. Оскільки частина проєктів була неправильно прокласифікована під час занесення в систему, для деяких проєктів в процесі оцінювання були оновлені значення змінної "Пріоритет уряду" (ці значення впливають на коефіцієнт, що застосовується під час оцінювання). Отже, тепера нам потрібно забирати значення "Пріоритету уряду" із таблиці. Це тимчасове рішення, і ми очікуємо, що згодом зможемо забирати всі дані з АРІ, але наразі маємо поставити тимчасову заплатку. У наведеній таблиці код Пріоритету уряду знаходиться у стовпчику Фінальний код ПУ, а назва Пріоритету уряду у стовпчику Фінальний критерій.
- **Потрібно додати посилання на сторінку проєкту у секторальній системі**. Посилання формується за структурою `https://my.dream.gov.ua/investment-projects/{internal/id}/view`. Трохи згодом ми замінимо це на посилання на публічний портал. Посилання має знаходитись на коді проєкту. У наведеній таблиці вже є стовпчик із посиланнями, реалізований із застосуванням формули. Втім, можна імплементувати створення посилання і просто на стороні BI.

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
**[Додати можливість обирати / приховувати стовпчик "Бал" у таблиці]**

Наразі стовпчик "Бал" у нас є в таблиці, але обирати чи прибирати його через панель "Оберіть стовпчики для відображення" неможливо. Чи є якась причина для цього? Чи ми можемо додати можливість вибору / приховування стовпчика?

![image](https://github.com/user-attachments/assets/005210f5-2e56-4d51-8caa-ae0d414aa5be)

**Comment by ndrhzn** [comment]
**[Налаштувати оновлення даних у таблиці]**

На попередньому кроці ми додали можливість підтягувати бали проєктів до таблиці із Google Spreadsheets. Проєктний офіс зауважив, що дані в Google Spreadsheets можуть змінюватися, тому важливо, аби ці зміни підтягувались до BI. Отже, потрібно налаштувати оновлення в такий же спосіб, як воно реалізовано для проєктів або ж для класифікаторів / словників - раз на добу.

**Comment by ndrhzn** [comment]
**[Додати переклади кодлістів для Стадії проєкту, Пріоритету уряду, та Функціональної природи послуги]**

До таблиці DREAM Translations я додав три нових аркуші із перекладами кодлістів

- Пріоритет уряду (GoU-GOALS)
- Функціональна природа послуги (KFK)
- Стадія проєкту (stage)

Потрібно додати ці переклади до моделі даних, аби на англійській версії сторінки відображалися англійські версії пріоритетів, послуг, стадій

**Comment by ndrhzn** [comment]
**[Транслітерувати назви організацій]**

Для звичайних проєктів ми вже реалізували транслітерацію назв організацій, потрібно зробити те саме і для інвестиційних проєктів.

На сторінці "Інвестиційні проєкти" транслітерувати потрібно

- Головний розпорядник коштів
- Ініціатор
- Виконавець

**Comment by andrzejbeletsky** [comment]
@ndrhzn 
Таблиця перекладів "Функціональна природа послуги (KFK)" не має кодів?

**Comment by ndrhzn** [comment]
Так, наразі їх переклали без кодів. Якщо ви, наприклад, додасте до DREAM Translations коди і поточні назви українською, я можу приєднати до них переклади

**Comment by ndrhzn** [comment]
**[Додати посилання на проєкти та документи під час експорту даних]**

Для звичайних проєктів у нас працює така логіка - у таблиці "Деталі проєктів" ми перетворюємо код проєкту на посилання, що веде на сторінку проєкту на порталі. Під час експорту таблиці, посилання додається окремим стовпчиком.

Для таблиці на сторінці "Інвестиційні проєкти" нам потрібно зробити так само, але не лише для коду проєкту, але й для коду стратегічного рівня.

У першому випадку під час експорту ми додаємо стовпчик "Посилання на портал" / URL. У другому випадку ми додаємо стовпчик "Посилання на документ" / Document URL

**Comment by ndrhzn** [comment]
**[Якщо проєкт має декілька кодів стратегічного рівня, давати їх через кому]**

У нас можлива сиутація, коли один проєкт має декілька кодів стратегічного рівня. Наразі це результує в тому, що для кожної комбінації "код проєкту" - "код стратегічного рівня" у нас створюється окремий рядок.

У наведеному прикладі один проєкт репрезентується пʼятьма рядками. 

![image](https://github.com/user-attachments/assets/f9eb2cbb-8443-4768-873c-dc358090c83e)

В аналогічних випадках на інших аркушах ми намагаємось один проєкт репрезентувати одним рядком таблиці. А якщо є випадки, коли один проєкт має декілька записів, наприклад, для громади, ми даємо їх в одній комірці через кому.

Отже, пропонуємо так вчинити і у цьому випадку. Однак є питання - чи ми зможемо в такому разі давати окреме посилання на кожен документ, чи в одній комірці може бути тільки одне посилання?

**Comment by ndrhzn** [comment]
FYI додав до таблиці DREAM Translations нові коди та відповідники для них до вкладки strategic level code. Бо в нас були пропущені значення. Потрібно впевнитися, що вони підтягуються

code | uk | en
-- | -- | --
none | Інший нормативний документ | Other regulatory document
nsdsDecree | Рішення Ради національної безпеки і оборони України | The decision of the NSDC of Ukraine

**Comment by andrzejbeletsky** [comment]
> **[Додати можливість обирати / приховувати стовпчик "Бал" у таблиці]**
> 
> Наразі стовпчик "Бал" у нас є в таблиці, але обирати чи прибирати його через панель "Оберіть стовпчики для відображення" неможливо. Чи є якась причина для цього? Чи ми можемо додати можливість вибору / приховування стовпчика?
> 
> ![image](https://private-user-images.githubusercontent.com/13032566/364261369-005210f5-2e56-4d51-8caa-ae0d414aa5be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzYxNjcsIm5iZiI6MTcyNTQzNTg2NywicGF0aCI6Ii8xMzAzMjU2Ni8zNjQyNjEzNjktMDA1MjEwZjUtMmU1Ni00ZDUxLThjYWEtYWUwZDQxNGFhNWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA3NDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMmFiNzVjNTQwMDlkOTFmYzZkZjUwMzBkZGY3MjVkMjhiNmVjOWU3ZTZiNjM4Y2MwMDA4MDg5OGY1ZjM2YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gh2Q71-JDbx29VCCKAetUUO-hUMRtdljLj2nRn_udJg)

done

**Comment by andrzejbeletsky** [comment]
> **[Налаштувати оновлення даних у таблиці]**
> 
> На попередньому кроці ми додали можливість підтягувати бали проєктів до таблиці із Google Spreadsheets. Проєктний офіс зауважив, що дані в Google Spreadsheets можуть змінюватися, тому важливо, аби ці зміни підтягувались до BI. Отже, потрібно налаштувати оновлення в такий же спосіб, як воно реалізовано для проєктів або ж для класифікаторів / словників - раз на добу.

done

**Comment by andrzejbeletsky** [comment]
> **[Додати переклади кодлістів для Стадії проєкту, Пріоритету уряду, та Функціональної природи послуги]**
> 
> До таблиці DREAM Translations я додав три нових аркуші із перекладами кодлістів
> 
> * Пріоритет уряду (GoU-GOALS)
> * Функціональна природа послуги (KFK)
> * Стадія проєкту (stage)
> 
> Потрібно додати ці переклади до моделі даних, аби на англійській версії сторінки відображалися англійські версії пріоритетів, послуг, стадій

done
для таблиці перекладів "Функціональна природа послуги (KFK)" треба перекласти останні рядки

**Comment by andrzejbeletsky** [comment]
> **[Транслітерувати назви організацій]**
> 
> Для звичайних проєктів ми вже реалізували транслітерацію назв організацій, потрібно зробити те саме і для інвестиційних проєктів.
> 
> На сторінці "Інвестиційні проєкти" транслітерувати потрібно
> 
> * Головний розпорядник коштів
> * Ініціатор
> * Виконавець

done

**Comment by andrzejbeletsky** [comment]
> **[Якщо проєкт має декілька кодів стратегічного рівня, давати їх через кому]**
> 
> У нас можлива сиутація, коли один проєкт має декілька кодів стратегічного рівня. Наразі це результує в тому, що для кожної комбінації "код проєкту" - "код стратегічного рівня" у нас створюється окремий рядок.
> 
> У наведеному прикладі один проєкт репрезентується пʼятьма рядками.
> 
> ![image](https://private-user-images.githubusercontent.com/13032566/364309381-f9eb2cbb-8443-4768-873c-dc358090c83e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDE0MzgsIm5iZiI6MTcyNTQ0MTEzOCwicGF0aCI6Ii8xMzAzMjU2Ni8zNjQzMDkzODEtZjllYjJjYmItODQ0My00NzY4LTg3M2MtZGMzNTgwOTBjODNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA5MTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMzI3ZmU4YzUxMGNlZmE4YjJjNTRhMWUyZjkyZTU5NzgxNWIzMmIwODY5NmZjY2MxYzUwMGFmZTY1MGIyNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.42wIbeOpufxVgBdpH7UhwuLt-Ju3RXI0ivzOf0omxv4)
> 
> В аналогічних випадках на інших аркушах ми намагаємось один проєкт репрезентувати одним рядком таблиці. А якщо є випадки, коли один проєкт має декілька записів, наприклад, для громади, ми даємо їх в одній комірці через кому.
> 
> Отже, пропонуємо так вчинити і у цьому випадку. Однак є питання - чи ми зможемо в такому разі давати окреме посилання на кожен документ, чи в одній комірці може бути тільки одне посилання?

Так, в одній комірці може бути тільки одне посилання. Що робити?

**Comment by andrzejbeletsky** [comment]
> **[Додати посилання на проєкти та документи під час експорту даних]**
> 
> Для звичайних проєктів у нас працює така логіка - у таблиці "Деталі проєктів" ми перетворюємо код проєкту на посилання, що веде на сторінку проєкту на порталі. Під час експорту таблиці, посилання додається окремим стовпчиком.
> 
> Для таблиці на сторінці "Інвестиційні проєкти" нам потрібно зробити так само, але не лише для коду проєкту, але й для коду стратегічного рівня.
> 
> У першому випадку під час експорту ми додаємо стовпчик "Посилання на портал" / URL. У другому випадку ми додаємо стовпчик "Посилання на документ" / Document URL

зроблено для проєкту.
для коду стратегічного рівня неможливо, якщо зведемо всі по проєкту в один рядок.

**Comment by andrzejbeletsky** [comment]
> FYI додав до таблиці DREAM Translations нові коди та відповідники для них до вкладки strategic level code. Бо в нас були пропущені значення. Потрібно впевнитися, що вони підтягуються
> 
> code	uk	en
> none	Інший нормативний документ	Other regulatory document
> nsdsDecree	Рішення Ради національної безпеки і оборони України	The decision of the NSDC of Ukraine

done

**Comment by ndrhzn** [comment]
> в одній комірці може бути тільки одне посилання. Що робити?

Прикро. Але в такому разі ми просто відмовляємось від посилань у цьому стовпчику, і просто даємо значення через кому

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Загалом наче все добре. Виявили, що у нас немає нормальних перекладів кодів стратегічного рівня англійською, поставили задачу щодо цього. Як буде готово, я додам до таблиці DREAM Translations. Звідти ж дані автоматично підтягуються раз на добу, так?

**Comment by andrzejbeletsky** [comment]
> Загалом наче все добре. Виявили, що у нас немає нормальних перекладів кодів стратегічного рівня англійською, поставили задачу щодо цього. Як буде готово, я додам до таблиці DREAM Translations. Звідти ж дані автоматично підтягуються раз на добу, так?

так

**Comment by ndrhzn** [comment]
**[Оновити кодліст "Мета інвестиційного проєкту"]**

У нас раніше в даних була помилка - замість "compliance" писали "copmliance". Тому і в кодлісті була ця помилка. Зараз помилку в даних виправили, тому нам треба поправити і кодліст. Також зʼявився новий код - equality, і його розшифровку потрібно додати.

**[Кодліст - Мета інвестиційного проєкту]**

code | en | ua
-- | -- | --
quality | Service quality improvement | Підвищення якості послуг
capacity | Capacity building | Нарощування потужностей
improvement | Infrastructure improvement | Покращення стану інфраструктури
equality | Improvement of benefit distribution equity | Поліпшення рівномірності розподілу благ
satisfaction | Meeting demand | Задоволення попиту
compliance | Increasing the level of compliance with modern standards | Підвищення рівня відповідності сучасним стандартам
other | other | Інше

@andrzejbeletsky

**Comment by ndrhzn** [comment]
**[Замінити посилання на сторінки проєктів]**

Наразі у нас код проєкту працює як посилання, але воно веде не на публічний портал, а на секторальну систему. Тепера ми вже маємо сторінки інвестпроєктів на публічному порталі, отже можемо оновити посилання.

**Приклад посилання**
- Українська версія: https://dream.gov.ua/ua/pip-pipeline/DREAM-UA-220824-F196BF41
- Англійська версія: https://dream.gov.ua/pip-pipeline/DREAM-UA-220824-F196BF41

**Структура посилання**
- Українська версія: https://dream.gov.ua/ua/pip-pipeline/DREAM-UA-{internal/code}
- Англійська версія: https://dream.gov.ua/pip-pipeline/DREAM-UA-{internal/code}

**Comment by andrzejbeletsky** [comment]
Take a look.
(Для  кодлісту "Мета інвестиційного проєкту" створений аркуш в транслейшн.)
