### ISSUE TITLE
Інвестиційні проєкти: Картки

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#197]
name_ua | name_en | endpoint | path | notes
-- | -- | -- | -- | --
Кількість інвестиційних проєктів | Number of investment projects | investmentprojects | internal/code | COUNT OF
Бюджет | Budget | investmentprojects | cdu_response/budget/budgetBreakdown/amount/amount | SUM OF
Фінансове покриття | Financial coverage | investmentprojects | budget/finance/value/amount / cdu_response/budget/budgetBreakdown/amount/amount | %
Кількість розпорядників коштів | Number of disposers | investmentprojects | cdu_response/parties/identifiers/id | COUNT OF, WHERE cdu_response/parties/roles LIKE "%disposer%"

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/fb67dfc9-965f-4697-b62f-2a837ac73708/state/analysis

**Comment by ndrhzn** [comment]
Вирішили трохи змінити картки - насамперед прибрати показник "Кількість розпорядників коштів", додати натомість показник "Наявне фінансування", та змінити порядок

name_ua | name_en | endpoint | path | notes
-- | -- | -- | -- | --
Кількість інвестиційних проєктів | Number of investment projects | investmentprojects | internal/code | COUNT OF
Бюджет | Budget | investmentprojects | cdu_response/budget/budgetBreakdown/amount/amount | SUM OF
Наявне фінансування | Commited funding | investmentprojects | budget/finance/value/amount | SUM OF
Фінансове покриття | Financial coverage | investmentprojects | budget/finance/value/amount / cdu_response/budget/budgetBreakdown/amount/amount | %

Відповідно, трохи зміниться взаємодія із графіками, але про це я напишу окремо.

**Comment by andrzejbeletsky** [comment]
done

**Comment by ndrhzn** [comment]
До картки "Наявне фінансування" потрібно додати символ валюти, як у нас відображається на інших сторінках та у картці "Бюджет"

**Comment by andrzejbeletsky** [comment]
done
