### ISSUE TITLE
Інвестиційні проєкти: Фільтри

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#198]
name_ua | name_en | endpoint | path | notes
-- | -- | -- | -- | --
Статус | Status | investmentprojects | cdu_response/status |  
Головний розпорядник коштів | Disposer | investmentprojects | cdu_response/parties/identifiers/id | COUNT OF, WHERE cdu_response/parties/roles LIKE "%disposer%"
Пріоритет уряду | Government priority | investmentprojects | cdu_response/additionalClassifications/id | cdu_response/additionalClassifications/scheme = "GoU-GOALS"
Сектор | Sector | investmentprojects | cdu_response/classification/id | WHERE cdu_response/classification/scheme = "WB-ECO"
Підсектор | Subsector | investmentprojects | cdu_response/classification/id | WHERE cdu_response/classification/scheme = "WB-ECO"
Профінансованість | Financial coverage | investmentprojects | budget/finance/value/amount / cdu_response/budget/budgetBreakdown/amount/amount | повністю, частково, відсутнє
Категорія джерела фінансування | Type of funding source | investmentprojects | cdu_response/budget/finance/financeCategory |  
Стадія проєкту | Stage | investmentprojects | cdu_response/requirementResponses/requirement/id > cdu_response/criteria/requirementGroups/requirements/title | Отриманий ідентифікатор треба звʼязати із cdu_response/criteria/requirementGroups/requirements/title за допомогою cdu_response/criteria/requirementGroups/requirements/id. При цому cdu_response/criteria/id = "ORTS0029001001000000000000"

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/fb67dfc9-965f-4697-b62f-2a837ac73708/state/analysis

**Comment by ndrhzn** [comment]
[Додати нові фільтри]

Тут нам потрібно додати пару нових фільтрів - "Наявність заявки" та "Статус заявки". Для цих фільтрів нам потрібно звʼязати між собою Інвестиційні проєкти та Бюджетні заявки.

Бюджетні заявки знаходяться у окремому API endpoint - https://public-api.dream.gov.ua/marketplace/public/dream/budgetsubmissions 

name_ua | name_en | endpoint | path | notes
-- | -- | -- | -- | --
Наявність заявки | Linked application | budgetsubmissions | cdu_response/relatedProcesses/identifier | WHERE cdu_response/relatedProcesses/scheme = "DREAM" and cdu_response/relatedProcesses/relationship="project"
Статус заявки | Application status | budgetsubmissions | cdu_response/status |  

Тобто нам потрібно зібрати всі заявки та їхні статуси, і встановити звʼязок заявок із інвестиційними проєктами, використовуючи ідентифікатор проєкту.

Нам також потрібно буде зробити пре-фільтр на цій сторінці, але це буде описано окремим пунктом. Кодліст статусів заявок також буде описаний окремо.

**Comment by ndrhzn** [comment]
**[Кодліст "Статус бюджетної заявки"]**

code | ua | en
-- | -- | --
withdrawn | Відкликано | Withdrawn
approval:preAssessment | Подано | Approval: Pre-assessment
approval:authority | На затвердженні у ініціатора | Approval: Authority
approval:grk | На затвердженні у ГРК | Approval: Dispenser

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Тут вирішили зробити наступне

- Зробити пре-фільтр за наступним принципом "Наявність заявки" = "Так", "Статус бюджетної заявки" = "Подано".  При цьому це має бути пре-фільтр "під капотом", тобто фільтри "Наявність заявки" та "Статус бюджетної заявки" наразі з панелі фільтрів треба прибрати, і користувачам вони не мають бути доступні
- Фільтр "Статус" прибрати

**Comment by a-radik** [comment]
Самим простим варіантом тут буде просто прибрати з моделі даних додатка все, що НЕ задовілняє описаним вами умовам. 
Плануємо зробити саме так.

**Comment by andrzejbeletsky** [comment]
take a look
