### ISSUE TITLE
Таблиці: Monospaced font

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#20]
Варто буде додати собі до задач на майбутнє - перейти на використання [monospaced шрифтів](https://en.wikipedia.org/wiki/Monospaced_font) щонайменше для таблиць. 

Якщо всі символи матимуть однакову ширину, тоді числа з однаковою кількістю символів в таблиці матимуть однакову ширину, і в таблиці їх буде простіше порівнювати між собою.

У поточній версії числа з однаковою кількістю знаків можуть мати різну ширину.

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/90ffc1d2-bca5-43b3-9a66-fec32228030f)

**Comment by ndrhzn** [comment]
Поточний статус: Проєктний офіс запропонував спробувати на вибір два шрифти - [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono?preview.text=%D0%BD%D0%B0%D0%BF%D0%BE%D0%B2%D0%BD%D0%B5%D0%BD%D0%BD%D1%8F%20%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D1%96%D0%B2&classification=Monospace&subset=cyrillic-ext&noto.script=Cyrl) та [Ubuntu Mono](https://fonts.google.com/specimen/Ubuntu+Mono?preview.text=%D0%BD%D0%B0%D0%BF%D0%BE%D0%B2%D0%BD%D0%B5%D0%BD%D0%BD%D1%8F%20%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82%D1%96%D0%B2&classification=Monospace&subset=cyrillic-ext&noto.script=Cyrl).

Можна почати тестування з Roboto Mono @andrzejbeletsky

**Comment by andrzejbeletsky** [comment]
Варіант з RobotoMono:
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/b7011c65-e80e-4ce8-850a-d567bafcdc80/state/analysis

**Comment by andrzejbeletsky** [comment]
Вариант з UbuntuMono:
https://qsdemo.rbcgrp.com/sense/app/d2fc0dd7-a9af-45ef-98d8-acb366537c2d/sheet/4cfb64bc-f648-4116-8d80-bc99f590fd77/state/analysis

**Comment by andrzejbeletsky** [comment]
VictorMono:
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/4cfb64bc-f648-4116-8d80-bc99f590fd77/state/analysis

**Comment by ndrhzn** [comment]
Зафіксували рішення не змінювати шрифт у поточному релізі, і продовжувати пошуки. В ідеалі нам потрібно знайти шрифт, який добре працює і для тексту, і для чисел (може бути одне сімейство шрифтів)

**Comment by ndrhzn** [comment]
@andrzejbeletsky можемо в якості есперименту подивитися на сторінку з бюджетами, де всі текстові елементи використовують Rubik, а числа, наприклад Roboto Mono?

**Comment by andrzejbeletsky** [comment]
Take a look at
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/421be31a-3828-425b-aa18-7f886a762cdb/state/analysis

**Comment by ndrhzn** [comment]
Виглядає непогано. Але маю уточнити - до яких елементів у цьому випадку застосовується Roboto Mono, а до яких Rubik? Чи це "всі числа - Roboto Mono, всі літери - Rubik"? Чи якось інакше?

Питаю, бо зауважив також зміни у тому, як відмальовуються числа у картках. Хочу зрозуміти, чи це intentional, чи by accident.

**Comment by andrzejbeletsky** [comment]
Усі цифри Roboto - і картки, і таблиці, і чарти.

Addon - тепер в pivot-ах не відображається "Values".

**Comment by ndrhzn** [comment]
Загалом мені видається, що це way to go. Але одне але - із застосуванням нового шрифту числа у картках стали більш масивними. Я бачу в консолі браузера, що там font-weight: 700, тобто Bold. Чи є у нас опція зробити для карток Semibold? Якщо немає, то може і Regular буде достатньо

**Comment by andrzejbeletsky** [comment]
Є Regular :
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/421be31a-3828-425b-aa18-7f886a762cdb/state/analysis

**Comment by ndrhzn** [comment]
Добре, я думаю, можна так і лишити. В такому разі наступні дії

- Застосувати ці зміни до інших аркушів
- Зробити ці зміни доступними в публічному додатку

**Comment by andrzejbeletsky** [comment]
in progress
треба зрозуміти, чи робити зміну на кожному аркуші окремо, чи спробувати змінити тему в додатку, і тоді це буде поширюватися на нові аркуші/об'єкти автоматично

**Comment by a-radik** [comment]
як зміна теми, так і зазначення шрифту для css стилю, що використовується в об'єктах може потребувати часу на пошук імені css, шо платформа використовує в кожному окремому випадку. Поки ця робота не буде розпочата лишається невідомим чи застосовуються в платформі різні css наприклад, для розрізів і мір в прямій таблиці.
Вважаю, що тема є більш надійним варіантом, але тим не менш треба зважати на те, що вендор може вносити зміни при релізі нових версій продукту.
Для дослідження треба буде витратити 4-8 годин, щоб передивитись всі обїекти візуалізації, де шрифт не вказується безпосередньо в налаштуваннях об'єктів.

**Comment by ndrhzn** [comment]
А коли ви задаєте тему, то вона формується десь кодом на рівні CSS чи в графічному інтерфейсі, і лише потім програмою збирається в CSS?

**Comment by ndrhzn** [comment]
Швидка розвідка показала, що на рівні таблиць зміна CSS може відбутися відносно просто, бо там є окремий клас для числових комірок  - .qv-st-data-cell-numeric.

Але для підписів чисел на графіках це може працювати інакше. Я поки не знайшов на рівні CSS правил окремо для текстових підписів на графіку та числових

**Comment by andrzejbeletsky** [comment]
Take a look.
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/4cfb64bc-f648-4116-8d80-bc99f590fd77/state/analysis
Тема в клику складається з 3 файлів і додатково, при необхідності, файлів фонтів.
Властивості основних типів об'єктів підтримуються в цих файлах.
З прямою і півот таблицею є відмінності - в мене шрифт змінений тільки для явно цифрових cells. Для текстових продовжує діяти основний Rubik.
Також потрібне було manual edit цифрових значень для всіх об'єктів-карток, бо це не стандартний об'єкт.

**Comment by a-radik** [comment]
> А коли ви задаєте тему, то вона формується десь кодом на рівні CSS чи в графічному інтерфейсі, і лише потім програмою збирається в CSS?

Це тектовий файл, в якому виконується опис на рівні класів.

**Comment by a-radik** [comment]
> Також потрібне було manual edit цифрових значень для всіх об'єктів-карток, бо це не стандартний об'єкт.

Питання чи це дійсно необхідно змінювати шрифт в картках на monospace, бо те для чого ми це робили в таблицях в картках doesn't make sense, does it?

**Comment by ndrhzn** [comment]
З практичної точки зору найбільше застосування monospace має сенс насамперед для таблиць, це правда.

В деяких випадках це також має сенс для графіків - якщо це table-like графіки, де числові значення можуть відображатися один під одним

В картках цілком може бути Rubik, бо в картках ми ніколи не читаємо значення один під одним.

**Comment by andrzejbeletsky** [comment]
Змінено шрифт в картках на Rubik

**Comment by andrzejbeletsky** [comment]
Done
