### ISSUE TITLE
Додати стовпчик "Географія проєкту" до таблиці на сторінці "Інвестиційні проєкти"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#203]
**[Додати до таблиці стовпчик "Географія проєкту"]**

До таблиці потрібно додати новий стовпчик. Назва українською - "Географія проєкту", назва англійською - "Project location".

Дані для цього стовпчика знаходяться в елементі `cdu_response/locations/gazetteer/identifiers`. 

У нас є декілька різних варіантів того, як користувачі зазначають географію проєкту:

- **Одна локація**. В такому разі у елементі міститься звичайний код КАТОТТГ. Нам потрібно з цього коду отримати лише область і зазначити її

Приклад даних

```
{
  "locations": [
    {
      "gazetteer": {
        "scheme": "UA-CATOTTG",
        "identifiers": [
          "UA74100390010054825"
        ]
      }
    }
  ]
}
```

- **Декілька локацій**. В такому разі у елементі міститься декілька кодів КАТОТТГ через кому. Нам потрібно з кожного коду отримати область. Якщо якась область фігурує декілька разів, видалити повторювані значення, зазначити її лише один раз. Дати перелік областей через кому.

Приклад даних

```
{
  "locations": [
    {
      "gazetteer": {
        "scheme": "UA-CATOTTG",
        "identifiers": [
          "UA32040110000047477",
          "UA32040110010043320",
          "UA32040210000086086",
          "UA32040210010094429",
          "UA32060010000086043",
          "UA32060010010055198",
          "UA32060050000030591",
          "UA32060050010081797",
          "UA32080170000086616",
          "UA32080170010013153",
          "UA32100070000076283",
          "UA32100070010044762",
          "UA32100130000093505",
          "UA32100130010084793",
          "UA32120030000030458",
          "UA32120030010069648",
          "UA32120170000094084",
          "UA32120170080064470",
          "UA32140050020038278",
          "UA32140130000030648",
          "UA32140130010098461"
        ]
      }
    }
  ]
}
```

- **Вся Україна**. В такому разі в елементі міститься лише один код, але це не є валідний код КАТОТТГ, а UA00000000000000000. Нам потрібно просто зазначити "Вся Україна" / Whole country

Приклад даних

```
{
  "locations": [
    {
      "gazetteer": {
        "scheme": "UA-CATOTTG",
        "identifiers": [
          "UA00000000000000000"
        ]
      }
    }
  ]
}
```

Стовпчик потрібно додати після стовпчика "Пріоритет уряду".  Він має бути видимим за замовчуванням. У користувачів має бути можливість обрати чи прибрати його для відображення за допомогою панелі "Оберіть стовпчики для відображення"

**Comment by ndrhzn** [comment]
Естімейт - 2-4 години
Зміни в мешапі - не потрібні

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Дякую! За змістом наче все добре

За формою у нас зара можлива ситуація, коли проєкт стосується 11 областей, але у комірці ми можемо побачити максимум 3. Для частини користувачів може бути неочевидно, що можна отримати додаткову інформацію при наведенні на комірку.

![image](https://github.com/user-attachments/assets/f91002fe-b1d8-47f4-8fd8-aad1e11c6153)

Чи ми можемо виправити це? Які у нас опції? 

- Зараз у нас кожен регіон на окремому рядку (здається). Чи принципово зміниться ситуація, якщо давати їх через кому?
- Чи може розмір комірки змінюватися відповідно до кількості контенту?

**Comment by andrzejbeletsky** [comment]
take a look.
розділення через кому. тому є натяк, що далі є ще текст.

**Comment by ndrhzn** [comment]
Добре, давайте на цьому поки і зупинимось. Можна на прод
