### ISSUE TITLE
Data: Додати стовпчик "Загальний бал заявки" до таблиці "Фінансові програми, заявки"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#206]
До таблиці "Фінансові програми, заявки" потрібно додати новий стовпчик - "Бал" / Score. Цей стовпчик має бути останнім у таблиці, він має бути видимим за замовчуванням, але у користувачів має бути можливість приховати його за допомогою бокової панелі "Оберіть стовпчики для відображення". За замовчуванням заявки мають бути відсортовані за стовпчиком "Бал" від найбільшого до найменшого.

Дані для цього стовпчика потрібно брати з самої заявки ([submissions endpoint](https://public-api.dream.gov.ua/marketplace/public/dream/submissions)). Але також для цього нам знадобляться дані з самої фінпрограми ([ifiprojects endpoint](https://public-api.dream.gov.ua/marketplace/public/dream/ifiprojects)). 

### Отримання критеріїв оцінки

У даних фінпрограми є набір критеріїв оцінки. Серед цих критерів є і критерій з назвою "Кумулятивний показник пріоритетності".

`cdu_response/criteria/requirementGroups/requirements/title = “Кумулятивний показник пріоритетності”
`

Нас цікавить ідентифікатор цього критерію, тобто

`cdu_response/criteria/requirementGroups/requirements/id WHERE cdu_response/criteria/requirementGroups/requirements/title = “Кумулятивний показник пріоритетності”`

Важливо, що в одній фінпрограмі може бути декілька таких ідентифікаторів. Скажімо, у програмі 35hclg3d-07o5-4zal-as22-401ixjl4uk00 їх 3, а в програмі 8w2ht6q5-613z-4td5-9rin-1s28he8p11e9 їх 15. 

### Отримання оцінок

Використовуючи отримані ідентифікатори, ми можемо відфільтрувати дані заявок, аби знайти бали. Елемент даних, що нас цікавить, має адресу `cdu_response/requirementResponses/value`.

Видається, що оцінки можуть бути не у всіх заявок. Якщо заявка не має оцінки, в такому разі ми маємо ставити N/A, аби сигналізувати, що дані відсутні.

**Comment by ndrhzn** [comment]
#168

**Comment by ndrhzn** [comment]
Естімейт - 2-4 години
Зміни в мешапі - не потрібні

**Comment by andrzejbeletsky** [comment]
take a look

дефолтний '-' при відсутній оцінки

**Comment by ndrhzn** [comment]
Дякую! Тут після консультацій з Проєктним офісом вирішили змінити принцип сортування заявок.

Першопочатково ми думали сортувати за замовчуванням за Балом. Однак зараз виходить так, що не всі заявки із найвищими балами є погодженими заявками (так, наприклад, заявка з найвищим балом має статус "Відкликано").

Тому ми хочемо за замовчуванням спершу сортувати за статусом, а вже потім за балом. При цьому у статусів має бути сортування не просто за алфавітом, а власне кастомне сортування. Порядок має бути таким:

1. Погоджено
2. На затвердженні
3. В очікуванні
4. Відкликано
5. Відхилено
6. Не схвалено

**Comment by andrzejbeletsky** [comment]
Take a look

**Comment by ndrhzn** [comment]
Виглядає добре, дякую! Готово до релізу на прод
