### ISSUE TITLE
UI: Перейменувати назву сторінки "Фінансові програми, заявки" в англійській версії

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#207]
Перед релізом сторінки "Фінансові програми, заявки", ми замінили слово submissions на applications. Однак подекуди у нас і досі використовується submissions. Це треба виправити.

![Image](https://github.com/user-attachments/assets/eda243b3-3564-4c2b-80fd-454260af2df0)

**Заголовок сторінки**: Financial programs, submissions замінити на Financial programs, applications

**Посилання на сторінку на боковій панелі**: Financial programs, submissions замінити на Financial programs, applications

**Comment by andrzejbeletsky** [comment]
бачу, що є заміна текста в транслейшн , тому done.

**Comment by ndrhzn** [comment]
Готово на проді

![Image](https://github.com/user-attachments/assets/a63bb312-77f7-4fb2-ad5b-279a568ded86)
