### ISSUE TITLE
UI: Перейменувати назву сторінки "Деталі фінансових програм" в англійській версії

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#208]
Наразі у нас англійська версія сторінки "Деталі фінансових програм" називається просто Financial programs. 

![Image](https://github.com/user-attachments/assets/29ead20e-6566-48d2-8c99-d2c13f69da94)

Це може стати проблемою, коли ми опублікуємо власне сторінку, котра стосується фінансових програм загалом, оскільки вона називатиметься Financial programs.

Заголовок сторінки: Financial programs замінити на Financial programs, details

Посилання на сторінку на боковій панелі: Financial programs замінити на Financial programs, details

**Comment by andrzejbeletsky** [comment]
done

**Comment by ndrhzn** [comment]
Готово на проді

![Image](https://github.com/user-attachments/assets/389b5ae7-561a-44e7-994f-11271de73874)
