### ISSUE TITLE
UI: Перемістити посилання на сторінку "Наповнення" після посилання на "Деталі проєктів". Перейменувати "Наповнення" на "Наповнення проєктів"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#210]
Оскільки у нас стає дедалі більше сторінок, ми хочемо почати групувати сторінки за тим, які сутності вони описують, або якої теми вони стосуються. В якості першого року у цьому напрямку хочемо перемістити сторінку "Наповнення".

Наразі сторінка "Наповнення" у нас знаходиться в самому кінці списку на боковій панелі. Ми хочемо, аби вона знаходилась після сторінки "Деталі проєктів".

![Image](https://github.com/user-attachments/assets/dccfbdb5-7de9-46f8-9532-b68b143956e2)

Також принагідно варто перейменувати сторінку "Наповнення". Коли у нас було небагато сторінок, всі вони так чи інакше стосувались проєктів. Однак зараз у нас зʼявились і фінансові програми, і інвестиційні проєкти, і тому з назви "Наповнення" може бути не дуже зрозуміло, про наповнення чого саме йдеться.

**Заголовок сторінки**: "Наповнення" замінити на "Наповнення проєктів". "Data availability" замінити на "Project data availability"

**Посилання на сторінку на боковій панелі**: "Наповнення" замінити на "Наповнення проєктів". "Data availability" замінити на "Project data availability"

**Comment by andrzejbeletsky** [comment]
@karandinserhii 
"Наповнення"  після сторінки "Деталі проєктів".

**Comment by ndrhzn** [comment]
Готово до релізу на прод

![Image](https://github.com/user-attachments/assets/898c436d-c12f-4456-a7df-50c4402b7ea7)
