### ISSUE TITLE
UI/UX: Додати можливість "Обрати всі стовпчики" у меню "Оберіть стовпчики для відображення"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#213]
Наразі у нас є декілька таблиць із можливістю вибору стовпчиків для відображення ("Деталі проєктів", "Інвестиційні проєкти", "Деталі фінансових програм", "Фінансові програми, заявки"). 

У користувачів є запит на те, аби мати можливість обирати всі стовпчики одразу. Наприклад, через опцію "Обрати всі стовпчики". Якщо опцій дуже багато, тоді користувачам доводиться здійснювати багато дій, аби обрати всі стовпчики.

Також припускаю, це може бути корисно, якщо хочеться скинути вибір всіх стовпчиків, і вибрати два-три, які є цікавими.

Чи можемо ми це зробити? Якою буде механіка такого вибору?

**Comment by andrzejbeletsky** [comment]
take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/b7011c65-e80e-4ce8-850a-d567bafcdc80/state/analysis

**Comment by a-radik** [comment]
Звертаю увагу на те, що коли жодну колонку не вибрано (з переліку), таблиця продовжує відображати першу колонку (її наразі немає в переліку).
Оскільки жодну міру не вибрано, автоматично приховується рядок Totals, де ми показуємо кількість  рядків/сутностей в таблиці. Щоб лишився рядок Total треба лишати бодай одну міру в таблиці.

**Comment by andrzejbeletsky** [comment]
наразі є баг з кнопками - виправляю..

**Comment by andrzejbeletsky** [comment]
done

**Comment by ndrhzn** [comment]
Дякую! Потестували разом із Проєктним офісом. Наразі є запит на те, аби уможливити ще один сценарій - скинути до першопочаткових налаштувань. Чи ми можемо реалізувати і його також?

В такому разі у нас має бути три кнопки

- Обрати всі
- Скинути всі
- Повернутися до першопочаткових налаштувань

Оскільки "Повернутися до першопочаткових налаштувань" займає дуже багато місця, ми можемо натомість спробувати замість тексту дати іконку "refresh" - "⟳"

Якщо ми зробимо так, тоді порядок кнопок може бути для симетрії наступним:

- Обрати всі
- ⟳
- Скинути всі

Можемо так зробити, @andrzejbeletsky?

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
По механіці наче все добре, дякую! Є запит від користувачів зробити іконку більшою, бо не дуже читається, що це власне іконка refresh, людям видається, що це просто коло

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Загалом добре, давайте тільки замінимо іконку на ось цю - ↻ 

[Clockwise Open Circle Arrow ↻](https://symbl.cc/en/21BB/)

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Дякую! Зафіксуємо поки цей варіант

![Image](https://github.com/user-attachments/assets/a55c08d5-aaf4-4605-9f7f-0689c6ba0341)

Готово до релізу на прод

**Comment by a-radik** [comment]
Вимагає змін в мешапі.
Бажано все зробити за один підхід разом с сторінкою географія інвестиційних проєктів. Цодо цієї сторінки будуть зауваження?

**Comment by ndrhzn** [comment]
@a-radik описував коментарі щодо сторінки "Географія інвестиційних проєктів" ось тут #219
