### ISSUE TITLE
Сторінка: Географія інвестиційних проєктів

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#215]
Потрібно створити нову сторінку

**Назва сторінки**: Географія інвестиційних проєктів / Investment projects locations
**Адреса сторінки**: /investmentProjectsLocations
**Можлива іконка**: Щось на зразок карти
**Місце сторінки в боковому меню:** Після сторінки "Інвестиційні проєкти"

Ця сторінка буде містити наступні елементи (для цих елементів у нас будуть окремі задачі):

- [ ] Картки #216 
- [ ] Графіки #219 
- [ ] Таблиця #218 
- [ ] Фільтри #217 

Джерело даних: [Investment Projects endpoint](https://public-api.dream.gov.ua/marketplace/public/dream/investmentprojects)

**Scope of data**: Беремо лише ті ж інвестиційні проєкти, які відображаємо на сторінці "Інвестиційні проєкти"

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by ndrhzn** [comment]
За аналогією зі сторінкою "Публічні інвестиційні проєкти", цю сторінку варто перейменувати на "Географія публічних інвестиційних проєктів" / Public investment projects locations

**Comment by andrzejbeletsky** [comment]
done

**Comment by ndrhzn** [comment]
@a-radik у нас наче для цієї сторінки залишились окремі правки щодо інтеракції / фільтрів та швидкодії, але поза тим розташування елементів, видається, вже змінювати не будемо. Тому ймовірно можна віддавати в mashup

**Comment by a-radik** [comment]
З стандартни об'єктом Layout container, що використовуються тут виникло дві проблеми.
* експорт даних не можливий, експорт зображення працює тільки для всього об'єкта цілком (окремо таблицю і мапу або графік експортувати не вдасться)
* при відображені на менших екранах всі об'єкти будуть пропорційно зменшуватись (особливо це стосується зменшення по-горизонталі), в той час, як на інших сторінках вони переносяться і відображаються по вертикалі.

Є рішення цієї проблеми - треба прибрати об'єкти з layout container і дещо додати коду на сторінці мешапу.

Або лишити як є, без експорту даних.
Що робимо?

**Comment by ndrhzn** [comment]
Дякую за контекст! Обговоримо із Проєктним офісом і повернемось з рішенням.

Хочу уточнити - якщо йти шляхом "прибрати об'єкти з layout container і дещо додати коду на сторінці мешапу":
- чи зберігається при цьому весь функціонал, чи шось може змінитися у поведінці?
- скільки орієнтовно часу це може зайняти?

**Comment by a-radik** [comment]
За задумом вони працюватимать ідентично, але в кожного об'єкта будуть власні кнопки для завантаження.
Якщо все піде за планом пару годин на додавання коду и тестування. Може трохи більше

**Comment by andrzejbeletsky** [comment]
Вибір layout container зумовлено тим, що ми одне і те ж місце використовуємо або для двох об'єктів (карта і таблиця) або тільки одного об'єкту (таблиця).
Без layout container-у треба міняти розташування об'єктів на аркуші.

**Comment by a-radik** [comment]
Плануємо той самий функціонал реалізувати за допомогою мешапу.
для перших трьох кнопок буде 2 звичайних контейнери з трьома візуалізаціями в кожному, перемикатись будуть за значенням змінної що ти встановлюєш по кнопці.
для 4-ї кнопки замість двох контейнерів буде одна таблиця.
Такий задум

**Comment by ndrhzn** [comment]
Добре, давайте зробимо так, аби у нас працював нормально і експорт даних, і експорт зображень

**Comment by ndrhzn** [comment]
@a-radik чи є у вас розуміння, коли всі ці зміни для коректного експорту зображень та даних будуть імплементовані?

**Comment by ndrhzn** [comment]
Гаразд, тоді ось мої спостереження / правки:

Наразі на сторінці іконки пропонують завантажувати дані з карти (що, очевидно, не працює), а також завантажувати картинки з таблиці (що, очевидно, не дуже корисно).

Що потрібно зробити:

- Карта має пропонувати завантажувати картинки, але не пропонувати завантажувати дані
- Таблиці мають пропонувати завантажувати дані, але не пропонувати завантажувати картинки

**Comment by a-radik** [comment]
done
