### ISSUE TITLE
Географія інвестиційних проєктів: Графіки

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#219]
Тут нам потрібні графік та карта.

### Графік - розподіл інвестиційних проєктів за типом географії
Як ми знаємо, географія інвестиційного проєкту може описуватися трьома різними способами - це може бути одна локація, декілька локацій, або ж вся Україна. На сторінці "Інвестиційні проєкти" у таблиці ми матимемо стовпчик "Географія проєкту", котрий власне містить або назву однієї області, або ж перелік областей, або ж позначку "Вся Україна". Тут нам потрібен графік, котрий демонструватиме ключові показники (Кількість інвестиційних проєктів, Бюджет, Наявне фінансування, Фінансове покриття). 

Пропонуємо зробити стовпчиковий графік, де по осі Х іде обраний ключовий показник (за замовчуванням - Кількість інвестиційних проєктів), а по осі Y - тип географії інвестиційного проєкту. Стовпчики мають бути відсортовані за кількісним показником від найбільшого до найменшого.

case when | name_ua | name_en
-- | -- | --
Географія проєкту = одна область | Проєкт стосується однієї області | One region
Географія проєкту = перелік областей | Проєкт стосується декількох областей | Multiple regions
Географія проєкту = Вся Україна | Проєкт стосується всієї України |  Whole country

### Карта - розподіл інвестиційних проєктів за регіонами

Тут нам, ймовірно, потрібно зробити **три вкладки - для кожного типу географії**.

#### **Якщо обраний тип географії "Проєкт стосується однієї області"**
Ми бачимо карту України, що відображає обраний ключовий показник (за замовчуванням - Кількість інвестиційних проєктів) у розрізі областей. Картки мають відображати ключові показники для категорії "Проєкт стосується однієї області". Таблиця має відображати перелік проєктів, що мають тип географії "Проєкт стосується однієї області".

#### **Якщо обраний тип географії "Проєкт стосується декількох областей"**
Ми бачимо карту України, яка не відображає області не зафарбовані жодним кольором, а також prompt "Оберіть проєкт у таблиці для відображення даних на карті" / Select a project in the table to display the data on the map. Коли обраний один проєкт, карта відображає ті області, котрих стосується цей проєкт, без градації за кольором. Обрати можна лише один проєкт за раз. Карта не реагує на вибір показника у картках.  Картки мають відображати ключові показники для категорії "Проєкт стосується декількох областей". Таблиця має відображати перелік проєктів, що мають тип географії "Проєкт стосується декількох областей".

#### **Якщо обраний тип географії "Проєкт стосується всієї України"**
Карту не відображаємо взагалі.  Картки мають відображати ключові показники для категорії "Проєкт стосується всієї України". Таблиця має відображати перелік проєктів, що мають тип географії "Проєкт стосується всієї України".

**Comment by ndrhzn** [comment]
#203

**Comment by ndrhzn** [comment]
Layout - Розглянути варіант зробити у дві колонки (карта та таблиця) - за аналогією із тим, як це зроблено на сторінці "Фінансування"

У другому варіанті - якщо не обрано жодного проєкту, ми не показуємо карту, а показуємо call to action. 

У третьому варіанті - показуємо контурну карту

Estimate - 16 годин

**Comment by andrzejbeletsky** [comment]
take a look
щоб бар чарт не був самотнім після відбору типу географії, зараз він розкривається на наступний рівень.
якщо проєкт стосується однієї області - вимір область. якщо 2 інших - сектор. щодо цієї поведінки - питання відкрите.

**Comment by ndrhzn** [comment]
Дякую, вивчаємо, тестуємо, документуємо пропозиції

**Comment by ndrhzn** [comment]
Отже, за результатами тестування у Проєктному офісі, розуміємо, що сторінку треба трохи переробити. Наразі ідентифікували декілька речей, котрі є не у повній мірі зручними чи зрозумілими для користувачів

## Коментарі 

- Коли користувачі тільки потрапляють на сторінку, їм потрібно обрати один тип географії, аби на карті зʼявились дані. При цьому користувачі не дуже розуміють, в який саме спосіб їм потрібно обрати цей тип географії. Очевидно, що для більшості користувачів графік із типами географії не є способом вибору / інтерфейсом для вибору типу географії. Додатково тут користувачам не дуже зрозуміло, в який спосіб скинути вибір. Тобто зрозуміло, що у нас для цього є картка фільтру зверху сторінки, однак для частини користувачів може бути неочевидним звʼязок між їхніми попередніми діями щодо графіку та панеллю фільтрів
- Коли обрано тип географії "Проєкт стосується декількох областей", користувачі хотіли б мати один проєкт preselected by default
- Коли обрано тип географії "Вся Україна", карта видається користувачам зайвою, оскільки вона не несе жодної інформації
- Деталі (підкладка із назвами населених пунктів, дорогами, іншими країнами) на карті видаються зайвими і не узгоджуються із тим, як ми працюємо із представленням областей на інших сторінках

## Пропозиції

- Змінити layout таким чином, аби у нас було чотири вкладки (Всі проєкти, Проєкт стосується однієї області, Проєкт стосується декількох областей, Проєкт стосується всієї України)
- За замовчуванням користувачі мають бачити вкладку "Всі проєкти". На цій вкладці має бути таблиця та графік розподілу проєктів за типом географії. 
- На вкладці "Проєкт стосується однієї області" має бути таблиця і карта. Графіку розподілу проєктів за типом географії не має бути. Картки мають відображати значення для цієї вибірки.
- На вкладці "Проєкт стосується декількох областей" має бути таблиця і карта. Графіку розподілу проєктів за типом географії не має бути. Картки мають відображати значення для цієї вибірки.
- На вкладці "Проєкт стосується всієї України" має бути лише таблиця. Картки мають відображати значення для цієї вибірки.

## Layout / Розташування елементів

- Наразі у нас простір розділений 50% на 50% між таблицею та графіками. Можливо варто змінити співвідношення між ними в такий спосіб, як це зроблено на сторінці "Показники", аби карта займала більше місця
- Також можливо є сенс поміняти карту і таблицю місцями
- Якщо на графік буде більше місця, тоді на першій вкладці ("Всі проєкти") є сенс показувати розподіл проєктів за типом географії не за допомогою стовпчикового графіку, а за допомогою treemap, аби краще заповнювати простір. Але тут важливо стежити за тим, аби всі підписи добре читалися

Що думаєте, @andrzejbeletsky?

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Дякую! 

Трохи потестували нову версію - загалом подобається, але є декілька коментарів:

- Коли переключаємось на сторінку "**Проєкт стосується декількох областей**", то перший проєкт є pre-selected. Загальна настанова тут була в тому, аби користувачі одразу бачили, як це працює, і як можна з цією сторінкою працювати. Однак ми виявили, що це може навпаки заплутувати користувачів, оскільки вони бачать в таблиці лише один проєкт, і їм може бути не дуже зрозуміло, що можна скинути пре-фільтр і отримати всю вибірку проєктів у цій категорії. Рішення тут наступне - **відмовитись від пре-фільтру і показувати всі проєкти у таблиці**
- На сторінці "**Проєкт стосується декількох областей**" замінити call to action текст на "Оберіть один проєкт у таблиці справа для відображення даних на карті" / Select one project in the table on the right to display data on the map
- На сторінці "**Проєкт стосується декількох областей**" ми бачимо кордони лише тих областей, у котрих є проєкти. Варто показувати кордони всіх областей, але зафарбовувати лише ті, у котрих є проєкти.

**Comment by ndrhzn** [comment]
Також зауважили, що картки у нас тут не є активними зовсім. Тобто якщо клікнути на картку "Бюджет", то графік на першій вкладці або ж карта на другій вкладці все одно показуватимуть кількість проєктів. 

Видається, що для першої та другої вкладок можна робити картки активними. 

Для вкладки "Всі проєкти"

- Кількість проєктів - treemap
- Бюджет - treemap
- Наявне фінансування - treemap
- Фінансове покриття - horizontal bar chart

Для вкладки "Проєкт стосується однієї області" всі показники можна відобразити на карті без зміни способу презентації

**Comment by ndrhzn** [comment]
І зауважили, що все працює доволі повільно. Тобто швидкість змін після переходу на нову вкладку доволі низька. Чому так? І чи можна це виправити? @andrzejbeletsky

**Comment by andrzejbeletsky** [comment]
take a look

Зі швидкістю працюємо..

**Comment by ndrhzn** [comment]
Дякую!

Ось для цієї сторінки ще потрібно додати кордони всіх областей, а не лише виділених

![image](https://github.com/user-attachments/assets/1f92aeec-99cf-4b07-b12d-dacc566f6ff4)

**Comment by andrzejbeletsky** [comment]
done

**Comment by ndrhzn** [comment]
Дякую! За формою наче все добре. Наразі все ще є відкритим питання щодо швидкодії, а також звертаємо увагу на деякі нюанси інтеракції.

Зокрема звернули увагу, що **після застосування певних фільтрів автоматично зʼявляється фільтр "Код інвестиційного проєкту"**. Чому так відбувається, і що це означає? @andrzejbeletsky 

![image](https://github.com/user-attachments/assets/9f230a9b-5a6e-416e-9a53-8d8e65a19d93)

Також виглядає так, що картка фільтру "Профінансованість" не відображається на панелі зверху, якщо фільтр застосувати (натомість зʼявляється картка "Код інвестиційного проєкту"

![image](https://github.com/user-attachments/assets/3019b7ae-0e48-4eae-8aae-2bcb92988144)

**Comment by andrzejbeletsky** [comment]
виправив
take a look

**Comment by ndrhzn** [comment]
Дякую! Щодо швидкості - це вже оптимізовано чи ми ще чекаємо пришвидшення?

**Comment by andrzejbeletsky** [comment]
Щодо швидкості - шукаємо можливості. Поки що немає очевидної відповіді, чого так.
