### ISSUE TITLE
Деталі фінансових програм: Звіт за період

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#220]
## Запит / Problem statement / User story

На сторінці "Деталі фінансових програм" ми надаємо інформацію про надходження та використання коштів станом на зараз. Тобто це завжди кумулятивні суми за весь період спостережень. Водночас у користувачів є запит на те, аби мати можливість бачити звіт за певний період. Тобто, наприклад, обрати вересень 2024 і побачити, скільки коштів надійшло за цей місяць, та скільки коштів було витрачено.

## Дані

З точки зору моделі даних, у нас має бути можливість показувати розбивку надходження та витрат коштів за періодами. 

### Надходження коштів

Надходження коштів у нас наразі привʼязано до періоду, як вже [було задокументовано під час реалізації показника "Надійшло" для таблиці "Деталі фінансових програм"](https://github.com/open-contracting/bi.dream.gov.ua/issues/163#issue-2400963491).

Потрібні нам дані містяться в елементі cdu_response/approaches/implementation/financialProgress/breakdown

```
"implementation": {

    "financialProgress": {

      "breakdown": [

        {

          "id": "0235c342-4781-4e83-8e31-699d4c171903",

          "period": {

            "endDate": "2024-05-31",

            "startDate": "2024-05-01"

          },

          "measures": {

            "disbursed": 21127088

          },

          "classifications": {

            "budgetFinanceId": "76467cb0-1f42-c8d5-f4f1-5dcae53eecdb"

          }

        },

        {

          "id": "4d90b9df-886a-4b0c-872e-a47c78dc24f6",

          "period": {

            "endDate": "2024-06-30",

            "startDate": "2024-06-01"

          },

          "measures": {

            "disbursed": 35211813

          },

          "classifications": {

            "budgetFinanceId": "76467cb0-1f42-c8d5-f4f1-5dcae53eecdb"

          }

        },

        {

          "id": "70d50484-3cc3-47ab-b670-c9b025795c2b",

          "period": {

            "endDate": "2024-08-31",

            "startDate": "2024-08-01"

          },

          "measures": {

            "disbursed": 11510589

          },

          "classifications": {

            "budgetFinanceId": "76467cb0-1f42-c8d5-f4f1-5dcae53eecdb"

          }

        },

        {

          "id": "80b31c62-c16c-4d2d-bcb0-a6f11d33dae0",

          "period": {

            "endDate": "2024-07-31",

            "startDate": "2024-07-01"

          },

          "measures": {

            "disbursed": 35211813

          },

          "classifications": {

            "budgetFinanceId": "76467cb0-1f42-c8d5-f4f1-5dcae53eecdb"

          }

        }

      ]

    }

  }
```
Тут є `period/startDate` та `period/endDate`, за дизайном вони завжди обмежені одним місяцем. Тобто ми можемо бачити, скільки надійшло коштів у розрізі місяців.

### Витрати

Витрати у нас також привʼязані до певного періоду, як [було задокументовано під час реалізації показника "Витрачено" для таблиці "Деталі фінансових програм"](https://github.com/open-contracting/bi.dream.gov.ua/issues/178#issue-2422765283).

```
{
  "id": "a9a61ac7-25b5-4e76-9c07-db4ae0e3ca2e",
  "period": {
    "endDate": "2023-12",
    "startDate": "2023-12"
  },
  "measures": {
    "paid": 3515872.94,
    "signed": 3515872.94
  },
  "classifications": {
    "date": "2024-07-10T09:35:11.630587Z",
    "contractingFinanceId": "f9974410-ccf8-41c4-9ed6-6e65d6d5f4bb"
  }
}
```

Тут також є `period/startDate` та `period/endDate`, і за дизайном вони також обмежені одним місяцем. Тобто ми можемо бачити, скільки витрачено коштів у розрізі місяців.

### Змінні показники, статичні показники, обчислювальні показники

Отже, частина показників у нас може змінюватися. Разом з тим, у нас також є статичні показники та обчислювальні показники (ті, що залежать від змінних показників)

показник | тип показника
-- | --
Код проєкту | статичний
Посилання на проєкт | статичний
Статус | статичний
Назва проєкту | статичний
Ініціатор | статичний
Орган управління | статичний
Область | статичний
Сектор | статичний
Фінансова програма | статичний
Код бюджету, з якого здійснюється співфінансування проєкту | статичний
Загальна кошторисна вартість | статичний
Загальний орієнтовний бюджет | статичний
Кошторисна вартість за результатами проведених тендерів | статичний
Дата та номер рішення (розпорядження) про розподіл коштів бюджетам місцевого рівня | статичний
Заплановано. Місцевий бюджет | статичний
Заплановано. Державний бюджет (субвенція) | статичний
Заплановано. Інші джерела | статичний
Надійшло. Місцевий бюджет | змінний
Надійшло. Державний бюджет (субвенція) | змінний
Надійшло. Інші джерела | змінний
Сума ще не виділених коштів. Місцевий бюджет | обчислювальний
Сума ще не виділених коштів. Державний бюджет (субвенція) | обчислювальний
Сума ще не виділених коштів. Інші джерела | обчислювальний
Витрачено. Місцевий бюджет | змінний
Витрачено. Державний бюджет (субвенція) | змінний
Витрачено. Інші джерела | змінний
Залишок коштів. Місцевий бюджет | обчислювальний
Залишок коштів. Державний бюджет (субвенція) | обчислювальний
Залишок коштів. Інші джерела | обчислювальний
Недофінансована частка проєкта | обчислювальний
Залишкова кошторисна вартість | обчислювальний
Дата оголошення тендеру | статичний
Дата підписання договору | статичний
Клас наслідків | статичний
Будівельні роботи | статичний
Відбувається коригування ПКД чи ні | статичний
Частка виконаних робіт | статичний
Плановий термін завершення виконання робіт | статичний
Фактична дата завершення, день, місяць, рік | статичний

Якщо ми хочемо запровадити можливість фільтрації даних за періодом, то поведінка статичних, змінних, та обчислювальних показників природньо має бути різною.

**Статичні показники** не мають залежати від фільтру. Тобто для будь-якого обраного періоду вони завжди показують однакову інформацію.

**Змінні показники** мають залежати від фільтру. Тобто для будь-якого обраного періоду вони мають показувати дані саме для обраного періоду.

**Обчислювані показники** у нас наразі залежать від тих показників, які є за природою змінними. Тобто за замовчуванням вони мали б теж змінюватися. Але на практиці це не дуже має сенс, бо, наприклад, показник "Сума ще не виділених коштів" ми розраховуємо як різницю "Заплановано" та "Надійшло". Якщо ми обрали дані для вересня 2024, нам немає сенсу співвідносити "Надійшло" у вересні 2024 із "Заплановано" загалом. Тобто для обчислювальних показників потрібно завжди використовувати лише кумулятивні значення (наприклад, "Надійшло" загалом, а не у обраному періоді).

В такому разі можливо для звіту за період нам має сенс запровадити показники на зразок "Надійшло загалом" та "Надійшло за обраний період". Або ж для звіту за період нам є сенс прибрати обчислювальні показники взагалі.

### Механіка вибору періоду

Тут треба визначитись, в який спосіб ми можемо реалізувати вибір періоду. Загальна ідея така, що у користувачів має бути можливість обрати або один місяць, або декілька місяців.  Треба зрозуміти, які опції для цього пропонує Qlik, і які з них будуть найпростішими з точки зору інтеракції.

### Презентація звіту за період

Тут треба зрозуміти, як нам краще організувати звіт за період на сторінці. 

- **Це може бути новий функціонал вже наявної таблиці**. В такому разі функціонал вибору періоду завжди доступний на панелі фільтрів, але за замовчуванням він налаштований таким чином, аби обраними були всі місяці, доступні в наборі даних
- **Це може бути нова вкладка на цій сторінці**

**Comment by ndrhzn** [comment]
#154

**Comment by ndrhzn** [comment]
Отже, після консультацій з Проєктним офісом погодили наступне:

## Вибір періоду

**Для вибору періоду потрібно додати фільтр "Період" / Date range**. Фільтр має знаходитись на боковій панелі фільтрів після фільтру "Фінансова програма".  У цьому фільтрі мають бути значення року та місяця, наприклад, у форматі "Рік, місяць"  (Вересень, 2024). 

### Перелік місяців

В ідеалі нас цікавлять, звісно, не всі місяці взагалі, а лише ті, за які вони можуть звітувати.  Можна було дивитися на якісь елементи в даних і задавати діапазон за ними, але загалом можна і простіше. Місяць, коли у нас зʼявились фінпрограми - це Червень, 2024. Це і є мінімальне значення діапазону. А максимальне значення діапазону це напевне завжди поточний місяць. Тобто у жовтні 2024, це Жовтень, 2024.

### Порядок місяців

За механікою користувачі подають звітність, здається, до 5 числа кожного місяця за попередній місяць. Тобто, наприклад, 5 листопада 2024 року, вони зроблять вигрузку даних за жовтень 2024. Таким чином, найбільш цікавий місяць для них - це умовно завжди останній / попередній місяць. Це потрібно враховувати у впорядкування місяців. Вони мають йти у зворотньому хронологічному порядку. Тобто, наприклад, "Жовтень, 2024", "Вересень, 2024", "Серпень, 2024" і т.д.

## Фільтрація даних

Ця звітність насамперед має на мені відстежувати фінансовий прогрес у виконанні проєктів. Ключовими показниками для нас тут є групи стовпчиків "Надійшло" та "Витрачено". Саме вони мають реагувати на фільтри. Тобто, якщо у фільтрі "Період" обрано "Вересень, 2024", то групи стовпчиків "Надійшло" та "Витрачено" мають показувати, скільки коштів надійшло, та скільки було витрачено впродовж вересня 2024 року. Обидва показники мають привʼязку до періодів, як описано у першому дописі в цьому треді.

## Зміна таблиці після застосування фільтру

Оскільки у нас є декілька обчислювальних показників, які залежать від груп показників "Надійшло" та "Витрачено" ("Сума ще не виділених коштів", "Залишок коштів",  "Недофінансована частка проєкта", "Залишкова кошторисна вартість"), то природна поведінка їх внаслідок застосування фільтрів буде не надто коректною в контексті звітності. Скажімо, у нас є "Сума ще не виділених коштів", що розраховується як різниця між "Заплановано" та "Надійшло". Якщо ми будемо порівнювати "Заплановано" взагалі та "Надійшло" за конкретний місяць, в контексті звітності ми отримаємо не дуже коректні результати, оскільки вони не будуть враховувати ті кошти, що могли бути виділені за всі попередні місяці.

У нас є декілька можливих способів роботи із цим:

### Якщо застосований фільтр за періодом, не показувати обчислювальні стовпчики і не давати можливість їх обрати

Тобто, якщо обрано один місяць або ж декілька місяців, але вибірка є меншою за весь доступний діапазон, тоді показники "Сума ще не виділених коштів", "Залишок коштів",  "Недофінансована частка проєкта", "Залишкова кошторисна вартість" з таблиці потрібно прибрати, і на панелі "Оберіть стовпчики для відображення" вони мають бути недоступними (або якщо неможливо їх зробити недоступними, тоді зробити неможливим вибір цих показників).

### Розраховувати обчислювальні показники не відносно обраного періоду, а відносно наростаючого підсумку

Тобто, якщо обрано один місяць - "Вересень, 2024", тоді для розрахунку, наприклад, показника "Сума ще не виділених коштів", ми беремо показник "Заплановано" та "Надійшло", але  для "Надійшло" ми беремо не те, скільки надійшло за вересень, 2024, а від самого початку включно з вереснем 2024. 

Якщо обрано період, наприклад - "Липень, 2024", "Серпень, 2024", "Вересень, 2024", тоді для розрахунку показника "Сума ще не виділених коштів" ми беремо "Заплановано" та "Надійшло", але для "Надійшло" ми беремо не те, скільки надійшло за обрані три місяці, а обираємо верхнє значення періоду - "Вересень, 2024", і рахуємо, скільки надійшло від самого початку включно з вереснем 2024.

Методологічно другий варіант видається ліпшим. І таким чином ми не втрачатимемо показники. Але, звісно, це вимагатиме трохи змін на рівні моделі даних.

Але скажіть, що ви думаєте про обидва варіанти, і який вам видається більш доречним у цьому випадку? @andrzejbeletsky

**Comment by andrzejbeletsky** [comment]
take a look
з реалізацією "Розраховувати обчислювальні показники не відносно обраного періоду, а відносно наростаючого підсумку"

**Comment by ndrhzn** [comment]
Поки ще тестуємо з користувачами, аби впевнитись, що все працює так, як вони очікують.

Але звернули увагу, що рядок "Всього" у нас не функціонує так, як всі інші рядки. Тобто, наприклад, для обчислення показника "Сума ще не виділених коштів" використовується показник "Надійшло" не наростаючим підсумком, а за обраний місяць. @andrzejbeletsky 

![image](https://github.com/user-attachments/assets/fac4ac8d-a01a-4fd1-8597-cacbe4ccea49)

**Comment by andrzejbeletsky** [comment]
виправив баги
take a look

**Comment by ndrhzn** [comment]
Дякую!

Хочу зрозуміти ще один кейс:

За нашою логікою, якщо обрано, наприклад, останній місяць, то для розрахунку показника “Сума ще не виділених коштів”, має використовуватись показник “Надійшло” наростаючим підсумком. Тобто, від самого початку, і до поточного місяця включно.

Тобто, якщо обрано жовтень 2024, тоді це має дорівнювати вибірці травень - жовтень. І в такому разі показник “Сума ще не виділених коштів” має бути однаковим якщо обрано період “Жовтень, 2024” та якщо не обрано жодного місяця. Так?

**Приклад перший: Застосовано фільтр "Період" = "Жовтень, 2024"**

![image](https://github.com/user-attachments/assets/b1acc029-4e12-43ba-972a-83b33afcad20)


**Приклад другий: Не застосовано жодного фільтра за періодом**

![image](https://github.com/user-attachments/assets/fd1fe203-9068-4b28-aed9-aa3a8066f49f)

Різниця у значеннях = 725 022.

Я перевірив всі дані на рівні проєктів, і, здається, ідентифікував проєкт, на котрому виникає проблема - [300424-B92E6E2A](https://dream.gov.ua/ua/project/DREAM-UA-300424-B92E6E2A/profile) ([проєкт в АРІ](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/v5p02667-6cr2-4m95-a1v0-48mqs1k628or)).

**Приклад перший: Застосовано фільтр "Період" = "Жовтень, 2024"**

![image](https://github.com/user-attachments/assets/11255df8-e9ab-4c1d-9b07-f819a42eeb90)

**Приклад другий: Не застосовано жодного фільтра за періодом**

![image](https://github.com/user-attachments/assets/a405ffc5-01c6-415a-a2f9-977e4c31f27d)

**Comment by ndrhzn** [comment]
Можливо проблема полягає в тому, що в проєкті є значення для disbursed, датовані листопадом та груднем 2024 року.

```
{
  "implementation": {
    "financialProgress": {
      "breakdown": [
        {
          "id": "1221fbb6-78ec-4329-a321-07084edf2118",
          "period": {
            "endDate": "2024-10-31",
            "startDate": "2024-10-01"
          },
          "measures": {
            "disbursed": 362511
          },
          "classifications": {
            "budgetFinanceId": "b508d30b-1f41-4a2b-a7c2-a2a9d3b66aeb"
          }
        },
        {
          "id": "304d4c1d-e64e-40b5-abd2-4df51d4cf161",
          "period": {
            "endDate": "2024-09-30",
            "startDate": "2024-09-01"
          },
          "measures": {
            "disbursed": 362511
          },
          "classifications": {
            "budgetFinanceId": "b508d30b-1f41-4a2b-a7c2-a2a9d3b66aeb"
          }
        },
        {
          "id": "4205269e-8ed7-4d52-865a-516af1587828",
          "period": {
            "endDate": "2024-08-31",
            "startDate": "2024-08-01"
          },
          "measures": {
            "disbursed": 362510
          },
          "classifications": {
            "budgetFinanceId": "b508d30b-1f41-4a2b-a7c2-a2a9d3b66aeb"
          }
        },
        {
          "id": "4d7b0507-9880-47b5-a509-abcf25349148",
          "period": {
            "endDate": "2024-12-31",
            "startDate": "2024-12-01"
          },
          "measures": {
            "disbursed": 362511
          },
          "classifications": {
            "budgetFinanceId": "b508d30b-1f41-4a2b-a7c2-a2a9d3b66aeb"
          }
        },
        {
          "id": "b259378e-d8ea-4b68-b628-0389e88e8c1c",
          "period": {
            "endDate": "2024-07-31",
            "startDate": "2024-07-01"
          },
          "measures": {
            "disbursed": 1450040
          },
          "classifications": {
            "budgetFinanceId": "b508d30b-1f41-4a2b-a7c2-a2a9d3b66aeb"
          }
        },
        {
          "id": "c4abb6f4-3d47-400b-a60e-cc0430062e85",
          "period": {
            "endDate": "2024-07-31",
            "startDate": "2024-07-01"
          },
          "measures": {
            "disbursed": 403242
          },
          "classifications": {
            "budgetFinanceId": "8a69d68e-7add-4276-944c-7c787c1c9dd9"
          }
        },
        {
          "id": "c7b07ea5-db9d-48aa-9d27-28c362f3f4de",
          "period": {
            "endDate": "2024-11-30",
            "startDate": "2024-11-01"
          },
          "measures": {
            "disbursed": 362511
          },
          "classifications": {
            "budgetFinanceId": "b508d30b-1f41-4a2b-a7c2-a2a9d3b66aeb"
          }
        }
      ]
    }
  }
}
```

За листопад зазначили 362511, за грудень 362511. Разом 725022.

Отже, ймовірно поведінка така: коли застосовується фільтр, то ці значення не враховуються. Коли фільтр не застосовується, тоді вони враховуються,  і звідси походять розбіжності в даних.

Потрібно зрозуміти, чи зазначення надходжень у майбутньому це валідний бізнес-кейс.

**Comment by andrzejbeletsky** [comment]
саме так і є.
майбутні періоди. у календар вони не занесені (бо тільки по поточний місяць), але якщо скинути фільтри, ці цифри також враховуються.
