### ISSUE TITLE
Bug: Проєкти з наявним фінансуванням, але без "Джерела фінансування"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#226]
У нас віднедавна почали зʼявлятися проєкти, у котрих є фінансування, але не зазначене джерело фінансування. Раніше таку ситуацію було важко уявити, однак зараз це принаймні технічно можливо.

![Image](https://github.com/user-attachments/assets/3d6935ce-c2e4-42a6-a95e-56a0c17715e7)

Проблема з такими проєктами полягає хоча б в тому, що на сторінці "Деталі фінансування" вони ніяк не фігурують. І через це у таблиці "Деталі фінансування" та на решті сторінок у нас не збігаються числа у показнику "Наявне фінансування". Скажімо, станом на зараз у таблиці "Деталі проєктів" ми маємо показник наявного фінансування - 68.8 млрд грн, а на сторінці "Деталі фінансування" - 56.7 млрд грн.

Звісно, в ідеалі ця проблема має бути вирішена на стороні джерела даних. Втім, ця задача їм була описана, але прогресу щодо виправлення проблеми ми наразі не бачимо. Тому є сенс зробити правки на стороні BI, аби принаймні числа у нас збігалися між різними сторінками.

Що потрібно зробити:

**Якщо у проєкту є наявне фінансування, але відсутній елемент financingParty/id, тоді  замість financingParty/id ми можемо ставити N/A.** Або ж ми можемо писати експліцитно "Джерело фінансування не зазначено" / Funding source is not specified.

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Дякую! Узгоджуємо із Проєктним офісом коректну назву для цієї категорії

**Comment by ndrhzn** [comment]
Після консультацій з командою розробки та Проєктним офісом погодили для тих випадків, коли є фінансування, але немає `financingParty/id`, використовувати в якості альтернативи `cdu_response/approaches/budget/finance/classification/budgetProgramKVK`.

```
"classification": {
        "budgetProgramId": "1201010",
        "budgetProgramKVK": "120",
        "budgetProgramName": "Керівництво та управління у сфері економіки"
    }
```

Це поле має містити числовий код - наприклад, 120. Аби отримати назву організації, нам потрібно із цим числовим кодом звернутися до довідника.

`https://public-isb.dream.gov.ua/isb/openbudget/classifiers/KVK?code=120
`

Цей запит поверне нам таку відповідь

```
{
  "data": [
    {
      "beginDate": "2011-01-14",
      "code": "221",
      "parentCode": null,
      "level": 1,
      "endDate": "2014-02-06",
      "name": "Міністерство освіти і науки, молоді та спорту України (загальнодержавні витрати)",
      "beginDoc": "Наказ Мінфіну № 11 від 14.01.11",
      "details": 1,
      "endDoc": "Наказ Мінфіну № 44 від 07.02.14"
    },
    {
      "beginDate": "2014-02-07",
      "code": "221",
      "parentCode": null,
      "level": 1,
      "endDate": "2017-12-31",
      "name": "Міністерство освіти і науки України (загальнодержавні витрати)",
      "beginDoc": "Наказ Мінфіну № 44 від 07.02.14",
      "details": 1,
      "endDoc": "Наказ Мінфіну № 1175 від 29.12.17"
    },
    {
      "beginDate": "2018-01-01",
      "code": "221",
      "parentCode": null,
      "level": 1,
      "endDate": null,
      "name": "Міністерство освіти і науки України (загальнодержавні видатки та кредитування)",
      "beginDoc": "Наказ Мінфіну № 1175 від 29.12.17",
      "details": 1,
      "endDoc": null
    }
  ]
}
```

Як бачимо, тут міститься декілька записів про назви організацій. Для нас ймовірно має сенс брати поточну. Тому можна взяти або обʼєкт із максимальним значенням `beginDate`, або ж обʼєкт без елементу `endDate`.

І у цьому обʼєкті нам потрібен елемент `name`.

Водночас, видається, що є сенс лишити N/A для тих випадків, коли ми не маємо ані `financingParty/id`, ані `finance/classification/budgetProgramKVK`, аби ми мали можливість діагностувати проблему.

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Дякую! Задокументую тут питання для внутрішнього обговорення і подальшого покращення сторінки:

- Обʼєднання / уніфікація назв організацій
- Транслітерація

## Обʼєднання / уніфікація назв організацій

Наразі можлива ситуація, коли у нас один ГРК фігурує декілька разів під різними назвами.

![image](https://github.com/user-attachments/assets/36c6774e-c420-4611-ae14-4b2df567c69f)

![image](https://github.com/user-attachments/assets/6a655573-e8b8-4352-afd3-80932747c69e)

Найперше, що потрібно зʼясувати - чи це виправляється на рівні джерела даних.

## Транслітерація

Наразі у нас всі назви ГРК дані кирилицею. Ймовірно, є сенс транслітерувати їх латиницею для англійської версії сторінки. Однак це ймовірно матиме сенс лише після уніфікації назв.

## Bonus: Назви громад

Насамкінець також звернув увагу, що з деяких назв може бути неочевидно, що йдеться про територіальні громади. Ймовірно, ми можемо тут трохи доповнити назви, аби користувачам не доводилось здогадуватись (однак це буде окрема задача).

**Comment by ndrhzn** [comment]
Щодо різних назв - встановили, що насамперед тут йдеться про різні коди, а вже потім про різні назви

[275 Міністерство розвитку громад та територій України](https://public-isb.dream.gov.ua/isb/openbudget/classifiers/KVK?code=275)
[276 Міністерство розвитку громад та територій України (загальнодержавні видатки та кредитування)](https://public-isb.dream.gov.ua/isb/openbudget/classifiers/KVK?code=276)
[312 Міністерство розвитку громад, територій та інфраструктури України (загальнодержавні видатки та кредитування)](https://public-isb.dream.gov.ua/isb/openbudget/classifiers/KVK?code=312)
[310 Міністерство розвитку громад, територій та інфраструктури України](https://public-isb.dream.gov.ua/isb/openbudget/classifiers/KVK?code=310)

**Comment by ndrhzn** [comment]
Довідковий документ - [Про затвердження Змін до бюджетної класифікації](https://zakon.rada.gov.ua/rada/show/v0154201-23#Text )
