### ISSUE TITLE
UI: Переглянути, які стовпчики мають бути visible, а які hidden у таблиці "Деталі фінансових програм"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#227]
На сторінці "Деталі фінансових програм" потрібно 

**Зробити видимими за замовчуванням стовпчики:**

- Витрачено. Державний бюджет
- Витрачено. Місцевий бюджет
- Витрачено. Інше

**Зробити прихованими за замовчуванням стовпчики:**

- Статус проєкту
- Код бюджету, з якого здійснюється співфінансування проєкту
- Дата та номер рішення (розпорядження) про розподіл коштів
- Кошторисна вартість за результатами проведених тендерів

**Comment by ndrhzn** [comment]
#154

**Comment by andrzejbeletsky** [comment]
take a look
