### ISSUE TITLE
Ui / UX: Замінити іконки для завантаження даних та зображень

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#231]
Наразі у нас використовуються три іконки для завантаження даних у форматах PDF, XLSX, та PNG. Користувачі декілька разів нам вказували на те, що з самих іконок не дуже зрозуміло, що вони роблять, і просили додати підказки щодо цього. Втім, видається, що ми знайшли більш елегантне рішення - замість того, аби додавати підказки до іконок, зробити самі іконки більш зрозумілими. А саме - використати іконки, які безпосередньо вказують на формат файлу.

Наприклад:

- [PDF](https://www.flaticon.com/free-icon/pdf-file_80942?related_id=80942)
- [PNG](https://www.flaticon.com/free-icon/png-file_81410?term=png&page=1&position=8&origin=search&related_id=81410)
- [XLSX](https://www.flaticon.com/free-icon/xlsx-file-format-extension_28841?term=xlsx&page=1&position=2&origin=search&related_id=28841)

Питання - чи ми можемо використати ці іконки? Якщо ні, тоді ми можемо попросити нашу дизайнерку зробити подібні.

**Comment by a-radik** [comment]
Виходить ось так. Перенести на stage?
![image](https://github.com/user-attachments/assets/0b1870bb-ad5a-4d40-ad8e-c1d6ec647e02)

**Comment by a-radik** [comment]
https://bi.qnalytics.com/dream/#/investmentProjects
