### ISSUE TITLE
Data / Filters: Деталізація розташування до рівня населеного пункту

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#232]
Наразі ми на рівні даних проєктів та фільтрів розкладаємо дані щодо розташування на елементи "область", "район", "громада". Однак у наших користувачів також є запит на те, аби бачити інформацію на рівні населеного пункту. Ця інформація потрібна для звітності для донорів, а також для аналітики організацій, котрі займаються проєктами саме на рівні міст / населених пунктів.

Це можна імплементувати як один елемент даних - "Населений пункт", і в такому разі він має складатися із вказівки на тип населеного пункту (наприклад, "м.") та назви населеного пункту (наприклад, "Чернігів").

Або це можна імплементувати як два окремих елементи даних - "Тип населеного пункту" та "Населений пункт".

Можна почати з простої версії імплементації, тобто з одного елементу даних.

Українська назва елементу даних - "Населений пункт"
Англійська назва елементу даних - "Locality"

Отже, пропонуємо додати нові елементи даних до сторінки "Всі фільтри" та таблиці "Деталі проєктів".

На сторінці "Всі фільтри" ми хочемо бачити

- Фільтр "Населений пункт". Він має бути розташований у блоці "Місцезнаходження" після фільтру "Громда"

На сторінці "Деталі проєктів" ми хочемо бачити стовпчик "Населений пункт". Він має бути розташований у таблиці після стовпчика "Громада". Він має бути прихованим за замочуванням, але у користувачів має бути можливість обрати його для відображення через панель "Оберіть стовпчики для відображення".

Звісно, не у всіх обʼєктів може бути деталізація до рівня населеного пункту. Тут у нас є дві стратегії - або ж лишати дефолтний "-", або ж ставити N/A. Видається, що можна почати з простою імплементації - ставити дефолтний "-".

**Comment by ndrhzn** [comment]
#10 #125

**Comment by a-radik** [comment]
чи треба розрізнивати "село" і "селище" при відображені чи достатньо писати "с."?

- якщо в джерелі буде вказано район у місті треба (в коді КАТОТТГ) його також відображати чи ні? якщо треба, то як це має виглядати? (м. Миколаїв, Корабельний р-н)?
- як працювати с містами зі спец. статусом: Київ і Севастополь? Наразі в таблиці це виглядає так: 
   Область: Київ, 
   Район: N/A
   Громада: Київ (якщо врахувати зміни що не було передано на прод) 
   Далі буде населений пуункт: Київ (можливо з районом міста)

- враховуючи всі особливості даних, простіше буде мати 2 колонки: тип населеного пункту і населений пункт. Обидві мають з'являтись/зникати при виборі опції Населений пункт в переліку полів чи треба робити окремі опції?

**Comment by ndrhzn** [comment]
@a-radik, дякую за питання!

- Розрізняти село та селище потрібно, за КАТОТТГ це різні сутності
- Деталізація до району міста нас наразі не цікавить (це є пʼятий, додатковий рівень деталізації у КАТОТТГ) 
- Міста зі спецстатусом нас тут цікавлять. Тобто Київ та Севастополь ми записуємо у стовпчику "Населений пункт"
- Мати дві колонки - "Тип населеного пункту" та "Населений пункт" видається гарним рішенням. Ймовірно, є сенс зробити їх окремими пунктами у блоці із вибором переліку полів, аби не міняти механіку

Щодо того, чи має бути Київ у територіальних громадах, відпишу у відповідному треді, в котрому це питання вперше постало

**Comment by andrzejbeletsky** [comment]
take a look
https://bi.qnalytics.com/dream/#/projectDetails

**Comment by andrzejbeletsky** [comment]
take a look
https://bi.qnalytics.com/dream/#/projectDetails
чи треба мати "Тип населеного пункту" у фільтрах на сторінці? Зараз вже дефолтного розміру не достатньо для всіх елементів у фільтрі.

**Comment by ndrhzn** [comment]
@andrzejbeletsky давайте поки лишимо, а далі будемо дивитися за ситуацією.

У нас наразі пишеться "Тип населеного пункта", хоча граматично має бути "Тип населеного пункту". Я замінив у Dream Translations, але треба буде підтягнути оновлення.

**Comment by andrzejbeletsky** [comment]
Done
