### ISSUE TITLE
Data / Bug: На сторінці "Бюджетування" фільтр за статею бюджету призводить до некоректних показників "Фінансування" та "Фінансове покриття"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#233]
## Проблема

На сторінці "Бюджетування" у нас є можливість застосувати фільтр за конкретною статею бюджету.

![Image](https://github.com/user-attachments/assets/265d1d89-8e1d-4cd7-852e-3d1c9346c633)

Наприклад, ми можемо обрати "Проєктування", і тоді будемо бачити у картках

- Кількість проєктів, що мають статтю бюджету "Проєктування"
- Суму всіх статей "Проєктування" для цієї вибірки проєктів
- Суму всього наявного фінансування для цієї вибірки проєктів
- Показник "Фінансового покриття", що розраховується з попередніх двох показників

Проблема тут полягає в тому, що ми не маємо даних щодо фінансування у привʼязці до статей бюджету. І таким чином ми завжди показуємо загальне фінансування. І фінансове покриття ми розраховуємо не дуже коректно - ми порівнюємо частину бюджету зо всім наявним фінансуванням.

## Рішення

Видається, що допоки ми не матимемо даних щодо фінансування у привʼязці до статей бюджету, є сенс не показувати "Наявне фінансування" та "Фінансове покриття", якщо застосовано фільтр за статею бюджету.

@andrzejbeletsky, чи це має сенс, і чи ми можемо таке зробити?

**Comment by ndrhzn** [comment]
#31

**Comment by a-radik** [comment]
на проді разом з іншими виправленнями

**Comment by ndrhzn** [comment]
Дякую! 

![image](https://github.com/user-attachments/assets/62c8c996-b0bb-4260-b505-ddb26736bf5a)

Давайте також додамо текст для англійської версії: Does not apply to cost items

**Comment by andrzejbeletsky** [comment]
змінив в транслейшн

**Comment by ndrhzn** [comment]
Дякую! Бачу на тесті, можна на прод

![image](https://github.com/user-attachments/assets/0d050c4e-a0d5-4bb3-b08d-f086d46c07f6)
