### ISSUE TITLE
Bug: Некоректне відображення даних на сторінці "Деталі фінансових програм"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#234]
На сторінці "Деталі фінансових програм" у нас наразі у фільтрі "Фінансова програма" відображається чотири фінпрограми. 

![Image](https://github.com/user-attachments/assets/7e9a66ea-edeb-4acd-a35a-9b65ed9d9a4c)

За трьома з них у нас справді є проєкти, котрі отримали фінансування у рамках цих фінпрограм. 

https://public-api.dream.gov.ua/marketplace/public/dream/ifiprojects/8w2ht6q5-613z-4td5-9rin-1s28he8p11e9/projects - 57

https://public-api.dream.gov.ua/marketplace/public/dream/ifiprojects/y7l8wi9y-98kg-49nb-btv0-l2385w5g9d35/projects - 45

https://public-api.dream.gov.ua/marketplace/public/dream/ifiprojects/l1x0agg9-zi1n-43s3-92t9-w41940t6kjk8/projects - 77

За ще однією у нас є заявки, але немає підтриманих проєктів 

https://public-api.dream.gov.ua/marketplace/public/dream/ifiprojects/0xt0eo6h-172r-43s2-8241-63880248r5ri/projects - 0

Але ця програма все одно доступна для вибору у фільтрі на цій сторінці, і якщо її вибрати у таблиці будуть відображатися проєкти.

![Image](https://github.com/user-attachments/assets/3ccd7b1a-2b24-4006-a12e-7ede3e0ea966)

Якщо завантажити таблицю, то там буде 245 проєктів. Очевидно, що це саме ті проєкти, заявки від котрих були подані на фінансування

![Image](https://github.com/user-attachments/assets/63b95117-3ba5-4dd7-9af6-4ded438f3a32)

Ця поведінка не є коректною, і її потрібно виправити.

Очікувана поведінка для цієї сторінки:

- На панелі фільтрів відображаються тільки ті фінпрограми, за якими є підтримані проєкти
- У таблиці відображають лише проєкти, підтримані у рамках фінпрограми

**Comment by ndrhzn** [comment]
#154 #228

**Comment by andrzejbeletsky** [comment]
виправлено
take a look

**Comment by andrzejbeletsky** [comment]
на проді

**Comment by ndrhzn** [comment]
Тут звернув увагу на пару проблем з експортом даних до таблиці @andrzejbeletsky 

- Якщо завантажити **всю таблицю**, то у ній буде **475 рядків** (має бути 176)
- Якщо завантажити таблицю для програми, у котрій 57 проєктів (_Державна субвенція на облаштування безпечних умов у закладах загальної середньої освіти_), то у цій таблиці буде 127 рядків
- Якщо завантажити таблицю для програми, у котрій 77 проєктів, то у цій таблиці буде 77 рядків
- Якщо завантажити таблицю для програми, у котрій 42 проєкти, то у цій таблиці буде 42 рядки

Ось ті 127 проєктів, котрі експортуються для програми _Державна субвенція на облаштування безпечних умов у закладах загальної середньої освіти_, це очевидно проєкти, котрі були подані (легко перевіряється за допомогою сторінки "Фінансові програми, заявки"), але з них лише 57 були відібрані

**Comment by andrzejbeletsky** [comment]
знайшов баг
виправив
