### ISSUE TITLE
Data: Прибрати проєкти, де ініціатором є "Проєктний офіс"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#237]
Наразі у нас у переліку проєктів є один, де ініціатором є "Проєктний офіс". Ймовірно на рівні моделі даних потрібно зробити префільтр, аби такі проєкти не потрапляли до переліку проєктів і не враховувались ніде під час обчислення ключових статистик, і щоби сам Проєктний офіс не фігурував у переліку організацій.

![Image](https://github.com/user-attachments/assets/14d0c4a1-f0ed-44ff-9ebc-3293289bf75b)

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Дякую, готово до релізу на прод
