### ISSUE TITLE
Загальне: Відображення / форматування чисел

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#24]
Є запит щодо відображення / форматування чисел на картках та графіках. Проблема, як її оригінально сформулювали в проєктному офісі, звучить таким чином

> З нюансів, які трохи турбують - це відображення сум ([скрін](https://drive.google.com/file/d/1dUTe-39mWNsR21BgZ8y0a7QPH_xY8I1i/view)) трохи збиває з пантелику, це 56 млн чи 56 млрд?) Можливо не всім буде зрозуміло.

Уточнення щодо бажаного формату відображення чисел

> Є пропозиція зробити як в ВІ прозорро:
> Якщо сума млрд, то так і виводити - [скрін 1](https://drive.google.com/file/d/1dYG-bgz8zzlK06gXi-NdgbKrKARYiDhk/view); [скрін 2](https://drive.google.com/file/d/1S8KSr1GC79rd6a__PfGlngH9lOxto2n5/view)
> Якщо сума млн, то так і виводити - [скрін 3](https://drive.google.com/file/d/1JTDUOzZjUOKk2bJOLeRVqKpwQypl6Ejy/view).
> Після невеликого опитування в офісі, такий варіант здається більш зрозумілим.

Мені здається, тут точно можна покращити користувацький досвід, але важливо подумати, як це зробити охайно, аби не ускладнити користування додатком.

Загальні настанови тут, думаю, полягають в тому, аби числа були зручними для читання (тобто вони не мають бути довгими), аби одиниці вимірювання були зрозумілими (без додаткової ментальної математики), і аби представлення чисел було за можливості консистентним поміж різних елементів на одному аркуші (аби користувачам не потрібно було постійно переключатися між різними варіантіами одиниць вимірювання)

**Comment by andrzejbeletsky** [comment]
Done in KPI's.
Take a look.

**Comment by ndrhzn** [comment]
Бачу зміни в KPI. На цьому етапі хіба що побажання робити пробіл між числом та одиницею виміру

**Comment by ndrhzn** [comment]
Також лишається відкритим питання, як із підписами значень / одиницями виміру працювати на графіках та картах. Поки у мене немає бачення щодо цього, оскільки: 

- одиниця виміру у нас зазначається в заголовку графіку, а не біля кожного окремого значення
- в межах одного графіку / карти цілком можуть бути значення і в млрд, в млн
