### ISSUE TITLE
Bug: Некоректне відображення кількості заявок у таблиці на сторінці "Фінансові програми, заявки"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#244]
На сторінці "Фінансові програми, заявки" у таблиці є підпис "Всього: 370". 370 то є кількість проєктів, а кількість заявок - 505. 

![Image](https://github.com/user-attachments/assets/dab93379-2e84-4baf-8a84-04b27b0698d8)

Некоректно відображається лише цей підпис, сама кількість заявок у таблиці є коректною (перевірено через експорт таблиці)

**Comment by andrzejbeletsky** [comment]
виправив
