### ISSUE TITLE
Data / Filters: Додати фільтр "Код стратегічного рівня" на сторінку "Публічні інвестиційні проєкти"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#245]
У таблиці на сторінці "Публічні інвестиційні проєкти" у нас є стовпчик "Код стратегічного рівня". Він наразі не може функціонувати як фільтр, оскільки один інвестпроєкт може мати декілька кодів, ми даємо ці коди через кому в одній комірці, і це поле у таблиці перестає бути виміром.

![Image](https://github.com/user-attachments/assets/54620a05-c92e-4f9e-a728-b0ab1c2b7ebb)

Водночас у користувачів є потреба фільтрувати цю таблицю за кодами стратегічного рівня.

Тому нам потрібно додати фільтр "Код стратегічного рівня" до сторінки "Публічні інвестиційні проєкти". Фільтр потрібно додати на бокову панель в самому кінці.

Ми розуміємо, що у нас вже є фільтр "Код стратегічного рівня", котрий застосовується не для інвестпроєктів, а до звичайних проєктів. З Проєктним офісом домовились розрізнити назви цих сутностей згодом.

**Comment by ndrhzn** [comment]
#196

**Comment by andrzejbeletsky** [comment]
take a look
https://bi.qnalytics.com/dream/#/investmentProjects
