### ISSUE TITLE
Bug / Feature: Сторінка "Всі фільтри" не відображається, якщо відкривати її зі сторінки "Публічні інвестиційні проєкти"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#246]
Звернули увагу, що якщо перебувати на сторінці "Публічні інвестиційні проєкти" та клікнути на кнопку "Всі фільтри", то замість набору фільтрів відображатиметься порожній білий екран.

![Image](https://github.com/user-attachments/assets/882c2ae2-4991-44f6-9339-2e9c8f1d624c)

Якщо цю операцію повторити у тестовому середовищі, то сторінка "Всі фільтри" відкривається зо всіма наявними фільтрами.

![Image](https://github.com/user-attachments/assets/92b21bd7-5b84-461b-9c2d-66af11906dfe)

Тому тут є декілька питань:

- Чи ми вважаємо поточну поведінку на публічному порталі ("замість набору фільтрів відображатиметься порожній білий екран") коректною? Скажімо, ми можемо припустити, що оскільки фільтри для звичайних проєктів не застосовуються для інвестпроєктів, то немає сенсу показувати ці фільтри користувачам, якщо вони відкривають фільтри зі сторінки інвестпроєктів. В такому випадку ми можемо сказати, що поведінка коректна.
- Якщо ця поведінка коректна, то чи є у нас можливість не просто показувати білий екран, а якийсь підпис, що пояснював би користувачам, чому саме вони не бачать звичайного набору фільтрів?

**Comment by a-radik** [comment]
Сергій помітив цю проблему і виправив її stage.
Але Інвест проєкти не пов'язані з іншими даними, а отже набір фільтрів з інших сторінок не впливатимуть на сторінки інвестпроєктів, тому є такі варіанти:
* відображати на панелі фільтрів повідомлення для користувача
* заповнити сторінку фільтрами, що стосується інвест. проєктів
* щось робити з кнопкою фільрів (наприклад, зробити так, щоб вона не натискалась а кнопка виглядала неактивною)

**Comment by ndrhzn** [comment]
@InnaStets, які наші преференції тут?

**Comment by InnaStets** [comment]
Мені здається, що 2й варіант "заповнити сторінку фільтрами, що стосується інвест. проєктів" найбільш логічний - але, все-одно, хочеться і до 2го варіанту додати на сторінці текст-пояснення, щоб користувач розумів, чому відбувається зміна фільтрів. Наскільки це реально зробити, поєднати 1 і 2 варіанти?

**Comment by ndrhzn** [comment]
Мені видається, що наразі можна релізнути, як є, аби не було просто порожньої сторінки, а згодом ми пропрацюємо це більш детально.

Заповнити сторінку фільтрами, які стосуються публічних інвестиційних проєктів загалом справді видається доречним рішенням, але у нас всі фільтри вже доступні на самій сторінці. Тому користь від того буде не дуже велика. Хіба що ми пропрацюємо додатковий набір фільтрів для публічних інвестиційних проєктів.

**Comment by InnaStets** [comment]
+ давайте виходити в прод так як є, і дійсно, подумаємо про розвиток цієї сторінки в листопадовому релізі)
