### ISSUE TITLE
Data / Filters: Додати інформацію про відбори до сторінок "Публічні інвестиційні проєкти" та "Географія публічних інвестиційних проєктів"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#248]
До сторінки **"Публічні інвестиційні проєкти"** нам потрібно додати 

- Фільтр "Відбір" / Selection
- Стовпчик Відбір" / Selection

Фільтр має розташовуватись у самому кінці панелі фільтрів
Стовпчик має бути першим у таблиці та блоці "Оберіть стовпчики для відображення". За замовчуванням стовпчик має бути прихованим

До сторінки **"Географія публічних інвестиційних проєктів"** нам потрібно додати 

- Фільтр "Відбір" / Selection

Фільтр має розташовуватись у самому кінці панелі фільтрів

**Дані** щодо відборів, до котрих належить певний публічний інвестиційний проєкт, нам потрібно брати із тієї ж таблички, з котрої ми беремо оцінки публічних інвестиційних проєктів.

До таблички додали три стовпчики
- qualification_id - ідентифікатор відбору 
- UA_translation - назва відбору українською мовою
- EN_translation - назва відбору англійською мовою

**Comment by andrzejbeletsky** [comment]
Take a look.
Стосовно розташування колонки в таблиці на сторінці "Публічні інвестиційні проєкти" - зробив його після Коду, бо той завжди відображається і в ньому настроєно підрахування "Всього". Це не критично?
