### ISSUE TITLE
Data: Додати інформацію щодо ПКД на сторінку "Деталі проєктів"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#251]
До таблиці на сторінці "Деталі проєктів" нам потрібно додати нові стовпчики, що стосуються проєктно-кошторисної документації.

ua | en | endpoint | path | notes
-- | -- | -- | -- | --
Кількість обʼєктів інвестицій, що потребують ПКД | Number of investment objects requiring design documents | ideas | cdu_response/approaches/items/additionalClassifications/id де cdu_response/approaches/items/additionalClassifications/scheme = "UA-CPV" | id має починатися з числа 45, що відповідатиме категорії Будівельні роботи та поточний ремонт
Кількість ПКД | Number of design documents | ideas, design-documentation | approaches/items/additionalClassifications/id де approaches/items/additionalClassifications/scheme="UA-SESC"; designDocumentation/code; | Беремо код завдання на проєктування у даних проєкту (має починатися з ZP). Із цим кодом звертаємось до design-documentation endpoint
Кількість затверджених ПКД | Number of approved design documents | design-documentation | designDocumentation/code, milestones/id де milestones/type="approved" |  
Дата затвердження ПКД | Date of design documents approval | design-documentation | milestones/dateMet де milestones/type="approved" | В одному проєкті у нас може бути декілька дат, ми даємо їх через кому в одній комірці

Загальна логіка така:

- **Встановити, скільки обʼєктів інвестицій у проєктів потребують ПКД**. В проєкті може бути декілька обʼєктів інвестицій (items). Не всіх з них можуть потребувати проєктно-кошторисної документації, а лише ті, що мають стосунок до будівництва. Отже, спершу нам потрібно зрозуміти, скільки обʼєктів інвестицій у проєкті в принципі можуть потребувати ПКД. Ми робимо це за допомогою додаткових класифікацій (additionalClassifications) обʼєктів інвестицій. Нам потрібно знайти всі обʼєкти інвестицій, котрі мають схему класифікації "UA-CPV", та коди котрих починаються з 45. 
- **Встановити, скільки обʼєктів інвестицій вже мають ПКД**. Далі нам потрібно зрозуміти, які з цих обʼєктів інвестицій, що потребують ПКД, вже мають ПКД. Для цього ми спершу встановлюємо, чи має обʼєкт інвестицій завдання на проєктування. Якщо має, тоді ми з кодом завдання на проєктування звертаємось до ендпойнту design-documentation. Якщо ми можемо отримати відповідь за цим запитом, і у відповіді знаходиться код ПКД, тоді ми можемо стверджувати, що обʼєкт інвестицій має ПКД.
- **Встановити, скільки ПКД вже було затверджено**. Для тих випадків, коли обʼєкт інвестицій вже має ПКД, ми можемо перевірити, чи це ПКД вже було затверджено. Для цього ми перевіряємо наявність певної ключової дати (milestones), що вказує на затвердження ПКД (type="approve")
- **Встановити дату затвердження ПКД**. Якщо ПКД було затверджено, ми також можемо встановити, коли саме воно було затверджено, перевіривши дату (milestones/dateMet) 

NB: У нас можлива сиутація, коли один обʼєкт інвестицій має декілька завдань на проєктування. 

Наприклад, у проєкті [y749d008-9650-47c9-aw7f-p5883h8m0eoh](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/y749d008-9650-47c9-aw7f-p5883h8m0eoh) в один обʼєкт інвестицій вписали 14 будинків, і відповідно цей обʼєкт має 14 завдань на проєктування. З погляду статистики у нас це виглядатиме так

- Кількість обʼєктів інвестицій, що потребують ПКД: 1
- Кількість ПКД: 14

З точки зору моделювання даних, більш коректно було б завести кожен будинок окремим обʼєктом інвестицій, і під кожен будинок підвʼязати те завдання на проєктування, котре стосується саме цього будинку.

**Comment by ndrhzn** [comment]
#10 #250

**Comment by andrzejbeletsky** [comment]
taek a look.

Щодо наведеного прикладу з проєктом y749d008-9650-47c9-aw7f-p5883h8m0eoh в design-documentation відсутні записи, тому маємо 
Кількість ПКД: 0

**Comment by ndrhzn** [comment]
@andrzejbeletsky, дякую!

У нас тут можлива ситуація, коли в одному стовпчику вживаються два різні шрифти. Очевидно, це відбувається через те, що частина значень (якщо у комірці є лише один запис) інтерпретується як число, а частина (якщо у комірці є декілька записів через кому - як текст). Чи ми можемо тут примусово для стовпчика "Дата затвердження ПКД" вживається лише один шрифт?

![image](https://github.com/user-attachments/assets/d798e3d0-fb58-4d92-a81d-14db1a8efdf6)

**Comment by andrzejbeletsky** [comment]
Зробив однакові, але це шрифт "тексту" в темі. Він відрізняється від тексту "чисел". Це не критично?

**Comment by ndrhzn** [comment]
Задокументую тут спостереження щодо даних в АРІ, котрі потенційно можуть впливати на наш підрахунок

Наразі для обчислення показника "Кількість обʼєктів інвестицій, що потребують ПКД" ми беремо обʼєкти інвестицій, у котрих є додаткова класифікація зі схемою UA-CPV, та код класифікації котрих починається з 45.

Виглядає так, що користувачі можуть привʼязувати завдання на проєктування до обʼєктів інвестицій, котрі не класифіковані, як такі, що стосуються будівництва.

Скажімо, у [цьому проєкті](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/kv9cmgks-rc80-4u28-826y-e0m6u4eqr0yu) ми маємо UA-CPV 85111200-2 - Medical hospital services, але при цьому тут також є завдання на проєктування

```
{
  "additionalClassifications": [
    {
      "id": "85111200-2",
      "scheme": "UA-CPV"
    },
    {
      "id": "1264",
      "scheme": "UA-DKBS"
    },
    {
      "id": "3142",
      "scheme": "UA-ECBE"
    },
    {
      "id": "ZP01:5428-0785-9134-5910",
      "scheme": "UA-SESC"
    }
  ]
}
```
Також можливий ще один клас випадків, коли UA-CPV класифікація відсутня в принципі, але завдання на проєктування є ([приклад проєкту](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/1366bko0-fg7j-4ei5-8rx0-0784h1ad91da))

```
{
  "additionalClassifications": [
    {
      "id": "3132",
      "scheme": "UA-ECBE"
    },
    {
      "id": "ZP01:4750-3887-9881-7576",
      "scheme": "UA-SESC"
    }
  ]
}
```
Поки рішення щодо того, як із цим працювати, немає. Можливий варіант - не обчислювати для таких випадків показник "Кількість обʼєктів інвестицій, що потребують ПКД", але всі інші показники обчислювати.

**Comment by ndrhzn** [comment]
Також тут варто зауважити, що коли для фільтру "Наявність завдання на проєктування" ми не застосовуємо фільтр за UA-CPV, тому цей фільтр та всі наступні (Наявність ПКД, Наявність завтердженого ПКД, експертизи, дозволу на будівництво), не залежать від класифікації обʼєкта інвестицій за UA-CPV
