### ISSUE TITLE
Bug: Некоректний експорт даних з таблиці на сторінці "Публічні інвестиційні проєкти"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#253]
Якщо експортувати дані до XLSX з таблиці на сторінці "Публічні інвестиційні проєкти", то 

- **Посилання у експортованій таблиці ведуть на внутрішню систему (my.dream.gov.ua), а не публічний портал (dream.gov.ua)**. При цьому посилання з самої таблиці в BI ведуть на публічний портал. Тобто проблема виникає на етапі експорту до XLSX. 

![Image](https://github.com/user-attachments/assets/6c9078b6-a6ac-450d-8d2a-33da82dc60ef)

Для контексту - спершу ми справді давали в таблиці посилання на внутрішній портал. Це мало сенс, коли сторінок інвестпроєктів на публічному порталі ще не було, і коли сторінка інвестпроєктів в BI була закритою для публіки. Коли зʼявилися сторінки інвестпроєктів на порталі, ми змінили логіки в BI, але в експорті, схоже, лишилась стара логіка

- Для частини проєктів посилань немає в принципі. Можливо це виправиться разом з виправленням першої проблеми. Але як ні, то треба буде пропрацювати окремо.

![Image](https://github.com/user-attachments/assets/a82ef3c9-fbd1-46df-a483-5db2f128046d)

**Comment by ndrhzn** [comment]
#196 

Коректний формат посилання описаний [ось тут](https://github.com/open-contracting/bi.dream.gov.ua/issues/196#issuecomment-2360737330)

**Comment by andrzejbeletsky** [comment]
Виправив посилання.
