### ISSUE TITLE
Data: Не враховувати для показників "Витрачено" дані скасованих контрактів

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#255]
У нас наразі можлива ситуація, коли на сторінці "Деталі фінансових програм" для показника "Витрачено" використовуються дані контрактів, котрі вже були скасовані.

Зауважили це на прикладі проєкту [kv9cmgks-rc80-4u28-826y-e0m6u4eqr0yu](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/kv9cmgks-rc80-4u28-826y-e0m6u4eqr0yu).

Тут у нас є дві контрактні процедури, але одна з них скасована. Втім, у таблиці "Деталі фінансових програм" ми цього не враховуємо, і тому сума "Витрачено. Місцевий бюджет" є некоректною

 ![Image](https://github.com/user-attachments/assets/ed1f7cb6-06e0-4e72-b140-0653af54c378)

Цікаво, що на сторінці "Деталі проєктів" ми цієї проблеми не маємо, оскільки раніше ми вже домовились [не враховувати контрактні процедури зі статусом cancelled для показників "Кількість укладених контрактів" та "Сума укладених контрактів" у таблиці "Деталі проєктів"](https://github.com/open-contracting/bi.dream.gov.ua/issues/181) #181

![Image](https://github.com/user-attachments/assets/addc7a84-9fa1-4fe0-a593-f02e0f9d5168)

У цьому випадку ми враховуємо лише одну контрактну процедуру.

Отже, що потрібно зробити:

- На сторінці "Деталі фінансових програм" для показників "Витрачено. Державний бюджет", "Витрачено. Місцевий бюджет" та "Витрачено. Інші джерела" не враховувати дані контрактних процедур зі статусом cancelled.

**Comment by andrzejbeletsky** [comment]
зроблено у рамках https://github.com/open-contracting/bi.dream.gov.ua/issues/256#issue-2644459861

**Comment by andrzejbeletsky** [comment]
так, знайшов баг - виправив.

take a look

**Comment by ndrhzn** [comment]
Дякую, можна на прод

**Comment by andrzejbeletsky** [comment]
на проді
