### ISSUE TITLE
Data: Вилучити з підрахунку дані щодо фінансування зі статусом cancelled

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#256]
У нас на рівні даних проєктів зʼявився новий статус для фінансування - cancelled. Таких випадків поки не дуже багато, але винятково тому, що скасування джерела фінансування це новий бізнес-процес у системі. Найближчим часом їх більшатиме, бо користувачі отримали інструмент для виправлення неправильно внесених даних.

Статус у нас міститься у елементі `cdu_response/approaches/budget/finance/status`

Приклад скасованого джерела фінансування, проєкт [974j5kn1-162j-46p3-b72s-bq6a8978ycpj](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/974j5kn1-162j-46p3-b72s-bq6a8978ycpj). 

```
  {
    "id": "0c2a378f-39fe-4f32-87ab-e6f6ea1fda34",
    "value": {
      "amount": 434689.12,
      "currency": "UAH"
    },
    "period": {
      "endDate": "2024-09-26",
      "startDate": "2024-09-26"
    },
    "status": "cancelled",
    "measures": {
      "fiscalYear": 2024,
      "budgetBreakdownId": "20875c27-19b2-4c56-8a0d-375b8df1f6d5"
    },
    "legalBasis": "https://nedrygaylivska-gromada.gov.ua/docs/1663555/",
    "financeType": "stateFunds",
    "justification": "https://zakon.rada.gov.ua/laws/show/954-2024-%D0%BF#Text",
    "classification": {
      "localBudgetCode": "1850600000",
      "localBudgetProgramKPK": "1021",
      "localBudgetProgramKFKId": "0921",
      "localBudgetProgramKFKName": "Надання загальної середньої освіти закладами загальної середньої освіти за рахунок коштів місцевого бюджету"
    },
    "financingParty": {
      "id": "UA59060090020070314"
    },
    "financeCategory": "localBudget",
    "cancellationReason": "не вірно вказано бюджет"
  }
```
Нам потрібно:

- Перестати враховувати скасовані джерела фінансування для розрахунку показника "Наявне фінансування" (і, відповідно, "Профінансованість", та інших похідних) на всіх аркушах, і показників "Заплановано" на сторінці "Деталі фінансових програм"
- Перестати враховувати показники "Надійшло" та "Витрачено", якщо вони повʼязані зі скасованим джерелом фінансування.

У нас надходження та витрати коштів привʼязані до конкретних джерел фінансування. Отже, якщо джерело фінансування було скасоване, ми маємо також перестати враховувати і всі надходження та витрати коштів, повʼязані з цим джерелом.

Як надходження повʼязані з джерелом фінансування описано у #163, а як витрати повʼязані з джерелом фінансування описано у  #178. 

Перелік проєктів, у котрих вже зʼявилися нові статуси, і на котрих можна буде перевірити розрахунки

33wgee50-eh33-4mn4-brlg-a3j1s16b26d1
7241smf0-6v0e-4f16-87fu-10o70x4k51x5
79eb5m7h-1m08-4a50-bshz-b039s14o68v7
974j5kn1-162j-46p3-b72s-bq6a8978ycpj
z3t96622-33i5-4122-97u6-266yd0nw237d

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by InnaStets** [comment]
@andrzejbeletsky підкажіть, будь ласка, коли ви зможете реалізувати цю задачу? Завтра презентуємось на Саміті, то цікавить чи можемо завтра вже на ці правки розраховувати?

**Comment by andrzejbeletsky** [comment]
Так, маю надію сьогодні буде.

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by andrzejbeletsky** [comment]
на проді
