### ISSUE TITLE
Bug / Data: Різна кількість контрактних процедур в АРІ та у модулі аналітики

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#257]
Звернув увагу, що у проєкті [100124-77ABDB90](https://dream.gov.ua/ua/project/DREAM-UA-100124-77ABDB90/profile) / [e1k8cgo2-7yn4-47we-ab3j-b3565vo1kbql](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/e1k8cgo2-7yn4-47we-ab3j-b3565vo1kbql) ми наразі маємо різну кількість контрактних процедур в АРІ та в BI

![Image](https://github.com/user-attachments/assets/20ecdc74-5d92-4024-b788-445b163c92ae)

В API ми маємо сім елементів. На порталі теж сім контрактних процедур.

![Image](https://github.com/user-attachments/assets/b002a8ce-4fd0-48d4-a477-037449e0a7b4)

Не дуже зрозуміло в такому разі, звідки береться 14 в модулі аналітики.

Наразі проблема ідентифікована на одному проєктів, однак варто буде перевірити, чи вона також заторкає інші проєкти.

**Comment by andrzejbeletsky** [comment]
Виправив баг.
Він з'явився після видалення проектів, зв'язаних з "ПРОЕКТНИЙ ОФІС DREAM".
