### ISSUE TITLE
Data: Вилучити з підрахунку обʼєкти інвестицій зі статусами  cancelled і unsuccessful

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#258]
Обʼєкти інвестицій (items) у складі технічного рішення (approaches) проєкту в нас теж мають статуси. Наразі для розрахунку всіх показників, що стосуються ПКД, ми не враховуємо статус обʼєкта інвестицій, а мали б.

Статус знаходиться в елементі `cdu_response/approaches/items/status`.

Значення, які може містити цей елемент:  active, complete, cancelled, unsuccessful.

Нам потрібно вилучити з підрахунку статуси cancelled та unsuccessful.

Це заторкає всі показники, що стосуються ПКД: всі фільтри, додані у  #250, та всі стовпчики, додані у #251

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Дякую, можна на прод

**Comment by a-radik** [comment]
released
