### ISSUE TITLE
Feature: Додати авторизацію для можливості збереження закладок / налаштувань вибірки

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#259]
Один із повторюваних запитів, що ми отримуємо, стосується можливості збереження налаштування вибірки. Користувачі налаштовують фільтри для своїх потреб, і хочуть зберегти ці налаштування, аби не повторювати операції з налаштування фільтрів щоразу.

Оскільки наша платформа не підтримує передачу параметрів з фільтрів у посилання, ми не можемо реалізувати сценарій збереження налаштування вибірки без імплементації авторизації / створення кабінетів користувачів.

В якості прикладу можна взяти BI Prozorro Sale

![Image](https://github.com/user-attachments/assets/e6160fe4-6b1b-4b81-b363-b84a50757187)

Тут є кнопка "Увійти" у правому верхньому куточку.

За кліком на цю кнопку користувачам пропонується авторизуватися. Наразі авторизація можлива лише за допомогою Google аккаунту.

![Image](https://github.com/user-attachments/assets/8b84ea84-ee7b-40c3-8afc-3d83f79566ac)

![Image](https://github.com/user-attachments/assets/ddf7b435-5e76-4e4a-a7c9-edf45b03b533)

Після авторизації у правому верхньому куточку зʼявиться панель закладок. Будь-які налаштування фільтрів можна зберегти за кліком на кнопку Create bookmark.

![Image](https://github.com/user-attachments/assets/cb802096-2267-4caa-827f-6e393e8c2ce8).

Наразі нам потрібно визначити, **в який спосіб користувачі мають авторизуватися?** У наведеному прикладі авторизація реалізована через Google аккаунт. 

Видається, що це хороша опція, однак не всі наші користувачі можуть мати Google аккаунт. Тому в ідеалі нам потрібно мати додаткові опції - на зразок створення власного аккаунту (логіну та паролю). З наших попередніх консультацій, це є валідна опція, однак вона вимагатиме додаткової розробки функціоналу для створення логіну-паролю, а також скидання паролю (веб-форми та бекенд для цього).

Ми також можемо додавати функціонал поступово - наприклад, у першій ітерації реалізувати авторизацію через Google, а потім додати інші способи.

**Comment by ndrhzn** [comment]
@InnaStets описав контекст щодо технічної імплементації у цій задачі. Наразі нам потрібно самим визначитися, яким шляхом ми хочемо йти.

Моя пропозиція полягає в тому, аби у першій ітерації зробити авторизацію через Google, а у наступній - додати можливість створення логіну-паролю та скидання паролю. Що думаєш?

**Comment by a-radik** [comment]
На стейджі можемо викатити вам версію для роботи десь +/- в середині наступного тижня. В мешапі там до 1 дня роботи

Сам модуль автентифікації зроблений у вигляді Docker контейнеру, попрошу нашу технічну команду його розгорнути, і якщо щодо роботи з автентифікацією прийняли, попрошу проговорити розгортання цього всього на проді з Джеймсом.

Поки чекатиму вашого підтвердження.

**Comment by ndrhzn** [comment]
@a-radik, дякую! Звучить добре, давайте робити

**Comment by a-radik** [comment]
Мешап наступного тижня почнемо, а з Джеймсом зараз почнемо пропрацьовувати

**Comment by a-radik** [comment]
Зробили на стейджі аутентифікацію користувачів і можливість зберігати закладки.
В єлементах управління закладками, мітки зараз беруться з інтерфейсу Qlik і відповідають мові браузера користувача. В мене, наприклад, мова браузера англійська, тому попри те, що інтерфейс додатка укарїнською, в цьому меню все відображається англійською. Цю поведінку можна змінити за необхідності

![Image](https://github.com/user-attachments/assets/69ee17c1-ce3e-47e4-8385-ea87e4d13af6)

Крім того відображається закладка start - це вибірки за замовчуванням, які застосовуються при відкритті додатка, її можна перейменувати або приховати

**Comment by a-radik** [comment]
> Я змінив мову браузера на українську, і перевірив, що мій браузер надсилає у headers Accept Language:uk, однак елементи інтерфейсу все одно англійською мовою.

Це так і є, нажаль. Вендор не підтримує української, є тільки російська, яку ми замінили українською, тому бажаного результату ви би досягли встановивши російську в вашому браузері. Якщо мова не підтримується, то відображаеться за замочуванням англійська.

Задача зрозуміла, пропрацюємо з нашим R&D як її найкраще реалізувати.

> У інтерфейсі наразі використовуються кольори, котрі не є властивими для додатку DREAM BI - у деяких випадках це зелений, у деяких випадках це червоний. Варто змінити кольорову гаму, аби вона узгоджувалась із рештою додатку.

Нам самим попрацювати над кольорами згідно теми і запропонувати вам варыант, правильно розумію?

**Comment by a-radik** [comment]
> Також можна подумати про заміну іконки на більш зрозумілу (скажімо, для "поширення" у інтерфейсах зараз здебільшого вживається щось на зразок цього [share](https://fontawesome.com/icons/share?f=classic&s=solid), [share-nodes](https://fontawesome.com/icons/share-nodes?f=classic&s=solid))

Іконка share-nodes  вже використовується, коли закладка опублікована і доступна для поширення. Іконка яку ви хочете змінити це не іконка поширення, це використовується для публікації закладки - зробити її доступною для всіх користувачів, щоб вони могли її використати в url. Після публікації є можливість прибрати з опублікованих. Для цього використовується аналогічний значок зі зворотньою стрілкою. Після публікації поруч із закладкою з'являється значок що показує які закладки опубліковані а які ні. Якщо змінювати то змінювати всі, або змінювати послідовність дій.
![Image](https://github.com/user-attachments/assets/b5bb5fd3-47be-4274-82b6-b4eb6e1ebbdd)

**Comment by ndrhzn** [comment]
@a-radik гаразд, давайте поки лишимо іконки, як є. Якщо з нашого боку зʼявиться бачення щодо змін всього набору іконок або ж послідовності дій, опишемо їх окремо

**Comment by karandinserhii** [comment]
@ndrhzn Доброго дня, на стейджі додали переклад інтерфейсу закладок, вже доступний до тестування. 
Англомовні мітки взяті з офіційних словників qlik'a, україномовні - запропоновані нами. Обидві мови підтягуються з файлу перекладів, за необхідності ви їх можете модифікувати в гугл докє "DREAM Translations", вкладка "translations", строки 524-542 
![image](https://github.com/user-attachments/assets/6ab53cba-d9e0-4fbc-a077-e74c64b82f43)

**Comment by ndrhzn** [comment]
Дякую! Я тільки замінив у таблиці "Букмарки відсутні" на "Закладки відсутні", все інше ніби добре

**Comment by ndrhzn** [comment]
Звернув увагу, що чомусь за кліком на "Букмарки відсутні" зʼявляється синій колір. Тут ймовірно найперше питання полягає в тому, навіщо нам потрібно щось змінювати за кліком на "Букмарки відсутні", про що це має сигналізувати користувачам.

![Image](https://github.com/user-attachments/assets/c1971801-2f1b-4b23-a4ab-117dc8788a94)

В ідеалі цю інтеракцію слід прибрати загалом. Якщо неможливо її прибрати, або це вимагає додаткових втручань, то принаймні прибрати правило, за яким змінюється колір на синій.

**Comment by ndrhzn** [comment]
Аналогічно за кліком на "Створити закладку" кнопка змінює колір на синій 

![image](https://github.com/user-attachments/assets/ed939c27-afde-45f5-ab80-5fa01585ced0)
