### ISSUE TITLE
Bug: Посилання на сторінку проєкту

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#26]
У таблиці "Деталі проєктів" у нас код проєкту є посиланням, котре веде на сторінку проєкту на основному порталі. Але наразі це посилання веде на англомовну сторінку проєкту. Ця ситуація виникла через те, що ми взяли за основу посилання саме на англомовну сторінку

Паттерн для англомовної сторінки https://dream.gov.ua/project/DREAM-UA-{code}/profile

Паттерн для україномовної сторінки https://dream.gov.ua/ua/project/DREAM-UA-{code}/profile 

Якщо ми можемо зрозбити так, аби посилання конструювалося залежно від того, яка мова інтерфейсу обрана, то варто зробити так, аби з англомовної таблиці вело на англомовні сторінки, а з україномовної на україномовні.

**Comment by ndrhzn** [comment]
Чи ми можемо слово "Посилання" / "Link" замінити, наприклад, знак 🔗 ([source](https://emojipedia.org/link))? Видається, що у таблицях цей стовпчик подекуди займає занадто багато місця. @andrzejbeletsky

**Comment by andrzejbeletsky** [comment]
Take a look
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/b7011c65-e80e-4ce8-850a-d567bafcdc80/state/analysis

**Comment by ndrhzn** [comment]
Зафіксували наступне

- Відображати посилання на сторінку проєкту на коді проєкту
- Посилання для експорту зберігати у прихованому стовпчику (котрий не відображається у застосунку, але стає доступним під час експорту)
