### ISSUE TITLE
UI/UX: Змінити розташування блоку "Оберіть стовпчики для відображення" на сторінках "Публічні інвестиційні проєкти" та "Фінансові програми, заявки"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#260]
На сторінках "Публічні інвестиційні проєкти" та "Фінансові програми, заявки" у нас є таблиці та, відповідно, блоки "Оберіть стовпчики для відображення". Однак візуально блок "Оберіть стовпчики для відображення" знаходиться досить далеко від таблиці. 

![Image](https://github.com/user-attachments/assets/c670e6ec-1d0a-48cf-b58a-26936941eb83)

![Image](https://github.com/user-attachments/assets/517f5c85-33e7-42d2-8b7c-1433e0d80456)

Є сенс для цих двох сторінок розташувати блоку "Оберіть стовпчики для відображення" на одному рівні з таблицею.

Таким чином у нас спершу буде блок фільтрів, а потім блок "Оберіть стовпчики для відображення".

**Comment by ndrhzn** [comment]
@a-radik дякую, що звернули увагу на цю деталь! Не дуже розумію, чи ця зміна має відбутися в нативному додатку, чи в мешапі. Чи в обох середовищах. Тому прошу підказати, на кого її розписати.

**Comment by andrzejbeletsky** [comment]
@a-radik Зробив у нативному.

**Comment by ndrhzn** [comment]
У нас наразі виходить ось таке розташування елементів - спершу блок "Обрати всі" / "Скинути всі", а вже потім текст "Оберіть стовпчики для відображення". 

![Image](https://github.com/user-attachments/assets/da386a48-b336-428d-a8f0-9cf4524a66be)

З точки зору логіки викладу, текст "Оберіть стовпчики для відображення" мав би йти першим. Блок "Обрати всі" / "Скинути всі" конкретизує цей загальний сценарій, тому він не має передувати цьому сценарію.

На обох сторінках варто **поставити блок Обрати всі" / "Скинути всі" після тексту "Оберіть стовпчики для відображення"**.

**Comment by a-radik** [comment]
Умисно робили так,щоб більше місця лишилось для відображення і вибору совбчиків, бо самі таблиці по висоті не великі а колонок для вибору багато.
Ми підбирали розмір об'єкту для вибору колонок під висоту таблиці, тому кнопки закинули над нею. Якщо треба розмістити якось по-іншому, скажіть як, зробимо

**Comment by ndrhzn** [comment]
@a-radik, дякую! Принагідно задокументував, що ми хочемо трохи змінити підхід до роботи з висотою таблиць (дивіться #267 ). Це дозволить нам трохи збільшити таблиці по висоті, і це також має нам дозволити змінити розташування блоку "Обрати всі" / "Скинути всі".

**Comment by ndrhzn** [comment]
Трохи не порозумілися тут. 

> На обох сторінках варто поставити блок Обрати всі" / "Скинути всі" після тексту "Оберіть стовпчики для відображення".

Наразі реалізовано таким чином, що блок "Обрати всі" / "Скинути всі" йде не одразу після тексту "Оберіть стовпчики для відображення", а вже після самого переліку стовпчиків.

![Image](https://github.com/user-attachments/assets/3b401bb6-7f46-40ea-a01f-72c6a1e4182a)

Уточню потрібне розташування елементів

1. Текст "Оберіть стовпчики для відображення"
2. Блок "Обрати всі" / "Скинути всі"
3. Перелік стовпчиків для вибору

@karandinserhii

**Comment by ndrhzn** [comment]
Хоча я бачу, що це створить розбіжності у розташуванні елементів з іншими сторінками. В ідеалі якщо застосовувати ці зміни, то застосовувати їх всюди, аби користувачам не доводилось перемикатися між різними правилами розташування елементів на різних сторінках.

**Comment by andrzejbeletsky** [comment]
take a look
