### ISSUE TITLE
UI/UX: Змінити ширину таблиці на вкладці "Проєкт стосується всієї країни" на сторінці "Географія публічних інвестиційних проєктів"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#261]
Тут у нас суто косметичний запит - змінити ширину таблиці

Наразі виглядає ось так

![Image](https://github.com/user-attachments/assets/9b33a2e1-0ede-45f6-8706-8332b3de2b37)

Чи ми можемо зробити, аби виглядало десь так?

![Image](https://github.com/user-attachments/assets/26ab0143-9fcc-4c9b-bc76-1d686447fdda)

**Comment by ndrhzn** [comment]
#215 #218

**Comment by ndrhzn** [comment]
@a-radik щодо цієї задачі теж не маю чіткого розуміння, чи вона стосується нативного додатку, чи мешапу

**Comment by ndrhzn** [comment]
@andrzejbeletsky дякую за контекст! Якщо робити це окремою таблицею, чи є ще якісь нюанси, які треба розуміти перед тим, як ухвалювати рішення? Умовно, чи не буде тут якихось performance issues?

**Comment by andrzejbeletsky** [comment]
Не бачу ускладнень.
@karandinserhii Я так розумію, в мешапі зміниться id на нового обжекта і цього достатньо?
