### ISSUE TITLE
Data: Додати звітність за мета-проєктами до сторінки "Деталі фінансових програм"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#262]
## Проблема 

У нас в даних є так звані "мета-проєкти". Це проєкти, які акумулюють у собі фінансування, але не всі кошти, виділені цим проєктам, використовуються цими проєктами.

Умовно, отримувачем коштів може бути один мета-проєкт, але фактично частина цих коштів буде витрачена іншими - повʼязаними проєктами. 

З точки зору даних це для нас означає, що дані про фінансування записані в одному проєкті (мета-проєкті), а дані про фактичне надходження та використання коштів будуть записані у проєктах, повʼязаних з цим мета-проєктом. 

В контексті фінансової звітності (сторінки "Деталі фінансових програм") це представляє для нас проблему. Наразі ми відстежуємо надходження та використання коштів лише на рівні одного проєкту, і фактично оминаємо увагою надходження та використання коштів проєктами, котрі повʼязані з цим мета-проєктом. Наша фінансова звітність не враховує частину коштів.

## Рішення

Отже, нам потрібно 

- Ідентифікувати мета-проєкти
- Звʼязати мета-проєкти зі звичайними проєктами, котрі отримали фінансування від мета-проєкту
- У кожному повʼязаному проєкті встановити суми надходження та витрат коштів (розподілених від мета-проєкту)
- Враховувати ці суми для фінансової звітності на сторінці "Деталі фінансових програм"

### **Ідентифікувати мета-проєкти в рамках фінпрограми**

Мета-проєкти можна визначити за наявністю елемента `cdu_response/approaches/items/relatedItem`. Тобто, якщо такий елемент наявний у проєкті, то ми знаємо, що це мета-проєкт.

Приклад з проєкту [94bjt485-kmu3-4g1w-90bp-4pl3e126n6gl](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/94bjt485-kmu3-4g1w-90bp-4pl3e126n6gl). 

```
{
  "id": "16df0c05-d246-4206-9bca-a6abb53c3a4f",
  "status": "active",
  "relatedItem": "[/ideas[vfbk7118-u2dk-4vb1-8clm-721dr65r0c66]/approaches[single]/items[29409317-252d-43f2-b865-1caa4a4f3004]](https://public-api.dream.gov.ua/ideas[vfbk7118-u2dk-4vb1-8clm-721dr65r0c66]/approaches[single]/items[29409317-252d-43f2-b865-1caa4a4f3004])"
}
```
Загалом у системі є близько двох десятків мета-проєктів, але оскільки ця задача стосується сторінки "Деталі фінансових програм", то нас цікавлять лише ті мета-проєкти, котрі мають стосунок до фінансової програми.

### **Визначити, з якими проєктами та обʼєктами інвестицій повʼязані ідентифіковані мета-проєкти**

У елементі `cdu_response/approaches/items/relatedItem` міститься інформація про те, із яким проєктом, технічним рішенням, та обʼєктом інвестицій повʼязний наш мета-проєкт.

У наведеному вище прикладі значення елемента relatedItem - `"[/ideas[vfbk7118-u2dk-4vb1-8clm-721dr65r0c66]/approaches[single]/items[29409317-252d-43f2-b865-1caa4a4f3004]](https://public-api.dream.gov.ua/ideas[vfbk7118-u2dk-4vb1-8clm-721dr65r0c66]/approaches[single]/items[29409317-252d-43f2-b865-1caa4a4f3004])"`.

Якщо розібрати цей елемент на компоненти, тоді ми побачимо 

- `ideas[vfbk7118-u2dk-4vb1-8clm-721dr65r0c66]` - ідентифікатор проєкту
- `approaches[single]` - ідентифікатор технічного рішення в рамках цього проєкту
- `items[29409317-252d-43f2-b865-1caa4a4f3004]` - ідентифікатор обʼєкта інвестицій в рамках технічного рішення

У першому прикладі ми бачимо лише один запис із елементом relatedItem, однак на практиці їх може бути декілька. Скажімо, у проєкті [74u01bi6-v7sk-45wk-bp86-hc0q4ioy51f4](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/74u01bi6-v7sk-45wk-bp86-hc0q4ioy51f4) їх три, однак лише два записи з трьох мають `status: "active"`.  #258

```
[
  {
    "id": "632b0a91-71f2-4398-8bdf-4ffd5fcfc67c",
    "status": "active",
    "relatedItem": "/ideas[u9war41v-2r0q-47lz-bk61-644u433qussh]/approaches[single]/items[a4fd29fb-18fa-4d4e-a47c-00dbc6ca8eb2]"
  },
  {
    "id": "b05c4591-5200-4b17-ba29-1dfff3aaad13",
    "status": "active",
    "relatedItem": "/ideas[368mt0vn-nuk4-4vfm-9530-sktfl835958w]/approaches[single]/items[45701fa4-0bc3-4eac-bd0d-06939869a9a8]"
  },
  {
    "id": "bcae2617-0651-4460-b669-dfbae3918471",
    "status": "cancelled",
    "relatedItem": "/ideas[4r7jle63-747h-40ca-99x4-e854b9q411o6]/approaches[single]/items[6dbebdba-82c0-40aa-9b65-b6dfb4b607fc]"
  }
]
```

### Звернутися до даних повʼязаного проєкту, технічного рішення, обʼєкта інвестицій

Маючи ідентфиікатори повʼязаного проєкту, технічного рішення, та обʼєкта інвестицій, ми можемо знайти потрібні нам елементи в АРІ.

Для нашого першого прикладу relatedItem - `"[/ideas[vfbk7118-u2dk-4vb1-8clm-721dr65r0c66]/approaches[single]/items[29409317-252d-43f2-b865-1caa4a4f3004]](https://public-api.dream.gov.ua/ideas[vfbk7118-u2dk-4vb1-8clm-721dr65r0c66]/approaches[single]/items[29409317-252d-43f2-b865-1caa4a4f3004])"`.

Якщо ми звернемось до проєкту [vfbk7118-u2dk-4vb1-8clm-721dr65r0c66](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/vfbk7118-u2dk-4vb1-8clm-721dr65r0c66), у ньому буде елемент `approaches` з `approaches/id = "single"`. І у цьому елементі є елемент масиву items за items/id = "29409317-252d-43f2-b865-1caa4a4f3004".

```
{
  "approaches": [
    {
      "id": "single",
      "items": [
        {
          "id": "29409317-252d-43f2-b865-1caa4a4f3004",
          "status": "active"
        }
      ]
    }
  ]
}
```

Нас цікавить не сам цей елемент / обʼєкт інвестицій, а те розподілене фінансування та витрачені кошти, повʼязані із цим обʼєктом інвестицій, у термінах сторінки "Деталі фінансових програм" - "Надійшло" та "Витрачено".

Нам потрібно взяти суми "Витрачено" та "Надійшло", асоційовані з цим обʼєктом інвестицій, та додати їх до сум "Витрачено" та "Надійшло" основного проєкту. Таким чином, звітність за проєктом [94bjt485-kmu3-4g1w-90bp-4pl3e126n6gl](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/94bjt485-kmu3-4g1w-90bp-4pl3e126n6gl) у нас включатиме у себе також звітність за повʼязаним проєктом [vfbk7118-u2dk-4vb1-8clm-721dr65r0c66](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/vfbk7118-u2dk-4vb1-8clm-721dr65r0c66).

#### Як фінансування повʼязано з обʼєктом інвестицій

У нас є елемент даних cdu_response/approaches/budget/finance/measures/relatedItem, котрий вказує на те, із яким обʼєктом інвестицій повʼязане певне джерело фінансування.

Приклад з проєкту [vfbk7118-u2dk-4vb1-8clm-721dr65r0c66](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/vfbk7118-u2dk-4vb1-8clm-721dr65r0c66)

```
{
  "budget": {
    "finance": [
      {
        "id": "067959c2-e587-77df-d87c-4c1bdd77a66c",
        "value": {"amount": 3700000, "currency": "UAH"},
        "period": {"endDate": "2024-12-31", "startDate": "2024-01-01"},
        "status": "committed",
        "measures": {
          "fiscalYear": 2024,
          "relatedItem": "29409317-252d-43f2-b865-1caa4a4f3004"
        }
      }
    ]
  }
}
```

Власне надходження коштів ми відтседжуємо за допомогою елементу `cdu_response/approaches/implementation/financialProgress/breakdown`, де `cdu_response/approaches/implementation/financialProgress/breakdown/classifications/budgetFinanceId` вказує на те, з якого джерела надійшли кошти. Цей елемент вже використовується для розрахунку показника "Надійшло", детальна методологія описана в #163

#### Як витрати повʼязані з обʼєктом інвестицій

Витрати ми фіксуємо у елементі `contractingProcesses/summary/contracts/implementations/financialProgress/breakdown`. Тут звʼязка із джерелом фінансування відбувається за допомогою елементів `contractingProcesses/summary/contracts/implementations/financialProgress/breakdown/classifications/contractingFinanceId` та `contractingProcesses/summary/budget/finance/classification/budgetFinanceId`. Обидва елементи вже використовуються для розрахунку показника "Витрачено", детальна методологія описана в #178

**Comment by ndrhzn** [comment]
@andrzejbeletsky чи я правильно розумію, що ви ще не мали часу взятися за цю задачу? Якщо так, чи є розуміння, коли зможете?

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by a-radik** [comment]
> Нам потрібно взяти суми "Витрачено" та "Надійшло", асоційовані з цим обʼєктом інвестицій, та додати їх до сум "Витрачено" та "Надійшло" основного проєкту. Таким чином, звітність за проєктом [94bjt485-kmu3-4g1w-90bp-4pl3e126n6gl](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/94bjt485-kmu3-4g1w-90bp-4pl3e126n6gl) у нас включатиме у себе також звітність за повʼязаним проєктом [vfbk7118-u2dk-4vb1-8clm-721dr65r0c66](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/vfbk7118-u2dk-4vb1-8clm-721dr65r0c66).

Таким чином сума за проєктом vfbk7118-u2dk-4vb1-8clm-721dr65r0c66 буде порахована двічі в тоталах таблиць і показників (хоча тут можга обійти, але будеть різні формули розрахунку показника для KPI), чи саме на такий результат ви очикуєте? Чи треба щоб одна і та сама сума враховувалась тільки один раз при обрахунку загальних сум? (Останній варіант потребуватиме змін в модель)

**Comment by ndrhzn** [comment]
Гм, наразі ми говоримо про два показники - "Надійшло" та "Витрачено". Мені здається, вони не використовуються ніде, окрім таблиці "Деталі фінансових програм", тому ця зміна не мала б спричинити задвоєння показників на інших сторінках - в графіках, таблицях, чи картках.

Втім, якщо ми згодом захочемо використовувати ці показники деінде (рано чи пізно це станеться, бо ми маємо на меті зробити окремий аркуш про виконання проєктів, і там буде про фінансовий прогрес), тоді нам буде потрібно врахувати цей нюанс.

Чи відповідає це на ваше питання наразі, @a-radik?

**Comment by ndrhzn** [comment]
Гм, але ж у нас має бути так, що до таблиці "Деталі фінпрограм" потрапляє умовно лише один проєкт - той, що парасольковий. А ті, до котрих він розподіляє кошти, до цієї таблиці не потрапляють. Тому їхні значення врахуються лише один раз - у складі мета-проєкту.

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Дякую! Розрахунки перевірили, наче все збігається. В принципі можна на прод

**Comment by andrzejbeletsky** [comment]
На проді
