### ISSUE TITLE
Data: Змінити принцип розрахунку показника "Кількість обʼєктів інвестицій, що потребують ПКД" на сторінці "Деталі проєктів"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#266]
У першій ітерації завдання #251 ми визначили наступний принцип розрахунку показника "Кількість обʼєктів інвестицій, що потребують ПКД"

ua | en | endpoint | path | notes
-- | -- | -- | -- | --
Кількість обʼєктів інвестицій, що потребують ПКД | Number of investment objects requiring design documents | ideas | cdu_response/approaches/items/additionalClassifications/id де cdu_response/approaches/items/additionalClassifications/scheme = "UA-CPV" | id має починатися з числа 45, що відповідатиме категорії Будівельні роботи та поточний ремонт

Втім, згодом ми [зʼясували, що користувачі можуть привʼязувати завдання на проєктування до обʼєктів інвестицій, котрі не класифіковані, як такі, що стосуються будівництва](https://github.com/open-contracting/bi.dream.gov.ua/issues/251#issuecomment-2464317909).

Подальше дослідження показало, що на рівні системи можливість додавати завдання на проєктування до обʼєкту інвестицій привʼязана не до класифікації за UA-CPV, а до класифікації за UA-ECBE, а точніше до конкретних кодів у цій класифікації - 3120, 3121, 3122, 3130, 3131, 3132, 3140, 3141, 3142, 3143.

Отже новий принцип розрахунку має спиратися на трохи інше правило.

ua | en | endpoint | path | notes
-- | -- | -- | -- | --
Кількість обʼєктів інвестицій, що потребують ПКД | Number of investment objects requiring design documents | ideas | cdu_response/approaches/items/additionalClassifications/id де cdu_response/approaches/items/additionalClassifications/scheme = "UA-ECBE" | id має бути одним з 3120, 3121, 3122, 3130, 3131, 3132, 3140, 3141, 3142, 3143

**Comment by a-radik** [comment]
Не зрозумів, новий скасовує старий чи маєпрацювати разом зі старим методом?

**Comment by ndrhzn** [comment]
Новий скасовує старий

**Comment by andrzejbeletsky** [comment]
take a look

**Comment by ndrhzn** [comment]
Тут наче все добре, дякую!

Скрипт для перевірки розрахунків

```
SELECT
  main.internal_code AS code,
  COUNT(
    cdu_response_approaches_items_additionalClassifications.id
  ) AS count_of_projects
FROM
  cdu_response_approaches_items
  JOIN cdu_response_approaches_items_additionalClassifications ON cdu_response_approaches_items._link = cdu_response_approaches_items_additionalClassifications._link_cdu_response_approaches_items
  JOIN main ON cdu_response_approaches_items._link_main = main._link
WHERE
  cdu_response_approaches_items.status NOT IN ('cancelled', 'unsuccessful')
  AND cdu_response_approaches_items_additionalClassifications.scheme IS 'UA-ECBE'
  AND cdu_response_approaches_items_additionalClassifications.id IN (
    3120,
    3121,
    3122,
    3130,
    3131,
    3132,
    3140,
    3141,
    3142,
    3143
  )
  AND main.cdu_response_status NOT IN ('cancelled', 'unsuccessful', 'complete')
GROUP BY
  code
ORDER BY
  count_of_projects DESC
```
