### ISSUE TITLE
Bug: На сторінці "Деталі фінансових програм" для розрахунку показника "Сума фінансового запиту" враховуються всі заявки, повʼязані з проєктом, а не лише успішна

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#269]
Звернули увагу, що у нас на сторінці "Деталі фінансових програм" для розрахунку показника "Сума фінансового запиту" можуть враховуватись всі заявки, повʼязані з проєктом, а не лише успішна заявка.

Наразі проблему задокументували на прикладі двох проєктів

[250424-753D758F](https://dream.gov.ua/ua/project/DREAM-UA-250424-753D758F/profile). В проєкті дві заявки. Сума успішної заявки 131 421 679. У нас відображається 262 843 358.

[220424-BDC659DA](https://dream.gov.ua/ua/project/DREAM-UA-220424-BDC659DA/profile). В проєкті три заявки. Сума успішної заявки 76 740 392. У нас відображається 230 221 176.

![Image](https://github.com/user-attachments/assets/bd8b9f6f-a995-4a59-af44-72d28d325b3f)

Видається, що цю  - або ж принаймні подібну - проблему ми вже вирішували у липні разом з релізом сторінки "Деталі фінансових програм" (#154). Тоді її спостерігали [на показнику "Загальна кошторисна вартість"](https://github.com/open-contracting/bi.dream.gov.ua/issues/154#issuecomment-2210707617). 

> Виявили помилку в розрахунках показника "Загальна кошторисна вартість", яка походить з того, що до одного проєкту можуть бути підвʼязані декілька заявок у різних статусах. Зафіксували, що для цього показника нам потрібно брати лише ті заявки, що мають статус active.

Зараз потрібно застосувати цю ж логіку і для показника "Сума фінансового запиту".

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
take a look
"Сума фінансового запиту" рахується тільки для заявок зі статусом active.
