### ISSUE TITLE
Feature: Можливість зберігати візуалізації

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#27]
З Проєктного офісу передали такий запит

> У користувачів ВІ є запит вивантажувати через натискання правою кнопкою миші на карті/графіку/діаграмі в форматі pdf або jpeg елементу, на якому вони це роблять (як в ВІ прозорро). Щоб одразу і гарну картинку

Видається, що додати такий функціонал має бути доволі просто, якщо це входить в базовий інструментарій Qlik.

Але також маю питання - чи можливо не просто зберігати картинку, а ще й додавати туди якісь метадані (умовно, зазначати, звідки походять дані, і станом на яку дату представлені дані)?

**Comment by a-radik** [comment]
Базова функціональність Qlik дозволяє робити експорт в форматах jpeg, png і pdf. В самому простому варіанті можемо зробити експорт в тому розмірі. як об'єкт відображается на екрані користувача (ширина і висота). 

Уточнюючі питання: 
* туди - це на самій картинці виводити текст чи треба доповнювати саме метаданні файлу, що буде скачано чи якись інший варіант? Якщо перше, то це можливо.
* походження даних - це має бути текст типу DREAM Аналітика?

Нижче наведу приклад, як це можна зробити за допомогою foot note в об'єкті. В об'єктів, що розміщено в мешапі footnote відображатись не буде, а при експорті буде динамічно додаватись. Наразі foot note в об'єктів в нас ніде не задіяно. Якщо буде така необхідність (вивести foot note об'єкта) процес експорта треба буде значно усладнити, бо треба одночасно вивести foot note об'єкта і додаткову інформацію про походження і дату.



![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/63779944/3482368d-2635-4104-a09d-902a342abf4b)

**Comment by ndrhzn** [comment]
Добре знати, що це можливо з технічної точки зору. Я проясню у юзерів, наскільки важливо їм мати footnote (з моєї точки зору, це важливо для уникнення неправильної комунікації), і тоді оберемо спосіб імплементації

**Comment by ndrhzn** [comment]
Тут зафіксували рішення використовувати функціонал footnote для відображення метаданих під час збереження картинок. 

Метадані для відображення
- Джерело даних - **DREAM Аналітика**
- Дата - **Дані станом на dd.mm.yyyy**

**Comment by ndrhzn** [comment]
Поточний статус - експорт зображень реалізовано на тестовому сервері. Наразі доступний експорт у png та pdf. Водночас є проблема із визначенням розміру зображення (наразі розмір зображення заданий однаковий для всіх, якщо контент візуалізації не вміщається повністю у цей розмір, на експортованому зображенні відображається scrollbar). Проблема насамперед заторкає візуалізації з великою кількістю категорій (наприклад, ті, де по осі Y іде довжелезний перелік громад або ж ініціаторів).

@a-radik давайте задокументуємо, які у нас є варіанти вирішення цієї проблеми, і спробуємо зрозуміти, який можливий таймлан (чи ми плануємо включати це в найближчий реліз, наприклад).

**Comment by a-radik** [comment]
Бажаний розмір картинки передається в Qlik Engine при виклику методу експорту разом з передачею ідентифікатора об'єкта який треба отримати у вигляді зображення. Способу попросити Engine самотійно визначити висоту/ширину об'єкта не існує, чи принаймні він не описаний в документації вендора. На етапі запиту на отримання зображення об'єкту необхідно визначити висоту (ширину) при якій скролл з'являтись не буде. Гадаю, що це можна зробити, якщо з'ясувати кількість значень розрізу в якому відображається об'єкт и помножити на приблизну висоту необхідно для відображення одного.

**Comment by ndrhzn** [comment]
Зафіксували рішення включити в реліз та збирати зворотній звʼязок. В окремих випадках експорт буде працювати неідеально (якщо всі елементи візуалізації не вміщаються в один екран). Наразі ми залишаємо це на розсуд користувачів, які картинки експортувати, а які ні.

**Comment by ndrhzn** [comment]
На додачу до можливості зберігати окремі зображення також зафіксували потребу зберігати всі елементи модулю в одному зображенні (наприклад, картки, графік та карту) для звітів. Сценарій використання - люди застосовують потрібні для себе фільтри і зберігають зображення (наразі - роблять скріншот) зо всією потрібною інформацією для презентації.
