### ISSUE TITLE
Bug: Некоректна робота фільтру "Період" для показника "Витрачено" на сторінці "Деталі фінансових програм"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#275]
## Проблема

Видається, що якщо обирати останній місяць у фільтрі "Період", тоді показники "Витрачено" у таблиці не змінюються, і лишаються такими, як і без застосування фільтру.

При цьому значення для показників "Надійшло" змінюються та відображають лише надходження у обраному періоді.

**Без застосування фільтру "Період"**

![Image](https://github.com/user-attachments/assets/f251d291-a815-4d91-8e6a-07caef919c00)

**Із застосуванням фільтру "Період", обрано значення "Грудень, 2024"**

![Image](https://github.com/user-attachments/assets/e699b2fc-eeb1-4dd8-aa1e-8faa830d9465)

## Можлива причина

Можливо, у цьому випадку для останнього місяця ще немає записів про витрати, і тому відображається нефільтрований діапазон даних.

Втім, це лише припущення, і причину такої поведінки фільтру ще потрібно встановити.

**Comment by ndrhzn** [comment]
#220 #154

**Comment by andrzejbeletsky** [comment]
Виправлено.
