### ISSUE TITLE
Feature: Візуалізація наявності даних щодо проєктів / наповнення проєктів

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#30]
Для потреб Проєктного офісу (та наших власних - аби розуміти стан наповнення даних) маємо зробити візуалізацію наявності даних щодо проєктів / наповнення проєктів.

Для Проєктного офісу це важливо, бо тоді вони можуть прицільно працювати із громадами над наповненнями проєктів.

> Є запит саме по Проектам - щоб було видно всю інформацію, яка зараз відображається на порталі. Тобто такі розділи як: Назва, Опис, Структура, Джерела фінансування, Технічне рішення, Документи, План ,Галерея.  Це нам допоможе в подальшому аналізувати, як йде наповнення по громадам, ОВА тощо.

Ідея тут достатньо проста - визначити, які секції представляють для нас інтерес, і перевіряти для кожного проєкту, чи наявні дані у цій секції (інакше кажучи, чи ця секція не є порожньою).

Я вже робив подібний аналіз для себе, і це було у вигляді простої таблички, де для кожної визначеної секції міститься запис про доступність даних.

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/3c6b5774-d444-4fff-8a15-b6caa3039d06)

У цьому разі алгоритм був простий - скрипт проходив по кожному проєкту, заглядав у кожну визначену секцію і перевіряв 1) чи цей елемент is not null 2) чи його довжина > 0 (ця перевірка не потрібна, якщо дані структуровані правильно, тобто у них немає просто порожніх елементів).

Я також виводив загальний data availability index на підставі інформації про наповнення всі визначених секцій.

На додачу до цього ми також можемо зробити декілька візуалізацій, котрі представлятимуть стан наповнення даних по всіх проєктах. Наприклад, візуалізація, котра показує, яка частка проєктів має заповнені бюджети, фінанси, і т.д.

У своєму аналізі я орієнтувався на наступні секції проєктів:

- targets
- criteria
- requirements
- documents
- approaches
- items
- budget
- finance
- relatedProcesses
- additionalClassifications
- contractingProcesses

Що потрібно буде врахувати / додати:

- наявність зображень (це по суті documents певного типу) - запит від Проєктного офісу
- наявність закупівельних планів у контрактних процедурах (треба зрозуміти, як це ідентифікується в даних)

Можливо, якісь секції можна буде навпаки прибрати. Наприклад, criteria ніби мали б бути у всіх проєктів (але це варто уточнити)

**Comment by ndrhzn** [comment]
**Поточний статус** - розроблено драфт сторінки з даними щодо наповнення проєктів. 

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/7d4d85ab-5557-40b2-9422-ae3f8580cc02)

**Поточні задачі**
- Визначити, які елементи мають лишитися, а які варто прибрати (або навпаки - що варто додати)
- Визначити перелік фільтрів та описати механіку їхньої роботи
- Визначити перелік розрізів 
- Перекласти всі назви

Далі окремо по пунктах

**Comment by ndrhzn** [comment]
**Які елементи мають лишитися, а які варто прибрати (або навпаки - що варто додати)**

Що для нас важливо у цьому блоці:

- Ідентифікувати проєкти з поганим наповненням
- Ідентифкувати ініціаторів із проєктами з поганим наповненням
- Ідентифікувати органи управління ыз проєктами з поганим наповненням
- Ідентифікувати найбільш проблематичні з точки зору наповнення секції даних

Мені видається, що можна **прибрати візуалізації "Повна заповненість" та "Заповнення властивостей"**. Ці показники для нас не є важливими / визначальними. 

До таблиці варто **додати Ініціатора проєкту разом з кодом ЄДРПОУ** (у тому ж форматі, що і в таблиці "Деталі проєктів")

З таблиці, графіків та фільтрів можна **прибрати relatedProcesses** - виглядає так, що цей елемент має 100% заповнюваність, що скоріш за все означає, що він генерується системно (наприклад, через звʼязок з обʼєктом).

**Comment by ndrhzn** [comment]
**Що варто змінити на графіках**

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/88a7f518-4b78-4d61-8f07-50928797b1d1)

Перший графік за замовчуванням має показувати дані у **розрізі ініціаторів**, сортовані **від найменшого показника до найбільшого**. Тобто спершу ми маємо бачити тих ініціаторів, у яких є найнижчі показники заповнюваності проєктів. Меню під графіком має дозволяти змінювати розріз на "Орган управління" (тобто, всі інші розрізи наразі можна прибрати).

Тут варто також **додати заголовок графіку**, котрий би пояснив, що саме означають відсотки на графіку (особливо це важливо з огляду на те, що у одного ініціатора або органу управління може бути багато проєктів, і тут треба дати зрозуміти, що це не дані на рівні проєкту, а агреговані дані проєктів)

**Для обговорення**: _Я також пропоную змінити показник, який тут відображається (для спрощення комунікації). Зараз відображається наповнення властивостей (тобто частка заповнених елементів від всієї кількості елементів у вибірці). Я пропоную відображати медіанний показник заповнення проєктів (тобто сукупності проєктів обраного ініціатора чи органу управління виводити медіану заповненості)._

Також можна додати у тултіп цього графіку кількість проєктів ініціатора чи органу управління.

**Comment by ndrhzn** [comment]
**Що варто змінити на графіках?** 

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/ab06dad3-c855-468f-8886-7550acb70372)

З другого графіку, як вже зазначалось, варто **прибрати relatedProcesses** (оскільки тут ми маємо 100%, мати цей елемент не дуже корисно).

Цей графік також є сенс за замовчуванням **сортувати за показником наповненості проєктів** (атрибут yes) від найменшого до найбільшого, аби одразу було легко ідентифікувати найменш заповнені секції.

Тут варто **додати заголовок**, котрий пояснює, що означають відсотки (моя інтерпретація така, що це відсоток проєктів, котрі мають цю властивість заповненою або не заповненою, але поправте мене, якщо це не так).

**Легенду, ймовірно, можна прибрати** - частково через те, що на таблиці нижче вже пояснено кольорове кодування, частково через те, що легенда також працює як фільтр, але результат фільтрації даних за допомогою легенди не дуже має сенс.

Окремо варто буде проговорити, як працює інтерактивність на цьому графіку (ми проговорювали сценарій на зустрічі, але, здається, на практиці трохи складніше виходить).

**Comment by ndrhzn** [comment]
Назви елементів

| Як зараз UA                 | Як має бути UA                        | Як має бути EN             |
|-----------------------------|---------------------------------------|----------------------------|
| Код проєкту                 | Код проєкту                           | Project code               |
| props_count/12              | Наповнення                            | Data availability          |
|                             | Показники                             | Metrics                    |
| Є targets                   | План реалізації                       | Targets                    |
| Є criteria                  | Запитання по SPILNO-мапі              | Criteria                   |
| Є requirements              | Відповіді на запитання по SPILNO-мапі | Requirements               |
| Є documents                 | Документи                             | Documents                  |
| Є document_images           | Зображення                            | Images                     |
| Є approaches                | Технічні рішення                      | Approaches                 |
| Є items                     | Обʼєкти інвестицій                    | Items                      |
| Є budgets                   | Бюджет                                | Budget                     |
| Є finance                   | Фінансування                          | Finance                    |
| Є additionalClassifications | Додаткові класифікації                | Additional classifications |
| Є contractingProcesses      | Контрактні процедури                  | Contracting processes      |

**Comment by ndrhzn** [comment]
**Які фільтри тут мають бути?**

- Ініціатор
- Орган управління
- Тип ініціатора
- Тип органу управління
- Фільтр відсутності даних за секцією (для нього потрібна коротка і зрозуміла назва, а також треба замінити назви елементі у фільтрі на людиночитані за прикладом у таблиці зверху)

**Comment by ndrhzn** [comment]
**Алгоритм визначення наявності даних**

Треба перевірити алгоритм визначення наявності даних. Наразі виявив випадки, коли наша таблиця показує, що дані є (документи і зображення), але в проєкті на сайті їх немає.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/1b35d26f-38c8-4881-a5c6-2c60680c5316)

Коди проєктів для прикладу - [301123-6AD99EAE](https://dream.gov.ua/project/DREAM-UA-301123-6AD99EAE/profile), [241123-4BBF70D5](https://dream.gov.ua/project/DREAM-UA-241123-4BBF70D5/profile).

Варто визначити
- Чи є це помилка в алгоритмі визначення наявності даних (якщо так - ідентифікувати та виправити; застосувати новий алгоритм до всіх секцій)
- Чи є це розбіжність між даними в АРІ та на порталі (комунікувати цю розбіжність проєктному офісу та команді розробки)

**Comment by andrzejbeletsky** [comment]
Щодо визначення наявності даних.

API повертає інформацію про документи:
https://public-api.dream.gov.ua/marketplace/public/dream/ideas/38q86r10-6yv2-42z3-a3x5-7960y3xcqa34
https://public-api.dream.gov.ua/marketplace/public/dream/ideas/mfy3u13f-2oeu-4y0d-8lz1-07fv8iwne04u
хоча лінки на документи не клікабельні, дає помилку 404.

**Comment by andrzejbeletsky** [comment]
Доброго.
Варіанти з іншими кольорами:

https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/04506417-6854-4d04-9283-8e1b8241c1d4/state/analysis

https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/6770d46d-0c92-41ef-baa6-4911bbfb444a/state/analysis

**Comment by ndrhzn** [comment]
**Урахування статусу проєкту**

Одне з питань, котре ми проговорювали, стосується урахування статусу проєкту під час аналізу наявності даних / секцій в проєкті. Резонно, що проєкт, котрий щойно був ініційований, ще не може мати таких елементів, як контрактні процедури.

Що ми можемо щодо цього зробити:
- Додати фільтр "Статус проєкту"
- Адаптувати алгоритм обчислення наявності даних в залежності від статусу проєкту

Пропонований алгоритм такий:

Якщо статус проєкту == "Ініціація", для "Контрактних процедур" ставимо не "Так" чи "Ні", а "-", і виключаємо цей показник з розрахунку відсотка заповненості проєкту. Тобто для проєктів у статусі "Ініціація" відсоток заповненості буде обчислюватися з меншої кількості секцій / елементів, ніж для проєктів у статусі "Виконання".

Звісно, це все ми можемо описати користувачам у довідці. Чи має сенс такий підхід? @a-radik @andrzejbeletsky

**Comment by andrzejbeletsky** [comment]
На разі в розробці - metrics, тултіп (кількість проєктів).
На сьогодні немає жодного проєкту зі статусом "Ініціація". Зроблю на майбутнє, зараз перевірити ніяк..

**Comment by ndrhzn** [comment]
Гм, у нас дешборд показує, що проєктів у статусі "Ініціація" - 759

**Comment by andrzejbeletsky** [comment]
my bad (
торможу - це ж він 'pending' і є..

**Comment by ndrhzn** [comment]
**Нова порція правок** @andrzejbeletsky 

1. З двох графіків - “Наповнення проєктів - Медіана” та “Наповнення проєктів - Середнє” - лишаємо тільки один - “Наповнення проєктів - Медіана”. Заголовок для цього графіку може бути “Наповнення проєктів”, а в тултіпі можна винести замість “Наповнення” щось на зразок “Медіана наповнення”.
2. У графіку "Наповнення властивостей" варто поправити тултіпи. Коли ми наводимо, наприклад, на "План реалізації", то у тултіпі найперший підпис "План реалізації. Sum of positives: 100%" - це не є дуже корисна для нас інформація, і це варто прибрати. 
3. Порядок стовпчиків у таблиці та у фільтрі має бути такий, як [описано ось тут](https://github.com/open-contracting/bi.dream.gov.ua/issues/30#issuecomment-1839270029).  Для таблиці це означає перенесення стовпчику "Показники" / Metrics на початок. Для фільтру це означає в принципі застосування іншого сортування / порядку, ніж зара.
4. Заголовок найпершого фільтру можна встановити наступний "Оберіть секції без даних" / "Select sections without data" (якщо я правильно розумію механіку цього фільтра)
5. До фільтрів варто додати "Тип ініціатора" перед "Типом органу управління". 
6. З фільтрів варто прибрати "Імплементатор" та "Код проєкту".
7. Видається, що всюди можна замінити "Так" і "Ні" на "Є" і "Немає". В такому разі буде більш зрозуміло читати, наприклад, "План реалізації" - "Є", або "Зображення" - "Немає".
8. Варто перевірити формули для кольорового кодування. У наведеному прикладі ми бачимо, що комірки із підписом "Ні" кодується кольором, який використовується для "Так"
 
![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/5db0e41a-e742-4066-9f37-52ddbf9b44bd)

**Comment by andrzejbeletsky** [comment]
поки без тултіпів:
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/660b2add-d9c1-435e-a303-07ffbbf62640/state/analysis

**Comment by andrzejbeletsky** [comment]
Це точно цей додаток
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/660b2add-d9c1-435e-a303-07ffbbf62640/state/analysis
?
Не можу зрозуміти - в мене інша картинка:
![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/63861139/ddbc3eb7-e7f9-4f4a-9b3a-172db77d35a5)

**Comment by ndrhzn** [comment]
За наведеним посиланням у мене нічого не відкривається / відбувається переадресація на головну сторінку, з котрої потрібно вже йти на DREAM Public > Наповнення. Можливо, це ознака того, що не всі оновлення доступні для мене

**Comment by ndrhzn** [comment]
Для англійської версії таблиці, думаю, варто замінити "Yes" / "No" на "Available" / "Not available" @andrzejbeletsky 

Поза тим можна вважати цей аркуш в цілому готовим.  Якщо виникнуть якісь правки згодом - опишемо та опрацюємо їх. Але наразі можна брати в роботу в mashup. @a-radik

**Comment by a-radik** [comment]
@ndrhzn  Чи планується зробити опис розрахунку показника медіана наповнення проєктів

**Comment by ndrhzn** [comment]
Так, я зроблю опис цього показника. А також показника наповнення проєктів загалом

**Comment by ndrhzn** [comment]
Коли ми застосовуємо вибір у фільтрі “Оберіть секції без даних”, на верхній панелі відображається картка фільтру із текстом prop_choice_ua. Варто замінити це на більш зрозуміле - наприклад, “Секції без даних” для української версії, “Sections without data” для англійської @andrzejbeletsky

**Comment by andrzejbeletsky** [comment]
Take a look:
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/660b2add-d9c1-435e-a303-07ffbbf62640/state/analysis

**Comment by a-radik** [comment]
https://bi.qnalytics.com/dream/#/dataAvailability
@ndrhzn мешап сторінки

**Comment by ndrhzn** [comment]
Чи ми можемо до цієї сторінки додати ще один фільтр, котрий би дозволяв фільтрувати проєкти за відсотком наповненості? Скажімо, якщо я хочу обрати всі проєкти, де відсоток менше 100%, або всі проєкти у діапазоні від 0% до 50%? Це може бути range slider, якщо Qlik має такий функціонал @andrzejbeletsky

**Comment by ndrhzn** [comment]
**Conflicting visual encodings** @a-radik 

У цьому випадку при наведенні на рядок таблиці він виділяється іншим кольором, що з одного боку дає нам visual confirmation, з іншого боку - зводить нанівець основне візуальне кодування.

Якщо у нас є можливість зробити visual confirmation в інший спосіб, є сенс поміняти підхід (наприклад, виділяти болдом)

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/e8454536-5a6f-453a-bca7-d111232a9947)

**Comment by a-radik** [comment]
там тільки колір тексту або фону можна вибрати. Пропоную погратись з колорами, можливо підібрати більш насичений жовтий
або колір шрифта наприклад, синій

**Comment by ndrhzn** [comment]
Давайте спробуєм колір тла лишити, як є, а колір шрифта змінити

**Comment by ndrhzn** [comment]
Якщо я правильно розумію, наразі зафіксували не давати visual confirmation on hover в принципі, що теж може бути рішенням.

Таким чином з точки зору функціоналу поки незакритим у цьому блоці є [фільтр за відсотком наповнення проєкту](https://github.com/open-contracting/bi.dream.gov.ua/issues/30#issuecomment-1862606080). Встигнемо зробити в цей реліз чи виносимо окремим тікетом на допрацювання? @a-radik  @andrzejbeletsky

**Comment by ndrhzn** [comment]
Також в мешап потрібно буде додати пояснення - перше стосується таблиці, друге стосується стовпчикового графіку

- Показник "Наповнення" у таблиці розраховується як частка заповнених секцій проєкту від загальної кількості секцій. Скажімо, якщо з 12 секцій у проєкті є дані для 6, тоді показник наповнення цього проєкту буде 50%. Цей показник враховує статус проєкту - для проєктів зі статусом "Ініціація" наявність контрактних процедур не враховується.
- Для порівняння ініціаторів та органів управління на графіку використовується медіанний показник наповнення проєктів. Скажімо, якщо в ініціатора є три проєкти, з котрих перший заповнений на 75%, другий заповнений на 40%, третій заповнений на 30%, медіанним значенням наповнення проєктів буде 40%.
