### ISSUE TITLE
Бюджети: Таблиця

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#32]
У цьому блоці нам потрібно відобразити детальну інформацію щодо бюджетів у табличному вигляді. Для початку пропонується представити наступні елементи.

- Код проєкту
- Назва проєкту
- Загальний орієнтовний бюджет
- Предмет витрат
- Тип предмету витрат
- Тип бюджетування
- Період

З точки зору презентації даних / зручності користування цією таблицею, один з найбільших викликів полягає у тому, що в одному проєкті може бути (і буде) декілька предметів витрат. Це своєю чергою означає, що дані для одного проєкту будуть розбиті на декілька окремих рядків (один рядок для одного предмету витрат).

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/1e3ff8b3-1416-4d1e-b577-f3f41e7cfd47)

Для нас важливо мати можливість дати розбивку бюджету за предметами витрат разом з можливістю бачити загальний бюджет проєкту / групувати предмети витрат за проєктами.

**Comment by ndrhzn** [comment]
[Правки для таблиць] @andrzejbeletsky 

Поточний статус 

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/3c2d41ac-a80a-405f-a294-361a1eb05de7)

Пропоную наступні правки

- **Змінити пропорції між стовпчиками**, на котрих користувачі обирають розрізи, та стовпчиками, котрі відображають дані. В такий спосіб буде простіше бачити тексти після розгортання категорій. Це буде особливо корисно у випадках, коли потрібно відобразити довжелезну назву ініціатора чи органу управління. Приклад додається

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/4df5d8e2-0805-47e3-8afe-cbc7edf90d0f)

- **За замовчуванням сортувати значення за показником "Загальний орієнтовний бюджет"** від найбільшого до найменшого (наразі, здається, сортування відбувається за алфавітом; вкладка Values в принципі не дозволяє застосовувати сортування значень)

- Прибрати показник "Доведене фінансування"

- Вкладку "Загальне" перейменувати у "Сектори економіки", і відображати у ній сектори та підсектори (прибрати з неї розрізи "Імплементатор та "Орган управління")

- Вкладка "Деталі" наразі фактично дублює ту ж інформацію, котру ми бачимо на графіках вище, тому можна її переробити. Перейменувати у "Органи управління та ініціатори", і показувати там дані у розрізі органів управління та ініціаторів".

- Додати вкладку "Проєкти", де просто відображати пласку таблицю із показниками - Код проєкту, Назва проєкту, Загальний орієнтовний бюджет, Предмет витрат, Тип предмету витрат, Тип бюджетування, Період. Це таблиця для тих, хто захоче просто вивантажити всі дані для власного аналізу.

- Вкладку "Потоки бюджетування" перейменувати на "Фінансування та бюджетування".  Візуалізацію переробити таким чином, аби звʼязати між собою показники "Підтверджене фінансування" та "Загальний орієнтовний бюджет". Наприклад, можна відображати "Підтверджене фінансування" у розрізі "Типу фінансування", звʼязати це з "Типом витрат" та "Типом проєкту". Ноду "Тип бюджету" можна прибрати", оскільки у нас тут лише одна категорія (на мабутнє я уточню, чи ми очікуємо взагалі за бізнес логікою, що будуть інші типи бюджету. Можливо, це артефакт, як і показник "Доведене фінансування".

- До фільтрів можна додати "Ініціатор" та "Орган управління"

**Comment by ndrhzn** [comment]
**Невеличкі правки до таблиць** @andrzejbeletsky 

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/087cb010-2573-4763-be7d-b2469b864a3a)

Ось тут з таблиці варто прибрати "Тип бюджету". 

Також в ідеалі цю таблицю за замовчуванням варто сортувати за кодом проєкту, а потім за бюджетом (якщо можливо застосовувати сортування за двома показниками; якщо ні, то за замовчуванням - за кодом проєкту, аби всі статті витрат групувались).

Totals варто перекласти (в інших таблицях наче перекладається, але тут не підтягується переклад)

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/b98c0f1b-c294-478c-af93-ae3af0d42b21)

Ось тут варто перекласти Values

**Comment by ndrhzn** [comment]
Зафіксували поки прибрати sankey chart. А таблицю зо всіма проєктами перенести до контейнера

**Comment by ndrhzn** [comment]
**Візуальне підтвердження вибору** @andrzejbeletsky 

Чи ми можемо тут додати візуальне підтвердження вибору? Якщо користувачі клікають на якусь категорію (Сектори економіки, Органи управління та ініціатори", "Деталі", чи ми можемо візуально виділяти кнопку / категорію, на котрій перебувають користувачі?

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/6ce1dfbc-841d-4fe5-a3a1-812ebf35a9c4)

Ця проблема також постає і на головному дешборді, але там хоч трохи простіше розібратися, бо всі три представлення / візуалізації різні. У цьому випадку в нас три таблиці, тому користувачам, котрі не обізнані з даними добре, може бути важко відстежувати, де вони перебувають.

**Comment by ndrhzn** [comment]
Також про всяк випадок документую, що в англійській версії є баг у відображення management bodies and initiators

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/2b643b52-39a7-4bf0-a389-af2479df5ea3)

**Comment by ndrhzn** [comment]
Можливо, рішення з контейнером візуально було ліпше, бо зараз візуально не одразу зрозуміло, до чого стосуються ці три кнопки посеред екрану.  І вони перебирають на себе занадто багато уваги @a-radik

**Comment by a-radik** [comment]
Стосовно зведеної таблиці - це не зовсім так, можливість розгорнути/згорнути працює при натисканні на + або -. Спробував, в мене на мобільному працює.
Стосовно кнопок - це була проміжна версія коли не було впевненості як працюватиме експорт. Наразі все зайве прибрали

**Comment by ndrhzn** [comment]
@a-radik ось, що я маю на увазі

![table](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/e7b42198-6bb7-40d7-9098-f42f467b29e5)

**Comment by ndrhzn** [comment]
Можемо перекласти Values? Єдине англійське слово в українській версії наразі

**Comment by a-radik** [comment]
> _Можемо перекласти Values? Єдине англійське слово в українській версії наразі_
Це залежить від мови вашого браузера. Ми на це не впиваємо, нажаль. Якщо мова браузера російська - буде перекладено українською. Український переклад, вендор поки що не робить, тому ми підкладаємо замість росій1ського український.

Стосовно роботи pivot table - якщо я правильно розумію питання, це стандартна поведінка об'єкта: клік на плюсі розгортає наступний рівень, клік на значенні робить вибір значення.

**Comment by ndrhzn** [comment]
> Стосовно роботи pivot table - якщо я правильно розумію питання, це стандартна поведінка об'єкта: клік на плюсі розгортає наступний рівень, клік на значенні робить вибір значення.

Мені трохи про інше йдеться. Після того, як я клікнув на значення - плюсик стає неактивним. І мені треба клікнути на додатковий елемент інтерфейсу, аби плюсик знову став активним. Ймовірно для вас це вже є природнім явищем, як для постійного користувача. Але для нових користувачів це може бути неочевидно, особливо з огляду на те, що елемент інтерфейсу, на котрий треба клікнути, аби плюсик знову став активним, знаходиться далеко від самого плюсика та значення.
