### ISSUE TITLE
Таблиці: Форматування чисел

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#33]
Користувачі зауважили, що у таблиці з проєктами у нас використовується два різних способи форматування чисел. 

Показники щодо бюджетів даються без жодних пробілів, а показники щодо фінансування даються з пробілами. Очевидно, що читати довгі числа простіше, якщо там є пробіли, котрі відокремлюють мільйони, тисячі, і т.д. 

Нам варто уніфікувати підхід до форматування чисел в таблицях.

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/10d2b366-e824-4c4e-9d57-efabc8f96967)

**Comment by ndrhzn** [comment]
#10

**Comment by andrzejbeletsky** [comment]
Done.
Take a look.

**Comment by ndrhzn** [comment]
Бачу зміни, дякую. Можливо, варто той самий принцип застосовувати до всіх числових значень за замовчуванням. Наприклад, там поруч є змінна "Фінансове покриття". Я розумію, що в ідеалі у нас там не має бути чисел понад 100%, але поки там зустрічається щось на зразок 119258%, є сенс застососувати форматування
