### ISSUE TITLE
Карти: Накладання підписів

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#34]
Користувачі вже декілька разів зауважували проблему із накладанням підписів на карті. Задокументую її тут, аби ми мали можливість проговорити можливі рішення (попередні наші обговорення не результували у якихось змінах до роботи із підписами).

- На карті України накладаються підписи для Києва та Київської області. Чи є можливість змістити їхні позиції (в технічних термінах, чи label / text має параметр offset)

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/05dbe813-b106-43a6-82d2-b9e3d78018ed)

- На рівні окремо взятої області теж можливе накладання підписів. У цьому разі offset (навіть якщо він є) не допоможе, оскільки за умови щільного розташування підписів зміщення / усунення накладання на одній позиції призведе до накладання підписів на іншій позиції. Чи має Qlik якісь інструменти для роботи із цим?

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/21bfd3fd-82c7-48f2-8f4a-2e473d1bcefe)

З моїх спостережень на рівні області ця проблема наразі помітно проявляється у Київській та Одеській областях, втім, за умов збільшення кількості проєктів з інших громад, ми можемо очікувати, що проблема з накладанням підписів буде відчуватися більш гостро і в інших областях.

Суто технічні варіанти підходу:

- Показувати підписи лише на певному рівні зуму. Це може з великою ймовірністю допомогти нам уникнути накладання підписів, однак це також означає, що на деяких представленнях підписів може і не бути. В такому разі потрібно буде показувати легенду (color scale), аби користувачі розуміли, як співвідносити відтінок кольору із числовим значенням

- Зменшити розмір підписів. Тут є очевидні ризики, що підписи можуть стати менш зручними для читання.

Можна розглядати варіанти рішення для накладання підписів на карті України та на карті обраної області окремо.

**Comment by andrzejbeletsky** [comment]
Take a look.
Легенда кольору.
Підписи з'являються тільки при зумі (різні для областей і громад. ступені зуму для появи вибрано вільні)
https://bi.qnalytics.com/dream/#/

**Comment by ndrhzn** [comment]
Мені здається, стало менш зручно. Треба ще пошукати оптимальний варіант

My reasoning

- Мати підписи на карті на рівні всієї країни за замовчуванням - зручно. Проблема лише у тому, що накладаються підписи для Києва та Київської області. Чи може це бути вирішено за допомогою параметра Label position?

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/517a66c5-1e01-4720-b842-a969465e28eb)


- Якщо підписи для громад активуються на певному рівні наближення, то варто це робити раніше (моя поточна проблема, наприклад, полягає в тому, що підписи можуть зʼявитися лише на тому рівні наближення, коли громада вже не відображається повністю на екрані).

- Якщо ми не знайдемо оптимальний варіант із появою підписів за рівнем наближення, завжди можемо повернутися до попередньої опції (підписи завжди присутні), але хіба трохи зменшити розмір підписів.

- За відсутності підписів легенда, звісно, корисна. Але вона зараз відʼїдає простір у самої мапи. Варто спробувати зробити легенду горизонтальною та розташувати у лівому нижньому куті.

**Comment by ndrhzn** [comment]
@andrzejbeletsky чи ми тестували варіант із newline character? Потрібно зрозуміти, чи закривати це питання, чи лишати відкритим

**Comment by ndrhzn** [comment]
Добре, тоді зафіксуємо, що це готово у нативному додатку, і можна включати в наступний реліз у публічній версії
