### ISSUE TITLE
Describe steps to build the assets for the mashup

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/bi.dream.gov.ua#38]
Assigning @ndrhzn as FYI / coordination.

I see the css and js files are chunked, so I assume they are built from source files.

Ideally, GitHub would also have the source files, and then we (or I) can configure a GitHub Actions workflow, that uses the source files to build the mashup, which would then be committed to a separate branch.

* [x] A first step would be to commit the source files to the `main` branch.
* [x] RBC: Share the precise commands to build the site from the `main` branch (i.e. to produce the output that is currently in the `build` branch).
* [x] James: Add GitHub Actions workflow to main branch, to regenerate build branch. For example, the https://github.com/peaceiris/actions-gh-pages action can be used to commit the built files, like we do here: https://github.com/open-contracting/extension-explorer/blob/main/.github/workflows/deploy.yml

**Comment by karandinserhii** [comment]
Hi 
@jpmckinney 

The following command builds source files into a production build:
`npm run build`
Please let me know if this is the information you needed, or if you have any other questions
(In case you need a detailed information about the build process itself, it can be found here  https://create-react-app.dev/docs/production-build )
