### ISSUE TITLE
Візуалізації: Форматування чисел на вісях

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#39]
Ми вже заторкали питання форматування чисел у картках (#24 ) та таблицях (#33 ), однак є сенс поговорити і про форматування чисел на вісях. Насамперед ця потреба відчувається тоді, коли у нас на вісях числа з великою кількістю символів.

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/87d6b1e3-a0d4-4f45-8de4-ec0d525dcebe)

Тут є два питання:

- Чи потрібні нам вісі та підписи на вісях в принципі, якщо ми підписуємо всі значення напряму біля кожного стовпчика?
- Якщо є якийсь аргумент за те, щоб зберегти підписи на вісях, як ми можемо їх форматувати, аби зменшити кількість знаків? Або ж зменшити кількість самих підписів (умовно до трьох - мінімум, максимум і ~ медіана)

**Comment by ndrhzn** [comment]
Схоже, що ми пішли шляхом прибирання підписів з вісей в принципі (works for me). Бачу, що майже всюди вже підписів немає, про всяк випадок звертаю увагу, що тут вони ще є

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/b31751a5-175e-40a6-8759-421300395f6b)

А на цьому представленні чомусь не відображаються підписи значень (хоча для всіх інших розрзів, окрім регіонів) вони відображаються

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/1f5d3dd0-a09e-4da2-975d-2568185c8b6e)

**Comment by andrzejbeletsky** [comment]
Не можу змоделювати відсутність підписів значень (

**Comment by ndrhzn** [comment]
Цікаво, помітив, що ця проблема у мене є на великому моніторі, але зникає під час перенесення вкладки на малий монітор. Можливо там є якась властивість, привʼязана до розміру контейнера?
