### ISSUE TITLE
Головний дешборд: Візуалізації

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#4]
В цьому блоці ми закладали

- Кількість проєктів / запланований бюджет / обсяг фінансування / профінансованість  за регіонами (choropleth map)
- Кількість проєктів за статусом (bar chart або treemap)
- Розподіл проєктів за датою реєстрації (histogram) - визначити binwidth (7 днів, місяць)

Правки загального характеру

**“За статусом”** 

Чи можливо або:

- Зробити  так, аби візуалізації заповнювала весь контейнер по ширині (_це може бути не дуже оптимальний варіант, оскільки наразі у нас всього лише три стовпчики, і розтягування їх по ширині результуватиме у дуже широких стовпчиках_)

- Замінити цю візуалізацію на treemap, тоді всі елементи природньо будуть заповнювати весь простір контейнера 

**“Розподіл”**

Мені здається, цю можна приховати / прибрати. Можливо, в майбутньому ми повернемось до якоїсь варіації на тему цієї візуалізації, але наразі не бачу у ній цінності / потреби

**“Динаміка створення”**

Тут краще зробити за замовчуванням відображення у розрізі тижнів року

TO DO: Підготувати / поправити заголовки контейнерів / представлень

**Comment by a-radik** [comment]
Стосовно "За статусом" і "Розподіл"
вкладка "Розподіл" саме і відображає обраний показник в розрізі статусів і областей. І замінює "За статусом" але в той-же час є більш інформативною оскільки дозволяє бачити одразу 2 розрізи. Можливо тут є сенс використовувати інший розріз або зробити можливим вибір розрізу?

**Comment by ndrhzn** [comment]
Гм, можна подумати про те, щоб зробити можливим вибір розрізу. 

В такому разі це, з одного боку, дублюватиме поведінку стовпчикового графіка, де можна обирати розріз. З іншого боку, буде можливість одні й ті ж самі дані розглянути у двох різних розрізах (наприклад, на стовпчиковому графіку "Обсяг фінансування у розрізі характеру проєкту", а на вкладці "Розподіл" - "Обсяг фінансування у розрізі типу фінансування та регіону".

Питання в такому разі таке - чи нам для Treemap завжди потрібні два виміри? Чи нам потрібно давати можливість обирати обидва?

**Comment by ndrhzn** [comment]
Я згоден, що в більшості випадків treemap з одним розрізом має мало сенсу. Тут питання радше в тому, чи робити це

**Comment by ndrhzn** [comment]
Я згоден, що робити treemap з одним розрізом _в більшості випадків_ не має сенсу

В такому разі можемо закласти такий сценарій - ми будуємо treemap, котрий демонструє показник, обраний користувачем через KPI / картку. Один із розрізів цього treemap може за замовчуванням дублювати розріз, обраний на головному стовпчиковому графіку. Другий розріз - за замовчуванням регіон, але у користувачів має бути можливість змінити його

Має сенс?

**Comment by andrzejbeletsky** [comment]
Зроблено низку змін. 
Take a look.

**Comment by ndrhzn** [comment]
**Layout**

"Розріз 2" відображається для всіх візуалізацій, але застосовується лише до візуалізації "Розподіл". Чи можна це дропдаун меню показувати лише у контейнері "Розподіл"?

Під фільтрами теж відображається підпис "Розрів 2", котрий не є функціональним. Варто прибрати

**Comment by ndrhzn** [comment]
**Текстові елементи**

Чи можна / має сенс прибрати ось ці текстові елементи

З підпису "Насиченість за мірою > Кількість проєктів" прибрати "Насиченість за мірою > " та відображати власне тільки назву показника, котрий відображається

З підпису "Розріз 2 > Тип проєкту" прибрати "Розріз 2 > " та відображати власне тільки назву показника, котрий відображається. Або замінити на call to action "Оберіть розріз для відображення"

Відмінювання

Родовий відмінок для слова "проєкт" - "проєкту" ([відмінки слова "проєкт"](https://slovnyk.ua/index.php?swrd=%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82)). Ця правка заторкає елементи і в dropdown menu, і в фільтрах

**Comment by ndrhzn** [comment]
**Проєкти без обʼєктів**

Якщо обрати "Фінансуюча сторона" > roadStateFund, то загальна кількість проєктів буде 9, але на карті відображатимуться лише 5. Ця проблема виникає через те, що не у всіх цих 9 проєктів є привʼязані обʼєкти

Тут варто

- Перевірити, чи справді обʼєкти відсутні (так не мало б бути). Якою є кількість проєктів без обʼєктів
- Підготувати дисклеймер для таких випадків, аби пояснити розбіжність між відображенням на графіку та карті

**Comment by andrzejbeletsky** [comment]
Зроблено: "проєкта" - "проєкту".

Э об'єкти, для яких вказано гео-приналежність не до громади, а до області.
У даному випадку - вказані геокоди
UA12000000000090473 Дніпропетровська
UA14000000000091971 Донецька

**Comment by ndrhzn** [comment]
**Розподіл за датою створення та оновлення проєктів**

Для візуалізації "Динаміка створення" варто додати ще одну лінію, котра б демонструвала розподіл проєктів за датою оновлення. Таким чином можна буде побачити, що хоча нові проєкти не обовʼязково створюються у тій же кількості, в якій вони створювались на самому початку, але робота над наповненням вже наявних проєктів триває.

![visualization](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/f09ff6a4-69d3-4df1-a357-c89517a8e230)

**Comment by ndrhzn** [comment]
**Layout - Вкладка “Розподіл”**

У вкладці “Розподіл” варто поправити layout. Наразі графік не відображається на всю висоту контейнера. І також dropdown menu не відображається повністю за замовчуванням (підписи видно лише якщо натиснути на меню).

В ідеалі dropdown menu для стовпчикового графіка та для treemap мають бути на одному рівні, а treemap своєю чергою має заповнювати всю висоту контейнера.

Як я вже зазначав раніше, слова "Розріз 2" перед dropdown menu варто або прибрати в принципі, або замінити на call to action на зразок "Оберіть показник для відображення".

Також можливо варто замінити іконку для вкладки "Розподіл". Зара кольорові елементи трохи вибиваються поміж монохромних іконок інших вкладок.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/daad5dad-c849-4915-b77b-399cc1aafd78)

**Comment by ndrhzn** [comment]
**Layout**

Тут та в інших випадках потрібно переконатися, що картки рівномірно розподілені по всій ширині і з правого боку немає дірки

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/56927d7e-fc1e-4698-be1b-67ff46e12513)

**Кнопки / Вкладки**

Може варто трохи приглушити колір кнопок / вкладок (TO DO: Підготувати для них нормальні назви)

Також на наступному дешборді теж використовуються вкладки, але в інакшому стилі. Варто уніфікувати стилістику між всіма сторінками
