### ISSUE TITLE
Feature request: Фільтр за наповненням проєктів

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#46]
Чи ми можемо до цієї сторінки додати ще один фільтр, котрий би дозволяв фільтрувати проєкти за відсотком наповненості? Скажімо, якщо я хочу обрати всі проєкти, де відсоток менше 100%, або всі проєкти у діапазоні від 0% до 50%? Це може бути range slider, якщо Qlik має такий функціонал @andrzejbeletsky

_Originally posted by @ndrhzn in https://github.com/open-contracting/bi.dream.gov.ua/issues/30#issuecomment-1862606080_

**Comment by andrzejbeletsky** [comment]
In progress

**Comment by ndrhzn** [comment]
Поточний статус - реалізовано драфт на тестовому сервері. 

Механіка у драфті наступна - за допомогою слайдера потрібно вибрати значення від 0 до 100 та натиснути кнопку "Вибрати". Обране значення використовується в якості верхнього значення діапазону - скажімо, якщо обране значення 60, тоді діапазон вибору - від 0 до 60.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/f450b120-bb50-4230-a265-5bb62fb5ff4f)

Ця механіка працює лише в тому випадку потрібний діапазон починається від нуля. Але якщо потрібно обрати діапазон від 10% до 50%, тоді ця механіка не спрацьовує.

Які тут можливі варіанти рішення?

- **Range slider** - наскільки я розумію, Qlik з коробки не підтримує це рішення, але можливо є extensions. [Посилання на дискусію](https://community.qlik.com/t5/New-to-Qlik-Sense/Range-Slider-filter-in-QlikSense/td-p/1587930)
- **Input box** - фільтрувати дані за допомогою простого input box, котрий приймає числові два числових значення - мінімум та максимум у діапазоні ([як у цьому прикладі Power BI, але лише number input, без слайдера](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-slicer-numeric-range))
- **Distribution chart / histogram** - використовувати гістограму, котра представляє розподіл проєктів за показником наповнення (binwidth=5%), із можливістю обирати діапазон значень прямо на графіку ([приклад наведено ось тут](https://community.qlik.com/t5/New-to-Qlik-Sense/Range-Slider-filter-in-QlikSense/m-p/1587976/highlight/true#M137276))

Що думаєте? @andrzejbeletsky @a-radik

**Comment by andrzejbeletsky** [comment]
Є варіант з вибором мін/макс :
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/660b2add-d9c1-435e-a303-07ffbbf62640/state/analysis

**Comment by andrzejbeletsky** [comment]
R&D передав початкову версію range-slider.
Реалізація на сторінці Наповнення:
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/660b2add-d9c1-435e-a303-07ffbbf62640/state/analysis

Todo: позбутися кнопки Вибрати.

**Comment by ndrhzn** [comment]
Виглядає як рух у правильному напрямку, дякую!

Щодо механіки та вигляду

- Справді, було б добре позбутися кнопки “Вибрати”, та застосовувати зміни після зупинки слайдера
- Зараз підпис мінімального значення знаходиться посередині слайдера, а підпис максимального - з правого боку

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/bf9caefa-4574-470a-9cf4-914a97827cba)

Хоча в деяких ситуаціях підпис максимального значення міняє позицію і відображається посередині. 

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/36cd93eb-9940-42d2-94f1-b5fa1f7c4d31)

Тут варто уніфікувати розташування (або обидва посередині, або по краях, або підписи змінюють позицію відповідно до позицій повзунків)

- Впевнений, що у цьому компоненті є можливість задавати значення за замовчуванням. В такому разі під час завантаження цього аркушу обрані значення за замовчуванням мають бути 0 - 100

Чи є у нас розуміння, коли робота над цим компонентом може бути завершена?

**Comment by ndrhzn** [comment]
Також хочу уточнити - якщо ми потім потенційно захочемо використати цей компонент на інших аркушах, то чи буде він, наприклад, працювати з діапазоном дат?

**Comment by andrzejbeletsky** [comment]
Зроблено 0 - 100 діапазон за замовчуванням.
R&D оновив слайдер. (Можливо, потрібно Refresh сторінки).
Наразі зроблено для роботи з простими значеннями (min, max, step).
R&D ще за 2 дні відшліфує цю першу версію. 
Базова функціональність здебільше реалізована. Можливі незначні багфікси.

Для вибору діапазону дат є окремий стандартний компонент Date picker.

**Comment by andrzejbeletsky** [comment]
In progress - видалення кнопки "Вибрати"

**Comment by andrzejbeletsky** [comment]
Реалізовано.
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/660b2add-d9c1-435e-a303-07ffbbf62640/state/analysis
Слайдер працює в межах сторінки.
Стає питання - чи потрібно залишити кнопку для відбору проєктів, щоб працювати з ними на інших аркушах.
Без кнопки користувач повинен самостійно селекнути предмет свого інтересу (на будь якому чарті чи таблиці)

**Comment by ndrhzn** [comment]
Що варто зробити далі

- [ ] Змінити заголовок для слайдера на "Оберіть діапазон наповнення проєктів"
- [ ] Вирішити проблему із розташуванням підписів слайдера, [описану ось тут](https://github.com/open-contracting/bi.dream.gov.ua/issues/46#issuecomment-1918696951)

Щодо того, має бути фільтр локальним чи глобальним - звернувся до користувачів, чекаємо відповіді

Також хочу зрозуміти, чи нам треба перейматися зміною кольору слайдера на цьому етапі, чи вже на мешапі

**Comment by andrzejbeletsky** [comment]
Довгий заголовок - не вміщається.
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/660b2add-d9c1-435e-a303-07ffbbf62640/state/analysis
Поведінку з підписами слайдера не вдається повторити..

Щодо кольору - який вибрати?

**Comment by ndrhzn** [comment]
В такому разі заголовок робимо "Оберіть діапазон значень". Для користувачів має бути зрозуміло, що йдеться про відсотки, в такому разі ми можемо або додати до самих числових значень знак "%", або ж підписати у заголовку "Оберіть діапазон значень, %".

Щодо проблеми із підписами слайдера - я відтестував у різних браузерах 

- Chrome (MacOS) - відображається коректно (позиція чисел збігається із позицією повзунків)
- Firefox (MacOS) - відображається некоректно (розташування чисел)
- Safari (MacOS) - відображається некоректно (числа не відображаються взагалі)
- Egde (Windows 11 Pro) - відображається коректно (позиція чисел збігається із позицією повзунків)

За статистикою у нас зараз найбільше користувачів на Chrome, далі йдуть Safari, Edge та Firefox.

Щодо кольору - вже бачу, що застосували чорний. Це вписується у той стиль, який ми застосовуємо у публічному додатку, дякую.

Щодо застосування фільтру до інших аркушів - є сенс зробити це можливим. Але в такий спосіб, аби це не була велика кнопка. Наприклад, це може бути галочка / check mark "Застосувати вибір до інших аркушів" (але в такому разі вона має зніматися щоразу, як діапазон змінюється). Або які у нас тут ще варіант?

Залишається прояснити ще один момент з поведінкою, на котрий я звернув увагу під час тестування - наразі фільтр застосовується до всіх елементів (таблиці та графіків) однаково, оскільки фільтрується underlying data для всіх елементів.

Водночас в процесі тестування я подумав, чи не було б доцільніше застосовувати інакшу логіку для таблиці та для графіку "Наповнення проєктів". Для таблиці в такому б разі ми фільтрували за тим, чи потрапляє показник наповнення індивідуального проєкту в обраний діапазон, а для графіку - чи потрапляє медіанне значення наповнення проєктів у обраний діапазон. З одного боку - ця поведінка видається мені більш природньою, з іншого боку - варто зрозуміти, чи це не заплутає користувачів.

**Comment by alner** [comment]
@ndrhzn  Щодо слайдера Firefox (MacOS), Safari (MacOS)  - пофіксили.

**Comment by andrzejbeletsky** [comment]
Додано кнопку вибору відбору проєктів за діапазоном
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/660b2add-d9c1-435e-a303-07ffbbf62640/state/analysis
Відбір відбувається не саме конкретних кодів проєктів, а в службовому полі з ім'ям "%", однаково в двох мовах.

**Comment by andrzejbeletsky** [comment]
Чи є сенс мати графік розподілу кількості проєктів за наповненістю?
https://qsdemo.rbcgrp.com/sense/app/b0f13ce0-e592-48bc-9432-6da4de1f8cfb/sheet/660b2add-d9c1-435e-a303-07ffbbf62640/state/analysis

**Comment by ndrhzn** [comment]
Мені подобається ідея мати графік розподілу. Ймовірно потрібно буде замінити заголовок на "Розподіл проєктів за наповненням".

Водночас звернув увагу на розбіжність між вибором у слайдері та тим, що я бачу на графіку розподілу. Чому так відбувається? @andrzejbeletsky 

У цьому прикладі ми вибираємо на слайдері нижню межу в 27%, однак на графіку можливі значення від 11% до 20%.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/f29e85b2-be71-47ee-8003-de697ee78da4)

Або у цьому прикладі ми бачимо в таблиці, що є записи із 83%, це теоретично означає, що вони мали б бути у категорії 81% - 90%, але ця категорія навіть не відображається.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/14717a4c-3f48-4fe8-b692-d5c9d4371686)

Заголовок до кнопки все ще треба поправити. Я правильно розумію, що запропонований не влізає?

**Comment by andrzejbeletsky** [comment]
Виправив логіку у графіку розподілу та назву кнопки
Take a look

**Comment by ndrhzn** [comment]
Залишились дрібні правки

Заголовок графіку змінити на “Розподіл проєктів за наповненням” / “Distribution of projects by data availability”

Коли користувачі обирають якийсь інтервал на графіку розподілу, картка фільтру називається “% class”. Є сенс для української мови писати “інтервал”, а для англійської - “bin”

Після цього можна робити mashup @andrzejbeletsky @a-radik

**Comment by andrzejbeletsky** [comment]
@a-radik 
Done.

**Comment by a-radik** [comment]
Вітаю, Колеги
Чи є у вас зауваження/побажання до аркушу з аналітикою по Наповненню проєктів в тестовому мешапі? 
Коли нам слід планувати реліз змін?
@ndrhzn

**Comment by ndrhzn** [comment]
Ось ця правка, описана вище, досі не застосована. Досі відображається просто знак % (проблема навіть не у мешапі, а у нативному додатку) @andrzejbeletsky

> Коли користувачі обирають якийсь інтервал на графіку розподілу, картка фільтру називається “% class”. Є сенс для української мови писати “інтервал”, а для англійської - “bin”  

Для англійської версії можна подовжити назву кнопки і замість "Apply to all sheets" писати "Apply filter to all sheets", в такий спосіб ми зменшимо різницю у розмірі шрифту між українською та англійською версіями.

Щойно ці правки будуть застосовані (в нативному додатку і в мешапі), можна релізити. @a-radik

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
Take a look.
Не зрозумів щодо назви фільтру %. Якщо користувач обирає довільний інтервал за допомогою слайдера, то дійсно, відбір відбувається у полі "%". Якщо на графіку відбір класа - то фільтр або “інтервал”, або “bin” в залежності від мови.

**Comment by ndrhzn** [comment]
Ah, sorry, my bad.

Дивовижним чином розмір шрифта для англійської версії принципово не змінився. Але я думаю, що наразі можемо релізити в такому вигляді @a-radik

**Comment by ndrhzn** [comment]
Та наче немає. Чи ми очікуємо, що додаток може бути якийсь час недоступним? Чи побоюємось, що щось може піти не так?

Якщо у нас немає серйозних пересторог, тоді можна релізити хоч зараз

**Comment by a-radik** [comment]
Декілька хвилин можеть будти проблеми з відображенням. Особливих пересторог немає, тоді подключимось до серверів і почнемо підготовку.
