### ISSUE TITLE
Bug: Відображення одного проєкту декілька разів у таблиці через дані повʼязаного обʼєкта

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#48]
У таблиці із проєктами для деяких проєктів може бути більше ніж один запис. Це виникає через те, що у повʼязаного обʼєкта можуть бути записи про декілька громад, і в такому разі для кожної громади створюється окремий рядок.

Це не впливає на підрахунки ключових статистик, але це викликає питання у користувачів. 

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/7529ed41-6021-4d1a-a8b7-4f9cdc17ae38)

Ми вже стикалися із подібною проблемою на прикладі проєктів із декількома ініціаторами. Відпочатку для кожного ініціатора створювався окремий запис, і тому один проєкт міг фігурувати декілька разів - один раз для кожного ініціатора. Але ми змінили цю поведінку, аби уникнути створення кількох записів для одного проєкту. Тепера для проєктів із декількома ініціаторами ми зазначаємо всіх ініціаторів через кому в одній комірці. 

Пропоную такий же підхід використовувати і для громад.

**Comment by andrzejbeletsky** [comment]
В таблиці для випадку проєкта в декількох громадах, вони будуть через кому.

**Comment by ndrhzn** [comment]
Перевірив за тими кодами, для яких у нас раніше було декілька записів - виглядає коректно, дякую.

Тоді наступний крок - зробити зміни доступними у публічному додатку.

**Comment by andrzejbeletsky** [comment]
Done
