### ISSUE TITLE
Bug: Ініціатори без legalName

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#49]
У даних щодо проєктів у нас є декілька випадків, коли для ініціатора проєкту відсутня ознака legalName. 

https://public-api.dream.gov.ua/marketplace/public/dream/ideas/250aoy97-io44-48gk-bcnj-pd7wq697529w UA-EDR-43927048
https://public-api.dream.gov.ua/marketplace/public/dream/ideas/647yw44v-iy0h-45za-9vyl-5m0181w77625 UA-EDR-04054889 
https://public-api.dream.gov.ua/marketplace/public/dream/ideas/rn6icnn7-07bv-4nz7-8j8h-12dfwx702h53  UA-EDR-04362680
https://public-api.dream.gov.ua/marketplace/public/dream/ideas/9djoif4s-tl80-4a6x-b913-5plv72xti24l 04055896

За словами команди розробки, це проблема, котра виникла під час першої міграції даних (додавання первинних даних у базу), через те, що у деяких історичних проєктів ознаки legalName просто не було. Виправлення цієї проблеми на боці бази даних вимагатиме ручної роботи.

За таких умов видається більш доречним забирати ознаку legalName із companies endpoint (там для всіх зазначених організацій назва є).

**Comment by andrzejbeletsky** [comment]
Done
