### ISSUE TITLE
Головний дешборд: Фільтри

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#5]
У цьому блоці ми закладали такі елементи

- Статус
- Тип
- Характер
- Орган управління
- Регіон (тут треба зрозуміти, за чим ми ідентифікуємо регіон - за регіоном обʼєкта чи ініціатора)
- Тип фінансування
- Джерело фінансування
- Фінансуюча сторона

**Текстові правки**

Проєкт: Замість “проект” всюди пишемо “проєкт”. Щодо відмінювання можна консультуватися [ось тут](https://slovnyk.ua/index.php?swrd=%D0%BF%D1%80%D0%BE%D1%94%D0%BA%D1%82), але з того, що у нас вже є - “статус проєкту”,  “тип проєкту”, “характер проєкту”. У множині все просто - “кількість проєктів”, “профінансованість проєктів” (це радше стосуєтьс карток / KPI, а не фільтрів, звісно)

**Layout**

Наразі всі фільтри знаходяться зверху сторінки, що має свої переваги та недоліки

Переваги

- Одразу видно, які опції для фільтрації даних доступні
- Не потрібно викликати панель з фільтрами (мінус одна дія для користувачів)

Недоліки

- Подібний спосіб розташування передбачає парну кількість елементів, котрі мають рівномірно заповнювати весь відведений простір
- Може бути проблематично додавати нові фільтри, оскільки це вимагатиме більшого простору та відбиратиме простір у візуалізацій та карток

Приховування фільтрів та викликання їх кліком на кнопку теж має свої переваги та недоліки

Переваги

- Економія місця 

Недоліки

- Додаткова дія для виклику фільтрів
- Панель з фільтрами після виклику перекриває частину візуалізації. Для перегляду візуалізації повноцінно панель потрібно закрити (а це ще одна додаткова дія)

Питання / Можливі способи альтернативного розташування фільтрів
- Чи можливо розташування фільтрів задавати динамічно в залежності від розміру екрану? Тобто, чи можемо ми, наприклад, на маленьких екранах показувати фільтри лише по кліку на кнопку, а на великих екранах видавати їх одразу / робити видимими постійно (наприклад, збоку від дешборду)?

**Comment by andrzejbeletsky** [comment]
Зроблено:
1. Фільтри справа
2. Перейменовано проект->проєкт

**Comment by a-radik** [comment]
>  Питання / Можливі способи альтернативного розташування фільтрів
> 
> Чи можливо розташування фільтрів задавати динамічно в залежності від розміру екрану? Тобто, чи можемо ми, наприклад, на маленьких екранах показувати фільтри лише по кліку на кнопку, а на великих екранах видавати їх одразу / робити видимими постійно (наприклад, збоку від дешборду)?

Так, можна буде зробити, єдине що за досвідом не варто прив'язуватись до ширини екрану, оскільки в мобільних телефонах ширина екрану в пікселях доволі велика зазвичай, але є альтернативне рішення.
[Ось тут схожий варіант нещодавно застосовували](https://echerha.gov.ua/statistics ) фільтри на мобільних телефонах переносяться вниз, а в нас будуть просто не відображатись, натомість треба буде відкрити панель фільтрів.

**Comment by ndrhzn** [comment]
Тут теж варто перейменувати назви фільтрів з метою уніфікації термінології 

| Як зараз      | Як має бути     |
|---------------|-----------------|
| Project kind  | Project type    |
| Project type  | Project purpose |
| Fund type     | Funding type    |
| Fund source   | Funding source  |
| Finance party | Financing party |

Ці зміни також варто застосувати до всіх місць, де ця термінологія використовується (наприклад, дешборд з проєктами, два дропдаун меню на головному дешборді, таблиця з фінансуванням

**Comment by ndrhzn** [comment]
Тут варто змінити порядок фільтрів. Пропоную такий порядок

Статус проєкту
Тип проєкту
Характер проєкту
Фінансуюча сторона
Тип фінансування
Джерело фінансування
Тип ініціатора
Тип органу управління
Область
Район
Громада

**Comment by ndrhzn** [comment]
Варто виправити одрук у фільтрі - "Наявність тенедерів" має бути "Наявність тендерів"
