### ISSUE TITLE
UI: Додати підказку для користувачів у тих випадках, коли всі фільтри не вміщаються в один екран

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#50]
Від Проєктного офісу прийшов запит / побажання додати до панелі з фільтрами підказку для користувачів для тих випадків, коли фільтрів багато і всі вони не вміщаються в один екран.

> Можна в усі місця, де пусте місце, але мається на увазі, що там є ще фільтри, додати слово “Більше“? Не дуже очевидно для користувачів, що там є ще якісь додаткові показники.

Приклад пропонованого рішення

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/a69fbeda-1f45-46c6-8649-37c807a5e434)

Що ви щодо цього думаєте? Чи це можливо технічно? Чи Qlik / mashup дозволяють нам щось таке зробити? @a-radik 

As a side comment - на наведеному скріншоті очевидні проблеми з оптимізацією додатку під різні розмірі екрану. Треба буде дослідити це питання трохи більш детально. Можливо у цьому випадку через те, що браузер не відкритий fullscreen, але можливо нам справді є куди покращувати оптимізацію.

**Comment by a-radik** [comment]
Відсутня можливість змінювати стандартні компоненти.
