### ISSUE TITLE
Data: Виключити з підрахунку ключових показників проєкти зі статусом "Неуспішно завершено"

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#51]
Від Проєктного офісу надійшла пропозиція щодо того, які проєкти ми враховуємо під час обчислення всіх ключових статистик. Від самого початку ми погодились, що ми виключимо з підрахунку ключових статистик всі проєкти зі статусом cancelled ("Скасовано"). Це було реалізовано через застосування префільтру за статусом проєкту.

Наразі у нас в даних також зʼявилися проєкти зі статусом unsuccessful (у нашій інтерпретації - "Неуспішно завершено"). Є пропозиція також додати ці проєкти до префільтру і за замовчуванням не показувати їх і не враховувати під час обчислення ключових статистик.

**Comment by andrzejbeletsky** [comment]
Done
