### ISSUE TITLE
UI: Додати підпис для іконок експорту зображення і даних

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#52]
Від Проєктного офісу є запит додати до іконок експорту зображення та даних підписи.

> Чи можливо технічно додати назву для іконки завантаження? Хоча б у вспливаючому вигляді при наведенні на цю іконку. Або прямо словами на екрані написати "Завантажити" і іконка. Бо наразі складно згадувати цей функціонал в роботі з користувачами.

Це питання також вже піднімалося раніше - після релізу функціоналу експорту зображень

> Підкажіть, чи може з'являтися короткий текст-пояснення, що це за іконка і що вона завантажить? Умовно “завантажити зображення у вигляді pdf”/ “завантажити вибрані дані у вигляді exl”?

Тут слід зрозуміти кілька речей

- Коли саме виводити цей текст? Чи одночасно з тим, як ми показуємо іконку, чи після?
- Який саме текст показувати?

Із запитів Проєктного офісу видається, що у користувачів може бути дві окремі проблеми. Перша полягає в тому, аби ідентифікувати (знайти на сторінці) обʼєкт, котрий відповідає за експорт даних. Друга полягає в тому, аби зрозуміти, за що саме відповідає та чи інша іконка.

Тому текст є сенс показувати в той самий момент, коли ми показуємо іконку - вивід тексту не має вимагати додаткової дії з боку користувачів. 

Сам текст має бути коротким, аби не займати багато місця

- Експортувати дані / Export data
- Експортувати зображення / Export image

Звісно, one might argue, що у нас є функціонал для експорту зображення у два різних формати. Тому в ідеалі нам потрібно два підписи. Водночас додавати два підписи не хотілось би, аби не захаращувати простір. Видається, що ми можемо тут

- Додавати підписи форматів по ховеру на іконку
- Прибрати можливість експорту до PDF і залишити тільки один формат

Що ви про це думаєте? @a-radik @andrzejbeletsky

**Comment by a-radik** [comment]
З опису я не зовсім розумію, куди має виводитись запропонований текст? Над іконкою/поруч з нею (наприклад Export data <знчок експорту>). Якщо текст має бути постійно відображеним, навіщо тоді у вспливаючому вигляді вона не потрібна?

Такж прошу зауважити, що на мобільних і тач пристроях зазначені іконки відображаються постійно (не спливають при наведенні бо на зазначених пристроях в разі невикористання миші немає такого поняття як наведення вказівника) і при постійному відображенні текста сторінка буде засмічена написами.

**Comment by ndrhzn** [comment]
On hold до конкретизації запиту користувачів / варіанту імплементації
