### ISSUE TITLE
Дані: N/A в Ініціаторах

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#53]
На вкладці "Деталі проєктів" у стовпчику Ініціатор подекуди трапляються записи, де у комірці один ініціатор N/A, а для другого ініціатора записано нормальна назва.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/3e8d3073-57c2-4151-9d1a-98d87c62830e)

Не дуже зрозуміло, чому так стається (це видається радше багом), і яка цінність цієї інформації (якщо з двох ініціаторів один - N/A, то чи ми можемо в принципі говорити, що там два ініціатора?). 

Якщо я правильно памʼятаю, ми обговорювали подібні випадки перед першим релізом, і тоді зафіксували, що в такому разі виводимо лише одну назву. Але можливо через якісь зміни / оновлення ця проблема знову почала проявлятися.

Це також стосується стовпчиків "Орган управління" та "Тип органу управління"

**Comment by ndrhzn** [comment]
Як extension of this issue - стовпчик "Балансоутримувач" - не дуже зрозуміло, про що тут сигналізує N/A - особливо якщо звернути увагу на те, що в сусідніх комірках "Виконавець", "Орган управління" та "Ініціатор" просто пропуски. Можливо, варто прояснити, в яких випадках ми використовуємо N/A, а в яких просто нічого не пишемо.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/e8e72bec-65a1-4095-b2b2-efc780b64d09)

**Comment by andrzejbeletsky** [comment]
Зробив подання "Балансоутримувач" в таблиці як інші.

**Comment by ndrhzn** [comment]
Думаю, можна робити зміни доступними у публічному додатку

**Comment by andrzejbeletsky** [comment]
Done
