### ISSUE TITLE
UI: Форматування назв організацій у різних контекстах

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#54]
Варто трохи змінити підхід до форматування назв організацій. Зміни мінімальні, і здебільшого стосуються того, де ми ставимо пробіли, а де не ставимо.

**Приклад перший - написання назви організації у комбінації із ідентифікатором**

**Як зараз**: ДЕРЖАВНЕ АГЕНТСТВО ВІДНОВЛЕННЯ ТА РОЗВИТКУ ІНФРАСТРУКТУРИ УКРАЇНИ |37641918
**Як має бути**: ДЕРЖАВНЕ АГЕНТСТВО ВІДНОВЛЕННЯ ТА РОЗВИТКУ ІНФРАСТРУКТУРИ УКРАЇНИ | 37641918
**Що потрібно змінити**: Додати пробіл після "|"
**Як може звучати правило**: Якщо ми використовуємо "|" в якості розділювача, то навколо "|" ми завжди ставимо пробіли (в такому разі можна зафіксувати, що розділювач " | ".

**Приклад другий - написання кількох організацій через кому**

**Як зараз**: ДЕРЖАВНЕ АГЕНТСТВО ВІДНОВЛЕННЯ ТА РОЗВИТКУ ІНФРАСТРУКТУРИ УКРАЇНИ |37641918 , КИЇВСЬКА ОБЛАСНА ДЕРЖАВНА АДМІНІСТРАЦІЯ |00022533
**Як має бути**: ДЕРЖАВНЕ АГЕНТСТВО ВІДНОВЛЕННЯ ТА РОЗВИТКУ ІНФРАСТРУКТУРИ УКРАЇНИ | 37641918, КИЇВСЬКА ОБЛАСНА ДЕРЖАВНА АДМІНІСТРАЦІЯ | 00022533
**Що потрібно змінити**: Прибрати пробіл перед комою
**Як може звучати правило**: Перед комою пробіл не ставимо, після коми пробіл ставимо. Це правило загалом застосовується до всіх випадків, коли ми зазначаємо щось через кому - наприклад, коли у нас декілька органів управління, декілька типів органів управління, декілька громад, і т.д.

**Comment by andrzejbeletsky** [comment]
Done.
Take a look.

**Comment by ndrhzn** [comment]
Дякую, виглядає, як треба. Можна робити зміни доступними у публічному додатку

**Comment by andrzejbeletsky** [comment]
Done
