### ISSUE TITLE
Головний дешборд: Картки

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#6]
У цьому блоці ми закладали

- Кількість проєктів
- Запланований бюджет проєктів
- Підтверджений обсяг фінансування проєктів
- Профінансованість проєктів (%)

Правки / обговорення:

Layout: Зара, здається, картки не заповнюють всю сторінку по ширині, через що виникає дірка з правого боку сторінки в ряду карток

Проєкт: “Кількість проєктів”, “Профінансованість проєктів”

Валюта: Чи варто пояснювати, що коли йдеться про бюджети та фінансування, ми зазначаємо все у гривнях?

Відсотки: Зара індикатор називається “Профінансованість проєктів, %”, а потім і саме значення теж має знак відсотка “ХХ%”. Можливо має сенс прибрати знак відсотка з назви індикатора

**Comment by andrzejbeletsky** [comment]
Зроблено:
1. Перейменування проект->проєкт
2. Прибрано % з картки-показника
3. Додано знак ₴ до найменування грошових показників

**Comment by ndrhzn** [comment]
Пропоную трохи **поміняти підписи у картках**, аби уніфікувати термінологію із порталом

| Як зараз (UA)              | Як зараз (EN)     | Як має бути (UA)             | Як має бути (EN)         |
|----------------------------|-------------------|------------------------------|--------------------------|
| Кількість проєктів         | Projects count    | Кількість проєктів           | Number of projects       |
| Запланований бюджет        | Budget            | Загальний орієнтовний бюджет | Overall estimated budget |
| Обсяг фінансування         | Finance volume    | Підтверджене фінансування    | Confirmed funding        |
| Профінансованість проєктів | Project financing | Фінансове покриття           | Financial coverage       |

Ці зміни також можна застосувати до дешборду із проєктами

Якщо "Загальний орієнтовний бюджет" та "Overall estimated budget" - занадто довго, можна писати "Орієнтовний бюджет" та "Estimated budget".

В майбутньому ми можемо також замінити “Кількість проєктів” на “Кількість активних проєктів”, якщо імплементуємо відображення ключових статистик лише для активних проєктів

**Comment by ndrhzn** [comment]
Звісно, все, що стосується підписів одиниць вимірювання (млн грн), можна лишати без змін
