### ISSUE TITLE
Візуалізація: Розподіл за датою оновлення проєктів

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#8]
Для візуалізації "Динаміка створення" варто додати ще одну лінію, котра б демонструвала розподіл проєктів за датою оновлення. Таким чином можна буде побачити, що хоча нові проєкти не обовʼязково створюються у тій же кількості, в якій вони створювались на самому початку, але робота над наповненням вже наявних проєктів триває.

![visualization](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/f09ff6a4-69d3-4df1-a357-c89517a8e230)

_Originally posted by @ndrhzn in https://github.com/open-contracting/bi.dream.gov.ua/issues/4#issuecomment-1793849373_

**Comment by a-radik** [comment]
В нас наразі намає історичності змін, а дата оновлення є останньою датою внесення змін в проєкт. За наявних даних графік буде вводити користувачів в оману адже якщо в проєкт вносились зміни декілька раз пораховано буде лише останню зміну.

**Comment by ndrhzn** [comment]
Та, я розумію, що дата оновлення - це дата останніх змін у проєкті. Аби не вводити в оману, достатньо просто чітко це сигналізувати і пояснити, що ми показуємо розподіл проєктів за датою останнього оновлення (можемо за потреби підказати, як це інтерпретувати)

**Comment by a-radik** [comment]
Тоді яка аналітична цінність цього показника якщо ми бачимо тільки дату останнього оновлення даних? Якщо по даті створення ми будемо бачити кількість проектів що були створені в певний час, то очикування від дати оновлення бачити кількість змін в проєктах за певний час, а насправді там цієї інформації не буде. 
Графік буде постійно змінюватись в минулому адже проєкти будуть постійно змінюватись що найменше завдяку руху по статусах.

Якщо треба побудувати аналітику на базі дати оновлення, краще дивитись кількість проєектів за секторам, типами, статусами, в яких за останні 30-60 днів сталась зміна.
