### ISSUE TITLE
Проєкти: Візуалізації

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#9]
У цьому блоці ми закладали
 
- Розподіл проєктів за датою реєстрації (histogram)  визначити binwidth (7 днів, місяць)
- Кількість проєктів за статусом (bar chart, treemap, donut)
- Кількість проєктів за типом (bar chart, treemap, donut)
- Кількість проєктів за характером (bar chart, treemap, donut)

Також, оскільки було ухвалено рішення не робити наразі окремий дешборд по обʼєктах, було вирішено додати до дешборду по проєктах наступні візуалізації

- Кількість проєктів за регіонами (choropleth map)тут беремо регіон із повʼязаного обʼєкта
- Кількість проєктів за секторами / підсекторами (treemap) тут беремо сектор із повʼязаного обʼєкта

**Проєкти та обʼєкти**

З огляду на це, найперші  - найбільш очевидні - правки стосуються насамперед того, що у поточній версії обʼєкти представлені окремим аркушем та окремою таблицею. І нам потрібно буде обʼєднати інформацію про обʼєкти з інформацією про проєкти. 

Стосовно візуалізацій це ймовірно означає необхідність використання контейнера, оскільки навряд без нього вийде розташувати все на одному аркуші. Правки щодо таблиць будуть винесені в окремий issue.

**Layout**

Оскільки на аркуш із візуалізаціями має додатися інформація про обʼєкти, неминуче доведеться міняти layout (його в будь-якому разі потрібно було б міняти, бо поточний далекий від ідеального).

Кілька речей, котрі варто взяти до уваги під час розробки нового способу розташування елементів

- Під графіками "Кількість проєктів у розрізі типів та характеру", здається, достатньо багато місця, аби розташувати там, наприклад, donut chart із розбивкою проєктів за статусами
- Графік розподілу проєктів за датою реєстрації цілком може жити на окремій вкладці в контейнері
- В ідеалі бажано було б розташувати карту і treemap з розбивкою проєктів / обʼєктів поруч, але не на різних вкладках контейнера, аби можна було, наприклад, реалізувати сценарій "Вибираємо певний сектор чи підсектор на  treemap і одразу бачимо, скільки проєктів/обʼєктів у нас у цьому секторі чи підсекторі за регіонами". Або ж "Вибираємо регіон і бачимо секторальний розподіл для цього регіона"

**Візуалізації**

У графіку кількості проєктів за характером стовпчики сортовані за алфавітом, а не за числовим показником. Варто впорядкувати їх за числовим показником від найбільшого до найменшого, оскільки все одно природнього способу сортування у цій категоріальній змінній немає (інакше кажучи, це не є впорядкована категоріальна змінна / ordered factor)

У графіку розподілу проєктів за статусом, здається, або відсутнє розрізнення сегментів за кольором, або ж кольори дуже подібні. Варто змінити, аби було простіше розрізняти сегменти

**Comment by a-radik** [comment]
`> В ідеалі бажано було б розташувати карту і treemap з розбивкою проєктів / обʼєктів поруч, але не на різних вкладках контейнера, аби можна було, наприклад, реалізувати сценарій "Вибираємо певний сектор чи підсектор на treemap і одразу бачимо, скільки проєктів/обʼєктів у нас у цьому секторі чи підсекторі за регіонами". Або ж "Вибираємо регіон і бачимо секторальний розподіл для цього регіона"`
Treemap поруч з картою буде маленьким і карта і treemap будуть не дуже зручними для роботи. описаний сценарій реалізовано за допомогою стовбчикової діаграми зліва, яка дозволяє при виборі регіона на мапі побачити розподіл за обраним розрізом і навпаки. Treemap це окремий, додатковий інструмент що дозволяє працювати з двома розрізами обночасно наприклад, бачити долю проєктів за типом а в середені певного типу бачити долі за статусом.

**Comment by ndrhzn** [comment]
Мені здається, ви зараз описуєте іншу ситуацію - інший дешборд. Я говорю про це у контексті не головного дешборду, а дешборду з проєктами

**Comment by a-radik** [comment]
Якщо я вірно розумію, пропонується зробити щось накшталт цього. Мені здається treemap тут зайва

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/63779944/b452b75c-267f-482b-939d-832c6043637d)

**Comment by ndrhzn** [comment]
I see your point

Мене ввело в оману те, що ви описуєте приклад так, наче описаний сценарій "Вибираємо певний сектор чи підсектор на treemap і одразу бачимо, скільки проєктів/обʼєктів у нас у цьому секторі чи підсекторі за регіонами" вже реалізований у поточному представлені, але насправді ж ще ні

Реітерую, що має бути

- Ми не робимо окремого дешборду по обʼєктах, це означає, що treemap з візуалізацією розподілу обʼєктів по секторах і підсекторах має переїхати до дешборду по проєктах

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/b2b7660b-366e-40d8-9c3c-9d91eba44294)

- Спосіб розташування treemap і позиціонування щодо інших елементів можна обговорювати (наприклад, він цілком може бути в контейнері), але він має бути

**Comment by ndrhzn** [comment]
Видається, що зараз вкладка "Карта" та вкладка "Обʼєкти" фактично дублюють інформацію. 

Оскільки інформація про географічну привʼязку проєкту ми все одно забираємо із повʼязаного обʼєкта, де-факто карти "Кількість проєктів" та "Кількість обʼєктів" представляють однакову інформацію.

Чи є сенс нам в такому разі зберігати вкладку "Обʼєкти"? @a-radik  @andrzejbeletsky

**Comment by ndrhzn** [comment]
Пропоную тут трохи **перейменувати назви кнопок**, котрими відбувається переключання способів візуалізації

| **Як зараз (UA)**  | **Як зараз (EN)** | **Як має бути (UA)** | **Як має бути (EN)** |
|--------------------|-------------------|----------------------|----------------------|
| Мапа               | Map               | За регіонами         | By region            |
| Динаміка створення | Creation Dynamics | За датами            | By date              |
| Розподіл           | Distribution      | За категоріями       | By category          |
