### ISSUE TITLE
 Дані: Задокументувати спосіб обчислення ключових показників

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#93]
Між головним порталом та BI досі спостерігається розбіжність у ключових статистиках (подекуди досить велика). Частково ця розбіжнсть може бути пояснена різним часом оновлення даних. Але в деяких випадках (якщо розбіжність дуже велика), можливо йдеться і про розбіжності в методиці обчислення. 

Саме тому нам потрібно задокументувати, в який спосіб ми обчислюємо ключові показники - які фільтри застосовуються (явні та приховані), що виключається з підрахунку (скільки тестових записів не враховуються), які групування застосовуються (за якими ідентифікаторами відбувається групування), і так далі.

На запит від Проєктного офісу та команди розробки потрібно описати детально, як в BI розраховуються ось ці показники.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/507868ac-97b2-4f9b-831a-6ac8a01ca4c7)

**Загальні показники**

Всього проєктів
Загальний бюджет
Профінансованість / фінансове покриття

**Базові фільтри**

Характер проєкту - Нове будівництво, кількість
Характер проєкту - Реконструкція/модеренізація/ремонт, кількість
Характер проєкту - Товари/обладнання, кількість

Статус проєкту - В процесі підготовки
Статус проєкту - Реалізується
Статус проєкту - Не реалізовано
Статус проєкту - Скасовано

Чим ліпше команда розробки розумітиме процес обчислення, тим простіше буде вирівняти показники на порталі та в BI.

**Comment by andrzejbeletsky** [comment]
In progress

**Comment by andrzejbeletsky** [comment]
Почав заповнювати табличку
https://docs.google.com/spreadsheets/d/1til_XSL-WItGP7rkAvajx--ZmooU1DiwUMjSC89VMrM/edit?usp=sharing

Звірка з порталом https://dream.gov.ua/ua показує розбіжності.
Те, на що звернув увагу:
1) розділ проєктів за характером проєкту включає "Project status code"=unsuccessful
2) бюджет - складає всі сатуси?

**Comment by ndrhzn** [comment]
Тобто, умовно можна мислити тут в категоріях SQL queries - SELECT, WHERE, GROUP BY, COUNT, SUM
