### ISSUE TITLE
Дані / Розріз / Фільтр: Наявність ПКД / Номер експертизи

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#96]
Один з нових запитів - додати інформацію про наявність ПКД (проєктно-кошторисної документації) до проєктів.

З точки зору моделі даних інформація про наявність міститься в

approaches/items/additionalClassifications/id де approaches/items/additionalClassifications/scheme="UA-SESC"

Якщо в проєкті знаходиться такий елемент, значить у проєкту є ПКД. Тобто на підставі цього ми можемо, наприклад, робити фільтр "Наявність ПКД". Тут варто памʼятати, що в одного проєкту фактично може бути декілька ПКД (якщо засновуватися на фактичних даних, то здебільшого у наявних проєктах по одному елементу ПКД, однак є один винятковий проєкт, в котрому більше десятка таких записів).

Також ми можемо за потреби додавати новий стовпчик "Номер експертизи", у котрий виводити значення approaches/items/additionalClassifications/id. Однак наразі цю задачу можна притримати і почекати, чи буде на неї більш конкретно сформульований запит від користувачів (номери експертиз подаються у форматі ZP01:4716-3206-7140-1240, не дуже очевидно, чи мають вони цінність для користувачів).

Тому наразі фокусуємось на додаванні фільтра "Наявність ПКД" до таблиці "Деталі проєктів". Згодом - після тестування та дослідження потреб аудиторії - можемо подумати про додавання стовпчиків до таблиці.

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by ndrhzn** [comment]
Перевірено, можна видавати на публічний додаток

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
done
