### ISSUE TITLE
Дані: Юридичні підстави використання коштів / legalBasis

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#97]
Є запит від Проєктного офісу додати новий елемент даних - наразі лише до таблиці "Деталі проєктів" #10 . Елемент називається "Юридичні підстави використання коштів" (в англійській версії можемо назвати просто Legal basis), і в моделі даних проєкту знаходиться у approaches/budget/finance/legalBasis.

![image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/9415413a-2a9d-4a17-9d48-7bc1a1e51c5c)

Деякі проєкти можуть не мати цього елемента, але також деякі проєкти - ті, що мають декілька джерел фінансування - можуть мати декілька юридичних підстав використання коштів. У такому разі є сенс діяти за тим же принципом, що ми використовуємо для інших змінних у подібних випадках - давати всі записи в одній комірці через кому. 

Цей стовпчик є сенс розташувати в кінці таблиці після стовпчика "Стратегічні документи"

**Comment by ndrhzn** [comment]
[Приклад проєкту з цим елементом в АРІ](https://public-api.dream.gov.ua/marketplace/public/dream/ideas/04wb59f7-1009-432h-b7lv-u0n2bd064161)

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
done

**Comment by ndrhzn** [comment]
Перевірено. Можна видавати на публічний додаток

**Comment by andrzejbeletsky** [comment]
done
