### ISSUE TITLE
Класифікатори: UA-MOH

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#98]
У нас є елемент, котрий називається Sector MOH, і позначає певний заклад Міністерства охорони здоровʼя. Цей елемент, якщо я не помиляся, забирається з additionalClassifications/id обʼєкта, де additionalClassifications/scheme="UA-MOH".

Наразі цей елемент ніде не використовується, і в ВІ доступний лише на сторінці selections. У нас є запит від Проєктного офісу зробити цей елемент доступним. Ми поки не знаємо, в якій формі і де він буде доступним (найбільш ймовірно - на сторінці "Деталі проєктів"). Однак перша задача, котру ми маємо - перетворити коди закладів на людиночитані назви закладів, використовуючи класифікатор від команди розробки.

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/95ef9174-7a2c-4654-ba02-885f8f413287)

Вже згодом ми можемо вирішити, де і як цей елемент має бути доступним - серед варіантів окремий стовпчик у таблиці та фільтр на панелі фільтрів. Один з користувацьких сценаріїв полягає у тому, щоби знайти всі проєкти, котрі мають стосунок до певного закладу (передбачається, що може бути декілька проєктів для одного закладу - якщо не зараз, то у майбутньому).

**Comment by ndrhzn** [comment]
Від команди розробки ми отримали ось цей класифікатор [UA-MOH.json](https://github.com/open-contracting/bi.dream.gov.ua/files/14460825/UA-MOH.json), наразі є задача додати його до моделі даних таким чином, аби замість кодів закладів ми бачили їхні назви.

Назва цього елементу може бути "Заклад МОЗ" / "MOH Facility"

**Comment by andrzejbeletsky** [comment]
done

**Comment by ndrhzn** [comment]
Можна робити зміни доступними у публічному додатку

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
done
