### ISSUE TITLE
Класифікатори: UA-MOS

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/bi.dream.gov.ua#99]
У нас є елемент, котрий називається Sector MOS, і позначає певний заклад Міністерства освіти. Цей елемент, якщо я не помиляюся, забирається з additionalClassifications/id обʼєкта, де additionalClassifications/scheme="UA-MOS".

Наразі цей елемент ніде не використовується, і в ВІ доступний лише на сторінці selections. У нас є запит від Проєктного офісу зробити цей елемент доступним. Ми поки не знаємо, в якій формі і де він буде доступним (найбільш ймовірно - на сторінці "Деталі проєктів"). Однак перша задача, котру ми маємо - перетворити коди закладів на людиночитані назви закладів, використовуючи класифікатор від команди розробки.

![Image](https://github.com/open-contracting/bi.dream.gov.ua/assets/13032566/f6aaf974-b6df-4c01-aa86-469e98dfdd28)

Вже згодом ми можемо вирішити, де і як цей елемент має бути доступним - серед варіантів окремий стовпчик у таблиці та фільтр на панелі фільтрів. Один з користувацьких сценаріїв полягає у тому, щоби знайти всі проєкти, котрі мають стосунок до певного закладу (передбачається, що може бути декілька проєктів для одного закладу - якщо не зараз, то у майбутньому).

**Comment by ndrhzn** [comment]
Від команди розробки ми отримали ось цей класифікатор [UA-MOS.json](https://github.com/open-contracting/bi.dream.gov.ua/files/14460974/UA-MOS.json), наразі є задача додати його до моделі даних таким чином, аби замість кодів закладів ми бачили їхні назви.

Назва цього елементу може бути "Заклад МОН" / "MOS Facility"

**Comment by andrzejbeletsky** [comment]
done

**Comment by andrzejbeletsky** [comment]
Потрібні додаткові розшифрування значень dnz, ptc, school, zpo
Приклад:
https://public-api.dream.gov.ua/marketplace/public/dream/objects/8022qj23-6452-4v2e-b2n0-rht6y7if3348

**Comment by ndrhzn** [comment]
| **code** | **value**                                        |
|----------|--------------------------------------------------|
| dnz      | Дошкільний навчальний заклад (ясла - садок)      |
| ptc      | Заклад професійної (професійно-технічної) освіти |
| school   | Заклад загальної середньої освіти                |
| zpo      | Будинок дитячої та юнацької творчості            |

**Comment by andrzejbeletsky** [comment]
in progress

**Comment by andrzejbeletsky** [comment]
done
